'use client';
import { useState, useEffect, useRef } from 'react';
import Head from 'next/head';
import Link from 'next/link';

const SCHEMA = {
  '@context': 'https://schema.org',
  '@graph': [
    { '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Home', item: 'https://www.1solutions.biz/' }, { '@type': 'ListItem', position: 2, name: 'Hire Data Scientist', item: 'https://www.1solutions.biz/hire-data-scientist/' }] },
    { '@type': 'Service', name: 'Hire Data Scientist', url: 'https://www.1solutions.biz/hire-data-scientist/', description: 'Hire expert data scientists from 1Solutions — statistical analysis, predictive modelling, A/B testing, EDA, business intelligence, Python/R data science, SQL analytics, and data-driven strategy. Dedicated, part-time, or fixed-scope. Start in 3–5 days.', provider: { '@type': 'Organization', name: '1Solutions', url: 'https://www.1solutions.biz', logo: { '@type': 'ImageObject', url: 'https://www.1solutions.biz/images/1solutions-logo.png' }, foundingDate: '2008', areaServed: ['US', 'GB', 'AU', 'CA', 'IN'] }, aggregateRating: { '@type': 'AggregateRating', ratingValue: '4.9', reviewCount: '55', bestRating: '5' } },
    { '@type': 'FAQPage', mainEntity: [
      { '@type': 'Question', name: 'What does a data scientist do?', acceptedAnswer: { '@type': 'Answer', text: 'A data scientist extracts insight and builds predictive models from data. Core activities include: exploratory data analysis (EDA) — understanding data distributions, identifying outliers and anomalies, detecting relationships between variables, and generating hypotheses about what the data reveals; statistical analysis — hypothesis testing (t-tests, chi-squared, ANOVA), confidence intervals, regression analysis, and causal inference (A/B testing, difference-in-differences, regression discontinuity); predictive modelling — building machine learning models (classification, regression, clustering, time series) to predict outcomes from historical data; feature engineering — creating new variables from raw data that improve model performance; A/B testing design and analysis — designing statistically valid experiments, calculating required sample sizes, analysing results with appropriate tests, and interpreting effect sizes; data visualisation and storytelling — communicating findings to stakeholders using charts, dashboards, and written analysis; and business intelligence — translating business questions into analytical frameworks and data queries.' } },
      { '@type': 'Question', name: 'What is the difference between a data scientist and an ML developer?', acceptedAnswer: { '@type': 'Answer', text: 'A data scientist focuses on extracting insight from data and building predictive models to answer business questions — the output is often a model, a statistical finding, a recommendation, or a dashboard. Work happens primarily in Python or R notebooks, with tools like Pandas, statsmodels, scipy, scikit-learn, and visualisation libraries. A data scientist needs strong statistical foundations: understanding of probability distributions, hypothesis testing, experimental design, and statistical inference. An ML developer focuses on building production ML systems — the model must run reliably at scale in production, with low latency, monitoring, and automated retraining. The output is a deployed system, not a finding. In practice, the boundary blurs: strong data scientists write production-quality code and can deploy models; strong ML developers understand statistical evaluation. We offer both profiles and can help you determine which you need.' } },
      { '@type': 'Question', name: 'What statistical methods do your data scientists use?', acceptedAnswer: { '@type': 'Answer', text: 'Our data scientists work with the full statistical toolkit: descriptive statistics (mean, median, variance, percentiles, distributions); inferential statistics (hypothesis tests — Student t-test, Welch t-test, Mann-Whitney U for non-parametric comparisons, chi-squared test for categorical variables, ANOVA for multi-group comparisons, Fisher exact test for small samples); regression analysis (OLS linear regression, logistic regression, Poisson regression for count data, survival analysis / Cox proportional hazards for time-to-event data); Bayesian methods (Bayesian A/B testing, posterior distributions, credible intervals, PyMC3/Stan for Bayesian models); causal inference (A/B testing, multi-armed bandits, difference-in-differences, instrumental variables, propensity score matching, regression discontinuity); time series analysis (ARIMA, decomposition, stationarity tests, autocorrelation analysis, Granger causality); and dimensionality reduction (PCA, UMAP, t-SNE for visualisation and feature reduction).' } },
      { '@type': 'Question', name: 'Can your data scientists design and analyse A/B tests?', acceptedAnswer: { '@type': 'Answer', text: 'Yes. A/B testing is a core data science competency. Our data scientists handle the full A/B testing lifecycle: experiment design (defining the hypothesis and primary metric, selecting the randomisation unit — user, session, or device, calculating required sample size for the desired statistical power — typically 80–90% — and significance level — typically 5%, identifying and controlling for confounders); monitoring (checking for novelty effects, day-of-week effects, and sample ratio mismatch — SRM — which indicates a broken randomisation); analysis (appropriate statistical tests for the metric type — t-test for means, z-test for proportions, Mann-Whitney U for skewed distributions, CUPED for variance reduction using pre-experiment covariates); and interpretation (effect size and practical significance vs statistical significance, confidence intervals, multiple comparison corrections with Bonferroni or Benjamini-Hochberg for multi-metric experiments, and go/no-go recommendation with business context).' } },
      { '@type': 'Question', name: 'What data science tools and languages do your data scientists use?', acceptedAnswer: { '@type': 'Answer', text: 'Our data scientists primarily work in Python (Pandas for data manipulation, NumPy for numerical computation, scikit-learn for ML, statsmodels for statistical modelling, scipy for statistical tests, Matplotlib and Seaborn for visualisation, Plotly for interactive charts) and SQL (PostgreSQL, Redshift, BigQuery, Snowflake for data extraction and analytical queries). For specific needs: R (ggplot2 for publication-quality charts, tidyverse, survival, mixed-effects models with lme4); Jupyter notebooks for exploratory work; dbt (data build tool) for modelling SQL transformations in a data warehouse; Spark (PySpark) for big data processing; and Looker, Tableau, Power BI, or Metabase for stakeholder dashboards. Experiment platform tools: Optimizely, LaunchDarkly, or custom A/B testing infrastructure.' } },
      { '@type': 'Question', name: 'Can your data scientists work with large datasets (big data)?', acceptedAnswer: { '@type': 'Answer', text: 'Yes. Our data scientists work across the full data volume spectrum: small datasets requiring careful statistical handling (high signal-to-noise analysis, bootstrap methods when parametric assumptions do not hold); medium datasets in Pandas (millions of rows, efficient with chunking, filtering, and vectorised operations); and large datasets requiring distributed processing — PySpark on Databricks, EMR, or Dataproc for petabyte-scale data; SQL on BigQuery, Snowflake, or Redshift for warehouse-scale analytics; and Polars (Rust-based Pandas alternative) for single-machine performance on datasets that exceed Pandas memory limits. For feature engineering for ML models, our data scientists design feature pipelines that are consistent between training (historical batch data) and inference (real-time or batch scoring) to prevent training-serving skew.' } },
      { '@type': 'Question', name: 'What data visualisation and communication skills do your data scientists have?', acceptedAnswer: { '@type': 'Answer', text: 'Data visualisation is not just making charts — it is communicating statistical findings to non-statistician stakeholders who make business decisions. Our data scientists: choose chart types appropriate to the data (distribution — histogram, KDE; comparison — bar chart, box plot; relationship — scatter plot, heatmap; time series — line chart with confidence bands; composition — stacked bar, Sankey; geographic — choropleth maps); use Matplotlib and Seaborn for publication-quality static charts; Plotly and Bokeh for interactive dashboards; Looker or Tableau for business intelligence dashboards consumed by non-technical stakeholders; and write clear analytical narratives that translate statistical findings into business recommendations — not just "p < 0.05, result is statistically significant" but "the new feature increases 30-day retention by 2.3 percentage points (95% CI: 1.1–3.5pp), which at current acquisition cost represents $180K additional annual revenue per cohort."' } },
      { '@type': 'Question', name: 'Can your data scientists work with our data warehouse (Snowflake, BigQuery, Redshift)?', acceptedAnswer: { '@type': 'Answer', text: 'Yes. Our data scientists are proficient in analytical SQL across major warehouses: Snowflake (window functions, QUALIFY, FLATTEN for semi-structured JSON, dynamic data masking, Time Travel, COPY INTO for data loading); BigQuery (UNNEST for arrays, JS UDFs, BigQuery ML for SQL-native ML, partitioned and clustered tables for cost optimisation, Scheduled Queries); Redshift (Redshift Spectrum for S3 external tables, DISTKEY and SORTKEY optimisation, WLM queue management); and PostgreSQL and MySQL for OLTP-source analytics. They also work with dbt (data build tool) for building modular, tested, documented SQL transformation layers on top of data warehouses.' } },
    ] },
  ],
};

const SKILLS = [
  { n: '01', title: 'Exploratory Data Analysis (EDA)', desc: 'Rigorous exploratory analysis — data quality assessment (missing values, duplicate detection, outlier identification using IQR, z-score, and domain knowledge), distribution analysis (histograms, KDE, Q-Q plots), feature correlation analysis (Pearson, Spearman, Kendall for mixed data types), categorical variable analysis (chi-squared, Cramers V), time patterns (seasonality, trends, structural breaks), and hypothesis generation from data — EDA is where the real insight begins, before any model is trained.' },
  { n: '02', title: 'Statistical Analysis & Hypothesis Testing', desc: 'Applied statistical analysis for business decisions — hypothesis testing (t-test, Mann-Whitney U, chi-squared, ANOVA, Kruskal-Wallis for non-parametric comparisons), confidence intervals and uncertainty quantification, regression analysis (OLS, logistic, Poisson, Cox proportional hazards for survival analysis), Bayesian inference (PyMC, posterior distributions, credible intervals for more intuitive uncertainty communication), multiple comparison correction (Bonferroni, Benjamini-Hochberg FDR), and effect size reporting (Cohen d, odds ratio, relative risk).', feat: true },
  { n: '03', title: 'A/B Testing & Experimentation Design', desc: 'End-to-end A/B testing — experiment design (hypothesis, randomisation unit, primary and guardrail metrics, sample size calculation for target statistical power and significance level), experiment monitoring (novelty effect detection, sample ratio mismatch — SRM check, metric sensitivity analysis), statistical analysis (appropriate test selection, CUPED variance reduction using pre-experiment covariates, sequential testing for early stopping), and results interpretation (practical vs statistical significance, business recommendation with confidence interval reporting).' },
  { n: '04', title: 'Predictive Modelling & Machine Learning', desc: 'Applied predictive modelling for business forecasting — classification models (XGBoost, LightGBM, Random Forest, Logistic Regression for churn prediction, lead scoring, health risk stratification); regression models (demand forecasting, revenue projection, price elasticity); clustering (K-means, DBSCAN, Hierarchical clustering for customer segmentation); dimensionality reduction (PCA, UMAP, t-SNE); and time-series forecasting (Prophet, ARIMA, LSTM for sales, inventory, and demand planning). Feature engineering, cross-validation, and model interpretability (SHAP values, LIME).' },
  { n: '05', title: 'SQL & Data Warehouse Analytics', desc: 'Advanced analytical SQL across data warehouses — window functions (LAG, LEAD, RANK, NTILE, running totals, rolling averages, funnel analysis with conditional aggregation), complex joins and subqueries, CTEs for readable query architecture, cohort analysis, retention curves, funnel analysis, revenue attribution, user journey analysis; Snowflake, BigQuery, Redshift, and PostgreSQL; dbt for modular SQL transformations; and query optimisation (partition pruning, cluster keys, materialisation strategy).' },
  { n: '06', title: 'Data Visualisation & Executive Reporting', desc: 'Statistical visualisation and business communication — appropriate chart type selection for the data (distributions, comparisons, relationships, time series, compositions, geographic); Python visualisation (Matplotlib, Seaborn, Plotly for interactive); BI dashboards (Tableau, Looker, Power BI, Metabase) for business stakeholders; animated and custom D3.js visualisations; and written analytical narratives that translate statistical findings into actionable business recommendations with quantified impact and confidence intervals.' },
  { n: '07', title: 'Customer Analytics & Segmentation', desc: 'Customer behaviour analytics — RFM (Recency, Frequency, Monetary) analysis for customer value segmentation; cohort retention analysis and LTV calculation (Customer Lifetime Value modelling with BG/NBD and Gamma-Gamma models); funnel analysis and conversion optimisation; churn prediction and propensity modelling; customer segmentation (K-means, hierarchical clustering on behavioural features); channel attribution modelling (last-touch, first-touch, data-driven multi-touch attribution using Markov chains or Shapley values); and product analytics (DAU/MAU, engagement depth, session analysis, feature adoption curves).' },
  { n: '08', title: 'Financial & Revenue Analytics', desc: 'Financial and revenue analytics — MRR/ARR analysis and forecasting (SaaS metrics), revenue cohort analysis, subscription economics (CAC, LTV, payback period), pricing elasticity analysis, revenue attribution across channels and products, financial modelling in Python, budget vs actuals analysis, P&L sensitivity analysis, unit economics modelling, and financial dashboards for investor reporting or executive review. Familiarity with financial data sources (Stripe, Braintree, QuickBooks, NetSuite APIs).' },
  { n: '09', title: 'Python & R Data Science Stack', desc: 'Production-quality Python data science — Pandas and Polars for data manipulation, NumPy for numerical computation, scikit-learn for ML pipelines (Pipeline, ColumnTransformer, cross_val_score), statsmodels and scipy.stats for statistical testing, Matplotlib/Seaborn/Plotly for visualisation, Optuna for hyperparameter optimisation, and SHAP for model interpretability. R when appropriate: ggplot2 for publication-quality charts, tidyverse, survival analysis with the survival package, mixed-effects models with lme4, and brms for Bayesian regression models.' },
  { n: '10', title: 'Data Strategy & Analytics Consulting', desc: 'Strategic data science consulting — data maturity assessment (what analytical capability does the organisation currently have, what is achievable with current data?), KPI framework design (which metrics actually measure business health vs vanity metrics?), analytics roadmap development, data team structure recommendations, make-vs-buy analysis for analytics tools, data governance and quality frameworks, and executive communication of data science ROI — translating analytical findings into revenue or cost impact estimates that resonate with non-technical leadership.' },
];

const TECH_STACK = [
  { group: 'Python Data Science', color: '#1e40af', items: ['Pandas / Polars', 'NumPy / SciPy', 'scikit-learn', 'statsmodels', 'PyMC (Bayesian)', 'Optuna (hyperparams)'] },
  { group: 'Visualisation', color: '#0369a1', items: ['Matplotlib / Seaborn', 'Plotly / Bokeh', 'Tableau / Looker', 'Power BI / Metabase', 'Streamlit (dashboards)', 'D3.js (custom)'] },
  { group: 'SQL & Data Warehouses', color: '#0f766e', items: ['PostgreSQL / MySQL', 'Snowflake', 'BigQuery', 'Redshift', 'dbt (transformations)', 'Apache Spark / PySpark'] },
  { group: 'ML & Predictive Modelling', color: '#7e22ce', items: ['XGBoost / LightGBM', 'scikit-learn Pipelines', 'Prophet (forecasting)', 'SHAP (interpretability)', 'Hugging Face (NLP)', 'FAISS (similarity)'] },
  { group: 'Statistical Testing', color: '#b45309', items: ['scipy.stats', 'statsmodels', 'Bayesian A/B (PyMC)', 'Bootstrap methods', 'CUPED (variance red.)', 'Permutation tests'] },
  { group: 'A/B & Experimentation', color: '#dc2626', items: ['Optimizely', 'LaunchDarkly', 'GrowthBook', 'Firebase Remote Config', 'Custom experiment infra', 'Multi-armed bandits'] },
  { group: 'Data Pipelines', color: '#059669', items: ['dbt (SQL transforms)', 'Airflow / Prefect', 'Great Expectations', 'Airbyte / Fivetran', 'Kafka (streaming)', 'AWS Glue / Databricks'] },
  { group: 'R & Specialised Stats', color: '#c2185b', items: ['ggplot2 (publication)', 'tidyverse (EDA)', 'survival (Kaplan-Meier)', 'lme4 (mixed models)', 'brms (Bayesian)', 'Stan (Bayesian MCMC)'] },
];

const ENGAGEMENT_MODELS = [
  { id: 'full', name: 'Full-Time Dedicated Data Scientist', badge: 'Most Popular', badgeColor: '#D97706', feat: true, icon: 'M16 11c1.66 0 2.99-1.34 2.99-3S17.66 5 16 5c-1.66 0-3 1.34-3 3s1.34 3 3 3zm-8 0c1.66 0 2.99-1.34 2.99-3S9.66 5 8 5C6.34 5 5 6.34 5 8s1.34 3 3 3zm0 2c-2.33 0-7 1.17-7 3.5V19h14v-2.5c0-2.33-4.67-3.5-7-3.5zm8 0c-.29 0-.62.02-.97.05 1.16.84 1.97 1.97 1.97 3.45V19h6v-2.5c0-2.33-4.67-3.5-7-3.5z', headline: '160 hrs/month — a data scientist embedded in your team.', desc: 'A dedicated data scientist committed to your analytical questions — building predictive models, designing and analysing A/B tests, performing EDA on new data sources, building dashboards, and turning data into decision-making tools for your business.', bestFor: ['Product analytics (A/B testing, funnel analysis, retention modelling)', 'Customer analytics (segmentation, LTV, churn prediction)', 'Revenue and financial analytics (MRR forecasting, pricing elasticity)', 'Teams building their first data science capability'], process: 'Requirements → shortlist in 24 hrs → technical interview → start in 3–5 days', timeline: 'Available within 3–5 business days' },
  { id: 'part', name: 'Part-Time Data Scientist (80 hrs/month)', badge: 'Flexible', badgeColor: '#1e40af', icon: 'M11.99 2C6.47 2 2 6.48 2 12s4.47 10 9.99 10C17.52 22 22 17.52 22 12S17.52 2 11.99 2zM12 20c-4.42 0-8-3.58-8-8s3.58-8 8-8 8 3.58 8 8-3.58 8-8 8zm.5-13H11v6l5.25 3.15.75-1.23-4.5-2.67V7z', headline: '80 hrs/month — analytical expertise without full-time overhead.', desc: 'A part-time data scientist for businesses that need rigorous analytical work a few days per week — A/B test design and analysis, periodic EDA on new data sources, monthly reporting, or model monitoring and maintenance.', bestFor: ['Ongoing A/B testing support for a product team', 'Monthly business analytics and executive dashboards', 'Seasonal demand forecasting and planning analytics', 'Supplementing a BI team with statistical depth'], process: 'Requirements → shortlist → start within 2–3 days', timeline: 'Available within 2–3 business days' },
  { id: 'project', name: 'Fixed-Scope Data Science Project', badge: 'Defined outcome', badgeColor: '#0369a1', icon: 'M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm-7 3c1.93 0 3.5 1.57 3.5 3.5S13.93 13 12 13s-3.5-1.57-3.5-3.5S10.07 6 12 6zm7 13H5v-.23c0-.62.28-1.2.76-1.58C7.47 15.82 9.64 15 12 15s4.53.82 6.24 2.19c.48.38.76.97.76 1.58V19z', headline: 'Fixed price for a defined analysis or model.', desc: 'Fixed-scope data science engagement for a well-defined analytical project — a customer segmentation analysis, a churn prediction model, an A/B testing framework, a cohort retention analysis, a demand forecast, or a statistical audit of an existing model.', bestFor: ['Customer segmentation analysis (RFM + clustering)', 'Churn prediction model with feature importance and SHAP analysis', 'A/B testing framework design and first experiment analysis', 'Cohort retention analysis and LTV model'], process: 'Scoping → data review → analysis → deliverable → presentation', timeline: 'Typical 2–8 week engagements' },
];

const PROCESS_STEPS = [
  { num: '01', title: 'Share Your Data Science Questions', desc: 'Tell us about the business questions you need to answer with data — are you trying to predict who will churn, understand which product features drive retention, design a pricing experiment, forecast next quarter demand, or segment your customer base? The more specific the business question, the better we can scope and match the right data scientist. Also tell us about your data — where it lives (warehouse, database, flat files), approximate volume, and what time period it covers.' },
  { num: '02', title: 'Data Scientist Shortlist in 24 Hours', desc: 'Within 24 business hours we send 2–3 data scientist profiles matched to your domain and analytical problem type — with their experience in your industry (SaaS, e-commerce, fintech, healthcare), specific analytical methods (Bayesian A/B testing, survival analysis, causal inference), and tools (your data warehouse, Python, R). Not generic profiles — specialists matched to your data and business context.' },
  { num: '03', title: 'Technical Interview — Test Statistical Depth', desc: 'Interview candidates on your specific analytical problems. Ask them to explain how they would design an A/B test for your product change, walk through their approach to a customer churn prediction, or describe how they would calculate statistical significance for your primary metric. Test real statistical reasoning — not just tool familiarity but conceptual understanding of when and why each method applies.' },
  { num: '04', title: 'Data Audit & Analytical Framework Design', desc: 'Before analysis begins, our data scientist audits your available data — quality, completeness, potential biases, and analytical limitations. We design the analytical framework upfront: which questions can be answered with current data, which require additional data collection, which require causal inference beyond correlation, and what the appropriate statistical methods are given your data characteristics.' },
  { num: '05', title: 'Analysis, Modelling & Validation', desc: 'Exploratory analysis (EDA), feature engineering, model development with rigorous cross-validation, statistical testing with appropriate test selection and multiple comparison correction, and model interpretability (SHAP values, feature importance, partial dependence plots). All code in Python or R, documented and reproducible. All findings documented with confidence intervals and clear statements of limitations.' },
  { num: '06', title: 'Insight Communication & Dashboard Delivery', desc: 'Executive summary of findings with business impact quantification, visualisations appropriate for stakeholder audience (not raw statistical output), a stakeholder presentation with actionable recommendations, dashboards in Tableau/Looker/Metabase for ongoing monitoring, and a handover document explaining the methodology, limitations, and how to rerun the analysis as new data arrives. Knowledge transfer to your team.' },
];

const TESTIMONIALS = [
  { text: "1Solutions provided a data scientist who redesigned our entire A/B testing programme. She introduced CUPED variance reduction (cutting our required sample size by 30%), built a sample ratio mismatch detection system that caught 3 broken experiments we would have shipped, and wrote our experiment analysis documentation. Our experiment velocity tripled with the same team size.", name: 'James K.', role: 'Director of Product Analytics, SaaS (UK)', init: 'JK', bg: '#0F3460' },
  { text: "We needed customer segmentation and churn prediction. 1Solutions sent a data scientist who did rigorous EDA on 3 years of transaction data, built an RFM + K-means segmentation with 7 clusters, and trained an XGBoost churn model with SHAP explanations. Our CRM team now acts on weekly churn risk scores. Churn in the at-risk segment dropped 18% in 90 days.", name: 'Sarah B.', role: 'Head of Customer Success, E-commerce (AU)', init: 'SB', bg: '#0a1a30', feat: true },
  { text: "We hired a data scientist for demand forecasting — seasonal consumer goods, 200+ SKUs, 5 years of weekly sales data. He built a Prophet + LightGBM ensemble that reduced our MAPE from 24% to 9% vs the baseline naive forecast. Inventory holding cost dropped 12% in the first quarter with the new forecasts feeding directly into our supply chain planning tool.", name: 'David W.', role: 'VP Supply Chain, Consumer Goods (US)', init: 'DW', bg: '#1e3a5f' },
];

const WHY_CARDS = [
  { title: 'Statistical Rigour, Not Data Theatre', desc: 'Data science without statistical rigour produces confident wrong answers. Our data scientists understand sampling distributions, appropriate hypothesis tests for the data type, multiple comparison correction, effect sizes vs p-values, and causal inference limitations — they do not just report "statistically significant (p=0.04)" without context.' },
  { title: 'Business Question First', desc: 'The best data science starts with a clear business question, not a dataset or model. Our data scientists translate business problems ("why are customers churning?") into analytical frameworks before touching the data — ensuring the analysis actually answers the question the business is asking.' },
  { title: 'A/B Testing Depth', desc: 'Running experiments well requires more than a t-test calculator. Our data scientists design experiments with the correct statistical power, monitor for sample ratio mismatch and novelty effects, apply variance reduction (CUPED), use sequential testing for early stopping, and report effect sizes with confidence intervals — not just p-values.' },
  { title: 'Domain-Specific Analytical Methods', desc: 'SaaS product analytics (cohort retention, LTV, funnel analysis) requires different methods than supply chain forecasting (ARIMA, seasonal decomposition, intermittent demand), financial analytics (time-series risk models), or healthcare (survival analysis, clinical trial statistics). We match your domain with appropriate analytical expertise.' },
  { title: 'Reproducible, Documented Analysis', desc: 'Analysis that only the original data scientist can reproduce is a liability. Our data scientists write clean, documented Python or R code in version-controlled notebooks with clear methodology sections, so your team can rerun, modify, and extend the analysis as new data arrives.' },
  { title: 'Causation vs Correlation Awareness', desc: 'Correlation does not equal causation. Our data scientists are explicit about when correlation-based analysis applies (EDA, segmentation) vs when causal inference methods are needed (A/B testing, difference-in-differences, propensity score matching) — and when the data simply cannot answer the causal question being asked.' },
  { title: 'Communication to Non-Technical Stakeholders', desc: 'Statistical findings that stay in a notebook do not change decisions. Our data scientists translate findings into business language: quantified impact with confidence intervals, visualisations appropriate for the audience, and a clear recommendation with stated assumptions. They write for the decision-maker, not the statistician.' },
  { title: 'Data Quality Honesty', desc: 'Garbage in, garbage out. Our data scientists audit data quality before analysis, flag sampling biases, selection effects, and missing data mechanisms that affect conclusions — and are explicit about what the data cannot tell you, not just what it can.' },
];

const FAQS = [
  { q: 'What does a data scientist do?', a: "A data scientist extracts insight from data and builds predictive models: EDA (exploratory data analysis), statistical hypothesis testing, A/B test design and analysis, predictive modelling (classification, regression, clustering, time series), SQL analytics, customer segmentation and LTV modelling, and communicating findings to business stakeholders as actionable recommendations." },
  { q: 'What is the difference between a data scientist and an ML developer?', a: "A data scientist focuses on extracting insight and answering business questions — statistical analysis, EDA, A/B testing, dashboards, predictive models. Output is a finding or recommendation. An ML developer focuses on building and deploying production ML systems at scale. Output is a deployed system with monitoring and MLOps. Strong data scientists write production code; strong ML developers understand statistical evaluation. We offer both profiles." },
  { q: 'What statistical methods do your data scientists use?', a: "T-tests, Mann-Whitney U, chi-squared, ANOVA (inferential statistics), OLS regression, logistic regression, Poisson regression, Cox survival analysis, Bayesian inference (PyMC, credible intervals), A/B testing (CUPED, sequential testing, SRM detection), dimensionality reduction (PCA, UMAP), multiple comparison correction (Bonferroni, Benjamini-Hochberg), and causal inference (DiD, propensity score matching)." },
  { q: 'Can your data scientists design and analyse A/B tests?', a: "Yes. Full A/B testing lifecycle: experiment design (hypothesis, randomisation unit, sample size calculation for target power and significance), monitoring (SRM check, novelty effects), statistical analysis (appropriate test selection, CUPED variance reduction, sequential testing for early stopping), and results interpretation (effect size, confidence intervals, practical vs statistical significance, business recommendation)." },
  { q: 'What data science tools do your data scientists use?', a: "Python (Pandas, NumPy, scikit-learn, statsmodels, scipy, Matplotlib, Seaborn, Plotly), SQL (Snowflake, BigQuery, Redshift, PostgreSQL), R (ggplot2, tidyverse, survival, lme4, brms), dbt for SQL transformations, Tableau/Looker/Power BI for dashboards, and Optimizely/GrowthBook for A/B testing platforms." },
  { q: 'Can your data scientists work with large datasets (big data)?', a: "Yes. Pandas for millions of rows (chunking, vectorised operations), Polars for high-performance single-machine processing, PySpark on Databricks/EMR/Dataproc for petabyte-scale processing, BigQuery/Snowflake/Redshift SQL for warehouse-scale analytics, and Airflow/dbt for data pipeline and transformation orchestration." },
  { q: 'What data visualisation skills do your data scientists have?', a: "Distribution (histogram, KDE), comparison (bar chart, box plot, violin), relationship (scatter, heatmap), time series (line chart with confidence bands), composition (Sankey, stacked bar), and geographic (choropleth). Tools: Matplotlib/Seaborn (Python), Plotly/Bokeh (interactive), Tableau/Looker/Power BI (BI dashboards), Streamlit (custom data apps), and D3.js for custom interactive visualisations." },
  { q: 'Can your data scientists work with our data warehouse?', a: "Yes. Snowflake (window functions, QUALIFY, FLATTEN, Time Travel), BigQuery (UNNEST, BigQuery ML, partitioned/clustered tables), Redshift (Spectrum, DISTKEY/SORTKEY optimisation), and PostgreSQL. Also dbt for modular, tested SQL transformations on top of your data warehouse." },
];

function useCountUp(target, duration = 1800, start = false) {
  const [count, setCount] = useState(0);
  useEffect(() => { if (!start) return; const num = parseInt(target.replace(/\D/g, ''), 10); if (!num) return; let t0 = null; const step = ts => { if (!t0) t0 = ts; const p = Math.min((ts - t0) / duration, 1); setCount(Math.floor((1 - Math.pow(1 - p, 3)) * num)); if (p < 1) requestAnimationFrame(step); }; requestAnimationFrame(step); }, [start, target, duration]);
  return count;
}
function StatItem({ label, val, started }) {
  const num = useCountUp(val, 1800, started);
  const suffix = val.replace(/[\d,]/g, '');
  return (<div className="hds-sc"><div className="hds-sv">{started ? (val.includes(',') ? num.toLocaleString() : num) + suffix : val}</div><div className="hds-sl">{label}</div></div>);
}

export default function HireDataScientist() {
  const [showAll, setShowAll] = useState(false);
  const [openFaq, setOpenFaq] = useState(0);
  const [ss, setSs] = useState(false);
  const [vis, setVis] = useState(new Set());
  const [vSk, setVSk] = useState([]); const [vEn, setVEn] = useState([]); const [vWh, setVWh] = useState([]); const [vTe, setVTe] = useState([]); const [vSt, setVSt] = useState([]);
  const stR = useRef(null); const secR = useRef({});
  const skR = useRef(null); const enR = useRef(null); const whR = useRef(null); const teR = useRef(null); const stGr = useRef(null);
  useEffect(() => { if (!stR.current) return; const o = new IntersectionObserver(([e]) => { if (e.isIntersecting) { setSs(true); o.disconnect(); } }, { threshold: 0.4 }); o.observe(stR.current); return () => o.disconnect(); }, []);
  useEffect(() => { const pairs = [[skR, SKILLS.length, setVSk],[enR, 3, setVEn],[whR, WHY_CARDS.length, setVWh],[teR, 3, setVTe],[stGr, TECH_STACK.length, setVSt]]; const obs = pairs.map(([ref, count, setter]) => { if (!ref.current) return null; const o = new IntersectionObserver(([e]) => { if (e.isIntersecting) { Array.from({ length: count }, (_, i) => setTimeout(() => setter(p => p.includes(i) ? p : [...p, i]), i * 80)); o.disconnect(); } }, { threshold: 0.05 }); o.observe(ref.current); return o; }); return () => obs.forEach(o => o?.disconnect()); }, []);
  useEffect(() => { const ks = Object.keys(secR.current); const obs = ks.map(k => { const el = secR.current[k]; if (!el) return null; const o = new IntersectionObserver(([e]) => { if (e.isIntersecting) { setVis(p => new Set([...p, k])); o.disconnect(); } }, { threshold: 0.1 }); o.observe(el); return o; }); return () => obs.forEach(o => o?.disconnect()); }, []);
  const visSkills = showAll ? SKILLS : SKILLS.slice(0, 6);
  return (
    <>
      <Head>
        <title>Hire Data Scientist | Python, SQL, A/B Testing, Predictive Modelling | 1Solutions</title>
        <meta name="description" content="Hire expert data scientists from 1Solutions — EDA, statistical analysis, A/B testing, predictive modelling, customer analytics, SQL, Python, R, Tableau, and Snowflake/BigQuery/Redshift. Dedicated, part-time, or fixed-scope." />
        <link rel="canonical" href="https://www.1solutions.biz/hire-data-scientist/" />
        <meta property="og:title" content="Hire Data Scientist | Python, SQL, A/B Testing | 1Solutions" />
        <meta property="og:description" content="Hire vetted data scientists — EDA, hypothesis testing, A/B testing, predictive modelling, customer analytics, Python, SQL, Tableau, Snowflake, BigQuery." />
        <meta property="og:url" content="https://www.1solutions.biz/hire-data-scientist/" />
        <meta property="og:image" content="https://www.1solutions.biz/images/banner-1sol.jpg" />
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(SCHEMA) }} />
        <style>{`
          .hds-page{font-family:'Inter',-apple-system,BlinkMacSystemFont,sans-serif;background:linear-gradient(135deg,#eff6ff 0%,#dbeafe 20%,#ede9fe 50%,#fef3c7 75%,#f0f9ff 100%);color:#0F1F40;line-height:1.6;position:relative;overflow-x:hidden}
          .hds-page *,.hds-page *::before,.hds-page *::after{box-sizing:border-box}
          .hds-orb{position:absolute;border-radius:50%;pointer-events:none;z-index:0;filter:blur(20px)}
          .hds-o1{width:860px;height:860px;background:radial-gradient(circle,rgba(30,64,175,.20) 0%,rgba(59,130,246,.08) 40%,transparent 70%);top:-260px;right:-240px}
          .hds-o2{width:760px;height:760px;background:radial-gradient(circle,rgba(217,119,6,.15) 0%,rgba(251,191,36,.06) 40%,transparent 70%);bottom:0;left:-220px}
          .hds-o3{width:520px;height:520px;background:radial-gradient(circle,rgba(109,40,217,.12) 0%,transparent 70%);top:44%;left:-100px;transform:translateY(-50%)}
          .hds-bc{position:relative;z-index:2;padding:16px 40px 0;max-width:1440px;margin:0 auto}
          .hds-bc ol{display:flex;flex-wrap:wrap;gap:6px;list-style:none;margin:0;padding:0;font-size:13px;color:#6A80A0}
          .hds-bc li{display:flex;align-items:center;gap:6px}
          .hds-bc li::after{content:'/';opacity:.45}
          .hds-bc li:last-child::after{display:none}
          .hds-bc a{color:#0F3460;text-decoration:none}
          .hds-hero{position:relative;z-index:2;text-align:center;max-width:960px;margin:0 auto;padding:44px 40px 32px}
          .hds-ey{display:block;font-size:11px;font-weight:700;letter-spacing:2.5px;text-transform:uppercase;color:#4A6080;margin-bottom:14px}
          .hds-hero h1{font-size:50px;font-weight:900;line-height:1.09;letter-spacing:-1.5px;margin-bottom:16px;background:linear-gradient(90deg,#0F3460 0%,#1e40af 100%);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text}
          .hds-desc{font-size:16px;color:#3A507A;line-height:1.65;max-width:740px;margin:0 auto 24px}
          .hds-tr{display:flex;flex-wrap:wrap;justify-content:center;gap:10px;margin-bottom:26px}
          .hds-badge{display:inline-flex;align-items:center;gap:6px;background:rgba(255,255,255,.60);backdrop-filter:blur(10px);border:1px solid rgba(255,255,255,.85);border-radius:100px;padding:6px 14px;font-size:12px;font-weight:600;color:#0F3460;box-shadow:0 2px 8px rgba(15,52,96,.07)}
          .hds-dot{width:7px;height:7px;border-radius:50%;background:#1e40af;flex-shrink:0}
          .hds-ctas{display:flex;flex-wrap:wrap;gap:12px;justify-content:center}
          .hds-p{display:inline-block;padding:14px 36px;background:#1e40af;color:#fff;border-radius:50px;font-weight:700;font-size:15px;text-decoration:none;transition:all .25s;box-shadow:0 6px 24px rgba(30,64,175,.28)}
          .hds-p:hover{background:#0F3460;transform:translateY(-2px)}
          .hds-g{display:inline-block;padding:14px 36px;background:rgba(255,255,255,.55);backdrop-filter:blur(16px);border:1.5px solid rgba(255,255,255,.85);border-radius:50px;color:#0F3460;font-weight:700;font-size:15px;text-decoration:none;transition:all .25s}
          .hds-g:hover{background:rgba(255,255,255,.85);border-color:rgba(30,64,175,.5);transform:translateY(-2px)}
          .hds-stats{position:relative;z-index:2;display:grid;grid-template-columns:repeat(4,1fr);max-width:940px;margin:28px auto 0;background:rgba(255,255,255,.45);backdrop-filter:blur(24px);border:1px solid rgba(255,255,255,.85);box-shadow:0 4px 24px rgba(15,52,96,.08),inset 0 1px 0 rgba(255,255,255,.95)}
          .hds-sc{padding:18px 16px;text-align:center;border-right:1px solid rgba(15,52,96,.10)}
          .hds-sc:last-child{border-right:none}
          .hds-sv{font-size:28px;font-weight:900;color:#1e40af;letter-spacing:-.5px;line-height:1}
          .hds-sl{font-size:11px;color:#4A6080;font-weight:500;margin-top:5px}
          .hds-logos{position:relative;z-index:2;padding:24px 40px 52px;display:flex;flex-direction:column;align-items:center;gap:14px}
          .hds-ll{font-size:10px;font-weight:700;letter-spacing:2px;text-transform:uppercase;color:#6A80A0}
          .hds-lw{width:100%;overflow:hidden}
          .hds-lt{display:flex;align-items:center;gap:60px;width:max-content;animation:hds-mq 28s linear infinite}
          .hds-lt:hover{animation-play-state:paused}
          @keyframes hds-mq{0%{transform:translateX(0)}100%{transform:translateX(-50%)}}
          .hds-cl{height:24px;width:auto;max-width:110px;object-fit:contain;filter:grayscale(100%);opacity:.45;transition:opacity .25s,filter .25s}
          .hds-cl:hover{opacity:.85;filter:grayscale(0%)}
          .hds-sey{font-size:11px;font-weight:700;letter-spacing:2px;text-transform:uppercase;color:#D97706;margin-bottom:10px;display:block}
          .hds-st{font-size:46px;font-weight:900;line-height:1.12;letter-spacing:-1px;background:linear-gradient(90deg,#0F3460 0%,#D97706 100%);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;margin-bottom:10px}
          .hds-sd{font-size:15px;color:#4A6080;line-height:1.7}
          .hds-rv{opacity:0;transform:translateY(44px);transition:opacity .7s cubic-bezier(0.22,1,.36,1),transform .7s cubic-bezier(0.22,1,.36,1)}
          .hds-rv.hds-ok{opacity:1;transform:translateY(0)}
          .hds-in{max-width:1300px;margin:0 auto}
          .hds-sk-s{background:transparent;padding:72px 40px 60px;position:relative;z-index:1}
          .hds-sk-g{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-top:40px}
          .hds-sk-c{background:linear-gradient(135deg,rgba(239,246,255,.50) 0%,rgba(255,255,255,.85) 55%,rgba(219,234,254,.40) 100%);backdrop-filter:blur(16px);border:1px solid rgba(255,255,255,.85);border-radius:20px;padding:26px 22px 22px;position:relative;overflow:hidden;box-shadow:0 4px 24px rgba(15,52,96,.08),inset 0 1px 0 rgba(255,255,255,.95);opacity:0;transform:translateY(36px);transition:opacity .6s cubic-bezier(0.22,1,.36,1),transform .6s cubic-bezier(0.22,1,.36,1),border-color .2s}
          .hds-sk-c.hds-cv{opacity:1;transform:translateY(0)}
          .hds-sk-c.hds-cv:hover{transform:translateY(-6px);border-color:rgba(30,64,175,.30);box-shadow:0 16px 48px rgba(15,52,96,.14)}
          .hds-sk-c.feat{border-color:rgba(30,64,175,.20)}
          .hds-sk-n{position:absolute;top:8px;right:14px;font-size:72px;font-weight:900;line-height:1;color:#0F3460;opacity:.055;pointer-events:none;letter-spacing:-4px;user-select:none}
          .hds-sk-c h3{font-size:16px;font-weight:700;color:#0F1F40;margin:0 0 8px;position:relative;z-index:1}
          .hds-sk-c p{font-size:13px;color:#4A6080;line-height:1.65;margin:0;position:relative;z-index:1}
          .hds-sk-c::before{content:'';position:absolute;left:0;top:12%;height:76%;width:3px;background:linear-gradient(180deg,#1e40af,#3b82f6);border-radius:0 2px 2px 0;transform:scaleY(0);transform-origin:top center;transition:transform .3s cubic-bezier(0.22,1,.36,1)}
          .hds-sk-c.hds-cv:hover::before{transform:scaleY(1)}
          .hds-sm{text-align:center;margin-top:22px}
          .hds-bm{display:inline-block;background:#fff;border:1.5px solid rgba(15,52,96,.18);color:#0F3460;padding:10px 30px;border-radius:20px;font-weight:600;font-size:14px;cursor:pointer;transition:all .2s;font-family:inherit}
          .hds-bm:hover{background:#0F3460;border-color:#0F3460;color:#fff;transform:translateY(-2px)}
          .hds-tec-s{background:#f8fafd;border-top:1px solid rgba(15,52,96,.08);border-bottom:1px solid rgba(15,52,96,.08);padding:72px 40px;position:relative;z-index:1}
          .hds-tec-g{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin-top:40px}
          .hds-tec-c{background:linear-gradient(135deg,rgba(239,246,255,.50) 0%,rgba(255,255,255,.85) 55%,rgba(219,234,254,.40) 100%);backdrop-filter:blur(16px);border:1px solid rgba(255,255,255,.85);border-radius:20px;padding:22px 20px;box-shadow:0 4px 24px rgba(15,52,96,.08),inset 0 1px 0 rgba(255,255,255,.95);opacity:0;transform:translateY(32px);transition:opacity .55s cubic-bezier(0.22,1,.36,1),transform .55s cubic-bezier(0.22,1,.36,1),border-color .2s}
          .hds-tec-c.hds-sv2{opacity:1;transform:translateY(0)}
          .hds-tec-c.hds-sv2:hover{border-color:rgba(30,64,175,.25);box-shadow:0 14px 40px rgba(15,52,96,.12)}
          .hds-tg{font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:1.2px;margin-bottom:12px;padding-bottom:8px;border-bottom:2px solid}
          .hds-pills{display:flex;flex-wrap:wrap;gap:6px}
          .hds-pill{display:inline-block;font-size:11.5px;font-weight:500;padding:4px 10px;border-radius:100px;border:1px solid}
          .hds-en-s{padding:80px 40px;position:relative;z-index:1}
          .hds-en-g{display:grid;grid-template-columns:repeat(3,1fr);gap:20px;margin-top:40px}
          .hds-en-c{background:linear-gradient(135deg,rgba(239,246,255,.50) 0%,rgba(255,255,255,.85) 55%,rgba(219,234,254,.40) 100%);backdrop-filter:blur(16px);border:1px solid rgba(255,255,255,.85);border-radius:24px;padding:32px 28px;box-shadow:0 4px 24px rgba(15,52,96,.08),inset 0 1px 0 rgba(255,255,255,.95);opacity:0;transform:translateY(44px);transition:opacity .65s cubic-bezier(0.22,1,.36,1),transform .65s cubic-bezier(0.22,1,.36,1),border-color .2s}
          .hds-en-c.hds-ev{opacity:1;transform:translateY(0)}
          .hds-en-c.hds-ev:hover{border-color:rgba(30,64,175,.25);box-shadow:0 16px 48px rgba(15,52,96,.14)}
          .hds-en-c.feat{background:linear-gradient(135deg,rgba(254,243,199,.52) 0%,rgba(255,255,255,.87) 55%,rgba(239,246,255,.45) 100%);border-color:rgba(217,119,6,.28);box-shadow:0 8px 32px rgba(217,119,6,.12),inset 0 1px 0 rgba(255,255,255,1);transform:translateY(-8px)}
          .hds-en-c.feat.hds-ev{transform:translateY(-8px)}
          .hds-en-c.feat.hds-ev:hover{transform:translateY(-12px)}
          .hds-en-b{display:inline-block;font-size:10px;font-weight:700;letter-spacing:1.2px;text-transform:uppercase;padding:5px 12px;border-radius:100px;border:1px solid;margin-bottom:18px}
          .hds-en-i{width:48px;height:48px;background:rgba(15,52,96,.07);border-radius:14px;display:flex;align-items:center;justify-content:center;margin-bottom:14px}
          .hds-en-i svg{fill:#0F3460}
          .hds-en-c.feat .hds-en-i{background:rgba(217,119,6,.10)}
          .hds-en-c.feat .hds-en-i svg{fill:#D97706}
          .hds-en-n{font-size:22px;font-weight:900;color:#0F3460;margin:0 0 6px;letter-spacing:-.3px}
          .hds-en-h{font-size:13px;font-weight:600;color:#1e40af;margin-bottom:12px}
          .hds-en-c.feat .hds-en-h{color:#D97706}
          .hds-en-d{font-size:14px;color:#4A6080;line-height:1.7;margin-bottom:18px}
          .hds-en-ll{font-size:10px;font-weight:700;letter-spacing:1px;text-transform:uppercase;color:#6A80A0;margin-bottom:8px}
          .hds-en-li{list-style:none;padding:0;margin:0 0 18px;display:flex;flex-direction:column;gap:7px}
          .hds-en-li li{display:flex;align-items:flex-start;gap:8px;font-size:13px;color:#374151;line-height:1.5}
          .hds-en-li li::before{content:'✓';font-weight:800;color:#1e40af;flex-shrink:0;margin-top:1px}
          .hds-en-c.feat .hds-en-li li::before{color:#D97706}
          .hds-en-p{font-size:12px;color:#6A80A0;padding-top:14px;border-top:1px solid rgba(15,52,96,.08)}
          .hds-en-p strong{color:#0F3460}
          .hds-en-tl{display:inline-block;font-size:11px;font-weight:600;color:#D97706;margin-top:6px}
          .hds-en-a{display:block;margin-top:18px;padding:11px;border-radius:50px;font-size:13px;font-weight:700;text-align:center;text-decoration:none;transition:all .22s;background:rgba(15,52,96,.09);color:#0F3460;border:1.5px solid rgba(15,52,96,.18)}
          .hds-en-a:hover{background:#0F3460;color:#fff}
          .hds-en-c.feat .hds-en-a{background:#1e40af;color:#fff;border-color:#1e40af}
          .hds-en-c.feat .hds-en-a:hover{background:#0F3460;border-color:#0F3460}
          .hds-pr-s{background:#f8fafd;border-top:1px solid rgba(15,52,96,.08);border-bottom:1px solid rgba(15,52,96,.08);padding:80px 40px;position:relative;z-index:1}
          .hds-ps{display:flex;flex-direction:column;margin-top:52px}
          .hds-ps-row{display:grid;grid-template-columns:56px 1fr;gap:0 20px;opacity:0;transform:translateY(48px);transition:opacity .65s cubic-bezier(0.22,1,.36,1),transform .65s cubic-bezier(0.22,1,.36,1)}
          .hds-ps-row.hds-pv{opacity:1;transform:translateY(0)}
          .hds-ps-l{display:flex;flex-direction:column;align-items:center}
          .hds-ps-ci{width:52px;height:52px;border-radius:50%;background:rgba(255,255,255,.65);backdrop-filter:blur(8px);border:2px solid rgba(15,52,96,.18);display:flex;align-items:center;justify-content:center;font-size:19px;font-weight:800;color:#0F3460;flex-shrink:0}
          .hds-ps-row.hds-pv:hover .hds-ps-ci{background:rgba(30,64,175,.10);border-color:#1e40af;color:#1e40af}
          .hds-ps-co{flex:1;display:flex;flex-direction:column;align-items:center;padding:6px 0;min-height:42px}
          .hds-ps-co::before{content:'';width:2px;flex:1;background:#0F3460;opacity:.22}
          .hds-ps-co::after{content:'';border-left:6px solid transparent;border-right:6px solid transparent;border-top:8px solid #0F3460;opacity:.40}
          .hds-ps-row:last-child .hds-ps-co{display:none}
          .hds-ps-r{padding:4px 0 38px}
          .hds-ps-row:last-child .hds-ps-r{padding-bottom:0}
          .hds-ps-t{font-size:20px;font-weight:700;color:#0F3460;margin:0 0 9px}
          .hds-ps-d{font-size:15px;color:#4A6080;line-height:1.75;margin:0}
          .hds-te-s{background:transparent;padding:80px 40px;position:relative;z-index:1}
          .hds-ch{text-align:center;margin-bottom:48px}
          .hds-tg2{display:grid;grid-template-columns:repeat(3,1fr);gap:24px}
          .hds-tc{background:linear-gradient(135deg,rgba(239,246,255,.50) 0%,rgba(255,255,255,.85) 55%,rgba(219,234,254,.40) 100%);backdrop-filter:blur(16px);border:1px solid rgba(255,255,255,.85);border-radius:20px;padding:28px 24px;display:flex;flex-direction:column;gap:12px;box-shadow:0 4px 24px rgba(15,52,96,.08),inset 0 1px 0 rgba(255,255,255,.95);opacity:0;transform:translateY(40px);transition:opacity .6s cubic-bezier(0.22,1,.36,1),transform .6s cubic-bezier(0.22,1,.36,1)}
          .hds-tc.feat{background:linear-gradient(135deg,rgba(254,243,199,.52) 0%,rgba(255,255,255,.87) 55%,rgba(239,246,255,.42) 100%);border-color:rgba(217,119,6,.22)}
          .hds-tc.hds-tv{opacity:1;transform:translateY(0)}
          .hds-tc.hds-tv:hover{transform:translateY(-6px);box-shadow:0 16px 48px rgba(15,52,96,.14)}
          .hds-stars{font-size:16px;color:#D97706;letter-spacing:2px}
          .hds-txt{font-size:14px;line-height:1.75;color:#374151;flex:1}
          .hds-au{display:flex;align-items:center;gap:12px}
          .hds-av{width:42px;height:42px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:13px;font-weight:800;color:#fff;flex-shrink:0}
          .hds-an{font-size:14px;font-weight:700;color:#0F3460}
          .hds-ar{font-size:12px;color:#6b7280}
          .hds-wy-s{background:#f8fafd;border-top:1px solid rgba(15,52,96,.08);border-bottom:1px solid rgba(15,52,96,.08);padding:80px 40px;position:relative;z-index:1}
          .hds-wy-g{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin-top:48px}
          .hds-wc{background:linear-gradient(135deg,rgba(239,246,255,.50) 0%,rgba(255,255,255,.85) 55%,rgba(219,234,254,.40) 100%);backdrop-filter:blur(16px);border:1px solid rgba(255,255,255,.85);border-radius:20px;padding:26px 22px;box-shadow:0 4px 24px rgba(15,52,96,.08),inset 0 1px 0 rgba(255,255,255,.95);opacity:0;transform:translateY(32px) scale(.97);transition:opacity .55s cubic-bezier(0.22,1,.36,1),transform .55s cubic-bezier(0.22,1,.36,1),border-color .2s}
          .hds-wc.hds-wv{opacity:1;transform:translateY(0) scale(1)}
          .hds-wc.hds-wv:hover{transform:translateY(-5px) scale(1);border-color:rgba(30,64,175,.25);box-shadow:0 14px 40px rgba(15,52,96,.12)}
          .hds-wd{width:10px;height:10px;border-radius:50%;background:#1e40af;margin-bottom:12px}
          .hds-wc h3{font-size:14px;font-weight:700;color:#0F1F40;margin:0 0 8px;line-height:1.35}
          .hds-wc p{font-size:13px;color:#4A6080;line-height:1.65;margin:0}
          .hds-ct-s{padding:70px 40px;background:linear-gradient(135deg,rgba(239,246,255,.55) 0%,rgba(255,255,255,.60) 40%,rgba(219,234,254,.55) 100%);backdrop-filter:blur(20px);border-top:1px solid rgba(255,255,255,.80);position:relative;z-index:1}
          .hds-ct-g{max-width:1440px;margin:0 auto;display:grid;grid-template-columns:1fr 1.15fr;gap:32px;align-items:start}
          .hds-ctt{font-size:42px;font-weight:900;line-height:1.18;margin:0 0 14px;background:linear-gradient(90deg,#0F3460 0%,#1e40af 100%);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text}
          .hds-ctd{font-size:14px;color:#4A6080;line-height:1.6;margin:0 0 22px}
          .hds-ben{background:rgba(255,255,255,.70);border:1px solid rgba(255,255,255,.90);border-radius:14px;padding:22px;backdrop-filter:blur(12px);display:flex;flex-direction:column;gap:14px}
          .hds-be{display:flex;gap:10px;align-items:flex-start}
          .hds-bi{flex-shrink:0;color:#1e40af;font-weight:800;font-size:16px;margin-top:1px}
          .hds-be p{font-size:13px;color:#4A6080;margin:0;line-height:1.55}
          .hds-fb{background:linear-gradient(135deg,rgba(255,255,255,.88) 0%,rgba(239,246,255,.18) 50%,rgba(255,255,255,.84) 100%);backdrop-filter:blur(20px);border:1px solid rgba(255,255,255,.92);border-radius:20px;padding:34px;box-shadow:0 8px 40px rgba(15,52,96,.10),inset 0 1px 0 rgba(255,255,255,1)}
          .hds-fb h3{font-size:22px;font-weight:700;color:#0F1F40;margin:0 0 22px;letter-spacing:-.3px}
          .hds-form{display:flex;flex-direction:column;gap:13px}
          .hds-fr{display:grid;grid-template-columns:1fr 1fr;gap:12px}
          .hds-fg{display:flex;flex-direction:column;gap:5px}
          .hds-fg.full{grid-column:1/-1}
          .hds-fg label{font-size:12px;font-weight:500;color:#0F1F40}
          .hds-fg input,.hds-fg textarea,.hds-fg select{padding:10px 13px;border:1px solid rgba(15,52,96,.14);border-radius:6px;font-size:13px;font-family:inherit;color:#0F1F40;background:rgba(255,255,255,.55);transition:border-color .2s}
          .hds-fg input:focus,.hds-fg textarea:focus,.hds-fg select:focus{outline:none;border-color:#1e40af;box-shadow:0 0 0 3px rgba(30,64,175,.10)}
          .hds-co{display:flex;gap:8px;align-items:flex-start}
          .hds-co input{margin-top:3px;width:15px;height:15px}
          .hds-co label{font-size:11px;color:#4A6080;line-height:1.5}
          .hds-co a{color:#0F3460}
          .hds-sub{width:100%;padding:14px;background:#1e40af;border:none;color:#fff;border-radius:50px;font-weight:700;font-size:15px;cursor:pointer;font-family:inherit;transition:all .25s;box-shadow:0 6px 24px rgba(30,64,175,.26)}
          .hds-sub:hover{background:#0F3460;transform:translateY(-2px)}
          .hds-fq-s{padding:80px 40px;background:#f8fafd;border-top:1px solid rgba(15,52,96,.08);position:relative;z-index:1}
          .hds-fq-s h2{font-size:46px;font-weight:900;letter-spacing:-1px;background:linear-gradient(90deg,#0F3460 0%,#D97706 100%);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;margin:0 0 8px}
          .hds-fq-sub{font-size:15px;color:#4A6080;margin:0 0 36px}
          .hds-fql{display:flex;flex-direction:column;gap:10px}
          .hds-fi{background:linear-gradient(135deg,rgba(239,246,255,.50) 0%,rgba(255,255,255,.85) 55%,rgba(219,234,254,.40) 100%);backdrop-filter:blur(16px);border:1px solid rgba(255,255,255,.85);border-radius:14px;overflow:hidden;box-shadow:0 4px 20px rgba(15,52,96,.06);transition:border-color .2s}
          .hds-fi.open{border-color:rgba(30,64,175,.30)}
          .hds-fi.open::before{content:'';display:block;height:3px;background:linear-gradient(90deg,#1e40af,#3b82f6);border-radius:3px 3px 0 0}
          .hds-fqb{width:100%;background:none;border:none;padding:20px 20px 20px 58px;display:flex;align-items:center;justify-content:space-between;cursor:pointer;text-align:left;gap:14px;font-family:inherit;position:relative}
          .hds-fqb2{position:absolute;left:16px;top:50%;transform:translateY(-50%);width:26px;height:26px;background:rgba(15,52,96,.08);color:#374151;font-size:11px;font-weight:700;display:flex;align-items:center;justify-content:center;border-radius:6px}
          .hds-fi.open .hds-fqb2{background:#1e40af;color:#fff}
          .hds-fqb span{font-size:15px;font-weight:600;color:#0F1F40;line-height:1.4}
          .hds-fi.open .hds-fqb span{color:#1d4ed8}
          .hds-fch{width:22px;height:22px;flex-shrink:0;color:#9ca3af;transition:transform .3s}
          .hds-fi.open .hds-fch{transform:rotate(180deg);color:#1e40af}
          .hds-faw{overflow:hidden;transition:max-height .35s ease;max-height:0}
          .hds-fi.open .hds-faw{max-height:500px}
          .hds-fa{padding:0 20px 20px 58px;font-size:14px;color:#4b5563;line-height:1.8}
          .hds-rel{padding:80px 40px;background:rgba(239,246,255,.14);backdrop-filter:blur(10px);border-top:1px solid rgba(255,255,255,.60)}
          .hds-ri{max-width:1300px;margin:0 auto;text-align:center}
          .hds-ri h2{font-size:34px;font-weight:900;background:linear-gradient(90deg,#0F3460 0%,#D97706 100%);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;margin:10px 0 12px}
          .hds-rs{font-size:14px;color:#4A6080;margin:0 auto;max-width:560px}
          .hds-ri hr{border:none;border-top:1px solid rgba(15,52,96,.10);margin:32px 0}
          .hds-rts{display:flex;flex-wrap:wrap;justify-content:center;gap:10px}
          .hds-rt{display:inline-block;padding:10px 20px;border:1.5px solid;border-radius:50px;font-size:14px;font-weight:500;text-decoration:none;transition:all .22s}
          .hds-rt:hover{transform:translateY(-2px);box-shadow:0 6px 18px rgba(0,0,0,.09)}
          .hds-b{background:rgba(30,64,175,.09);border-color:rgba(30,64,175,.28);color:#1e3a8a}
          .hds-v{background:rgba(109,40,217,.09);border-color:rgba(109,40,217,.28);color:#4c1d95}
          .hds-fu{background:rgba(162,28,175,.09);border-color:rgba(162,28,175,.28);color:#86198f}
          .hds-o{background:rgba(249,115,22,.09);border-color:rgba(249,115,22,.28);color:#c2410c}
          .hds-a{background:rgba(202,138,4,.09);border-color:rgba(202,138,4,.28);color:#92400e}
          @media(max-width:1024px){.hds-hero h1,.hds-st,.hds-fq-s h2{font-size:36px}.hds-sk-g{grid-template-columns:repeat(2,1fr)}.hds-tec-g{grid-template-columns:repeat(2,1fr)}.hds-en-g{grid-template-columns:1fr;max-width:480px;margin-left:auto;margin-right:auto}.hds-en-c.feat{transform:none}.hds-en-c.feat.hds-ev{transform:none}.hds-en-c.feat.hds-ev:hover{transform:translateY(-4px)}.hds-wy-g{grid-template-columns:repeat(2,1fr)}.hds-tg2{grid-template-columns:1fr}.hds-ct-g{grid-template-columns:1fr}}
          @media(max-width:768px){.hds-bc,.hds-hero,.hds-sk-s,.hds-tec-s,.hds-en-s,.hds-pr-s,.hds-te-s,.hds-wy-s,.hds-fq-s,.hds-rel{padding-left:20px;padding-right:20px}.hds-hero{padding-top:28px;padding-bottom:20px}.hds-hero h1{font-size:26px;letter-spacing:-.3px}.hds-stats{grid-template-columns:1fr 1fr}.hds-sc:nth-child(2){border-right:none}.hds-sc:nth-child(3),.hds-sc:nth-child(4){border-top:1px solid rgba(15,52,96,.10)}.hds-sc:nth-child(4){border-right:none}.hds-sk-g,.hds-tec-g,.hds-wy-g{grid-template-columns:1fr}.hds-fr{grid-template-columns:1fr}.hds-ctt{font-size:28px}.hds-st{font-size:28px}.hds-ct-s{padding:48px 20px}.hds-logos{padding-left:20px;padding-right:20px}}
        `}</style>
      </Head>
      <div className="hds-page">
        <div className="hds-orb hds-o1" /><div className="hds-orb hds-o2" /><div className="hds-orb hds-o3" />
        <nav className="hds-bc" aria-label="Breadcrumb"><ol itemScope itemType="https://schema.org/BreadcrumbList"><li itemScope itemType="https://schema.org/ListItem" itemProp="itemListElement"><Link href="/" itemProp="item"><span itemProp="name">Home</span></Link><meta itemProp="position" content="1" /></li><li itemScope itemType="https://schema.org/ListItem" itemProp="itemListElement"><span itemProp="name">Hire Data Scientist</span><meta itemProp="position" content="2" /></li></ol></nav>
        <section className="hds-hero">
          <span className="hds-ey">Hire Data Scientist</span>
          <h1>Hire Expert Data Scientists — Python, SQL, A/B Testing & Predictive Modelling</h1>
          <p className="hds-desc">Hire pre-vetted data scientists specialising in EDA, statistical analysis, A/B testing and experimentation design, predictive modelling, customer analytics, Python, R, SQL (Snowflake, BigQuery, Redshift), and Tableau/Looker dashboards. Dedicated, part-time, or fixed-scope. Start in 3–5 business days.</p>
          <div className="hds-tr">{['EDA & Statistical Analysis','A/B Testing & Experimentation','Predictive Modelling','Python / R','SQL & Data Warehouses'].map(b => (<div className="hds-badge" key={b}><span className="hds-dot" />{b}</div>))}</div>
          <div className="hds-ctas"><Link href="#contact" className="hds-p">Hire a Data Scientist</Link><Link href="#engagement" className="hds-g">View Engagement Models →</Link></div>
        </section>
        <div className="hds-stats" ref={stR}>{[['110+','Data Science Projects'],['15+','Years Dev Experience'],['48hr','Avg Scientist Match'],['98%','Client Retention']].map(([v, l]) => (<StatItem key={l} label={l} val={v} started={ss} />))}</div>
        <div className="hds-logos"><span className="hds-ll">Trusted by Data & Analytics Teams</span><div className="hds-lw"><div className="hds-lt">{[['/logo/Indian_Express_Logo_full.png','Indian Express'],['/logo/Verizon_2015_logo_-vector.svg.png','Verizon'],['/logo/Uniphore.jpg','Uniphore'],['/logo/ICCoLogo.png','ICC'],['/logo/Honor_Logo_(2020).svg.png','Honor'],['/logo/Zuari-Finserv-logo-new.png','Zuari Finserv'],['/logo/Indian_Express_Logo_full.png','Indian Express 2'],['/logo/Verizon_2015_logo_-vector.svg.png','Verizon 2'],['/logo/Uniphore.jpg','Uniphore 2'],['/logo/ICCoLogo.png','ICC 2'],['/logo/Honor_Logo_(2020).svg.png','Honor 2'],['/logo/Zuari-Finserv-logo-new.png','Zuari Finserv 2']].map(([src, alt]) => (<img key={alt} src={src} alt={alt.replace(/ \d$/, '')} className="hds-cl" />))}</div></div></div>
        <section className="hds-sk-s" aria-labelledby="hds-sk-h"><div className="hds-in"><div className={`hds-rv${vis.has('sk') ? ' hds-ok' : ''}`} ref={el => { secR.current['sk'] = el; }}><span className="hds-sey">What Our Data Scientists Do</span><h2 id="hds-sk-h" className="hds-st">Data Science Skills & Expertise</h2><p className="hds-sd" style={{ maxWidth: 720 }}>EDA, statistical analysis, A/B testing, predictive modelling, SQL analytics, data visualisation, customer analytics, financial analytics, Python and R data science stack, and data strategy consulting.</p></div><div className="hds-sk-g" ref={skR}>{visSkills.map((s, i) => (<div key={s.n} className={`hds-sk-c${s.feat ? ' feat' : ''}${vSk.includes(i) ? ' hds-cv' : ''}`} style={{ transitionDelay: `${i * 55}ms` }}><span className="hds-sk-n">{s.n}</span><h3>{s.title}</h3><p>{s.desc}</p></div>))}</div>{SKILLS.length > 6 && (<div className="hds-sm"><button className="hds-bm" onClick={() => setShowAll(p => !p)}>{showAll ? 'Show fewer ↑' : `Show all ${SKILLS.length} areas ↓`}</button></div>)}</div></section>
        <section className="hds-tec-s" aria-labelledby="hds-tec-h"><div className="hds-in"><div className={`hds-rv${vis.has('stk') ? ' hds-ok' : ''}`} ref={el => { secR.current['stk'] = el; }}><span className="hds-sey">Technology Stack</span><h2 id="hds-tec-h" className="hds-st">Data Science Tools & Technologies</h2><p className="hds-sd" style={{ maxWidth: 680 }}>Python (Pandas, NumPy, scikit-learn, statsmodels, PyMC), SQL (Snowflake, BigQuery, Redshift, dbt), R (ggplot2, survival, lme4), Tableau, Looker, Power BI, XGBoost, SHAP, Prophet, Plotly, and Evidently AI.</p></div><div className="hds-tec-g" ref={stGr}>{TECH_STACK.map((grp, i) => (<div key={grp.group} className={`hds-tec-c${vSt.includes(i) ? ' hds-sv2' : ''}`} style={{ transitionDelay: `${i * 60}ms` }}><div className="hds-tg" style={{ color: grp.color, borderBottomColor: grp.color + '33' }}>{grp.group}</div><div className="hds-pills">{grp.items.map(item => <span key={item} className="hds-pill" style={{ color: grp.color, background: grp.color + '12', borderColor: grp.color + '30' }}>{item}</span>)}</div></div>))}</div></div></section>
        <section id="engagement" className="hds-en-s" aria-labelledby="hds-en-h"><div className="hds-in"><div className={`hds-rv${vis.has('eng') ? ' hds-ok' : ''}`} ref={el => { secR.current['eng'] = el; }}><span className="hds-sey">Engagement Models</span><h2 id="hds-en-h" className="hds-st">How to Hire a Data Scientist</h2><p className="hds-sd" style={{ maxWidth: 680 }}>Full-time dedicated data scientist, part-time specialist, or fixed-scope analytical project — structured for your data maturity and analytical objectives.</p></div><div className="hds-en-g" ref={enR}>{ENGAGEMENT_MODELS.map((m, i) => (<div key={m.id} className={`hds-en-c${m.feat ? ' feat' : ''}${vEn.includes(i) ? ' hds-ev' : ''}`} style={{ transitionDelay: `${i * 100}ms` }}><span className="hds-en-b" style={{ color: m.badgeColor, borderColor: m.badgeColor + '44', background: m.badgeColor + '14' }}>{m.badge}</span><div className="hds-en-i"><svg viewBox="0 0 24 24" width="26" height="26"><path d={m.icon} /></svg></div><div className="hds-en-n">{m.name}</div><div className="hds-en-h">{m.headline}</div><div className="hds-en-d">{m.desc}</div><div className="hds-en-ll">Best for</div><ul className="hds-en-li">{m.bestFor.map(b => <li key={b}>{b}</li>)}</ul><div className="hds-en-p"><strong>Process:</strong> {m.process}<br /><span className="hds-en-tl">{m.timeline}</span></div><Link href="#contact" className="hds-en-a">Get a free estimate →</Link></div>))}</div></div></section>
        <section className="hds-pr-s" aria-labelledby="hds-pr-h"><div className="hds-in" style={{ maxWidth: 760 }}><div className={`hds-rv${vis.has('proc') ? ' hds-ok' : ''}`} ref={el => { secR.current['proc'] = el; }}><span className="hds-sey">How We Hire</span><h2 id="hds-pr-h" className="hds-st">Our Data Scientist Hiring Process</h2><p className="hds-sd">From analytical question to first insight in 3–5 business days — domain-matched vetting, data audit, rigorous statistical analysis, and stakeholder-ready deliverables.</p></div><div className="hds-ps">{PROCESS_STEPS.map((step, i) => (<div key={step.num} className={`hds-ps-row${vis.has('proc') ? ' hds-pv' : ''}`} style={{ transitionDelay: `${i * 120}ms` }}><div className="hds-ps-l"><div className="hds-ps-ci">{step.num}</div><div className="hds-ps-co" /></div><div className="hds-ps-r"><div className="hds-ps-t">{step.title}</div><p className="hds-ps-d">{step.desc}</p></div></div>))}</div></div></section>
        <section className="hds-te-s" aria-labelledby="hds-te-h"><div className="hds-in"><div className={`hds-ch hds-rv${vis.has('ts') ? ' hds-ok' : ''}`} ref={el => { secR.current['ts'] = el; }}><span className="hds-sey">Client Results</span><h2 id="hds-te-h" className="hds-st">What Our Clients Say</h2><p className="hds-sd">Analytics directors, customer success leads, and VP Supply Chain roles across the UK, AU, and US on hiring data scientists from 1Solutions.</p></div><div className="hds-tg2" ref={teR}>{TESTIMONIALS.map((t, i) => (<div key={i} className={`hds-tc${t.feat ? ' feat' : ''}${vTe.includes(i) ? ' hds-tv' : ''}`} style={{ transitionDelay: `${i * 100}ms` }} itemScope itemType="https://schema.org/Review"><div className="hds-stars">★★★★★</div><p className="hds-txt" itemProp="reviewBody">{t.text}</p><div className="hds-au"><div className="hds-av" style={{ background: t.bg }}>{t.init}</div><div><div className="hds-an" itemProp="author">{t.name}</div><div className="hds-ar">{t.role}</div></div></div></div>))}</div></div></section>
        <section className="hds-wy-s" aria-labelledby="hds-wy-h"><div className="hds-in"><div className={`hds-rv${vis.has('wy') ? ' hds-ok' : ''}`} ref={el => { secR.current['wy'] = el; }}><span className="hds-sey">Why 1Solutions</span><h2 id="hds-wy-h" className="hds-st">Why Hire Data Scientists From 1Solutions</h2><p className="hds-sd" style={{ maxWidth: 680 }}>Statistical rigour, business question first, A/B testing depth, domain-specific methods, reproducible analysis, causation awareness, stakeholder communication, and data quality honesty.</p></div><div className="hds-wy-g" ref={whR}>{WHY_CARDS.map((c, i) => (<div key={i} className={`hds-wc${vWh.includes(i) ? ' hds-wv' : ''}`} style={{ transitionDelay: `${i * 60}ms` }}><div className="hds-wd" /><h3>{c.title}</h3><p>{c.desc}</p></div>))}</div></div></section>
        <section id="contact" className="hds-ct-s" aria-labelledby="hds-ct-h"><div className="hds-ct-g"><div><h2 id="hds-ct-h" className="hds-ctt">Hire a Data Scientist Today</h2><p className="hds-ctd">Share your data science questions — the business questions you need answered, your data sources, current analytical capability, and timeline — and we will shortlist pre-vetted data scientists within 24 business hours matched to your domain and analytical problem type.</p><div className="hds-ben">{[['✓','Shortlisted data scientists within 24 business hours'],['✓','Domain-matched — SaaS analytics, e-commerce, fintech, supply chain'],['✓','Full-time, part-time, or fixed-scope — flexible engagement'],['✓','Data audit before analysis begins'],['✓','5-day rapid replacement guarantee']].map(([icon, text]) => (<div className="hds-be" key={text}><span className="hds-bi">{icon}</span><p>{text}</p></div>))}</div></div>
        <div className="hds-fb"><h3>Tell Us Your Data Science Questions</h3><form className="hds-form" onSubmit={e => e.preventDefault()}>
          <div className="hds-fr"><div className="hds-fg"><label htmlFor="hds-nm">Full Name *</label><input id="hds-nm" type="text" placeholder="Your name" required /></div><div className="hds-fg"><label htmlFor="hds-em">Work Email *</label><input id="hds-em" type="email" placeholder="you@company.com" required /></div></div>
          <div className="hds-fr"><div className="hds-fg"><label htmlFor="hds-co">Company Name</label><input id="hds-co" type="text" placeholder="Your company" /></div><div className="hds-fg"><label htmlFor="hds-ph">Phone / WhatsApp</label><input id="hds-ph" type="tel" placeholder="+1 555 000 0000" /></div></div>
          <div className="hds-fg full"><label htmlFor="hds-en">Engagement Type *</label><select id="hds-en" required><option value="">Select engagement...</option><option>Full-Time Dedicated Data Scientist (160 hrs/month)</option><option>Part-Time Data Scientist (80 hrs/month)</option><option>Fixed-Scope Data Science Project</option></select></div>
          <div className="hds-fg full"><label htmlFor="hds-ty">Primary Analytics Need *</label><select id="hds-ty" required><option value="">Select analytics type...</option><option>A/B Testing & Experimentation Design</option><option>Customer Segmentation & Analytics</option><option>Churn Prediction & Propensity Modelling</option><option>Demand / Revenue Forecasting</option><option>EDA & Statistical Analysis</option><option>Product Analytics (funnel, retention, LTV)</option><option>Financial Analytics & Reporting</option><option>Dashboard & BI Reporting</option><option>Multiple / Not sure yet</option></select></div>
          <div className="hds-fg full"><label htmlFor="hds-dw">Data Warehouse / Database</label><select id="hds-dw"><option value="">Select data source...</option><option>Snowflake</option><option>BigQuery</option><option>Redshift</option><option>PostgreSQL / MySQL</option><option>Databricks</option><option>dbt + warehouse</option><option>Flat files / Spreadsheets</option><option>Multiple / Other</option></select></div>
          <div className="hds-fg full"><label htmlFor="hds-ms">Project Description *</label><textarea id="hds-ms" rows={4} placeholder="Describe the business questions you want to answer with data, your data sources, current analytical capability, industry context, and timeline..." required /></div>
          <div className="hds-co"><input id="hds-co2" type="checkbox" required /><label htmlFor="hds-co2">I agree to the <Link href="/privacy-policy">Privacy Policy</Link>. Details are treated confidentially.</label></div>
          <button type="submit" className="hds-sub">Get Shortlisted Data Scientists →</button>
        </form></div></div></section>
        <section className="hds-fq-s" aria-labelledby="hds-fq-h"><div className="hds-in" style={{ maxWidth: 860 }}><span className="hds-sey">FAQ</span><h2 id="hds-fq-h">Hiring Data Scientists — FAQ</h2><p className="hds-fq-sub">Common questions about hiring data scientists — what they do, statistical methods, A/B testing, tools, big data, visualisation, and data warehouse compatibility.</p><div className="hds-fql">{FAQS.map((item, i) => (<div key={i} className={`hds-fi${openFaq === i ? ' open' : ''}`} itemScope itemType="https://schema.org/Question"><button className="hds-fqb" onClick={() => setOpenFaq(openFaq === i ? -1 : i)} aria-expanded={openFaq === i}><div className="hds-fqb2">{String(i + 1).padStart(2, '0')}</div><span itemProp="name">{item.q}</span><svg className="hds-fch" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2"><polyline points="6 9 12 15 18 9" /></svg></button><div className="hds-faw" itemScope itemType="https://schema.org/Answer"><div className="hds-fa" itemProp="text">{item.a}</div></div></div>))}</div></div></section>
        <section className="hds-rel"><div className="hds-ri"><span className="hds-sey">Explore More</span><h2>Related Hire Developer Pages</h2><p className="hds-rs">We also provide dedicated AI, ML, Salesforce, and cloud engineering specialists for data-driven businesses worldwide.</p><hr /><div className="hds-rts">{[['/hire-ai-developer/','Hire AI Developer','hds-v'],['/hire-ml-developer/','Hire ML Developer','hds-fu'],['/hire-salesforce-developer/','Hire Salesforce Developer','hds-b'],['/hire-blockchain-developer/','Hire Blockchain Developer','hds-o'],['/hire-ar-developer/','Hire AR Developer','hds-v'],['/devops-services-company/','DevOps Services','hds-a'],['/cloud-native-services/','Cloud Native Services','hds-v'],['/software-development-company/','Software Development','hds-b']].map(([href, label, cls]) => (<Link key={href} href={href} className={`hds-rt ${cls}`}>{label}</Link>))}</div></div></section>
      </div>
    </>
  );
}
