'use client';
import { useState, useEffect, useRef } from 'react';
import Head from 'next/head';
import Link from 'next/link';

const SCHEMA = {
  '@context': 'https://schema.org',
  '@graph': [
    { '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Home', item: 'https://www.1solutions.biz/' }, { '@type': 'ListItem', position: 2, name: 'Software Development Cost Optimization', item: 'https://www.1solutions.biz/software-development-cost-optimization/' }] },
    { '@type': 'Service', name: 'Software Development Cost Optimization', url: 'https://www.1solutions.biz/software-development-cost-optimization/', description: '1Solutions software development cost optimization — reduce engineering spend through offshore team transition, cloud cost reduction, technical debt elimination, process automation, test automation ROI, and architecture rationalization. Typical engagements reduce software development costs by 40–65% within 90 days.', provider: { '@type': 'Organization', name: '1Solutions', url: 'https://www.1solutions.biz', logo: { '@type': 'ImageObject', url: 'https://www.1solutions.biz/images/1solutions-logo.png' }, foundingDate: '2008', areaServed: ['US', 'GB', 'AU', 'CA', 'IN'] }, aggregateRating: { '@type': 'AggregateRating', ratingValue: '4.9', reviewCount: '67', bestRating: '5' } },
    { '@type': 'FAQPage', mainEntity: [
      { '@type': 'Question', name: 'What does software development cost optimization involve?', acceptedAnswer: { '@type': 'Answer', text: 'Software development cost optimization involves systematically identifying and reducing the largest drivers of software engineering expenditure without sacrificing product quality, delivery speed, or system reliability. The main cost levers are: (1) Engineering labour cost — the largest single cost for most software teams. Transitioning to offshore or nearshore talent for roles that do not require local presence (most development, QA, DevOps, data engineering) can reduce this by 60–70%. (2) Cloud infrastructure spend — typically 15–30% of total software costs. Cloud cost optimisation through right-sizing, reserved instance purchasing, spot instance usage, autoscaling, and wasteful resource elimination typically saves 20–40% of cloud bills. (3) Technical debt — hidden costs that slow development velocity without appearing as direct line items. Each feature takes longer to build because the codebase is harder to change, and regressions are more frequent. (4) Process inefficiency — manual processes that could be automated, redundant tooling, inadequate test coverage causing expensive bug fixing cycles, and poor sprint planning leading to rework.' } },
      { '@type': 'Question', name: 'How much can software development costs be reduced?', acceptedAnswer: { '@type': 'Answer', text: 'Achievable savings vary significantly by starting point, but typical results from our cost optimization engagements: Labour cost reduction (offshore transition of appropriate roles): 55–70% reduction in engineering labour cost for transitioned roles. A 5-person engineering team transitioning 3 of 5 roles offshore saves $400,000–$600,000 per year. Cloud cost reduction: 20–40% reduction in monthly cloud spend, typically achieved within 30–60 days. For a company spending $30,000/month on AWS, this is $6,000–$12,000/month or $72,000–$144,000/year. Technical debt elimination: 25–40% improvement in development velocity (more features delivered per sprint) and 30–50% reduction in production incidents, which reduces expensive on-call engineering time and customer support costs. Test automation: manual QA that takes 40 hours per release cycle can be reduced to 8–12 hours with a comprehensive automated test suite — a 70–80% reduction in QA man-hours for each release.' } },
      { '@type': 'Question', name: 'What is the ROI of switching to offshore development?', acceptedAnswer: { '@type': 'Answer', text: 'The ROI of switching appropriate development roles to offshore depends on current team composition and costs, but the typical calculation for a US company: current annual cost of a 5-person senior development team (US market) — $1,100,000–$1,500,000 (salary + benefits + employer taxes + office + equipment). Equivalent 5-person offshore senior team through 1Solutions — $200,000–$350,000 per year all-inclusive. Annual saving — $750,000–$1,150,000. Setup and transition cost (3–6 months of overlap, onboarding, tooling) — typically $50,000–$120,000 one-time. Payback period — 1–2 months of savings covers the transition cost. 5-year NPV of the saving (at 10% discount rate) — $2.8M–$4.3M. The ROI is exceptionally high because the transition cost is one-time and the saving is annual. The main risk factors are team productivity during transition (managed by overlapping the new and old team for 4–8 weeks) and communication quality (mitigated by 1Solutions pre-vetting for English communication and client-facing experience).' } },
      { '@type': 'Question', name: 'How do you reduce cloud infrastructure costs?', acceptedAnswer: { '@type': 'Answer', text: 'Cloud cost optimisation begins with a spend analysis — identifying the top 10 cost drivers in your AWS, Azure, or GCP account, which typically represent 80% of total spend. Common savings opportunities: Right-sizing — EC2 instances or RDS instances provisioned for peak load run at 10–20% average utilisation; right-sizing to actual utilisation reduces cost by 30–60% for over-provisioned resources. Reserved Instances and Savings Plans — committing to 1-year or 3-year terms for predictable baseline workloads saves 40–60% vs on-demand pricing. Spot instances — for non-critical batch workloads, ML training, and dev/test environments, spot instances cost 70–90% less than on-demand. Autoscaling — properly configured autoscaling ensures resources scale down during off-peak hours (nights, weekends) rather than running at peak capacity 24/7. Idle resource elimination — unused EBS volumes, unattached load balancers, idle RDS instances, and old snapshots that are charged but provide no value. Storage tiering — moving infrequently accessed S3 objects to Glacier or Intelligent-Tiering reduces storage costs by 40–80%.' } },
      { '@type': 'Question', name: 'How does technical debt affect development costs?', acceptedAnswer: { '@type': 'Answer', text: 'Technical debt increases software development costs in four ways: (1) Slower feature delivery — features that take 2 weeks to build on a clean codebase take 4–6 weeks on a heavily indebted one, because every change requires understanding a tangle of undocumented dependencies. This directly reduces the amount of product value delivered per engineering dollar. (2) Higher defect rate — untested, tightly-coupled code breaks more often when changed. More defects mean more engineering time on bug fixing vs feature development. (3) Onboarding friction — new team members take 3–6 months to reach full productivity vs 4–6 weeks on a clean, well-documented codebase. This hidden cost is rarely measured. (4) Deployment risk — poorly tested, monolithic architectures make deployments risky, leading to infrequent releases. Infrequent releases mean feedback cycles are slow, which means more rework. The interest rate on technical debt compounds — a codebase that is slightly difficult to work with today becomes a major productivity constraint in 2–3 years without deliberate remediation.' } },
      { '@type': 'Question', name: 'What is included in a software development cost audit?', acceptedAnswer: { '@type': 'Answer', text: 'Our software development cost audit covers: (1) Engineering labour analysis — current team composition, fully-loaded cost per role, roles that are candidates for offshore transition vs roles requiring local presence, and potential annual saving from a partial or full offshore transition. (2) Cloud spend analysis — current monthly AWS/Azure/GCP spend by service, right-sizing opportunities, reserved instance coverage, idle resources, and storage tiering opportunities. We typically identify 20–40% in savings in the first week of analysis. (3) Development velocity analysis — sprint velocity data, defect rate, deployment frequency, lead time, and MTTR (Mean Time to Recover). Low deployment frequency and high defect rate are indicators of technical debt that is costing you engineering time. (4) Tooling audit — software subscriptions your team is paying for that are unused or duplicated. (5) QA process analysis — what percentage of testing is manual vs automated, time spent on regression testing per release, and defect escape rate to production. (6) Architecture review — bottlenecks in your current architecture that slow development or increase infrastructure cost (e.g. a monolith that prevents independent service scaling).' } },
      { '@type': 'Question', name: 'Can you reduce costs without slowing down development?', acceptedAnswer: { '@type': 'Answer', text: 'Yes — in most cases, well-executed cost optimisation actually increases development speed. The key mechanisms: (1) Offshore team transition, done correctly (with a 4–8 week overlap period and proper onboarding), adds engineering capacity at lower cost — the team is larger, not smaller. (2) Cloud cost optimisation does not reduce capacity; it eliminates waste while maintaining or improving performance. (3) Technical debt elimination directly increases development velocity — features take less time to build, defect rates drop, and deployment confidence increases. (4) Test automation reduces the manual QA bottleneck on each release, enabling faster and more frequent deployments. The risk of slowing development exists primarily if the transition is done poorly — inadequate overlap period, insufficient onboarding of offshore team members, or a poorly scoped technical debt remediation that touches too many systems simultaneously. We de-risk transitions by doing them in phases with explicit velocity measurement at each stage.' } },
      { '@type': 'Question', name: 'How long does a cost optimization engagement take?', acceptedAnswer: { '@type': 'Answer', text: 'A software development cost audit takes 2–3 weeks and produces a prioritised savings roadmap. Cloud cost quick wins (right-sizing, idle resource removal, savings plans purchase) can be implemented in 2–4 weeks and generate immediate savings. Offshore team transition takes 6–12 weeks from decision to full team productivity (2–4 weeks of shortlisting and interviews, 2–4 weeks of onboarding and overlap, 2–4 weeks of ramping to full productivity). Technical debt remediation is a 3–6 month ongoing programme, not a single sprint — we scope it as a parallel track to feature development so it does not pause product delivery. Full realization of all identified savings typically occurs at 6 months from engagement start.' } },
    ] },
  ],
};

const SERVICES = [
  { n: '01', title: 'Offshore Team Transition & Labour Cost Reduction', desc: 'The largest single lever for reducing software development costs — transitioning appropriate roles (most development, QA, DevOps, data engineering) from high-cost local markets to offshore talent at 60–70% lower cost. We design and execute the transition: role assessment (which roles to offshore, which to retain locally), shortlisting, interviews, overlap period management, and productivity validation. Typical result: $400,000–$1,100,000 in annual savings for a 5–10 person team.' },
  { n: '02', title: 'Cloud Infrastructure Cost Optimisation', desc: 'AWS, Azure, and GCP spend analysis and reduction — right-sizing over-provisioned EC2/RDS instances (typically saves 30–60% on oversized resources), Reserved Instance and Savings Plan purchasing (40–60% discount vs on-demand for baseline workloads), spot instance adoption for batch and dev workloads (70–90% savings), idle resource elimination, storage tiering to Glacier/Intelligent-Tiering, and autoscaling to eliminate off-hours waste. Typical first-month saving: 20–40% of current cloud bill.', feat: true },
  { n: '03', title: 'Technical Debt Assessment & Remediation', desc: 'Technical debt compounds — a codebase that is slightly difficult today becomes a major productivity constraint in 2–3 years. We assess: code complexity (cyclomatic complexity, module coupling, code coverage), deployment frequency and lead time (DORA metrics), defect rate and MTTR, and engineer self-reported friction. We then design a phased remediation programme — running parallel to feature development — that progressively improves velocity without stopping product delivery.' },
  { n: '04', title: 'Test Automation ROI Programme', desc: 'Manual QA that consumes 30–60 engineer-hours per release can be reduced to 8–12 hours with a comprehensive automated suite. We assess current test coverage, identify the highest-ROI tests to automate (high-frequency regression paths, critical user journeys), implement Cypress/Playwright (E2E), Jest/Vitest/Pytest (unit), k6 (performance), and Postman/REST-assured (API) test automation, and measure the reduction in manual QA hours and defect escape rate to production.' },
  { n: '05', title: 'Process Automation & DevOps Efficiency', desc: 'Manual engineering processes that could be automated represent hidden labour costs. Common examples: manual deployments (replaced with CI/CD pipelines), manual infrastructure provisioning (replaced with Terraform IaC), manual security reviews (replaced with DevSecOps SAST/SCA in CI), and manual monitoring triage (replaced with alert rules and runbooks). We identify, quantify, and automate the highest-cost manual processes in your engineering workflow.' },
  { n: '06', title: 'Software Licence & Tooling Audit', desc: 'Engineering teams accumulate SaaS subscriptions — many unused, duplicated, or replaceable with open-source alternatives. We audit current tooling spend across CI/CD, monitoring, error tracking, project management, design tools, cloud IDE, and security scanning. Typical tooling audits identify 15–25% of tooling spend as immediately cuttable (unused seats, duplicate tools), and a further 20–30% that can be reduced through consolidation or open-source replacement.' },
  { n: '07', title: 'Architecture Rationalisation & Scalability', desc: 'Architectures designed for early-stage products often become cost-inefficient at scale — monoliths that cannot scale horizontally (requiring expensive vertical scaling), microservices that over-provision for independence, synchronous chains that bottleneck throughput. We assess your current architecture against your actual traffic and cost profile, identify rationalisation opportunities (service consolidation, caching layer introduction, async queue adoption), and quantify the infrastructure cost saving of each change.' },
  { n: '08', title: 'Vendor & Contract Renegotiation Support', desc: 'Enterprise software vendor contracts (databases, monitoring platforms, security tools, cloud commitment tiers) are typically negotiated poorly at renewal time. We provide technical input to procurement and finance teams on: minimum viable commitment (what features do you actually use?), alternative vendor options and realistic migration cost, negotiating leverage (competitive alternatives, volume commitments, multi-year terms), and contract red flags (automatic renewal clauses, usage overages without caps).' },
  { n: '09', title: 'Sprint Velocity & Delivery Efficiency', desc: 'If your team is spending 40–50% of sprint time on unplanned rework, bug fixes, and operational firefighting rather than planned feature work, this is a hidden cost. We analyse sprint data, identify root causes of unplanned work (inadequate definition of done, missing automated testing, poor technical specification, premature optimisation), and implement engineering process improvements that increase the ratio of planned feature work to reactive rework.' },
  { n: '10', title: 'Software Development Cost Audit & Savings Roadmap', desc: 'A structured 2–3 week cost audit across engineering labour, cloud infrastructure, technical debt, tooling, QA, process, and architecture. Deliverable: a prioritised savings roadmap with quantified savings for each initiative, implementation complexity and timeline, recommended sequencing (quick wins first, then structural changes), and a 12-month savings projection. Suitable as a standalone engagement or as the discovery phase of a longer optimisation programme.' },
];

const TECH_STACK = [
  { group: 'Cloud Cost Tools', color: '#166534', items: ['AWS Cost Explorer', 'Azure Cost Management', 'GCP Billing', 'Infracost (Terraform)', 'CloudHealth / Apptio', 'Spot.io / CAST AI'] },
  { group: 'Infrastructure as Code', color: '#15803d', items: ['Terraform / Terragrunt', 'Pulumi', 'AWS CDK / CloudFormation', 'Ansible', 'Crossplane', 'Checkov (cost scanning)'] },
  { group: 'Test Automation', color: '#0369a1', items: ['Cypress / Playwright', 'Jest / Vitest / Pytest', 'k6 / Locust (perf)', 'Postman / REST-assured', 'Appium (mobile)', 'SonarQube (quality gate)'] },
  { group: 'CI/CD & DevOps', color: '#b45309', items: ['GitHub Actions', 'GitLab CI/CD', 'Jenkins / CircleCI', 'ArgoCD / Flux', 'Docker / Kubernetes', 'Helm / Kustomize'] },
  { group: 'Monitoring & Observability', color: '#7e22ce', items: ['Prometheus / Grafana', 'Datadog', 'ELK Stack / Loki', 'Jaeger / Zipkin', 'PagerDuty / OpsGenie', 'Sentry / Rollbar'] },
  { group: 'Code Quality', color: '#dc2626', items: ['SonarQube / SonarCloud', 'ESLint / Prettier', 'Semgrep (SAST)', 'Snyk (dependencies)', 'CodeClimate', 'DeepSource'] },
  { group: 'Architecture Analysis', color: '#0f766e', items: ['Structurizr (C4)', 'PlantUML', 'Graphviz dependency maps', 'Jaeger (trace analysis)', 'Lightstep / Honeycomb', 'AWS X-Ray'] },
  { group: 'Process & Productivity', color: '#c2185b', items: ['Jira / Linear (DORA metrics)', 'GitHub Insights', 'Waydev / LinearB', 'Pluralsight Flow', 'Clockify / Toggl', 'Retool (internal tools)'] },
];

const ENGAGEMENT_MODELS = [
  { id: 'audit', name: 'Cost Audit & Savings Roadmap', badge: 'Start Here', badgeColor: '#D97706', feat: true, icon: 'M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z', headline: '2–3 week audit with a quantified savings roadmap.', desc: 'A structured cost audit across engineering labour, cloud, tooling, QA, and architecture — delivering a prioritised roadmap with quantified savings per initiative, implementation complexity, and 12-month projection. Can be standalone or the discovery phase of a full optimisation programme.', bestFor: ['Understanding where engineering costs can be reduced before committing to a programme', 'Preparing for a board or investor conversation on cost efficiency', 'Identifying the highest-ROI optimisation initiatives from a long list', 'Building a business case for offshore transition or cloud rearchitecture'], process: 'Kick-off → data collection → analysis → roadmap → presentation', timeline: '2–3 weeks to deliverable' },
  { id: 'cloud', name: 'Cloud Cost Optimisation', badge: 'Fastest ROI', badgeColor: '#166534', icon: 'M3 15a4 4 0 004 4h9a5 5 0 10-.1-9.999 5.002 5.002 0 10-9.78 2.096A4.001 4.001 0 003 15z', headline: 'Reduce your AWS, Azure, or GCP bill by 20–40% in 30 days.', desc: 'Cloud spend analysis and immediate cost reduction — right-sizing, Reserved Instance and Savings Plan purchasing, spot instance adoption for eligible workloads, idle resource elimination, and storage tiering. Fastest payback of any cost optimisation initiative.', bestFor: ['Companies spending $10,000+/month on cloud with no dedicated FinOps function', 'Post-funding startups with rapidly growing cloud bills', 'Pre-IPO companies preparing for profitability metrics scrutiny', 'Businesses consolidating infrastructure after a merger or acquisition'], process: 'Spend analysis → savings identification → implementation → monitoring', timeline: 'First savings visible within 2–4 weeks' },
  { id: 'programme', name: 'Full Cost Optimisation Programme', badge: 'Maximum Saving', badgeColor: '#0369a1', icon: 'M13 10V3L4 14h7v7l9-11h-7z', headline: '6-month programme — offshore transition, cloud, tech debt, automation.', desc: 'A comprehensive 6-month cost optimisation programme covering all major cost levers: offshore team transition, cloud cost reduction, technical debt remediation, test automation, and process efficiency — coordinated to maximise total savings without disrupting product delivery.', bestFor: ['Companies targeting 40–65% total software development cost reduction', 'Scale-ups preparing for a down-round or extending runway without headcount cuts', 'Enterprises with $2M+ annual engineering spend and no systematic optimisation', 'Businesses preparing for a sale process that requires demonstrable EBITDA improvement'], process: 'Audit → quick wins → offshore transition → structural improvements → sustained optimisation', timeline: 'Full savings realised by month 6' },
];

const PROCESS_STEPS = [
  { num: '01', title: 'Engineering Cost Baseline', desc: 'Before optimising, we establish the full cost baseline: fully-loaded engineering labour cost per role (salary, benefits, employer taxes, office, equipment, management overhead), monthly cloud spend by service with 3-month trend, tooling subscriptions, QA man-hours per release cycle, and estimated technical debt cost (slower velocity multiplied by engineer cost rate). This baseline makes the savings in every subsequent step concrete and measurable.' },
  { num: '02', title: 'Multi-Lever Cost Audit', desc: 'A 2–3 week structured audit across every cost lever — cloud (right-sizing analysis, reserved instance coverage, idle resources), labour (role-by-role offshore viability assessment), tooling (subscription audit, duplicate and unused tools), QA (manual vs automated coverage, hours per release), technical debt (code complexity metrics, deployment frequency, defect rate), and process (manual steps that could be automated, rework rate from sprint data).' },
  { num: '03', title: 'Prioritised Savings Roadmap', desc: 'We rank identified savings opportunities by: annual savings potential, implementation cost and complexity, time to first saving, and risk to existing delivery. The roadmap distinguishes quick wins (cloud right-sizing, tooling rationalisation — weeks to implement, low risk) from structural changes (offshore transition, technical debt remediation — months to implement, managed risk). Quick wins are implemented first to generate savings that fund the structural changes.' },
  { num: '04', title: 'Cloud Quick Wins (Weeks 3–6)', desc: 'Cloud cost optimisation is the fastest-payback initiative — savings begin within 2–4 weeks of implementation. We implement: right-sizing for over-provisioned instances, Reserved Instance and Savings Plan purchasing for baseline workloads, idle resource elimination (unused EBS volumes, unattached ELBs, old snapshots), storage tiering for infrequently accessed data, and autoscaling configuration for variable-load workloads. Savings are monitored against the baseline weekly.' },
  { num: '05', title: 'Offshore Team Transition (Months 2–4)', desc: 'The largest saving in most engagements. We design the transition: which roles to offshore (developers and QA roles with no local client interaction requirement are the best candidates), which to retain locally (CTO, product managers, client-facing roles, roles requiring domain clearance). We manage the overlap period — new offshore team members join before local equivalents transition out, providing knowledge transfer and continuity of delivery.' },
  { num: '06', title: 'Structural Optimisation & Sustained Savings', desc: 'Technical debt remediation (phased, parallel to feature work), test automation programme (reducing QA man-hours per release by 60–80%), architecture rationalisation (eliminating over-provisioned microservices or scaling bottlenecks), and process automation (CI/CD, IaC, DevSecOps). Monthly savings review against the baseline, with a 12-month savings realisation report delivered to executive stakeholders.' },
];

const TESTIMONIALS = [
  { text: "1Solutions reduced our annual engineering cost by 61% without reducing our team size or velocity. The cloud audit alone saved $8,400/month in the first 30 days. The offshore team transition (we moved 4 of 6 developer roles offshore over 10 weeks) added capacity while reducing cost. 14 months later, our roadmap delivery pace is faster than before the transition.", name: 'David K.', role: 'CEO, B2B SaaS Platform (UK)', init: 'DK', bg: '#0F3460' },
  { text: "We engaged 1Solutions for a cloud cost audit before our Series B. They identified $14,200/month in AWS waste — right-sizing, idle resources, and moving dev/test to spot instances. Implementation took 3 weeks. At our Series B close, the improved unit economics contributed to a higher valuation multiple. The audit paid for itself 8 times over in the first month.", name: 'Priya M.', role: 'CFO, HealthTech Startup (AU)', init: 'PM', bg: '#0a2a1a', feat: true },
  { text: "Our manual QA process was consuming 52 engineer-hours per release and we were releasing every 3 weeks. 1Solutions built our Playwright + API test suite over 10 weeks — 412 automated tests covering 94% of critical user journeys. We now release weekly. QA man-hours per release dropped to 8 hours. The velocity improvement was worth more than the QA cost saving.", name: 'James T.', role: 'VP Engineering, E-Commerce (US)', init: 'JT', bg: '#1e3a5f' },
];

const WHY_CARDS = [
  { title: 'Quantified Savings, Not Vague Estimates', desc: 'Every savings recommendation we make is quantified: annual dollar saving, implementation cost, payback period. We do not say "consider offshore development to save costs" — we say "transitioning 3 developer roles offshore saves $380,000/year, with a transition cost of $45,000 and 6-week payback period."' },
  { title: 'Savings Without Delivery Risk', desc: 'Cost optimisation that disrupts product delivery is self-defeating. We sequence savings initiatives to minimise delivery risk: cloud quick wins first (zero delivery impact), offshore transition with managed overlap (delivery continuity), technical debt in parallel sprints (not instead of feature work), test automation (increases deployment confidence).' },
  { title: '15 Years of Offshore Delivery', desc: 'Our offshore transition recommendations are backed by 15+ years of actually delivering offshore teams. We know which roles transition well, which do not, how to structure the overlap period, and how long ramp-up takes — because we have done it hundreds of times, not just advised on it.' },
  { title: 'Cloud Cost Expertise', desc: 'Our cloud cost optimisation is delivered by engineers who have managed AWS, Azure, and GCP infrastructure at scale — not by a cost management SaaS tool that generates a report. We know which right-sizing opportunities are safe to implement immediately and which require load testing first.' },
  { title: 'Technical Debt Realism', desc: 'We scope technical debt remediation realistically: parallel to feature work, in bounded modules, with measurable velocity improvement gates. We do not recommend a 6-month freeze of all feature development to rewrite the system from scratch — that approach destroys more value than it saves.' },
  { title: 'Measurable Outcomes', desc: 'Every engagement ends with a measured savings report against the baseline: actual monthly cloud spend reduction vs projected, developer velocity improvement (story points per sprint before and after), QA hours per release before and after, and fully-loaded engineering cost before and after the offshore transition.' },
  { title: 'No Conflict of Interest', desc: 'We recommend the right mix of savings levers — not just offshore transition (which would be in our commercial interest to recommend for every engagement). If your highest-ROI opportunity is cloud cost reduction with no offshore transition needed, that is what we recommend.' },
  { title: 'Executive-Ready Reporting', desc: 'Our cost savings roadmap is designed for the CFO, board, and investors — not just the engineering team. Dollar savings, payback periods, risk ratings, and 12-month projections in a format that enables confident investment decisions about the optimisation programme.' },
];

const FAQS = [
  { q: 'What does software development cost optimization involve?', a: 'Systematically reducing the largest engineering cost drivers: labour (offshore transition at 60–70% savings), cloud infrastructure (right-sizing, reserved instances, idle resource elimination — 20–40% savings), technical debt (slow velocity, high defect rates), test automation (reducing manual QA hours per release by 60–80%), tooling (unused and duplicate subscriptions), and process automation (manual steps replaced with CI/CD and IaC).' },
  { q: 'How much can software development costs be reduced?', a: 'Typical results: Labour (offshore transition of 3–5 roles) — $400,000–$1,100,000/year saved. Cloud (right-sizing + reserved instances) — $72,000–$144,000/year for a $30,000/month cloud bill. Test automation — 70–80% reduction in manual QA hours per release. Tooling audit — 15–25% of tooling spend eliminated immediately. Combined 12-month saving: 40–65% of total software development cost.' },
  { q: 'How much can cloud costs be reduced?', a: 'Typically 20–40% within 30 days through right-sizing over-provisioned instances, Reserved Instance and Savings Plan purchasing (40–60% discount for baseline workloads), spot instances for batch and dev/test (70–90% savings), idle resource elimination, and storage tiering. For a $30,000/month AWS bill, this is $6,000–$12,000/month or $72,000–$144,000/year.' },
  { q: 'How does technical debt affect development costs?', a: 'Technical debt slows feature delivery (features take 2–3x longer on heavily indebted codebases), increases defect rate (more bugs, more QA and on-call engineering time), raises onboarding costs (new developers take 3–6 months to reach productivity vs 4–6 weeks on clean code), and increases deployment risk (infrequent releases, more rework). Each of these has a quantifiable cost in engineering hours.' },
  { q: 'Can you reduce costs without slowing development?', a: 'Yes — in most cases cost optimisation increases development speed. Offshore transition adds capacity at lower cost. Cloud optimisation does not reduce capacity. Technical debt elimination directly increases velocity. Test automation reduces release cycle time. The risk of slowdown occurs only if the transition is poorly managed — inadequate overlap period or insufficient onboarding.' },
  { q: 'What is included in a cost audit?', a: 'Engineering labour analysis (role costs, offshore viability), cloud spend analysis (service breakdown, right-sizing, idle resources), tooling audit (unused subscriptions, duplicates), QA process analysis (manual hours per release, test coverage), technical debt assessment (DORA metrics, code complexity, defect rate), and architecture review (scaling bottlenecks, over-provisioned services). Delivered in 2–3 weeks as a quantified savings roadmap.' },
  { q: 'How long does a cost optimization engagement take?', a: 'Cost audit: 2–3 weeks. Cloud quick wins: 2–4 weeks to implement. Offshore team transition: 6–12 weeks from decision to full productivity. Technical debt remediation: 3–6 month parallel programme. Full savings realisation: 6 months from engagement start.' },
  { q: 'What is the ROI of offshore team transition?', a: 'A 5-person senior development team costs $1,100,000–$1,500,000/year all-in (US market). The equivalent offshore team through 1Solutions: $200,000–$350,000/year. Annual saving: $750,000–$1,150,000. Transition cost: $50,000–$120,000 one-time. Payback period: 1–2 months of savings.' },
];

function useCountUp(target, duration = 1800, start = false) {
  const [count, setCount] = useState(0);
  useEffect(() => { if (!start) return; const num = parseInt(target.replace(/\D/g, ''), 10); if (!num) return; let t0 = null; const step = ts => { if (!t0) t0 = ts; const p = Math.min((ts - t0) / duration, 1); setCount(Math.floor((1 - Math.pow(1 - p, 3)) * num)); if (p < 1) requestAnimationFrame(step); }; requestAnimationFrame(step); }, [start, target, duration]);
  return count;
}
function StatItem({ label, val, started }) {
  const num = useCountUp(val, 1800, started);
  const suffix = val.replace(/[\d,]/g, '');
  return (<div className="sco-sc"><div className="sco-sv">{started ? (val.includes(',') ? num.toLocaleString() : num) + suffix : val}</div><div className="sco-sl">{label}</div></div>);
}

export default function SoftwareCostOptimization() {
  const [showAll, setShowAll] = useState(false);
  const [openFaq, setOpenFaq] = useState(0);
  const [ss, setSs] = useState(false);
  const [vis, setVis] = useState(new Set());
  const [vSk, setVSk] = useState([]); const [vEn, setVEn] = useState([]); const [vWh, setVWh] = useState([]); const [vTe, setVTe] = useState([]); const [vSt, setVSt] = useState([]);
  const stR = useRef(null); const secR = useRef({});
  const skR = useRef(null); const enR = useRef(null); const whR = useRef(null); const teR = useRef(null); const stGr = useRef(null);
  useEffect(() => { if (!stR.current) return; const o = new IntersectionObserver(([e]) => { if (e.isIntersecting) { setSs(true); o.disconnect(); } }, { threshold: 0.4 }); o.observe(stR.current); return () => o.disconnect(); }, []);
  useEffect(() => { const pairs = [[skR, SERVICES.length, setVSk],[enR, 3, setVEn],[whR, WHY_CARDS.length, setVWh],[teR, 3, setVTe],[stGr, TECH_STACK.length, setVSt]]; const obs = pairs.map(([ref, count, setter]) => { if (!ref.current) return null; const o = new IntersectionObserver(([e]) => { if (e.isIntersecting) { Array.from({ length: count }, (_, i) => setTimeout(() => setter(p => p.includes(i) ? p : [...p, i]), i * 80)); o.disconnect(); } }, { threshold: 0.05 }); o.observe(ref.current); return o; }); return () => obs.forEach(o => o?.disconnect()); }, []);
  useEffect(() => { const ks = Object.keys(secR.current); const obs = ks.map(k => { const el = secR.current[k]; if (!el) return null; const o = new IntersectionObserver(([e]) => { if (e.isIntersecting) { setVis(p => new Set([...p, k])); o.disconnect(); } }, { threshold: 0.1 }); o.observe(el); return o; }); return () => obs.forEach(o => o?.disconnect()); }, []);
  const visServices = showAll ? SERVICES : SERVICES.slice(0, 6);
  return (
    <>
      <Head>
        <title>Software Development Cost Optimization | Reduce Engineering Spend 40–65% | 1Solutions</title>
        <meta name="description" content="Software development cost optimization — reduce engineering spend by 40–65% through offshore team transition, cloud cost reduction, technical debt elimination, test automation, and process efficiency. Free cost audit with quantified savings roadmap." />
        <link rel="canonical" href="https://www.1solutions.biz/software-development-cost-optimization/" />
        <meta property="og:title" content="Software Development Cost Optimization | 1Solutions" />
        <meta property="og:description" content="Reduce software development costs by 40–65%. Offshore transition, cloud cost reduction (20–40% savings), technical debt elimination, and test automation ROI." />
        <meta property="og:url" content="https://www.1solutions.biz/software-development-cost-optimization/" />
        <meta property="og:image" content="https://www.1solutions.biz/images/banner-1sol.jpg" />
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(SCHEMA) }} />
        <style>{`
          .sco-page{font-family:'Inter',-apple-system,BlinkMacSystemFont,sans-serif;background:linear-gradient(135deg,#f0fdf4 0%,#dcfce7 20%,#f0fdfa 50%,#fef3c7 75%,#f0f9ff 100%);color:#052e16;line-height:1.6;position:relative;overflow-x:hidden}
          .sco-page *,.sco-page *::before,.sco-page *::after{box-sizing:border-box}
          .sco-orb{position:absolute;border-radius:50%;pointer-events:none;z-index:0;filter:blur(20px)}
          .sco-o1{width:860px;height:860px;background:radial-gradient(circle,rgba(22,101,52,.20) 0%,rgba(34,197,94,.08) 40%,transparent 70%);top:-260px;right:-240px}
          .sco-o2{width:760px;height:760px;background:radial-gradient(circle,rgba(217,119,6,.15) 0%,rgba(251,191,36,.06) 40%,transparent 70%);bottom:0;left:-220px}
          .sco-o3{width:520px;height:520px;background:radial-gradient(circle,rgba(3,105,161,.12) 0%,transparent 70%);top:44%;left:-100px;transform:translateY(-50%)}
          .sco-bc{position:relative;z-index:2;padding:16px 40px 0;max-width:1440px;margin:0 auto}
          .sco-bc ol{display:flex;flex-wrap:wrap;gap:6px;list-style:none;margin:0;padding:0;font-size:13px;color:#14532d}
          .sco-bc li{display:flex;align-items:center;gap:6px}
          .sco-bc li::after{content:'/';opacity:.45}
          .sco-bc li:last-child::after{display:none}
          .sco-bc a{color:#052e16;text-decoration:none}
          .sco-hero{position:relative;z-index:2;text-align:center;max-width:960px;margin:0 auto;padding:44px 40px 32px}
          .sco-ey{display:block;font-size:11px;font-weight:700;letter-spacing:2.5px;text-transform:uppercase;color:#166534;margin-bottom:14px}
          .sco-hero h1{font-size:50px;font-weight:900;line-height:1.09;letter-spacing:-1.5px;margin-bottom:16px;background:linear-gradient(90deg,#052e16 0%,#166534 100%);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text}
          .sco-desc{font-size:16px;color:#14532d;line-height:1.65;max-width:740px;margin:0 auto 24px}
          .sco-tr{display:flex;flex-wrap:wrap;justify-content:center;gap:10px;margin-bottom:26px}
          .sco-badge{display:inline-flex;align-items:center;gap:6px;background:rgba(255,255,255,.60);backdrop-filter:blur(10px);border:1px solid rgba(255,255,255,.85);border-radius:100px;padding:6px 14px;font-size:12px;font-weight:600;color:#052e16;box-shadow:0 2px 8px rgba(5,46,22,.07)}
          .sco-dot{width:7px;height:7px;border-radius:50%;background:#166534;flex-shrink:0}
          .sco-ctas{display:flex;flex-wrap:wrap;gap:12px;justify-content:center}
          .sco-p{display:inline-block;padding:14px 36px;background:#166534;color:#fff;border-radius:50px;font-weight:700;font-size:15px;text-decoration:none;transition:all .25s;box-shadow:0 6px 24px rgba(22,101,52,.28)}
          .sco-p:hover{background:#052e16;transform:translateY(-2px)}
          .sco-g{display:inline-block;padding:14px 36px;background:rgba(255,255,255,.55);backdrop-filter:blur(16px);border:1.5px solid rgba(255,255,255,.85);border-radius:50px;color:#052e16;font-weight:700;font-size:15px;text-decoration:none;transition:all .25s}
          .sco-g:hover{background:rgba(255,255,255,.85);border-color:rgba(22,101,52,.5);transform:translateY(-2px)}
          .sco-stats{position:relative;z-index:2;display:grid;grid-template-columns:repeat(4,1fr);max-width:940px;margin:28px auto 0;background:rgba(255,255,255,.45);backdrop-filter:blur(24px);border:1px solid rgba(255,255,255,.85);box-shadow:0 4px 24px rgba(5,46,22,.08),inset 0 1px 0 rgba(255,255,255,.95)}
          .sco-sc{padding:18px 16px;text-align:center;border-right:1px solid rgba(5,46,22,.10)}
          .sco-sc:last-child{border-right:none}
          .sco-sv{font-size:28px;font-weight:900;color:#166534;letter-spacing:-.5px;line-height:1}
          .sco-sl{font-size:11px;color:#14532d;font-weight:500;margin-top:5px}
          .sco-logos{position:relative;z-index:2;padding:24px 40px 52px;display:flex;flex-direction:column;align-items:center;gap:14px}
          .sco-ll{font-size:10px;font-weight:700;letter-spacing:2px;text-transform:uppercase;color:#14532d}
          .sco-lw{width:100%;overflow:hidden}
          .sco-lt{display:flex;align-items:center;gap:60px;width:max-content;animation:sco-mq 28s linear infinite}
          .sco-lt:hover{animation-play-state:paused}
          @keyframes sco-mq{0%{transform:translateX(0)}100%{transform:translateX(-50%)}}
          .sco-cl{height:24px;width:auto;max-width:110px;object-fit:contain;filter:grayscale(100%);opacity:.45;transition:opacity .25s,filter .25s}
          .sco-cl:hover{opacity:.85;filter:grayscale(0%)}
          .sco-sey{font-size:11px;font-weight:700;letter-spacing:2px;text-transform:uppercase;color:#D97706;margin-bottom:10px;display:block}
          .sco-st{font-size:46px;font-weight:900;line-height:1.12;letter-spacing:-1px;background:linear-gradient(90deg,#052e16 0%,#D97706 100%);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;margin-bottom:10px}
          .sco-sd{font-size:15px;color:#14532d;line-height:1.7}
          .sco-rv{opacity:0;transform:translateY(44px);transition:opacity .7s cubic-bezier(0.22,1,.36,1),transform .7s cubic-bezier(0.22,1,.36,1)}
          .sco-rv.sco-ok{opacity:1;transform:translateY(0)}
          .sco-in{max-width:1300px;margin:0 auto}
          .sco-sk-s{background:transparent;padding:72px 40px 60px;position:relative;z-index:1}
          .sco-sk-g{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-top:40px}
          .sco-sk-c{background:linear-gradient(135deg,rgba(240,253,244,.50) 0%,rgba(255,255,255,.85) 55%,rgba(220,252,231,.40) 100%);backdrop-filter:blur(16px);border:1px solid rgba(255,255,255,.85);border-radius:20px;padding:26px 22px 22px;position:relative;overflow:hidden;box-shadow:0 4px 24px rgba(5,46,22,.08),inset 0 1px 0 rgba(255,255,255,.95);opacity:0;transform:translateY(36px);transition:opacity .6s cubic-bezier(0.22,1,.36,1),transform .6s cubic-bezier(0.22,1,.36,1),border-color .2s}
          .sco-sk-c.sco-cv{opacity:1;transform:translateY(0)}
          .sco-sk-c.sco-cv:hover{transform:translateY(-6px);border-color:rgba(22,101,52,.30);box-shadow:0 16px 48px rgba(5,46,22,.14)}
          .sco-sk-c.feat{border-color:rgba(22,101,52,.20)}
          .sco-sk-n{position:absolute;top:8px;right:14px;font-size:72px;font-weight:900;line-height:1;color:#052e16;opacity:.055;pointer-events:none;letter-spacing:-4px;user-select:none}
          .sco-sk-c h3{font-size:16px;font-weight:700;color:#052e16;margin:0 0 8px;position:relative;z-index:1}
          .sco-sk-c p{font-size:13px;color:#14532d;line-height:1.65;margin:0;position:relative;z-index:1}
          .sco-sk-c::before{content:'';position:absolute;left:0;top:12%;height:76%;width:3px;background:linear-gradient(180deg,#166534,#22c55e);border-radius:0 2px 2px 0;transform:scaleY(0);transform-origin:top center;transition:transform .3s cubic-bezier(0.22,1,.36,1)}
          .sco-sk-c.sco-cv:hover::before{transform:scaleY(1)}
          .sco-sm{text-align:center;margin-top:22px}
          .sco-bm{display:inline-block;background:#fff;border:1.5px solid rgba(5,46,22,.18);color:#052e16;padding:10px 30px;border-radius:20px;font-weight:600;font-size:14px;cursor:pointer;transition:all .2s;font-family:inherit}
          .sco-bm:hover{background:#052e16;border-color:#052e16;color:#fff;transform:translateY(-2px)}
          .sco-tec-s{background:#f4fdf6;border-top:1px solid rgba(5,46,22,.08);border-bottom:1px solid rgba(5,46,22,.08);padding:72px 40px;position:relative;z-index:1}
          .sco-tec-g{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin-top:40px}
          .sco-tec-c{background:linear-gradient(135deg,rgba(240,253,244,.50) 0%,rgba(255,255,255,.85) 55%,rgba(220,252,231,.40) 100%);backdrop-filter:blur(16px);border:1px solid rgba(255,255,255,.85);border-radius:20px;padding:22px 20px;box-shadow:0 4px 24px rgba(5,46,22,.08),inset 0 1px 0 rgba(255,255,255,.95);opacity:0;transform:translateY(32px);transition:opacity .55s cubic-bezier(0.22,1,.36,1),transform .55s cubic-bezier(0.22,1,.36,1),border-color .2s}
          .sco-tec-c.sco-sv2{opacity:1;transform:translateY(0)}
          .sco-tec-c.sco-sv2:hover{border-color:rgba(22,101,52,.25);box-shadow:0 14px 40px rgba(5,46,22,.12)}
          .sco-tg{font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:1.2px;margin-bottom:12px;padding-bottom:8px;border-bottom:2px solid}
          .sco-pills{display:flex;flex-wrap:wrap;gap:6px}
          .sco-pill{display:inline-block;font-size:11.5px;font-weight:500;padding:4px 10px;border-radius:100px;border:1px solid}
          .sco-en-s{padding:80px 40px;position:relative;z-index:1}
          .sco-en-g{display:grid;grid-template-columns:repeat(3,1fr);gap:20px;margin-top:40px}
          .sco-en-c{background:linear-gradient(135deg,rgba(240,253,244,.50) 0%,rgba(255,255,255,.85) 55%,rgba(220,252,231,.40) 100%);backdrop-filter:blur(16px);border:1px solid rgba(255,255,255,.85);border-radius:24px;padding:32px 28px;box-shadow:0 4px 24px rgba(5,46,22,.08),inset 0 1px 0 rgba(255,255,255,.95);opacity:0;transform:translateY(44px);transition:opacity .65s cubic-bezier(0.22,1,.36,1),transform .65s cubic-bezier(0.22,1,.36,1),border-color .2s}
          .sco-en-c.sco-ev{opacity:1;transform:translateY(0)}
          .sco-en-c.sco-ev:hover{border-color:rgba(22,101,52,.25);box-shadow:0 16px 48px rgba(5,46,22,.14)}
          .sco-en-c.feat{background:linear-gradient(135deg,rgba(254,243,199,.52) 0%,rgba(255,255,255,.87) 55%,rgba(240,253,244,.45) 100%);border-color:rgba(217,119,6,.28);box-shadow:0 8px 32px rgba(217,119,6,.12),inset 0 1px 0 rgba(255,255,255,1);transform:translateY(-8px)}
          .sco-en-c.feat.sco-ev{transform:translateY(-8px)}
          .sco-en-c.feat.sco-ev:hover{transform:translateY(-12px)}
          .sco-en-b{display:inline-block;font-size:10px;font-weight:700;letter-spacing:1.2px;text-transform:uppercase;padding:5px 12px;border-radius:100px;border:1px solid;margin-bottom:18px}
          .sco-en-i{width:48px;height:48px;background:rgba(5,46,22,.07);border-radius:14px;display:flex;align-items:center;justify-content:center;margin-bottom:14px}
          .sco-en-i svg{fill:#052e16;stroke:#052e16;stroke-width:0}
          .sco-en-c.feat .sco-en-i{background:rgba(217,119,6,.10)}
          .sco-en-c.feat .sco-en-i svg{fill:#D97706;stroke:#D97706}
          .sco-en-n{font-size:22px;font-weight:900;color:#052e16;margin:0 0 6px;letter-spacing:-.3px}
          .sco-en-h{font-size:13px;font-weight:600;color:#166534;margin-bottom:12px}
          .sco-en-c.feat .sco-en-h{color:#D97706}
          .sco-en-d{font-size:14px;color:#14532d;line-height:1.7;margin-bottom:18px}
          .sco-en-ll{font-size:10px;font-weight:700;letter-spacing:1px;text-transform:uppercase;color:#14532d;margin-bottom:8px;opacity:.7}
          .sco-en-li{list-style:none;padding:0;margin:0 0 18px;display:flex;flex-direction:column;gap:7px}
          .sco-en-li li{display:flex;align-items:flex-start;gap:8px;font-size:13px;color:#374151;line-height:1.5}
          .sco-en-li li::before{content:'✓';font-weight:800;color:#166534;flex-shrink:0;margin-top:1px}
          .sco-en-c.feat .sco-en-li li::before{color:#D97706}
          .sco-en-p{font-size:12px;color:#14532d;padding-top:14px;border-top:1px solid rgba(5,46,22,.08);opacity:.8}
          .sco-en-p strong{color:#052e16}
          .sco-en-tl{display:inline-block;font-size:11px;font-weight:600;color:#D97706;margin-top:6px}
          .sco-en-a{display:block;margin-top:18px;padding:11px;border-radius:50px;font-size:13px;font-weight:700;text-align:center;text-decoration:none;transition:all .22s;background:rgba(5,46,22,.09);color:#052e16;border:1.5px solid rgba(5,46,22,.18)}
          .sco-en-a:hover{background:#052e16;color:#fff}
          .sco-en-c.feat .sco-en-a{background:#166534;color:#fff;border-color:#166534}
          .sco-en-c.feat .sco-en-a:hover{background:#052e16;border-color:#052e16}
          .sco-pr-s{background:#f4fdf6;border-top:1px solid rgba(5,46,22,.08);border-bottom:1px solid rgba(5,46,22,.08);padding:80px 40px;position:relative;z-index:1}
          .sco-ps{display:flex;flex-direction:column;margin-top:52px}
          .sco-ps-row{display:grid;grid-template-columns:56px 1fr;gap:0 20px;opacity:0;transform:translateY(48px);transition:opacity .65s cubic-bezier(0.22,1,.36,1),transform .65s cubic-bezier(0.22,1,.36,1)}
          .sco-ps-row.sco-pv{opacity:1;transform:translateY(0)}
          .sco-ps-l{display:flex;flex-direction:column;align-items:center}
          .sco-ps-ci{width:52px;height:52px;border-radius:50%;background:rgba(255,255,255,.65);backdrop-filter:blur(8px);border:2px solid rgba(5,46,22,.18);display:flex;align-items:center;justify-content:center;font-size:19px;font-weight:800;color:#052e16;flex-shrink:0}
          .sco-ps-row.sco-pv:hover .sco-ps-ci{background:rgba(22,101,52,.10);border-color:#166534;color:#166534}
          .sco-ps-co{flex:1;display:flex;flex-direction:column;align-items:center;padding:6px 0;min-height:42px}
          .sco-ps-co::before{content:'';width:2px;flex:1;background:#052e16;opacity:.22}
          .sco-ps-co::after{content:'';border-left:6px solid transparent;border-right:6px solid transparent;border-top:8px solid #052e16;opacity:.40}
          .sco-ps-row:last-child .sco-ps-co{display:none}
          .sco-ps-r{padding:4px 0 38px}
          .sco-ps-row:last-child .sco-ps-r{padding-bottom:0}
          .sco-ps-t{font-size:20px;font-weight:700;color:#052e16;margin:0 0 9px}
          .sco-ps-d{font-size:15px;color:#14532d;line-height:1.75;margin:0}
          .sco-te-s{background:transparent;padding:80px 40px;position:relative;z-index:1}
          .sco-ch{text-align:center;margin-bottom:48px}
          .sco-tg2{display:grid;grid-template-columns:repeat(3,1fr);gap:24px}
          .sco-tc{background:linear-gradient(135deg,rgba(240,253,244,.50) 0%,rgba(255,255,255,.85) 55%,rgba(220,252,231,.40) 100%);backdrop-filter:blur(16px);border:1px solid rgba(255,255,255,.85);border-radius:20px;padding:28px 24px;display:flex;flex-direction:column;gap:12px;box-shadow:0 4px 24px rgba(5,46,22,.08),inset 0 1px 0 rgba(255,255,255,.95);opacity:0;transform:translateY(40px);transition:opacity .6s cubic-bezier(0.22,1,.36,1),transform .6s cubic-bezier(0.22,1,.36,1)}
          .sco-tc.feat{background:linear-gradient(135deg,rgba(254,243,199,.52) 0%,rgba(255,255,255,.87) 55%,rgba(240,253,244,.42) 100%);border-color:rgba(217,119,6,.22)}
          .sco-tc.sco-tv{opacity:1;transform:translateY(0)}
          .sco-tc.sco-tv:hover{transform:translateY(-6px);box-shadow:0 16px 48px rgba(5,46,22,.14)}
          .sco-stars{font-size:16px;color:#D97706;letter-spacing:2px}
          .sco-txt{font-size:14px;line-height:1.75;color:#374151;flex:1}
          .sco-au{display:flex;align-items:center;gap:12px}
          .sco-av{width:42px;height:42px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:13px;font-weight:800;color:#fff;flex-shrink:0}
          .sco-an{font-size:14px;font-weight:700;color:#052e16}
          .sco-ar{font-size:12px;color:#6b7280}
          .sco-wy-s{background:#f4fdf6;border-top:1px solid rgba(5,46,22,.08);border-bottom:1px solid rgba(5,46,22,.08);padding:80px 40px;position:relative;z-index:1}
          .sco-wy-g{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin-top:48px}
          .sco-wc{background:linear-gradient(135deg,rgba(240,253,244,.50) 0%,rgba(255,255,255,.85) 55%,rgba(220,252,231,.40) 100%);backdrop-filter:blur(16px);border:1px solid rgba(255,255,255,.85);border-radius:20px;padding:26px 22px;box-shadow:0 4px 24px rgba(5,46,22,.08),inset 0 1px 0 rgba(255,255,255,.95);opacity:0;transform:translateY(32px) scale(.97);transition:opacity .55s cubic-bezier(0.22,1,.36,1),transform .55s cubic-bezier(0.22,1,.36,1),border-color .2s}
          .sco-wc.sco-wv{opacity:1;transform:translateY(0) scale(1)}
          .sco-wc.sco-wv:hover{transform:translateY(-5px) scale(1);border-color:rgba(22,101,52,.25);box-shadow:0 14px 40px rgba(5,46,22,.12)}
          .sco-wd{width:10px;height:10px;border-radius:50%;background:#166534;margin-bottom:12px}
          .sco-wc h3{font-size:14px;font-weight:700;color:#052e16;margin:0 0 8px;line-height:1.35}
          .sco-wc p{font-size:13px;color:#14532d;line-height:1.65;margin:0}
          .sco-ct-s{padding:70px 40px;background:linear-gradient(135deg,rgba(240,253,244,.55) 0%,rgba(255,255,255,.60) 40%,rgba(220,252,231,.55) 100%);backdrop-filter:blur(20px);border-top:1px solid rgba(255,255,255,.80);position:relative;z-index:1}
          .sco-ct-g{max-width:1440px;margin:0 auto;display:grid;grid-template-columns:1fr 1.15fr;gap:32px;align-items:start}
          .sco-ctt{font-size:42px;font-weight:900;line-height:1.18;margin:0 0 14px;background:linear-gradient(90deg,#052e16 0%,#166534 100%);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text}
          .sco-ctd{font-size:14px;color:#14532d;line-height:1.6;margin:0 0 22px}
          .sco-ben{background:rgba(255,255,255,.70);border:1px solid rgba(255,255,255,.90);border-radius:14px;padding:22px;backdrop-filter:blur(12px);display:flex;flex-direction:column;gap:14px}
          .sco-be{display:flex;gap:10px;align-items:flex-start}
          .sco-bi{flex-shrink:0;color:#166534;font-weight:800;font-size:16px;margin-top:1px}
          .sco-be p{font-size:13px;color:#14532d;margin:0;line-height:1.55}
          .sco-fb{background:linear-gradient(135deg,rgba(255,255,255,.88) 0%,rgba(240,253,244,.18) 50%,rgba(255,255,255,.84) 100%);backdrop-filter:blur(20px);border:1px solid rgba(255,255,255,.92);border-radius:20px;padding:34px;box-shadow:0 8px 40px rgba(5,46,22,.10),inset 0 1px 0 rgba(255,255,255,1)}
          .sco-fb h3{font-size:22px;font-weight:700;color:#052e16;margin:0 0 22px;letter-spacing:-.3px}
          .sco-form{display:flex;flex-direction:column;gap:13px}
          .sco-fr{display:grid;grid-template-columns:1fr 1fr;gap:12px}
          .sco-fg{display:flex;flex-direction:column;gap:5px}
          .sco-fg.full{grid-column:1/-1}
          .sco-fg label{font-size:12px;font-weight:500;color:#052e16}
          .sco-fg input,.sco-fg textarea,.sco-fg select{padding:10px 13px;border:1px solid rgba(5,46,22,.14);border-radius:6px;font-size:13px;font-family:inherit;color:#052e16;background:rgba(255,255,255,.55);transition:border-color .2s}
          .sco-fg input:focus,.sco-fg textarea:focus,.sco-fg select:focus{outline:none;border-color:#166534;box-shadow:0 0 0 3px rgba(22,101,52,.10)}
          .sco-co{display:flex;gap:8px;align-items:flex-start}
          .sco-co input{margin-top:3px;width:15px;height:15px}
          .sco-co label{font-size:11px;color:#14532d;line-height:1.5}
          .sco-co a{color:#052e16}
          .sco-sub{width:100%;padding:14px;background:#166534;border:none;color:#fff;border-radius:50px;font-weight:700;font-size:15px;cursor:pointer;font-family:inherit;transition:all .25s;box-shadow:0 6px 24px rgba(22,101,52,.26)}
          .sco-sub:hover{background:#052e16;transform:translateY(-2px)}
          .sco-fq-s{padding:80px 40px;background:#f4fdf6;border-top:1px solid rgba(5,46,22,.08);position:relative;z-index:1}
          .sco-fq-s h2{font-size:46px;font-weight:900;letter-spacing:-1px;background:linear-gradient(90deg,#052e16 0%,#D97706 100%);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;margin:0 0 8px}
          .sco-fq-sub{font-size:15px;color:#14532d;margin:0 0 36px}
          .sco-fql{display:flex;flex-direction:column;gap:10px}
          .sco-fi{background:linear-gradient(135deg,rgba(240,253,244,.50) 0%,rgba(255,255,255,.85) 55%,rgba(220,252,231,.40) 100%);backdrop-filter:blur(16px);border:1px solid rgba(255,255,255,.85);border-radius:14px;overflow:hidden;box-shadow:0 4px 20px rgba(5,46,22,.06);transition:border-color .2s}
          .sco-fi.open{border-color:rgba(22,101,52,.30)}
          .sco-fi.open::before{content:'';display:block;height:3px;background:linear-gradient(90deg,#166534,#22c55e);border-radius:3px 3px 0 0}
          .sco-fqb{width:100%;background:none;border:none;padding:20px 20px 20px 58px;display:flex;align-items:center;justify-content:space-between;cursor:pointer;text-align:left;gap:14px;font-family:inherit;position:relative}
          .sco-fqb2{position:absolute;left:16px;top:50%;transform:translateY(-50%);width:26px;height:26px;background:rgba(5,46,22,.08);color:#374151;font-size:11px;font-weight:700;display:flex;align-items:center;justify-content:center;border-radius:6px}
          .sco-fi.open .sco-fqb2{background:#166534;color:#fff}
          .sco-fqb span{font-size:15px;font-weight:600;color:#052e16;line-height:1.4}
          .sco-fi.open .sco-fqb span{color:#166534}
          .sco-fch{width:22px;height:22px;flex-shrink:0;color:#9ca3af;transition:transform .3s}
          .sco-fi.open .sco-fch{transform:rotate(180deg);color:#166534}
          .sco-faw{overflow:hidden;transition:max-height .35s ease;max-height:0}
          .sco-fi.open .sco-faw{max-height:500px}
          .sco-fa{padding:0 20px 20px 58px;font-size:14px;color:#4b5563;line-height:1.8}
          .sco-rel{padding:80px 40px;background:rgba(240,253,244,.14);backdrop-filter:blur(10px);border-top:1px solid rgba(255,255,255,.60)}
          .sco-ri{max-width:1300px;margin:0 auto;text-align:center}
          .sco-ri h2{font-size:34px;font-weight:900;background:linear-gradient(90deg,#052e16 0%,#D97706 100%);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;margin:10px 0 12px}
          .sco-rs{font-size:14px;color:#14532d;margin:0 auto;max-width:560px}
          .sco-ri hr{border:none;border-top:1px solid rgba(5,46,22,.10);margin:32px 0}
          .sco-rts{display:flex;flex-wrap:wrap;justify-content:center;gap:10px}
          .sco-rt{display:inline-block;padding:10px 20px;border:1.5px solid;border-radius:50px;font-size:14px;font-weight:500;text-decoration:none;transition:all .22s}
          .sco-rt:hover{transform:translateY(-2px);box-shadow:0 6px 18px rgba(0,0,0,.09)}
          .sco-b{background:rgba(22,101,52,.09);border-color:rgba(22,101,52,.28);color:#14532d}
          .sco-v{background:rgba(67,56,202,.09);border-color:rgba(67,56,202,.28);color:#3730a3}
          .sco-c{background:rgba(14,116,144,.09);border-color:rgba(14,116,144,.28);color:#155e75}
          .sco-o{background:rgba(180,83,9,.09);border-color:rgba(180,83,9,.28);color:#92400e}
          .sco-a{background:rgba(190,18,60,.09);border-color:rgba(190,18,60,.28);color:#9f1239}
          @media(max-width:1024px){.sco-hero h1,.sco-st,.sco-fq-s h2{font-size:36px}.sco-sk-g{grid-template-columns:repeat(2,1fr)}.sco-tec-g{grid-template-columns:repeat(2,1fr)}.sco-en-g{grid-template-columns:1fr;max-width:480px;margin-left:auto;margin-right:auto}.sco-en-c.feat{transform:none}.sco-en-c.feat.sco-ev{transform:none}.sco-en-c.feat.sco-ev:hover{transform:translateY(-4px)}.sco-wy-g{grid-template-columns:repeat(2,1fr)}.sco-tg2{grid-template-columns:1fr}.sco-ct-g{grid-template-columns:1fr}}
          @media(max-width:768px){.sco-bc,.sco-hero,.sco-sk-s,.sco-tec-s,.sco-en-s,.sco-pr-s,.sco-te-s,.sco-wy-s,.sco-fq-s,.sco-rel{padding-left:20px;padding-right:20px}.sco-hero{padding-top:28px;padding-bottom:20px}.sco-hero h1{font-size:26px;letter-spacing:-.3px}.sco-stats{grid-template-columns:1fr 1fr}.sco-sc:nth-child(2){border-right:none}.sco-sc:nth-child(3),.sco-sc:nth-child(4){border-top:1px solid rgba(5,46,22,.10)}.sco-sc:nth-child(4){border-right:none}.sco-sk-g,.sco-tec-g,.sco-wy-g{grid-template-columns:1fr}.sco-fr{grid-template-columns:1fr}.sco-ctt{font-size:28px}.sco-st{font-size:28px}.sco-ct-s{padding:48px 20px}.sco-logos{padding-left:20px;padding-right:20px}}
        `}</style>
      </Head>
      <div className="sco-page">
        <div className="sco-orb sco-o1" /><div className="sco-orb sco-o2" /><div className="sco-orb sco-o3" />
        <nav className="sco-bc" aria-label="Breadcrumb"><ol itemScope itemType="https://schema.org/BreadcrumbList"><li itemScope itemType="https://schema.org/ListItem" itemProp="itemListElement"><Link href="/" itemProp="item"><span itemProp="name">Home</span></Link><meta itemProp="position" content="1" /></li><li itemScope itemType="https://schema.org/ListItem" itemProp="itemListElement"><span itemProp="name">Software Development Cost Optimization</span><meta itemProp="position" content="2" /></li></ol></nav>
        <section className="sco-hero">
          <span className="sco-ey">Cost Optimization</span>
          <h1>Software Development Cost Optimization — Reduce Engineering Spend by 40–65%</h1>
          <p className="sco-desc">Systematically reduce software development costs through offshore team transition (60–70% labour saving), cloud infrastructure optimisation (20–40% cloud bill reduction), technical debt elimination, test automation ROI, and process efficiency — without slowing delivery. Free cost audit with quantified savings roadmap.</p>
          <div className="sco-tr">{['Offshore Transition — 60–70% Labour Saving','Cloud Cost Reduction — 20–40%','Technical Debt Elimination','Test Automation ROI','Free Cost Audit'].map(b => (<div className="sco-badge" key={b}><span className="sco-dot" />{b}</div>))}</div>
          <div className="sco-ctas"><Link href="#contact" className="sco-p">Get Your Free Cost Audit</Link><Link href="#engagement" className="sco-g">View Engagement Options →</Link></div>
        </section>
        <div className="sco-stats" ref={stR}>{[['40-65%','Typical Cost Reduction'],['20-40%','Cloud Bill Saving'],['60-70%','Labour Cost Saving'],['6mo','Full Savings Realised']].map(([v, l]) => (<StatItem key={l} label={l} val={v} started={ss} />))}</div>
        <div className="sco-logos"><span className="sco-ll">Engineering Cost Reduction Delivered for Companies in US, UK, Australia</span><div className="sco-lw"><div className="sco-lt">{[['/logo/Indian_Express_Logo_full.png','Indian Express'],['/logo/Verizon_2015_logo_-vector.svg.png','Verizon'],['/logo/Uniphore.jpg','Uniphore'],['/logo/ICCoLogo.png','ICC'],['/logo/Honor_Logo_(2020).svg.png','Honor'],['/logo/Zuari-Finserv-logo-new.png','Zuari Finserv'],['/logo/Indian_Express_Logo_full.png','Indian Express 2'],['/logo/Verizon_2015_logo_-vector.svg.png','Verizon 2'],['/logo/Uniphore.jpg','Uniphore 2'],['/logo/ICCoLogo.png','ICC 2'],['/logo/Honor_Logo_(2020).svg.png','Honor 2'],['/logo/Zuari-Finserv-logo-new.png','Zuari Finserv 2']].map(([src, alt]) => (<img key={alt} src={src} alt={alt.replace(/ \d$/, '')} className="sco-cl" />))}</div></div></div>
        <section className="sco-sk-s" aria-labelledby="sco-sk-h"><div className="sco-in"><div className={`sco-rv${vis.has('sk') ? ' sco-ok' : ''}`} ref={el => { secR.current['sk'] = el; }}><span className="sco-sey">Cost Optimization Services</span><h2 id="sco-sk-h" className="sco-st">How We Reduce Your Software Development Costs</h2><p className="sco-sd" style={{ maxWidth: 720 }}>Offshore team transition, cloud optimisation, technical debt remediation, test automation, process automation, tooling audit, architecture rationalisation, vendor renegotiation, sprint efficiency, and comprehensive cost audits.</p></div><div className="sco-sk-g" ref={skR}>{visServices.map((s, i) => (<div key={s.n} className={`sco-sk-c${s.feat ? ' feat' : ''}${vSk.includes(i) ? ' sco-cv' : ''}`} style={{ transitionDelay: `${i * 55}ms` }}><span className="sco-sk-n">{s.n}</span><h3>{s.title}</h3><p>{s.desc}</p></div>))}</div>{SERVICES.length > 6 && (<div className="sco-sm"><button className="sco-bm" onClick={() => setShowAll(p => !p)}>{showAll ? 'Show fewer ↑' : `Show all ${SERVICES.length} services ↓`}</button></div>)}</div></section>
        <section className="sco-tec-s" aria-labelledby="sco-tec-h"><div className="sco-in"><div className={`sco-rv${vis.has('stk') ? ' sco-ok' : ''}`} ref={el => { secR.current['stk'] = el; }}><span className="sco-sey">Tools & Platforms</span><h2 id="sco-tec-h" className="sco-st">Tools We Use to Optimise Your Engineering Costs</h2><p className="sco-sd" style={{ maxWidth: 680 }}>AWS Cost Explorer, Infracost, Terraform, Cypress, SonarQube, GitHub Actions, Prometheus, Grafana, Structurizr, Jira/Linear DORA metrics, and cloud cost management platforms.</p></div><div className="sco-tec-g" ref={stGr}>{TECH_STACK.map((grp, i) => (<div key={grp.group} className={`sco-tec-c${vSt.includes(i) ? ' sco-sv2' : ''}`} style={{ transitionDelay: `${i * 60}ms` }}><div className="sco-tg" style={{ color: grp.color, borderBottomColor: grp.color + '33' }}>{grp.group}</div><div className="sco-pills">{grp.items.map(item => <span key={item} className="sco-pill" style={{ color: grp.color, background: grp.color + '12', borderColor: grp.color + '30' }}>{item}</span>)}</div></div>))}</div></div></section>
        <section id="engagement" className="sco-en-s" aria-labelledby="sco-en-h"><div className="sco-in"><div className={`sco-rv${vis.has('eng') ? ' sco-ok' : ''}`} ref={el => { secR.current['eng'] = el; }}><span className="sco-sey">Engagement Options</span><h2 id="sco-en-h" className="sco-st">Cost Optimization Engagement Options</h2><p className="sco-sd" style={{ maxWidth: 680 }}>Start with a 2–3 week cost audit, target a specific quick win (cloud), or commission a full 6-month optimisation programme across all cost levers.</p></div><div className="sco-en-g" ref={enR}>{ENGAGEMENT_MODELS.map((m, i) => (<div key={m.id} className={`sco-en-c${m.feat ? ' feat' : ''}${vEn.includes(i) ? ' sco-ev' : ''}`} style={{ transitionDelay: `${i * 100}ms` }}><span className="sco-en-b" style={{ color: m.badgeColor, borderColor: m.badgeColor + '44', background: m.badgeColor + '14' }}>{m.badge}</span><div className="sco-en-i"><svg viewBox="0 0 24 24" width="26" height="26" fill="none" stroke={m.feat ? '#D97706' : '#052e16'} strokeWidth="2"><path strokeLinecap="round" strokeLinejoin="round" d={m.icon} /></svg></div><div className="sco-en-n">{m.name}</div><div className="sco-en-h">{m.headline}</div><div className="sco-en-d">{m.desc}</div><div className="sco-en-ll">Best for</div><ul className="sco-en-li">{m.bestFor.map(b => <li key={b}>{b}</li>)}</ul><div className="sco-en-p"><strong>Process:</strong> {m.process}<br /><span className="sco-en-tl">{m.timeline}</span></div><Link href="#contact" className="sco-en-a">Get a free estimate →</Link></div>))}</div></div></section>
        <section className="sco-pr-s" aria-labelledby="sco-pr-h"><div className="sco-in" style={{ maxWidth: 760 }}><div className={`sco-rv${vis.has('proc') ? ' sco-ok' : ''}`} ref={el => { secR.current['proc'] = el; }}><span className="sco-sey">How It Works</span><h2 id="sco-pr-h" className="sco-st">Our Cost Optimization Process</h2><p className="sco-sd">From cost baseline to full savings realisation — quantified audit, cloud quick wins, offshore transition, and structural optimisation in a sequenced programme that maintains delivery continuity.</p></div><div className="sco-ps">{PROCESS_STEPS.map((step, i) => (<div key={step.num} className={`sco-ps-row${vis.has('proc') ? ' sco-pv' : ''}`} style={{ transitionDelay: `${i * 120}ms` }}><div className="sco-ps-l"><div className="sco-ps-ci">{step.num}</div><div className="sco-ps-co" /></div><div className="sco-ps-r"><div className="sco-ps-t">{step.title}</div><p className="sco-ps-d">{step.desc}</p></div></div>))}</div></div></section>
        <section className="sco-te-s" aria-labelledby="sco-te-h"><div className="sco-in"><div className={`sco-ch sco-rv${vis.has('ts') ? ' sco-ok' : ''}`} ref={el => { secR.current['ts'] = el; }}><span className="sco-sey">Client Results</span><h2 id="sco-te-h" className="sco-st">Cost Reduction Results From Our Clients</h2><p className="sco-sd">CEOs, CFOs, and VPs of Engineering across the UK, AU, and US on measurable cost savings delivered by 1Solutions.</p></div><div className="sco-tg2" ref={teR}>{TESTIMONIALS.map((t, i) => (<div key={i} className={`sco-tc${t.feat ? ' feat' : ''}${vTe.includes(i) ? ' sco-tv' : ''}`} style={{ transitionDelay: `${i * 100}ms` }} itemScope itemType="https://schema.org/Review"><div className="sco-stars">★★★★★</div><p className="sco-txt" itemProp="reviewBody">{t.text}</p><div className="sco-au"><div className="sco-av" style={{ background: t.bg }}>{t.init}</div><div><div className="sco-an" itemProp="author">{t.name}</div><div className="sco-ar">{t.role}</div></div></div></div>))}</div></div></section>
        <section className="sco-wy-s" aria-labelledby="sco-wy-h"><div className="sco-in"><div className={`sco-rv${vis.has('wy') ? ' sco-ok' : ''}`} ref={el => { secR.current['wy'] = el; }}><span className="sco-sey">Why 1Solutions</span><h2 id="sco-wy-h" className="sco-st">Why Choose 1Solutions for Cost Optimization</h2><p className="sco-sd" style={{ maxWidth: 680 }}>Quantified savings, no delivery risk, 15 years of offshore delivery, cloud expertise, technical debt realism, measurable outcomes, no conflict of interest, and executive-ready reporting.</p></div><div className="sco-wy-g" ref={whR}>{WHY_CARDS.map((c, i) => (<div key={i} className={`sco-wc${vWh.includes(i) ? ' sco-wv' : ''}`} style={{ transitionDelay: `${i * 60}ms` }}><div className="sco-wd" /><h3>{c.title}</h3><p>{c.desc}</p></div>))}</div></div></section>
        <section id="contact" className="sco-ct-s" aria-labelledby="sco-ct-h"><div className="sco-ct-g"><div><h2 id="sco-ct-h" className="sco-ctt">Get Your Free Cost Audit</h2><p className="sco-ctd">Share your current team size, monthly cloud spend, and primary cost concerns — we will deliver a quantified savings roadmap identifying the highest-ROI cost reduction opportunities for your specific situation within 2–3 weeks.</p><div className="sco-ben">{[['✓','Free 2–3 week cost audit with quantified savings roadmap'],['✓','Every saving quantified: annual dollar amount, payback period, risk'],['✓','Cloud quick wins deliverable within 30 days of engagement'],['✓','15+ years of offshore delivery — not just advisory'],['✓','No conflict of interest — we recommend the right mix of levers']].map(([icon, text]) => (<div className="sco-be" key={text}><span className="sco-bi">{icon}</span><p>{text}</p></div>))}</div></div>
        <div className="sco-fb"><h3>Tell Us About Your Engineering Costs</h3><form className="sco-form" onSubmit={e => e.preventDefault()}>
          <div className="sco-fr"><div className="sco-fg"><label htmlFor="sco-nm">Full Name *</label><input id="sco-nm" type="text" placeholder="Your name" required /></div><div className="sco-fg"><label htmlFor="sco-em">Work Email *</label><input id="sco-em" type="email" placeholder="you@company.com" required /></div></div>
          <div className="sco-fr"><div className="sco-fg"><label htmlFor="sco-co">Company Name</label><input id="sco-co" type="text" placeholder="Your company" /></div><div className="sco-fg"><label htmlFor="sco-ph">Phone / WhatsApp</label><input id="sco-ph" type="tel" placeholder="+1 555 000 0000" /></div></div>
          <div className="sco-fg full"><label htmlFor="sco-ts">Engineering Team Size *</label><select id="sco-ts" required><option value="">Select team size...</option><option>1–3 engineers</option><option>4–8 engineers</option><option>9–15 engineers</option><option>16–30 engineers</option><option>30+ engineers</option></select></div>
          <div className="sco-fg full"><label htmlFor="sco-cs">Monthly Cloud Spend (approx.)</label><select id="sco-cs"><option value="">Select monthly cloud spend...</option><option>Under $5,000/month</option><option>$5,000–$15,000/month</option><option>$15,000–$50,000/month</option><option>$50,000–$150,000/month</option><option>$150,000+/month</option><option>No cloud spend / on-premises</option></select></div>
          <div className="sco-fg full"><label htmlFor="sco-pr">Primary Cost Concern *</label><select id="sco-pr" required><option value="">Select primary concern...</option><option>Engineering labour cost too high</option><option>Cloud infrastructure spend growing too fast</option><option>Low development velocity / features taking too long</option><option>High defect rate and QA costs</option><option>Manual processes and DevOps inefficiency</option><option>Technical debt slowing the team</option><option>Multiple of the above</option></select></div>
          <div className="sco-fg full"><label htmlFor="sco-ms">Context & Goals *</label><textarea id="sco-ms" rows={4} placeholder="Describe your current engineering setup, where you believe costs are highest, and what savings target or timeline you are working toward..." required /></div>
          <div className="sco-co"><input id="sco-co2" type="checkbox" required /><label htmlFor="sco-co2">I agree to the <Link href="/privacy-policy">Privacy Policy</Link>. Details are treated confidentially.</label></div>
          <button type="submit" className="sco-sub">Get Free Cost Audit →</button>
        </form></div></div></section>
        <section className="sco-fq-s" aria-labelledby="sco-fq-h"><div className="sco-in" style={{ maxWidth: 860 }}><span className="sco-sey">FAQ</span><h2 id="sco-fq-h">Software Development Cost Optimization — FAQ</h2><p className="sco-fq-sub">Savings quantum, offshore ROI, cloud cost reduction, technical debt impact, delivery risk, audit scope, and engagement timeline.</p><div className="sco-fql">{FAQS.map((item, i) => (<div key={i} className={`sco-fi${openFaq === i ? ' open' : ''}`} itemScope itemType="https://schema.org/Question"><button className="sco-fqb" onClick={() => setOpenFaq(openFaq === i ? -1 : i)} aria-expanded={openFaq === i}><div className="sco-fqb2">{String(i + 1).padStart(2, '0')}</div><span itemProp="name">{item.q}</span><svg className="sco-fch" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2"><polyline points="6 9 12 15 18 9" /></svg></button><div className="sco-faw" itemScope itemType="https://schema.org/Answer"><div className="sco-fa" itemProp="text">{item.a}</div></div></div>))}</div></div></section>
        <section className="sco-rel"><div className="sco-ri"><span className="sco-sey">Related Services</span><h2>Related Offshore & Efficiency Services</h2><p className="sco-rs">Offshore development, staff augmentation, IT outsourcing, virtual CTO, and DevOps engineering services from 1Solutions.</p><hr /><div className="sco-rts">{[['/offshore-development-company/','Offshore Development','sco-b'],['/it-staff-augmentation-services/','Staff Augmentation','sco-v'],['/it-outsourcing-services/','IT Outsourcing','sco-a'],['/virtual-cto-services/','Virtual CTO','sco-o'],['/devops-services-company/','DevOps Services','sco-c'],['/cloud-migration-services/','Cloud Migration','sco-c'],['/cloud-native-services/','Cloud Native','sco-v'],['/software-development-company/','Software Development','sco-b']].map(([href, label, cls]) => (<Link key={href} href={href} className={`sco-rt ${cls}`}>{label}</Link>))}</div></div></section>
      </div>
    </>
  );
}
