'use client';
import { useState, useEffect, useRef } from 'react';
import Head from 'next/head';
import Link from 'next/link';

const SCHEMA = {
  '@context': 'https://schema.org',
  '@graph': [
    { '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Home', item: 'https://www.1solutions.biz/' }, { '@type': 'ListItem', position: 2, name: 'Offshore Development Company', item: 'https://www.1solutions.biz/offshore-development-company/' }] },
    { '@type': 'Service', name: 'Offshore Software Development', url: 'https://www.1solutions.biz/offshore-development-company/', description: 'Offshore software development company — dedicated offshore development teams, staff augmentation, project-based offshore delivery, QA and testing, mobile and web application development. Hire pre-vetted offshore developers in India with 15+ years of experience at 60-70% below Western market rates.', provider: { '@type': 'Organization', name: '1Solutions', url: 'https://www.1solutions.biz', logo: { '@type': 'ImageObject', url: 'https://www.1solutions.biz/images/1solutions-logo.png' }, foundingDate: '2008', areaServed: ['US', 'GB', 'AU', 'CA', 'IN'] }, aggregateRating: { '@type': 'AggregateRating', ratingValue: '4.9', reviewCount: '142', bestRating: '5' } },
    { '@type': 'FAQPage', mainEntity: [
      { '@type': 'Question', name: 'What is an offshore development company?', acceptedAnswer: { '@type': 'Answer', text: 'An offshore development company provides software engineering talent and delivery capacity located in a different country from the client — typically in a lower-cost labour market such as India, Eastern Europe, or Southeast Asia. The offshore model allows US, UK, Australian, and Canadian businesses to access highly skilled developers, designers, QA engineers, DevOps specialists, and data scientists at significantly lower cost than hiring locally. An offshore development company differs from a freelance marketplace: it provides vetted, long-term dedicated team members who operate as an extension of your in-house team, with consistent quality, management oversight, and accountability. 1Solutions is headquartered in India with 15+ years of offshore delivery experience, serving clients primarily in the US, UK, Australia, and Canada.' } },
      { '@type': 'Question', name: 'What is the typical cost saving with an offshore development team?', acceptedAnswer: { '@type': 'Answer', text: 'Offshore development typically reduces engineering labour costs by 60–70% compared to hiring equivalent talent in the US, UK, or Australia. A senior full-stack developer hired locally in San Francisco might cost $180,000–$220,000 per year in salary alone, plus 30–40% in employer taxes, benefits, and overhead — totalling $250,000+ all-in. An equivalent offshore senior developer through 1Solutions costs $36,000–$60,000 per year all-inclusive, with no employer overhead, recruitment fees, or HR administration. The saving is on labour cost only — the code quality, communication standard, and engineering rigour are equivalent. Over a 5-person team this represents $800,000–$1,200,000 in annual savings, which is typically reinvested into faster product development or additional team capacity.' } },
      { '@type': 'Question', name: 'How do you handle time zone differences with offshore teams?', acceptedAnswer: { '@type': 'Answer', text: 'India Standard Time (IST) overlaps with US time zones for 4–5 hours per day, with UK time zones for 4.5 hours per day, and with Australian Eastern time zones for 3–4 hours per day. In practice this means: for US clients, the India team starts work during the US client evening, meaning deliverables are ready at the start of the US business day — creating a productive follow-the-sun development cycle. We schedule daily standup calls at overlap hours — typically 8:00–9:00 AM IST (which is 7:30–8:30 PM PST or 2:30–3:30 PM GMT). For UK clients, afternoon UK overlap (1:00–5:00 PM GMT = 6:30–10:30 PM IST) is typical. We adapt to client-preferred overlap windows. Extended shift hours (10:00 AM–7:00 PM IST, with some team members on late shift) maximise US East Coast overlap.' } },
      { '@type': 'Question', name: 'What is the difference between offshore development and IT outsourcing?', acceptedAnswer: { '@type': 'Answer', text: 'Offshore development specifically refers to building software or maintaining a development team in another country, with a focus on software engineering capacity. The offshore team writes code, manages infrastructure, conducts QA, and delivers software products. IT outsourcing is a broader term that includes offshore development but also covers IT support, helpdesk, managed services, data entry, business process outsourcing (BPO), and infrastructure management. All offshore development is IT outsourcing, but not all IT outsourcing is offshore development. 1Solutions focuses specifically on software engineering offshore services — we do not provide general BPO, data entry, or call centre services. Our offshore teams build and maintain web applications, mobile apps, cloud infrastructure, data pipelines, and SaaS products.' } },
      { '@type': 'Question', name: 'How do you ensure code quality and communication with an offshore team?', acceptedAnswer: { '@type': 'Answer', text: 'Code quality is maintained through mandatory code reviews (all pull requests require review from a senior developer before merge), automated CI/CD with test gates (unit tests, integration tests, linting, security scanning), weekly architecture review sessions, and monthly code quality audits using SonarQube or equivalent. Communication quality is maintained through: daily standups via Zoom/Meet, project management in Jira or Linear with full visibility for the client, Slack/Teams channel integration so the offshore team is present in your communication tools, detailed sprint planning and retrospectives, and a dedicated client success manager as an escalation point. We use English as the sole working language. All offshore developers at 1Solutions have worked with US, UK, or Australian clients for a minimum of 3 years before joining a new engagement.' } },
      { '@type': 'Question', name: 'How quickly can I start an offshore development team with 1Solutions?', acceptedAnswer: { '@type': 'Answer', text: 'A single offshore developer can typically start within 5–7 business days — the shortlist takes 24–48 hours, technical interview 1–2 days, contract 1–2 days, onboarding 1–2 days. A dedicated offshore team of 3–5 developers typically starts within 2–3 weeks — team composition is agreed first, then parallel shortlisting and interviews for each role. Teams of 10+ with specialised roles (ML engineer, DevOps lead, mobile developer) take 4–6 weeks to fully staff. We maintain a bench of pre-vetted developers across common technology stacks so the shortlisting step is fast. During the ramp-up period we can start with available team members and add specialist roles as they are confirmed.' } },
      { '@type': 'Question', name: 'What engagement models do you offer for offshore development?', acceptedAnswer: { '@type': 'Answer', text: 'We offer three engagement models: (1) Dedicated Offshore Team — a fixed team of developers and specialists working exclusively for your company, typically on a monthly retainer. Best for long-term product development, SaaS companies, and businesses building internal platforms. Team composition is flexible — you choose the roles. (2) Staff Augmentation — individual offshore developers or specialists embedded directly in your existing team, working in your tools (Jira, Slack, GitHub) and under your direct management. Best for supplementing a local team with specific technical skills. (3) Fixed-Price Project — a defined scope, timeline, and price for a specific software deliverable. Best for well-scoped projects with clear requirements, such as building a new mobile app, migrating a legacy system, or developing a new SaaS module.' } },
      { '@type': 'Question', name: 'What technologies does 1Solutions offshore team cover?', acceptedAnswer: { '@type': 'Answer', text: 'Our offshore development team covers the full modern software stack: Frontend (React, Next.js, Angular, Vue.js, TypeScript); Backend (Node.js, Python/Django/FastAPI, PHP/Laravel, Java/Spring Boot, .NET/C#, Ruby on Rails, Go); Mobile (React Native, Flutter, Swift/iOS, Kotlin/Android); Database (PostgreSQL, MySQL, MongoDB, Redis, Elasticsearch); Cloud & DevOps (AWS, Azure, GCP, Kubernetes, Terraform, Docker, CI/CD); Data Science & AI (Python ML, TensorFlow, PyTorch, scikit-learn, LLM integration, RAG pipelines); Blockchain (Solidity, Web3.js, Hardhat); and CMS (WordPress, Shopify, Magento, Drupal). We provide specialists rather than generalists — each team member has deep expertise in their primary stack rather than superficial knowledge across everything.' } },
    ] },
  ],
};

const SERVICES = [
  { n: '01', title: 'Dedicated Offshore Development Team', desc: 'A permanent offshore team working exclusively for your company — frontend, backend, mobile, DevOps, QA, and data science specialists assembled to your exact requirements. The team integrates with your workflow (Jira, GitHub, Slack, daily standups), operates on your processes, and scales up or down as your product roadmap evolves. You get senior engineers at 60–70% below Western market rates with no recruitment overhead or employer liabilities.' },
  { n: '02', title: 'Offshore Staff Augmentation', desc: 'Individual offshore developers embedded directly in your existing engineering team — working in your tools, attending your standups, committing to your repositories. Staff augmentation is the fastest way to add specific technical skills (e.g. a React specialist, a DevOps engineer, a data scientist) without the 3–6 month local hiring timeline or the full cost of a permanent hire. Developers are available in 5–7 business days.', feat: true },
  { n: '03', title: 'Fixed-Price Offshore Project Delivery', desc: 'Well-scoped software projects delivered at a fixed price — new web or mobile application, legacy system migration, SaaS module development, API integration, or platform rebuild. Fixed-price engagement begins with a discovery phase (requirements, architecture, prototyping), followed by sprint-based delivery with weekly client demos and a fixed delivery date. Best for businesses with clear requirements that need cost predictability.' },
  { n: '04', title: 'Offshore QA & Software Testing', desc: 'Dedicated offshore QA engineers and test automation specialists — manual testing (functional, regression, UAT, exploratory), automated test suite development (Selenium, Cypress, Playwright, Appium for mobile), performance testing (k6, Locust, JMeter), API testing (Postman, REST-assured), and security testing. QA teams integrated with your CI/CD pipeline to prevent regressions from reaching production.' },
  { n: '05', title: 'Offshore Mobile App Development', desc: 'Cross-platform and native mobile application development — React Native and Flutter for cross-platform iOS and Android, Swift for native iOS, Kotlin for native Android. Full-cycle offshore mobile development: UI/UX design, frontend development, backend API, app store submission, and post-launch maintenance. Experienced in consumer apps, enterprise mobile, healthcare (HIPAA), fintech (PCI-DSS), and e-commerce.' },
  { n: '06', title: 'Offshore Web Application Development', desc: 'Custom web application development — React/Next.js for performant frontend, Node.js, Python (Django/FastAPI), PHP (Laravel), or Java (Spring Boot) for backend, PostgreSQL/MySQL/MongoDB for data layer, Redis for caching, AWS/Azure/GCP for cloud infrastructure. Full-stack offshore teams for SaaS products, internal tools, customer portals, e-commerce platforms, and B2B web applications.' },
  { n: '07', title: 'Offshore Cloud & DevOps Engineering', desc: 'Offshore cloud engineering and DevOps specialists — AWS, Azure, GCP architecture and management, Kubernetes cluster operations, Terraform infrastructure as code, CI/CD pipeline implementation (GitHub Actions, GitLab CI), monitoring (Prometheus, Grafana, Datadog), and security (DevSecOps). Cloud cost optimisation reviews typically save 20–40% on existing cloud spend as a first-week deliverable.' },
  { n: '08', title: 'Offshore AI & Data Science Teams', desc: 'Offshore AI and data science specialists — machine learning model development (scikit-learn, XGBoost, PyTorch, TensorFlow), LLM integration and RAG pipeline development (LangChain, OpenAI, Claude API), computer vision, NLP, time-series forecasting, A/B testing and statistical analysis, MLOps (ML pipeline, model monitoring), and data engineering (Spark, dbt, Airflow). AI capability at offshore economics.' },
  { n: '09', title: 'Offshore CMS & E-Commerce Development', desc: 'Offshore CMS and e-commerce development specialists — WordPress (custom themes, plugins, WooCommerce), Shopify (custom themes, Hydrogen/Remix, app development), Magento/Adobe Commerce, Drupal, and headless CMS (Contentful, Sanity, Strapi). Offshore CMS teams provide significantly faster delivery on content-heavy sites and e-commerce projects than boutique local agencies.' },
  { n: '10', title: 'Offshore Team Setup & Management Consulting', desc: 'Offshore team setup advisory for businesses building their first offshore capability — technology stack selection, role definition, interview process design, KPI and SLA framework, toolchain setup (Jira, GitHub, Slack integration, time tracking, code review process), onboarding playbook, and ongoing management support. We help you build a high-performing offshore team that operates as transparently as a local hire.' },
];

const TECH_STACK = [
  { group: 'Frontend', color: '#0e7490', items: ['React / Next.js', 'Angular / Vue.js', 'TypeScript', 'Tailwind CSS', 'React Native', 'Flutter'] },
  { group: 'Backend', color: '#0369a1', items: ['Node.js / Express', 'Python / Django / FastAPI', 'PHP / Laravel', 'Java / Spring Boot', '.NET / C#', 'Go / Ruby on Rails'] },
  { group: 'Mobile', color: '#0f766e', items: ['React Native', 'Flutter', 'Swift (iOS)', 'Kotlin (Android)', 'Expo', 'Capacitor'] },
  { group: 'Database & Cache', color: '#7e22ce', items: ['PostgreSQL / MySQL', 'MongoDB / DynamoDB', 'Redis / Memcached', 'Elasticsearch', 'Snowflake / BigQuery', 'Supabase / PlanetScale'] },
  { group: 'Cloud & DevOps', color: '#b45309', items: ['AWS / Azure / GCP', 'Kubernetes / Docker', 'Terraform / Ansible', 'GitHub Actions / GitLab CI', 'Prometheus / Grafana', 'Datadog / PagerDuty'] },
  { group: 'AI / ML & Data', color: '#6d28d9', items: ['Python ML (scikit-learn, XGBoost)', 'PyTorch / TensorFlow', 'LangChain / OpenAI API', 'dbt / Apache Spark', 'Airflow / Prefect', 'Tableau / Power BI'] },
  { group: 'QA & Testing', color: '#dc2626', items: ['Cypress / Playwright', 'Selenium / Appium', 'Jest / Pytest', 'k6 / Locust (perf)', 'Postman / REST-assured', 'SonarQube / Trivy'] },
  { group: 'CMS & E-Commerce', color: '#059669', items: ['WordPress / WooCommerce', 'Shopify / Hydrogen', 'Magento / Adobe Commerce', 'Drupal', 'Contentful / Sanity', 'Strapi / Payload CMS'] },
];

const ENGAGEMENT_MODELS = [
  { id: 'dedicated', name: 'Dedicated Offshore Team', badge: 'Most Popular', badgeColor: '#D97706', feat: true, icon: 'M16 11c1.66 0 2.99-1.34 2.99-3S17.66 5 16 5c-1.66 0-3 1.34-3 3s1.34 3 3 3zm-8 0c1.66 0 2.99-1.34 2.99-3S9.66 5 8 5C6.34 5 5 6.34 5 8s1.34 3 3 3zm0 2c-2.33 0-7 1.17-7 3.5V19h14v-2.5c0-2.33-4.67-3.5-7-3.5zm8 0c-.29 0-.62.02-.97.05 1.16.84 1.97 1.97 1.97 3.45V19h6v-2.5c0-2.33-4.67-3.5-7-3.5z', headline: 'Your own offshore engineering team — exclusive, scalable, cost-effective.', desc: 'A dedicated team of offshore developers working exclusively for your company on a monthly retainer. Team members use your tools, attend your meetings, and are fully committed to your product roadmap — not juggled across multiple client projects. Start from 1 developer, scale to 50+ as needed.', bestFor: ['SaaS product companies building and maintaining their platform', 'Scale-ups needing to grow engineering capacity quickly and affordably', 'Enterprises running long-term digital transformation programmes', 'Startups post-funding building their core product team offshore'], process: 'Requirements → shortlist 24–48 hrs → technical interviews → start in 2–3 weeks', timeline: 'Team of 3–5 available within 2–3 weeks' },
  { id: 'augmentation', name: 'Staff Augmentation', badge: 'Fastest Start', badgeColor: '#0e7490', icon: 'M11.99 2C6.47 2 2 6.48 2 12s4.47 10 9.99 10C17.52 22 22 17.52 22 12S17.52 2 11.99 2zM12 20c-4.42 0-8-3.58-8-8s3.58-8 8-8 8 3.58 8 8-3.58 8-8 8zm.5-13H11v6l5.25 3.15.75-1.23-4.5-2.67V7z', headline: 'Add individual offshore specialists to your existing team in 5–7 days.', desc: 'One or more offshore developers embedded directly in your team — working in your Jira, GitHub, and Slack. You manage them directly. Ideal for adding specific skills quickly without the overhead of a full team setup.', bestFor: ['Companies needing 1–3 specific technology specialists quickly', 'Teams augmenting local developers with offshore cost-efficiency', 'Project bursts requiring temporary engineering capacity increase', 'Covering gaps created by local hiring delays or attrition'], process: 'Role definition → shortlist 24 hrs → interview → start in 5–7 days', timeline: 'Individual developers available within 5–7 business days' },
  { id: 'project', name: 'Fixed-Price Project', badge: 'Cost Certainty', badgeColor: '#0369a1', icon: 'M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm-7 3c1.93 0 3.5 1.57 3.5 3.5S13.93 13 12 13s-3.5-1.57-3.5-3.5S10.07 6 12 6zm7 13H5v-.23c0-.62.28-1.2.76-1.58C7.47 15.82 9.64 15 12 15s4.53.82 6.24 2.19c.48.38.76.97.76 1.58V19z', headline: 'Defined scope, fixed price, guaranteed delivery.', desc: 'A complete software project delivered at a fixed price with a guaranteed delivery timeline. Discovery phase agrees requirements and architecture before development begins. Best for well-scoped projects where budget certainty is the priority.', bestFor: ['New web or mobile application with defined requirements', 'Legacy system migration with clear source and target architecture', 'SaaS MVP or new product module with defined feature set', 'E-commerce or CMS build with established design brief'], process: 'Scoping → discovery → sprint delivery → UAT → launch', timeline: 'Project kick-off within 1 week of contract' },
];

const PROCESS_STEPS = [
  { num: '01', title: 'Define Your Team Requirements', desc: 'Share your technology stack, team size needed, required seniority levels, domain expertise (fintech, healthtech, e-commerce), and preferred working hours overlap. The more specific your requirements, the faster and more accurate our shortlisting. We will ask clarifying questions about your team culture, communication style, and what has or has not worked with previous developers or contractors.' },
  { num: '02', title: 'Shortlist Within 24–48 Hours', desc: 'Within 24–48 business hours we send a shortlist of pre-vetted offshore developer profiles matched to your requirements — including CV, portfolio, years of experience per technology, and client references from similar engagements. Not a bulk database search — a curated shortlist from our active developer pool and pre-screened candidate network.' },
  { num: '03', title: 'Technical Interviews on Your Terms', desc: 'Interview shortlisted candidates using your own technical assessment — coding challenge, architecture discussion, live debugging session, or take-home project. You select the format. Our developers are accustomed to rigorous technical interviews with US and UK engineering teams. You make the hiring decision; we never pressure you toward a candidate.' },
  { num: '04', title: 'Toolchain Setup & Team Onboarding', desc: 'Once candidates are selected, we handle the offshore-side onboarding: NDAs, contracts, equipment provisioning, VPN and security setup, and communication tool access. We configure the team in your project management tools (Jira, Linear, Asana), version control (GitHub, GitLab, Bitbucket), and communication channels (Slack, Teams). Typically complete within 3–5 business days.' },
  { num: '05', title: 'Sprint Delivery & Daily Collaboration', desc: 'The offshore team joins your agile workflow — daily standups, sprint planning, code reviews, and retrospectives. All code goes through pull request review before merge. We provide a dedicated client success manager as an escalation point separate from the delivery team. Velocity is tracked from sprint one and shared transparently so you can make capacity decisions with data.' },
  { num: '06', title: 'Scale, Optimise & Retain', desc: 'As your product evolves, your offshore team scales with it — adding new roles, transitioning from sprint-based to continuous delivery, building specialised sub-teams (data, mobile, platform). We conduct quarterly performance reviews with you and the team, and provide salary benchmarking to ensure competitive retention. Most clients retain offshore teams for 3+ years.' },
];

const TESTIMONIALS = [
  { text: "We grew our offshore team at 1Solutions from 2 developers to 11 over 18 months. The quality is genuinely equal to our local hires — rigorous pull request culture, proactive communication, and solid architectural judgment. Our product velocity doubled and our engineering cost per feature dropped by 58%. The investment thesis for offshore development at scale is completely validated.", name: 'Mark T.', role: 'CTO, SaaS Platform (UK)', init: 'MT', bg: '#0F3460' },
  { text: "We hired a single offshore senior React developer via 1Solutions for what we thought was a 3-month project. He is still with us 2 years later — now leading our frontend architecture. The staff augmentation model let us move fast, evaluate the fit, and convert to a long-term arrangement without risk. We have since added 4 more offshore engineers through 1Solutions.", name: 'Jessica R.', role: 'VP Engineering, E-Commerce (AU)', init: 'JR', bg: '#0a2a1a', feat: true },
  { text: "Our fixed-price offshore project (Rails API migration + React frontend rebuild) was delivered on time and 3% under budget. Code quality was audited by our in-house lead after delivery — zero architectural concerns. 1Solutions delivered exactly what was scoped. We are now moving to a dedicated team model for ongoing development.", name: 'Chris L.', role: 'Co-founder, Fintech Startup (US)', init: 'CL', bg: '#1e3a5f' },
];

const WHY_CARDS = [
  { title: '15+ Years of Offshore Delivery', desc: 'Founded in 2008, 1Solutions has 15+ years of offshore software development experience serving US, UK, Australian, and Canadian clients. We have worked through the maturation of the offshore model — from early email-based coordination to modern real-time collaboration — and our processes reflect what actually works.' },
  { title: '60–70% Cost Reduction', desc: 'Senior offshore developers at 1Solutions typically cost 60–70% less than equivalent local hires in the US or UK — with no recruitment fee, employer taxes, benefits overhead, or office cost. The cost saving is on labour only; the engineering quality is equivalent.' },
  { title: 'Pre-Vetted, Not Random Matching', desc: 'Every developer in our offshore pool has been vetted through a technical coding assessment, architectural interview, and English communication test. When we send you a shortlist, every candidate has already passed our internal bar — you are not filtering a bulk database.' },
  { title: 'Zero Freelancer Instability', desc: 'Unlike freelance platforms, our offshore team members are full-time employees with stable employment — not contract-to-contract. This means no sudden unavailability, no competing projects during your sprint, and genuine long-term commitment to your product.' },
  { title: 'Full Timezone Flexibility', desc: 'India Standard Time gives 4–5 hours of daily overlap with US timezones and 4.5 hours with UK — enough for a daily standup, async review cycles, and responsive communication throughout the day. We adapt to your preferred overlap window.' },
  { title: 'Full-Stack Capability', desc: 'Frontend, backend, mobile, DevOps, QA, data science, AI, CMS, and e-commerce — covered by specialists, not generalists. You can build a complete product team offshore through 1Solutions rather than splitting across multiple vendors.' },
  { title: 'Transparent Management', desc: 'Full visibility into your offshore team — Jira velocity tracking, GitHub commit history, weekly status reports, monthly retrospectives, and a dedicated client success manager. No black-box delivery where you find out about problems after they become blockers.' },
  { title: '5-Day Replacement Guarantee', desc: 'If a team member leaves or is not the right fit, we replace within 5 business days at no additional recruitment cost. Team continuity is our responsibility, not yours.' },
];

const FAQS = [
  { q: 'What is an offshore development company?', a: 'An offshore development company provides software engineering capacity located in another country — typically India — for clients in the US, UK, Australia, or Canada. It provides dedicated development teams, staff augmentation, or project delivery at significantly lower cost than hiring locally, without sacrificing code quality or communication.' },
  { q: 'What is the typical cost saving with offshore development?', a: 'Offshore development typically saves 60–70% on engineering labour cost vs equivalent US/UK hires. A 5-person offshore senior development team costs approximately $150,000–$250,000/year all-inclusive through 1Solutions, vs $1,000,000–$1,400,000 for an equivalent local team in San Francisco or London.' },
  { q: 'How do you handle time zone differences?', a: 'IST provides 4–5 hours of daily overlap with US East Coast, 4.5 hours with UK, and 3–4 hours with Australia Eastern. Daily standups are scheduled in the overlap window. Follow-the-sun development means deliverables are ready at the start of your business day.' },
  { q: 'How quickly can I start an offshore development team?', a: 'A single developer can start in 5–7 business days. A team of 3–5 is typically ready within 2–3 weeks. Larger teams (10+) take 4–6 weeks to fully staff, depending on specialisation requirements.' },
  { q: 'What technologies does 1Solutions cover?', a: 'React, Next.js, Angular, Vue.js, Node.js, Python, PHP/Laravel, Java, .NET, Go, React Native, Flutter, Swift, Kotlin, PostgreSQL, MongoDB, AWS, Azure, GCP, Kubernetes, Terraform, ML/AI, and CMS (WordPress, Shopify, Magento, Drupal).' },
  { q: 'What engagement models do you offer?', a: 'Dedicated Offshore Team (monthly retainer, exclusive team), Staff Augmentation (individual developers embedded in your team, available in 5–7 days), and Fixed-Price Project (defined scope, fixed price, guaranteed delivery date).' },
  { q: 'How do you ensure code quality and communication?', a: 'Mandatory code reviews on all PRs, CI/CD with automated test gates, daily standups, Jira/GitHub visibility, weekly status reports, and a dedicated client success manager. All offshore developers use English as their sole working language.' },
  { q: 'What is your replacement guarantee?', a: 'If a team member leaves or is not the right fit, we replace within 5 business days at no additional recruitment cost. We also conduct quarterly performance reviews and provide salary benchmarking to retain the best team members long-term.' },
];

function useCountUp(target, duration = 1800, start = false) {
  const [count, setCount] = useState(0);
  useEffect(() => { if (!start) return; const num = parseInt(target.replace(/\D/g, ''), 10); if (!num) return; let t0 = null; const step = ts => { if (!t0) t0 = ts; const p = Math.min((ts - t0) / duration, 1); setCount(Math.floor((1 - Math.pow(1 - p, 3)) * num)); if (p < 1) requestAnimationFrame(step); }; requestAnimationFrame(step); }, [start, target, duration]);
  return count;
}
function StatItem({ label, val, started }) {
  const num = useCountUp(val, 1800, started);
  const suffix = val.replace(/[\d,]/g, '');
  return (<div className="od-sc"><div className="od-sv">{started ? (val.includes(',') ? num.toLocaleString() : num) + suffix : val}</div><div className="od-sl">{label}</div></div>);
}

export default function OffshoreDevCompany() {
  const [showAll, setShowAll] = useState(false);
  const [openFaq, setOpenFaq] = useState(0);
  const [ss, setSs] = useState(false);
  const [vis, setVis] = useState(new Set());
  const [vSk, setVSk] = useState([]); const [vEn, setVEn] = useState([]); const [vWh, setVWh] = useState([]); const [vTe, setVTe] = useState([]); const [vSt, setVSt] = useState([]);
  const stR = useRef(null); const secR = useRef({});
  const skR = useRef(null); const enR = useRef(null); const whR = useRef(null); const teR = useRef(null); const stGr = useRef(null);
  useEffect(() => { if (!stR.current) return; const o = new IntersectionObserver(([e]) => { if (e.isIntersecting) { setSs(true); o.disconnect(); } }, { threshold: 0.4 }); o.observe(stR.current); return () => o.disconnect(); }, []);
  useEffect(() => { const pairs = [[skR, SERVICES.length, setVSk],[enR, 3, setVEn],[whR, WHY_CARDS.length, setVWh],[teR, 3, setVTe],[stGr, TECH_STACK.length, setVSt]]; const obs = pairs.map(([ref, count, setter]) => { if (!ref.current) return null; const o = new IntersectionObserver(([e]) => { if (e.isIntersecting) { Array.from({ length: count }, (_, i) => setTimeout(() => setter(p => p.includes(i) ? p : [...p, i]), i * 80)); o.disconnect(); } }, { threshold: 0.05 }); o.observe(ref.current); return o; }); return () => obs.forEach(o => o?.disconnect()); }, []);
  useEffect(() => { const ks = Object.keys(secR.current); const obs = ks.map(k => { const el = secR.current[k]; if (!el) return null; const o = new IntersectionObserver(([e]) => { if (e.isIntersecting) { setVis(p => new Set([...p, k])); o.disconnect(); } }, { threshold: 0.1 }); o.observe(el); return o; }); return () => obs.forEach(o => o?.disconnect()); }, []);
  const visServices = showAll ? SERVICES : SERVICES.slice(0, 6);
  return (
    <>
      <Head>
        <title>Offshore Development Company | Dedicated Offshore Teams | 1Solutions</title>
        <meta name="description" content="Offshore software development company — dedicated offshore development teams, staff augmentation, and fixed-price project delivery. Senior developers in India at 60–70% below US/UK rates. 15+ years experience serving US, UK, AU clients." />
        <link rel="canonical" href="https://www.1solutions.biz/offshore-development-company/" />
        <meta property="og:title" content="Offshore Development Company | Dedicated Teams | 1Solutions" />
        <meta property="og:description" content="Hire dedicated offshore development teams from India. 60–70% cost savings vs US/UK rates. Senior developers across React, Node.js, Python, Mobile, DevOps, AI/ML." />
        <meta property="og:url" content="https://www.1solutions.biz/offshore-development-company/" />
        <meta property="og:image" content="https://www.1solutions.biz/images/banner-1sol.jpg" />
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(SCHEMA) }} />
        <style>{`
          .od-page{font-family:'Inter',-apple-system,BlinkMacSystemFont,sans-serif;background:linear-gradient(135deg,#f0fdff 0%,#cffafe 20%,#ecfeff 50%,#fef3c7 75%,#f0fdf4 100%);color:#0c2340;line-height:1.6;position:relative;overflow-x:hidden}
          .od-page *,.od-page *::before,.od-page *::after{box-sizing:border-box}
          .od-orb{position:absolute;border-radius:50%;pointer-events:none;z-index:0;filter:blur(20px)}
          .od-o1{width:860px;height:860px;background:radial-gradient(circle,rgba(14,116,144,.20) 0%,rgba(6,182,212,.08) 40%,transparent 70%);top:-260px;right:-240px}
          .od-o2{width:760px;height:760px;background:radial-gradient(circle,rgba(217,119,6,.15) 0%,rgba(251,191,36,.06) 40%,transparent 70%);bottom:0;left:-220px}
          .od-o3{width:520px;height:520px;background:radial-gradient(circle,rgba(15,118,110,.12) 0%,transparent 70%);top:44%;left:-100px;transform:translateY(-50%)}
          .od-bc{position:relative;z-index:2;padding:16px 40px 0;max-width:1440px;margin:0 auto}
          .od-bc ol{display:flex;flex-wrap:wrap;gap:6px;list-style:none;margin:0;padding:0;font-size:13px;color:#5a7a8a}
          .od-bc li{display:flex;align-items:center;gap:6px}
          .od-bc li::after{content:'/';opacity:.45}
          .od-bc li:last-child::after{display:none}
          .od-bc a{color:#0c2340;text-decoration:none}
          .od-hero{position:relative;z-index:2;text-align:center;max-width:960px;margin:0 auto;padding:44px 40px 32px}
          .od-ey{display:block;font-size:11px;font-weight:700;letter-spacing:2.5px;text-transform:uppercase;color:#4a6a7a;margin-bottom:14px}
          .od-hero h1{font-size:50px;font-weight:900;line-height:1.09;letter-spacing:-1.5px;margin-bottom:16px;background:linear-gradient(90deg,#0c2340 0%,#0e7490 100%);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text}
          .od-desc{font-size:16px;color:#2a4a5a;line-height:1.65;max-width:740px;margin:0 auto 24px}
          .od-tr{display:flex;flex-wrap:wrap;justify-content:center;gap:10px;margin-bottom:26px}
          .od-badge{display:inline-flex;align-items:center;gap:6px;background:rgba(255,255,255,.60);backdrop-filter:blur(10px);border:1px solid rgba(255,255,255,.85);border-radius:100px;padding:6px 14px;font-size:12px;font-weight:600;color:#0c2340;box-shadow:0 2px 8px rgba(12,35,64,.07)}
          .od-dot{width:7px;height:7px;border-radius:50%;background:#0e7490;flex-shrink:0}
          .od-ctas{display:flex;flex-wrap:wrap;gap:12px;justify-content:center}
          .od-p{display:inline-block;padding:14px 36px;background:#0e7490;color:#fff;border-radius:50px;font-weight:700;font-size:15px;text-decoration:none;transition:all .25s;box-shadow:0 6px 24px rgba(14,116,144,.28)}
          .od-p:hover{background:#0c2340;transform:translateY(-2px)}
          .od-g{display:inline-block;padding:14px 36px;background:rgba(255,255,255,.55);backdrop-filter:blur(16px);border:1.5px solid rgba(255,255,255,.85);border-radius:50px;color:#0c2340;font-weight:700;font-size:15px;text-decoration:none;transition:all .25s}
          .od-g:hover{background:rgba(255,255,255,.85);border-color:rgba(14,116,144,.5);transform:translateY(-2px)}
          .od-stats{position:relative;z-index:2;display:grid;grid-template-columns:repeat(4,1fr);max-width:940px;margin:28px auto 0;background:rgba(255,255,255,.45);backdrop-filter:blur(24px);border:1px solid rgba(255,255,255,.85);box-shadow:0 4px 24px rgba(12,35,64,.08),inset 0 1px 0 rgba(255,255,255,.95)}
          .od-sc{padding:18px 16px;text-align:center;border-right:1px solid rgba(12,35,64,.10)}
          .od-sc:last-child{border-right:none}
          .od-sv{font-size:28px;font-weight:900;color:#0e7490;letter-spacing:-.5px;line-height:1}
          .od-sl{font-size:11px;color:#4a6a7a;font-weight:500;margin-top:5px}
          .od-logos{position:relative;z-index:2;padding:24px 40px 52px;display:flex;flex-direction:column;align-items:center;gap:14px}
          .od-ll{font-size:10px;font-weight:700;letter-spacing:2px;text-transform:uppercase;color:#5a7a8a}
          .od-lw{width:100%;overflow:hidden}
          .od-lt{display:flex;align-items:center;gap:60px;width:max-content;animation:od-mq 28s linear infinite}
          .od-lt:hover{animation-play-state:paused}
          @keyframes od-mq{0%{transform:translateX(0)}100%{transform:translateX(-50%)}}
          .od-cl{height:24px;width:auto;max-width:110px;object-fit:contain;filter:grayscale(100%);opacity:.45;transition:opacity .25s,filter .25s}
          .od-cl:hover{opacity:.85;filter:grayscale(0%)}
          .od-sey{font-size:11px;font-weight:700;letter-spacing:2px;text-transform:uppercase;color:#D97706;margin-bottom:10px;display:block}
          .od-st{font-size:46px;font-weight:900;line-height:1.12;letter-spacing:-1px;background:linear-gradient(90deg,#0c2340 0%,#D97706 100%);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;margin-bottom:10px}
          .od-sd{font-size:15px;color:#3a5a6a;line-height:1.7}
          .od-rv{opacity:0;transform:translateY(44px);transition:opacity .7s cubic-bezier(0.22,1,.36,1),transform .7s cubic-bezier(0.22,1,.36,1)}
          .od-rv.od-ok{opacity:1;transform:translateY(0)}
          .od-in{max-width:1300px;margin:0 auto}
          .od-sk-s{background:transparent;padding:72px 40px 60px;position:relative;z-index:1}
          .od-sk-g{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-top:40px}
          .od-sk-c{background:linear-gradient(135deg,rgba(240,253,255,.50) 0%,rgba(255,255,255,.85) 55%,rgba(207,250,254,.40) 100%);backdrop-filter:blur(16px);border:1px solid rgba(255,255,255,.85);border-radius:20px;padding:26px 22px 22px;position:relative;overflow:hidden;box-shadow:0 4px 24px rgba(12,35,64,.08),inset 0 1px 0 rgba(255,255,255,.95);opacity:0;transform:translateY(36px);transition:opacity .6s cubic-bezier(0.22,1,.36,1),transform .6s cubic-bezier(0.22,1,.36,1),border-color .2s}
          .od-sk-c.od-cv{opacity:1;transform:translateY(0)}
          .od-sk-c.od-cv:hover{transform:translateY(-6px);border-color:rgba(14,116,144,.30);box-shadow:0 16px 48px rgba(12,35,64,.14)}
          .od-sk-c.feat{border-color:rgba(14,116,144,.20)}
          .od-sk-n{position:absolute;top:8px;right:14px;font-size:72px;font-weight:900;line-height:1;color:#0c2340;opacity:.055;pointer-events:none;letter-spacing:-4px;user-select:none}
          .od-sk-c h3{font-size:16px;font-weight:700;color:#0c2340;margin:0 0 8px;position:relative;z-index:1}
          .od-sk-c p{font-size:13px;color:#3a5a6a;line-height:1.65;margin:0;position:relative;z-index:1}
          .od-sk-c::before{content:'';position:absolute;left:0;top:12%;height:76%;width:3px;background:linear-gradient(180deg,#0e7490,#06b6d4);border-radius:0 2px 2px 0;transform:scaleY(0);transform-origin:top center;transition:transform .3s cubic-bezier(0.22,1,.36,1)}
          .od-sk-c.od-cv:hover::before{transform:scaleY(1)}
          .od-sm{text-align:center;margin-top:22px}
          .od-bm{display:inline-block;background:#fff;border:1.5px solid rgba(12,35,64,.18);color:#0c2340;padding:10px 30px;border-radius:20px;font-weight:600;font-size:14px;cursor:pointer;transition:all .2s;font-family:inherit}
          .od-bm:hover{background:#0c2340;border-color:#0c2340;color:#fff;transform:translateY(-2px)}
          .od-tec-s{background:#f5fdfe;border-top:1px solid rgba(12,35,64,.08);border-bottom:1px solid rgba(12,35,64,.08);padding:72px 40px;position:relative;z-index:1}
          .od-tec-g{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin-top:40px}
          .od-tec-c{background:linear-gradient(135deg,rgba(240,253,255,.50) 0%,rgba(255,255,255,.85) 55%,rgba(207,250,254,.40) 100%);backdrop-filter:blur(16px);border:1px solid rgba(255,255,255,.85);border-radius:20px;padding:22px 20px;box-shadow:0 4px 24px rgba(12,35,64,.08),inset 0 1px 0 rgba(255,255,255,.95);opacity:0;transform:translateY(32px);transition:opacity .55s cubic-bezier(0.22,1,.36,1),transform .55s cubic-bezier(0.22,1,.36,1),border-color .2s}
          .od-tec-c.od-sv2{opacity:1;transform:translateY(0)}
          .od-tec-c.od-sv2:hover{border-color:rgba(14,116,144,.25);box-shadow:0 14px 40px rgba(12,35,64,.12)}
          .od-tg{font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:1.2px;margin-bottom:12px;padding-bottom:8px;border-bottom:2px solid}
          .od-pills{display:flex;flex-wrap:wrap;gap:6px}
          .od-pill{display:inline-block;font-size:11.5px;font-weight:500;padding:4px 10px;border-radius:100px;border:1px solid}
          .od-en-s{padding:80px 40px;position:relative;z-index:1}
          .od-en-g{display:grid;grid-template-columns:repeat(3,1fr);gap:20px;margin-top:40px}
          .od-en-c{background:linear-gradient(135deg,rgba(240,253,255,.50) 0%,rgba(255,255,255,.85) 55%,rgba(207,250,254,.40) 100%);backdrop-filter:blur(16px);border:1px solid rgba(255,255,255,.85);border-radius:24px;padding:32px 28px;box-shadow:0 4px 24px rgba(12,35,64,.08),inset 0 1px 0 rgba(255,255,255,.95);opacity:0;transform:translateY(44px);transition:opacity .65s cubic-bezier(0.22,1,.36,1),transform .65s cubic-bezier(0.22,1,.36,1),border-color .2s}
          .od-en-c.od-ev{opacity:1;transform:translateY(0)}
          .od-en-c.od-ev:hover{border-color:rgba(14,116,144,.25);box-shadow:0 16px 48px rgba(12,35,64,.14)}
          .od-en-c.feat{background:linear-gradient(135deg,rgba(254,243,199,.52) 0%,rgba(255,255,255,.87) 55%,rgba(240,253,255,.45) 100%);border-color:rgba(217,119,6,.28);box-shadow:0 8px 32px rgba(217,119,6,.12),inset 0 1px 0 rgba(255,255,255,1);transform:translateY(-8px)}
          .od-en-c.feat.od-ev{transform:translateY(-8px)}
          .od-en-c.feat.od-ev:hover{transform:translateY(-12px)}
          .od-en-b{display:inline-block;font-size:10px;font-weight:700;letter-spacing:1.2px;text-transform:uppercase;padding:5px 12px;border-radius:100px;border:1px solid;margin-bottom:18px}
          .od-en-i{width:48px;height:48px;background:rgba(12,35,64,.07);border-radius:14px;display:flex;align-items:center;justify-content:center;margin-bottom:14px}
          .od-en-i svg{fill:#0c2340}
          .od-en-c.feat .od-en-i{background:rgba(217,119,6,.10)}
          .od-en-c.feat .od-en-i svg{fill:#D97706}
          .od-en-n{font-size:22px;font-weight:900;color:#0c2340;margin:0 0 6px;letter-spacing:-.3px}
          .od-en-h{font-size:13px;font-weight:600;color:#0e7490;margin-bottom:12px}
          .od-en-c.feat .od-en-h{color:#D97706}
          .od-en-d{font-size:14px;color:#3a5a6a;line-height:1.7;margin-bottom:18px}
          .od-en-ll{font-size:10px;font-weight:700;letter-spacing:1px;text-transform:uppercase;color:#5a7a8a;margin-bottom:8px}
          .od-en-li{list-style:none;padding:0;margin:0 0 18px;display:flex;flex-direction:column;gap:7px}
          .od-en-li li{display:flex;align-items:flex-start;gap:8px;font-size:13px;color:#374151;line-height:1.5}
          .od-en-li li::before{content:'✓';font-weight:800;color:#0e7490;flex-shrink:0;margin-top:1px}
          .od-en-c.feat .od-en-li li::before{color:#D97706}
          .od-en-p{font-size:12px;color:#5a7a8a;padding-top:14px;border-top:1px solid rgba(12,35,64,.08)}
          .od-en-p strong{color:#0c2340}
          .od-en-tl{display:inline-block;font-size:11px;font-weight:600;color:#D97706;margin-top:6px}
          .od-en-a{display:block;margin-top:18px;padding:11px;border-radius:50px;font-size:13px;font-weight:700;text-align:center;text-decoration:none;transition:all .22s;background:rgba(12,35,64,.09);color:#0c2340;border:1.5px solid rgba(12,35,64,.18)}
          .od-en-a:hover{background:#0c2340;color:#fff}
          .od-en-c.feat .od-en-a{background:#0e7490;color:#fff;border-color:#0e7490}
          .od-en-c.feat .od-en-a:hover{background:#0c2340;border-color:#0c2340}
          .od-pr-s{background:#f5fdfe;border-top:1px solid rgba(12,35,64,.08);border-bottom:1px solid rgba(12,35,64,.08);padding:80px 40px;position:relative;z-index:1}
          .od-ps{display:flex;flex-direction:column;margin-top:52px}
          .od-ps-row{display:grid;grid-template-columns:56px 1fr;gap:0 20px;opacity:0;transform:translateY(48px);transition:opacity .65s cubic-bezier(0.22,1,.36,1),transform .65s cubic-bezier(0.22,1,.36,1)}
          .od-ps-row.od-pv{opacity:1;transform:translateY(0)}
          .od-ps-l{display:flex;flex-direction:column;align-items:center}
          .od-ps-ci{width:52px;height:52px;border-radius:50%;background:rgba(255,255,255,.65);backdrop-filter:blur(8px);border:2px solid rgba(12,35,64,.18);display:flex;align-items:center;justify-content:center;font-size:19px;font-weight:800;color:#0c2340;flex-shrink:0}
          .od-ps-row.od-pv:hover .od-ps-ci{background:rgba(14,116,144,.10);border-color:#0e7490;color:#0e7490}
          .od-ps-co{flex:1;display:flex;flex-direction:column;align-items:center;padding:6px 0;min-height:42px}
          .od-ps-co::before{content:'';width:2px;flex:1;background:#0c2340;opacity:.22}
          .od-ps-co::after{content:'';border-left:6px solid transparent;border-right:6px solid transparent;border-top:8px solid #0c2340;opacity:.40}
          .od-ps-row:last-child .od-ps-co{display:none}
          .od-ps-r{padding:4px 0 38px}
          .od-ps-row:last-child .od-ps-r{padding-bottom:0}
          .od-ps-t{font-size:20px;font-weight:700;color:#0c2340;margin:0 0 9px}
          .od-ps-d{font-size:15px;color:#3a5a6a;line-height:1.75;margin:0}
          .od-te-s{background:transparent;padding:80px 40px;position:relative;z-index:1}
          .od-ch{text-align:center;margin-bottom:48px}
          .od-tg2{display:grid;grid-template-columns:repeat(3,1fr);gap:24px}
          .od-tc{background:linear-gradient(135deg,rgba(240,253,255,.50) 0%,rgba(255,255,255,.85) 55%,rgba(207,250,254,.40) 100%);backdrop-filter:blur(16px);border:1px solid rgba(255,255,255,.85);border-radius:20px;padding:28px 24px;display:flex;flex-direction:column;gap:12px;box-shadow:0 4px 24px rgba(12,35,64,.08),inset 0 1px 0 rgba(255,255,255,.95);opacity:0;transform:translateY(40px);transition:opacity .6s cubic-bezier(0.22,1,.36,1),transform .6s cubic-bezier(0.22,1,.36,1)}
          .od-tc.feat{background:linear-gradient(135deg,rgba(254,243,199,.52) 0%,rgba(255,255,255,.87) 55%,rgba(240,253,255,.42) 100%);border-color:rgba(217,119,6,.22)}
          .od-tc.od-tv{opacity:1;transform:translateY(0)}
          .od-tc.od-tv:hover{transform:translateY(-6px);box-shadow:0 16px 48px rgba(12,35,64,.14)}
          .od-stars{font-size:16px;color:#D97706;letter-spacing:2px}
          .od-txt{font-size:14px;line-height:1.75;color:#374151;flex:1}
          .od-au{display:flex;align-items:center;gap:12px}
          .od-av{width:42px;height:42px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:13px;font-weight:800;color:#fff;flex-shrink:0}
          .od-an{font-size:14px;font-weight:700;color:#0c2340}
          .od-ar{font-size:12px;color:#6b7280}
          .od-wy-s{background:#f5fdfe;border-top:1px solid rgba(12,35,64,.08);border-bottom:1px solid rgba(12,35,64,.08);padding:80px 40px;position:relative;z-index:1}
          .od-wy-g{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin-top:48px}
          .od-wc{background:linear-gradient(135deg,rgba(240,253,255,.50) 0%,rgba(255,255,255,.85) 55%,rgba(207,250,254,.40) 100%);backdrop-filter:blur(16px);border:1px solid rgba(255,255,255,.85);border-radius:20px;padding:26px 22px;box-shadow:0 4px 24px rgba(12,35,64,.08),inset 0 1px 0 rgba(255,255,255,.95);opacity:0;transform:translateY(32px) scale(.97);transition:opacity .55s cubic-bezier(0.22,1,.36,1),transform .55s cubic-bezier(0.22,1,.36,1),border-color .2s}
          .od-wc.od-wv{opacity:1;transform:translateY(0) scale(1)}
          .od-wc.od-wv:hover{transform:translateY(-5px) scale(1);border-color:rgba(14,116,144,.25);box-shadow:0 14px 40px rgba(12,35,64,.12)}
          .od-wd{width:10px;height:10px;border-radius:50%;background:#0e7490;margin-bottom:12px}
          .od-wc h3{font-size:14px;font-weight:700;color:#0c2340;margin:0 0 8px;line-height:1.35}
          .od-wc p{font-size:13px;color:#3a5a6a;line-height:1.65;margin:0}
          .od-ct-s{padding:70px 40px;background:linear-gradient(135deg,rgba(240,253,255,.55) 0%,rgba(255,255,255,.60) 40%,rgba(207,250,254,.55) 100%);backdrop-filter:blur(20px);border-top:1px solid rgba(255,255,255,.80);position:relative;z-index:1}
          .od-ct-g{max-width:1440px;margin:0 auto;display:grid;grid-template-columns:1fr 1.15fr;gap:32px;align-items:start}
          .od-ctt{font-size:42px;font-weight:900;line-height:1.18;margin:0 0 14px;background:linear-gradient(90deg,#0c2340 0%,#0e7490 100%);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text}
          .od-ctd{font-size:14px;color:#3a5a6a;line-height:1.6;margin:0 0 22px}
          .od-ben{background:rgba(255,255,255,.70);border:1px solid rgba(255,255,255,.90);border-radius:14px;padding:22px;backdrop-filter:blur(12px);display:flex;flex-direction:column;gap:14px}
          .od-be{display:flex;gap:10px;align-items:flex-start}
          .od-bi{flex-shrink:0;color:#0e7490;font-weight:800;font-size:16px;margin-top:1px}
          .od-be p{font-size:13px;color:#3a5a6a;margin:0;line-height:1.55}
          .od-fb{background:linear-gradient(135deg,rgba(255,255,255,.88) 0%,rgba(240,253,255,.18) 50%,rgba(255,255,255,.84) 100%);backdrop-filter:blur(20px);border:1px solid rgba(255,255,255,.92);border-radius:20px;padding:34px;box-shadow:0 8px 40px rgba(12,35,64,.10),inset 0 1px 0 rgba(255,255,255,1)}
          .od-fb h3{font-size:22px;font-weight:700;color:#0c2340;margin:0 0 22px;letter-spacing:-.3px}
          .od-form{display:flex;flex-direction:column;gap:13px}
          .od-fr{display:grid;grid-template-columns:1fr 1fr;gap:12px}
          .od-fg{display:flex;flex-direction:column;gap:5px}
          .od-fg.full{grid-column:1/-1}
          .od-fg label{font-size:12px;font-weight:500;color:#0c2340}
          .od-fg input,.od-fg textarea,.od-fg select{padding:10px 13px;border:1px solid rgba(12,35,64,.14);border-radius:6px;font-size:13px;font-family:inherit;color:#0c2340;background:rgba(255,255,255,.55);transition:border-color .2s}
          .od-fg input:focus,.od-fg textarea:focus,.od-fg select:focus{outline:none;border-color:#0e7490;box-shadow:0 0 0 3px rgba(14,116,144,.10)}
          .od-co{display:flex;gap:8px;align-items:flex-start}
          .od-co input{margin-top:3px;width:15px;height:15px}
          .od-co label{font-size:11px;color:#3a5a6a;line-height:1.5}
          .od-co a{color:#0c2340}
          .od-sub{width:100%;padding:14px;background:#0e7490;border:none;color:#fff;border-radius:50px;font-weight:700;font-size:15px;cursor:pointer;font-family:inherit;transition:all .25s;box-shadow:0 6px 24px rgba(14,116,144,.26)}
          .od-sub:hover{background:#0c2340;transform:translateY(-2px)}
          .od-fq-s{padding:80px 40px;background:#f5fdfe;border-top:1px solid rgba(12,35,64,.08);position:relative;z-index:1}
          .od-fq-s h2{font-size:46px;font-weight:900;letter-spacing:-1px;background:linear-gradient(90deg,#0c2340 0%,#D97706 100%);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;margin:0 0 8px}
          .od-fq-sub{font-size:15px;color:#3a5a6a;margin:0 0 36px}
          .od-fql{display:flex;flex-direction:column;gap:10px}
          .od-fi{background:linear-gradient(135deg,rgba(240,253,255,.50) 0%,rgba(255,255,255,.85) 55%,rgba(207,250,254,.40) 100%);backdrop-filter:blur(16px);border:1px solid rgba(255,255,255,.85);border-radius:14px;overflow:hidden;box-shadow:0 4px 20px rgba(12,35,64,.06);transition:border-color .2s}
          .od-fi.open{border-color:rgba(14,116,144,.30)}
          .od-fi.open::before{content:'';display:block;height:3px;background:linear-gradient(90deg,#0e7490,#06b6d4);border-radius:3px 3px 0 0}
          .od-fqb{width:100%;background:none;border:none;padding:20px 20px 20px 58px;display:flex;align-items:center;justify-content:space-between;cursor:pointer;text-align:left;gap:14px;font-family:inherit;position:relative}
          .od-fqb2{position:absolute;left:16px;top:50%;transform:translateY(-50%);width:26px;height:26px;background:rgba(12,35,64,.08);color:#374151;font-size:11px;font-weight:700;display:flex;align-items:center;justify-content:center;border-radius:6px}
          .od-fi.open .od-fqb2{background:#0e7490;color:#fff}
          .od-fqb span{font-size:15px;font-weight:600;color:#0c2340;line-height:1.4}
          .od-fi.open .od-fqb span{color:#0e7490}
          .od-fch{width:22px;height:22px;flex-shrink:0;color:#9ca3af;transition:transform .3s}
          .od-fi.open .od-fch{transform:rotate(180deg);color:#0e7490}
          .od-faw{overflow:hidden;transition:max-height .35s ease;max-height:0}
          .od-fi.open .od-faw{max-height:500px}
          .od-fa{padding:0 20px 20px 58px;font-size:14px;color:#4b5563;line-height:1.8}
          .od-rel{padding:80px 40px;background:rgba(240,253,255,.14);backdrop-filter:blur(10px);border-top:1px solid rgba(255,255,255,.60)}
          .od-ri{max-width:1300px;margin:0 auto;text-align:center}
          .od-ri h2{font-size:34px;font-weight:900;background:linear-gradient(90deg,#0c2340 0%,#D97706 100%);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;margin:10px 0 12px}
          .od-rs{font-size:14px;color:#3a5a6a;margin:0 auto;max-width:560px}
          .od-ri hr{border:none;border-top:1px solid rgba(12,35,64,.10);margin:32px 0}
          .od-rts{display:flex;flex-wrap:wrap;justify-content:center;gap:10px}
          .od-rt{display:inline-block;padding:10px 20px;border:1.5px solid;border-radius:50px;font-size:14px;font-weight:500;text-decoration:none;transition:all .22s}
          .od-rt:hover{transform:translateY(-2px);box-shadow:0 6px 18px rgba(0,0,0,.09)}
          .od-b{background:rgba(14,116,144,.09);border-color:rgba(14,116,144,.28);color:#155e75}
          .od-v{background:rgba(109,40,217,.09);border-color:rgba(109,40,217,.28);color:#4c1d95}
          .od-fu{background:rgba(162,28,175,.09);border-color:rgba(162,28,175,.28);color:#86198f}
          .od-o{background:rgba(180,83,9,.09);border-color:rgba(180,83,9,.28);color:#92400e}
          .od-a{background:rgba(190,18,60,.09);border-color:rgba(190,18,60,.28);color:#9f1239}
          @media(max-width:1024px){.od-hero h1,.od-st,.od-fq-s h2{font-size:36px}.od-sk-g{grid-template-columns:repeat(2,1fr)}.od-tec-g{grid-template-columns:repeat(2,1fr)}.od-en-g{grid-template-columns:1fr;max-width:480px;margin-left:auto;margin-right:auto}.od-en-c.feat{transform:none}.od-en-c.feat.od-ev{transform:none}.od-en-c.feat.od-ev:hover{transform:translateY(-4px)}.od-wy-g{grid-template-columns:repeat(2,1fr)}.od-tg2{grid-template-columns:1fr}.od-ct-g{grid-template-columns:1fr}}
          @media(max-width:768px){.od-bc,.od-hero,.od-sk-s,.od-tec-s,.od-en-s,.od-pr-s,.od-te-s,.od-wy-s,.od-fq-s,.od-rel{padding-left:20px;padding-right:20px}.od-hero{padding-top:28px;padding-bottom:20px}.od-hero h1{font-size:26px;letter-spacing:-.3px}.od-stats{grid-template-columns:1fr 1fr}.od-sc:nth-child(2){border-right:none}.od-sc:nth-child(3),.od-sc:nth-child(4){border-top:1px solid rgba(12,35,64,.10)}.od-sc:nth-child(4){border-right:none}.od-sk-g,.od-tec-g,.od-wy-g{grid-template-columns:1fr}.od-fr{grid-template-columns:1fr}.od-ctt{font-size:28px}.od-st{font-size:28px}.od-ct-s{padding:48px 20px}.od-logos{padding-left:20px;padding-right:20px}}
        `}</style>
      </Head>
      <div className="od-page">
        <div className="od-orb od-o1" /><div className="od-orb od-o2" /><div className="od-orb od-o3" />
        <nav className="od-bc" aria-label="Breadcrumb"><ol itemScope itemType="https://schema.org/BreadcrumbList"><li itemScope itemType="https://schema.org/ListItem" itemProp="itemListElement"><Link href="/" itemProp="item"><span itemProp="name">Home</span></Link><meta itemProp="position" content="1" /></li><li itemScope itemType="https://schema.org/ListItem" itemProp="itemListElement"><span itemProp="name">Offshore Development Company</span><meta itemProp="position" content="2" /></li></ol></nav>
        <section className="od-hero">
          <span className="od-ey">Offshore Software Development</span>
          <h1>Offshore Development Company — Dedicated Teams at 60–70% Below Western Rates</h1>
          <p className="od-desc">1Solutions is an offshore software development company based in India with 15+ years serving clients in the US, UK, Australia, and Canada. Dedicated offshore teams, staff augmentation, and fixed-price project delivery — senior developers, DevOps engineers, mobile specialists, QA, and data scientists at significantly lower cost than hiring locally.</p>
          <div className="od-tr">{['Dedicated Offshore Teams','Staff Augmentation','Fixed-Price Projects','React / Node / Python / Mobile','60–70% Cost Savings'].map(b => (<div className="od-badge" key={b}><span className="od-dot" />{b}</div>))}</div>
          <div className="od-ctas"><Link href="#contact" className="od-p">Build Your Offshore Team</Link><Link href="#engagement" className="od-g">View Engagement Models →</Link></div>
        </section>
        <div className="od-stats" ref={stR}>{[['500+','Projects Delivered'],['15+','Years Offshore Delivery'],['98%','Client Retention'],['60-70%','Cost Savings vs Local']].map(([v, l]) => (<StatItem key={l} label={l} val={v} started={ss} />))}</div>
        <div className="od-logos"><span className="od-ll">Trusted by Businesses in US, UK, Australia, Canada</span><div className="od-lw"><div className="od-lt">{[['/logo/Indian_Express_Logo_full.png','Indian Express'],['/logo/Verizon_2015_logo_-vector.svg.png','Verizon'],['/logo/Uniphore.jpg','Uniphore'],['/logo/ICCoLogo.png','ICC'],['/logo/Honor_Logo_(2020).svg.png','Honor'],['/logo/Zuari-Finserv-logo-new.png','Zuari Finserv'],['/logo/Indian_Express_Logo_full.png','Indian Express 2'],['/logo/Verizon_2015_logo_-vector.svg.png','Verizon 2'],['/logo/Uniphore.jpg','Uniphore 2'],['/logo/ICCoLogo.png','ICC 2'],['/logo/Honor_Logo_(2020).svg.png','Honor 2'],['/logo/Zuari-Finserv-logo-new.png','Zuari Finserv 2']].map(([src, alt]) => (<img key={alt} src={src} alt={alt.replace(/ \d$/, '')} className="od-cl" />))}</div></div></div>
        <section className="od-sk-s" aria-labelledby="od-sk-h"><div className="od-in"><div className={`od-rv${vis.has('sk') ? ' od-ok' : ''}`} ref={el => { secR.current['sk'] = el; }}><span className="od-sey">Offshore Development Services</span><h2 id="od-sk-h" className="od-st">What Our Offshore Teams Deliver</h2><p className="od-sd" style={{ maxWidth: 720 }}>Dedicated offshore teams, staff augmentation, project delivery, QA, mobile, web, cloud, AI/ML, and CMS development — all at offshore economics with the quality and communication standards of a local team.</p></div><div className="od-sk-g" ref={skR}>{visServices.map((s, i) => (<div key={s.n} className={`od-sk-c${s.feat ? ' feat' : ''}${vSk.includes(i) ? ' od-cv' : ''}`} style={{ transitionDelay: `${i * 55}ms` }}><span className="od-sk-n">{s.n}</span><h3>{s.title}</h3><p>{s.desc}</p></div>))}</div>{SERVICES.length > 6 && (<div className="od-sm"><button className="od-bm" onClick={() => setShowAll(p => !p)}>{showAll ? 'Show fewer ↑' : `Show all ${SERVICES.length} services ↓`}</button></div>)}</div></section>
        <section className="od-tec-s" aria-labelledby="od-tec-h"><div className="od-in"><div className={`od-rv${vis.has('stk') ? ' od-ok' : ''}`} ref={el => { secR.current['stk'] = el; }}><span className="od-sey">Technology Stack</span><h2 id="od-tec-h" className="od-st">Technologies Our Offshore Teams Cover</h2><p className="od-sd" style={{ maxWidth: 680 }}>React, Next.js, Angular, Node.js, Python, PHP, Java, .NET, Flutter, React Native, PostgreSQL, MongoDB, AWS, Azure, GCP, Kubernetes, Terraform, ML/AI, and CMS platforms.</p></div><div className="od-tec-g" ref={stGr}>{TECH_STACK.map((grp, i) => (<div key={grp.group} className={`od-tec-c${vSt.includes(i) ? ' od-sv2' : ''}`} style={{ transitionDelay: `${i * 60}ms` }}><div className="od-tg" style={{ color: grp.color, borderBottomColor: grp.color + '33' }}>{grp.group}</div><div className="od-pills">{grp.items.map(item => <span key={item} className="od-pill" style={{ color: grp.color, background: grp.color + '12', borderColor: grp.color + '30' }}>{item}</span>)}</div></div>))}</div></div></section>
        <section id="engagement" className="od-en-s" aria-labelledby="od-en-h"><div className="od-in"><div className={`od-rv${vis.has('eng') ? ' od-ok' : ''}`} ref={el => { secR.current['eng'] = el; }}><span className="od-sey">Engagement Models</span><h2 id="od-en-h" className="od-st">How to Engage Our Offshore Team</h2><p className="od-sd" style={{ maxWidth: 680 }}>Three offshore engagement models — dedicated team, staff augmentation, or fixed-price project — structured to match your development stage, team size, and budget requirements.</p></div><div className="od-en-g" ref={enR}>{ENGAGEMENT_MODELS.map((m, i) => (<div key={m.id} className={`od-en-c${m.feat ? ' feat' : ''}${vEn.includes(i) ? ' od-ev' : ''}`} style={{ transitionDelay: `${i * 100}ms` }}><span className="od-en-b" style={{ color: m.badgeColor, borderColor: m.badgeColor + '44', background: m.badgeColor + '14' }}>{m.badge}</span><div className="od-en-i"><svg viewBox="0 0 24 24" width="26" height="26"><path d={m.icon} /></svg></div><div className="od-en-n">{m.name}</div><div className="od-en-h">{m.headline}</div><div className="od-en-d">{m.desc}</div><div className="od-en-ll">Best for</div><ul className="od-en-li">{m.bestFor.map(b => <li key={b}>{b}</li>)}</ul><div className="od-en-p"><strong>Process:</strong> {m.process}<br /><span className="od-en-tl">{m.timeline}</span></div><Link href="#contact" className="od-en-a">Get a free estimate →</Link></div>))}</div></div></section>
        <section className="od-pr-s" aria-labelledby="od-pr-h"><div className="od-in" style={{ maxWidth: 760 }}><div className={`od-rv${vis.has('proc') ? ' od-ok' : ''}`} ref={el => { secR.current['proc'] = el; }}><span className="od-sey">How We Work</span><h2 id="od-pr-h" className="od-st">Our Offshore Team Setup Process</h2><p className="od-sd">From requirements to your first offshore sprint in 2–3 weeks — domain-matched shortlisting, rigorous technical interviews, toolchain setup, and transparent management.</p></div><div className="od-ps">{PROCESS_STEPS.map((step, i) => (<div key={step.num} className={`od-ps-row${vis.has('proc') ? ' od-pv' : ''}`} style={{ transitionDelay: `${i * 120}ms` }}><div className="od-ps-l"><div className="od-ps-ci">{step.num}</div><div className="od-ps-co" /></div><div className="od-ps-r"><div className="od-ps-t">{step.title}</div><p className="od-ps-d">{step.desc}</p></div></div>))}</div></div></section>
        <section className="od-te-s" aria-labelledby="od-te-h"><div className="od-in"><div className={`od-ch od-rv${vis.has('ts') ? ' od-ok' : ''}`} ref={el => { secR.current['ts'] = el; }}><span className="od-sey">Client Outcomes</span><h2 id="od-te-h" className="od-st">What Our Clients Say</h2><p className="od-sd">CTOs, VPs of Engineering, and co-founders in the UK, AU, and US on building offshore development teams with 1Solutions.</p></div><div className="od-tg2" ref={teR}>{TESTIMONIALS.map((t, i) => (<div key={i} className={`od-tc${t.feat ? ' feat' : ''}${vTe.includes(i) ? ' od-tv' : ''}`} style={{ transitionDelay: `${i * 100}ms` }} itemScope itemType="https://schema.org/Review"><div className="od-stars">★★★★★</div><p className="od-txt" itemProp="reviewBody">{t.text}</p><div className="od-au"><div className="od-av" style={{ background: t.bg }}>{t.init}</div><div><div className="od-an" itemProp="author">{t.name}</div><div className="od-ar">{t.role}</div></div></div></div>))}</div></div></section>
        <section className="od-wy-s" aria-labelledby="od-wy-h"><div className="od-in"><div className={`od-rv${vis.has('wy') ? ' od-ok' : ''}`} ref={el => { secR.current['wy'] = el; }}><span className="od-sey">Why 1Solutions</span><h2 id="od-wy-h" className="od-st">Why Choose 1Solutions as Your Offshore Partner</h2><p className="od-sd" style={{ maxWidth: 680 }}>15 years of offshore delivery, 60–70% cost savings, pre-vetted developers, zero freelancer instability, full-stack capability, transparent management, and a 5-day replacement guarantee.</p></div><div className="od-wy-g" ref={whR}>{WHY_CARDS.map((c, i) => (<div key={i} className={`od-wc${vWh.includes(i) ? ' od-wv' : ''}`} style={{ transitionDelay: `${i * 60}ms` }}><div className="od-wd" /><h3>{c.title}</h3><p>{c.desc}</p></div>))}</div></div></section>
        <section id="contact" className="od-ct-s" aria-labelledby="od-ct-h"><div className="od-ct-g"><div><h2 id="od-ct-h" className="od-ctt">Build Your Offshore Team Today</h2><p className="od-ctd">Share your team requirements — technology stack, team size, required seniority, domain, and timeline. We will shortlist pre-vetted offshore developers within 24–48 business hours and have your team ready to sprint within 2–3 weeks.</p><div className="od-ben">{[['✓','Shortlist within 24–48 business hours'],['✓','Senior developers at 60–70% below US/UK rates'],['✓','Pre-vetted — coding test + architecture + English communication'],['✓','5-day replacement guarantee at no extra cost'],['✓','15+ years of offshore delivery — US, UK, AU, CA clients']].map(([icon, text]) => (<div className="od-be" key={text}><span className="od-bi">{icon}</span><p>{text}</p></div>))}</div></div>
        <div className="od-fb"><h3>Tell Us About Your Offshore Team Needs</h3><form className="od-form" onSubmit={e => e.preventDefault()}>
          <div className="od-fr"><div className="od-fg"><label htmlFor="od-nm">Full Name *</label><input id="od-nm" type="text" placeholder="Your name" required /></div><div className="od-fg"><label htmlFor="od-em">Work Email *</label><input id="od-em" type="email" placeholder="you@company.com" required /></div></div>
          <div className="od-fr"><div className="od-fg"><label htmlFor="od-co">Company Name</label><input id="od-co" type="text" placeholder="Your company" /></div><div className="od-fg"><label htmlFor="od-ph">Phone / WhatsApp</label><input id="od-ph" type="tel" placeholder="+1 555 000 0000" /></div></div>
          <div className="od-fg full"><label htmlFor="od-en2">Engagement Type *</label><select id="od-en2" required><option value="">Select engagement...</option><option>Dedicated Offshore Team (monthly retainer)</option><option>Staff Augmentation (add to existing team)</option><option>Fixed-Price Project</option></select></div>
          <div className="od-fg full"><label htmlFor="od-ts">Primary Technology Stack *</label><select id="od-ts" required><option value="">Select stack...</option><option>React / Next.js / Frontend</option><option>Node.js / Python / Backend</option><option>React Native / Flutter / Mobile</option><option>DevOps / Cloud / Kubernetes</option><option>AI / ML / Data Science</option><option>WordPress / Shopify / CMS</option><option>Full-Stack (multiple roles)</option><option>Other / Multiple</option></select></div>
          <div className="od-fg full"><label htmlFor="od-tz">Team Size Needed</label><select id="od-tz"><option value="">Select team size...</option><option>1 developer</option><option>2–3 developers</option><option>4–6 developers</option><option>7–10 developers</option><option>10+ developers</option></select></div>
          <div className="od-fg full"><label htmlFor="od-ms">Project / Team Description *</label><textarea id="od-ms" rows={4} placeholder="Describe your product, technology stack, current team, what offshore roles you need, timeline, and any domain specifics (fintech, healthtech, e-commerce)..." required /></div>
          <div className="od-co"><input id="od-co3" type="checkbox" required /><label htmlFor="od-co3">I agree to the <Link href="/privacy-policy">Privacy Policy</Link>. Details are treated confidentially.</label></div>
          <button type="submit" className="od-sub">Get Your Offshore Team Shortlist →</button>
        </form></div></div></section>
        <section className="od-fq-s" aria-labelledby="od-fq-h"><div className="od-in" style={{ maxWidth: 860 }}><span className="od-sey">FAQ</span><h2 id="od-fq-h">Offshore Development — Frequently Asked Questions</h2><p className="od-fq-sub">Cost savings, time zone management, team quality, engagement models, technology coverage, and getting started with an offshore development team.</p><div className="od-fql">{FAQS.map((item, i) => (<div key={i} className={`od-fi${openFaq === i ? ' open' : ''}`} itemScope itemType="https://schema.org/Question"><button className="od-fqb" onClick={() => setOpenFaq(openFaq === i ? -1 : i)} aria-expanded={openFaq === i}><div className="od-fqb2">{String(i + 1).padStart(2, '0')}</div><span itemProp="name">{item.q}</span><svg className="od-fch" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2"><polyline points="6 9 12 15 18 9" /></svg></button><div className="od-faw" itemScope itemType="https://schema.org/Answer"><div className="od-fa" itemProp="text">{item.a}</div></div></div>))}</div></div></section>
        <section className="od-rel"><div className="od-ri"><span className="od-sey">Related Services</span><h2>Related IT & Offshore Services</h2><p className="od-rs">Staff augmentation, IT outsourcing, cost optimisation, virtual CTO, and dedicated hire developer services from 1Solutions.</p><hr /><div className="od-rts">{[['/it-staff-augmentation-services/','IT Staff Augmentation','od-b'],['/it-outsourcing-services/','IT Outsourcing Services','od-a'],['/software-development-cost-optimization/','Cost Optimization','od-o'],['/virtual-cto-services/','Virtual CTO Services','od-fu'],['/devops-services-company/','DevOps Services','od-v'],['/cloud-native-services/','Cloud Native Services','od-v'],['/hire-ai-developer/','Hire AI Developer','od-fu'],['/software-development-company/','Software Development','od-b']].map(([href, label, cls]) => (<Link key={href} href={href} className={`od-rt ${cls}`}>{label}</Link>))}</div></div></section>
      </div>
    </>
  );
}
