'use client';
import { useState, useEffect, useRef } from 'react';
import Head from 'next/head';
import Link from 'next/link';

const SCHEMA = {
  '@context': 'https://schema.org',
  '@graph': [
    { '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Home', item: 'https://www.1solutions.biz/' }, { '@type': 'ListItem', position: 2, name: 'Hire AR Developer', item: 'https://www.1solutions.biz/hire-ar-developer/' }] },
    { '@type': 'Service', name: 'Hire AR Developer', url: 'https://www.1solutions.biz/hire-ar-developer/', description: 'Hire expert AR (Augmented Reality) developers from 1Solutions — Unity AR, ARKit, ARCore, WebAR, spatial computing, Apple Vision Pro, Microsoft HoloLens, and industrial AR applications. Dedicated, part-time, or fixed-scope. Start in 3–5 days.', provider: { '@type': 'Organization', name: '1Solutions', url: 'https://www.1solutions.biz', logo: { '@type': 'ImageObject', url: 'https://www.1solutions.biz/images/1solutions-logo.png' }, foundingDate: '2008', areaServed: ['US', 'GB', 'AU', 'CA', 'IN'] }, aggregateRating: { '@type': 'AggregateRating', ratingValue: '4.9', reviewCount: '34', bestRating: '5' } },
    { '@type': 'FAQPage', mainEntity: [
      { '@type': 'Question', name: 'What can an AR developer build?', acceptedAnswer: { '@type': 'Answer', text: 'An AR developer builds: mobile AR applications using ARKit (iOS) and ARCore (Android) — marker-based AR, markerless AR with plane detection, image tracking, object detection, face tracking, and body tracking; WebAR experiences using 8thWall, AR.js, or Three.js + WebXR Device API (no app install required); Unity-based cross-platform AR with AR Foundation (runs on ARKit, ARCore, and HoloLens); mixed reality applications for Microsoft HoloLens 2 (spatial anchors, holographic UI, hand and eye tracking); Apple Vision Pro visionOS spatial computing apps; industrial AR (step-by-step guided assembly, remote expert assistance, equipment maintenance overlays); retail AR (virtual try-on for glasses, apparel, furniture placement in room); and marker-based AR with Vuforia, Wikitude, or ZapWorks for print, packaging, and marketing activations.' } },
      { '@type': 'Question', name: 'What is the difference between ARKit, ARCore, and WebAR?', acceptedAnswer: { '@type': 'Answer', text: 'ARKit is Apple\'s AR framework — runs natively on iOS devices with LiDAR (iPhone 12 Pro+, iPad Pro) for real-time depth sensing; uses Swift/Objective-C or RealityKit/SceneKit APIs, or Unity AR Foundation with ARKit backend. ARCore is Google\'s equivalent for Android — plane detection, hit testing, light estimation, and cloud anchors for shared AR experiences; runs on a wide range of Android devices (ARCore supported devices list). WebAR runs in the mobile browser — no app install required; 8thWall (commercial, production-grade, image tracking, slam tracking, WebAR effects) and Three.js + WebXR for simpler experiences; lower device capability access than native. Our developers recommend WebAR for marketing campaigns and product launches (zero install friction), and native ARKit/ARCore or Unity AR Foundation for applications requiring persistent anchors, high performance, or offline capability.' } },
      { '@type': 'Question', name: 'What is Unity AR Foundation and when should I use it?', acceptedAnswer: { '@type': 'Answer', text: 'Unity AR Foundation is a cross-platform framework that provides a common API layer that works on top of ARKit (iOS), ARCore (Android), and other AR platforms including Magic Leap and HoloLens. Use AR Foundation when: you need to ship the same AR experience on both iOS and Android from a single codebase; you want to use Unity\'s 3D engine (rendering, physics, animations, shaders) for complex interactive AR content; you are building a game or highly interactive experience that benefits from Unity\'s game object hierarchy; or you are targeting multiple platforms including mobile and HoloLens. Use native ARKit or ARCore APIs (in Swift/Kotlin) when you need the latest platform-specific features before they appear in Unity, when you are building a camera-first mobile app that happens to include AR (native UX patterns), or when binary size matters and Unity\'s overhead is unacceptable.' } },
      { '@type': 'Question', name: 'Can your AR developers build for Apple Vision Pro?', acceptedAnswer: { '@type': 'Answer', text: 'Yes. Our AR developers build visionOS applications for Apple Vision Pro — native visionOS apps using SwiftUI + RealityKit 4, which combines SwiftUI layout with RealityKit\'s 3D rendering and physics engine; volumetric apps (3D app windows that float in space); fully immersive spaces for complete spatial computing environments; and shared spaces (windows alongside other apps). We also build Unity apps for visionOS using PolySpatial. Key visionOS capabilities we work with: eye tracking input (gaze detection, pinch gestures), hand tracking, spatial audio, ARKit for visionOS (plane detection, scene reconstruction, image tracking), and RealityKit animations and materials (PhysicallyBasedMaterial, ShaderGraphMaterial).' } },
      { '@type': 'Question', name: 'What is WebAR and can you build AR without an app?', acceptedAnswer: { '@type': 'Answer', text: 'WebAR delivers AR experiences in the mobile web browser without requiring an app download — users scan a QR code or tap a link and the AR experience launches immediately. Production-grade WebAR uses 8thWall (by Niantic) — supporting image tracking, world tracking (SLAM), face effects, and QR codes in the browser on both iOS and Android. For simpler experiences, Three.js + WebXR or AR.js with A-Frame. Use cases: product packaging AR activations (scan to see 3D product demo), e-commerce AR (see product in your space), event marketing (scan poster to see AR overlay), and brand activation campaigns. The trade-off vs native app: no persistent spatial anchors, lower device sensor access, limited background processing — but zero install friction, which dramatically improves campaign conversion rates.' } },
      { '@type': 'Question', name: 'Can your AR developers build industrial AR applications?', acceptedAnswer: { '@type': 'Answer', text: 'Yes. Industrial AR is one of the highest-value AR application areas — ROI is measurable. Our AR developers build: assembly guidance (step-by-step holographic overlay on the work surface, connected to PLM or CAD data, reducing training time and assembly errors); remote expert assistance (technician sees the equipment through camera, remote expert annotates in AR what to do — Microsoft Dynamics 365 Remote Assist, PTC Vuforia Chalk, or custom); equipment maintenance and repair (AR overlay showing part numbers, torque specs, and procedure steps from the maintenance manual); safety training (AR simulation of hazard scenarios); and warehouse pick-by-vision (Microsoft HoloLens 2 or smart glasses showing pick locations without hands-free scanning). Platforms: Microsoft HoloLens 2 (MRTK), Unity AR, PTC Vuforia Engine, and WebAR for lighter industrial use cases.' } },
      { '@type': 'Question', name: 'What hardware platforms do your AR developers target?', acceptedAnswer: { '@type': 'Answer', text: 'Mobile AR: iPhone (ARKit, LiDAR on Pro models, TrueDepth face tracking on front camera) and Android (ARCore on supported devices). Mixed Reality headsets: Microsoft HoloLens 2 (enterprise MR, hand tracking, eye tracking, spatial anchors) and Magic Leap 2 (enterprise, developer-friendly, larger FOV than HoloLens). Standalone VR/AR: Meta Quest 3 (mixed reality passthrough, Presence Platform hand tracking, Scene API for room mapping) and Meta Quest Pro. Spatial computing: Apple Vision Pro (visionOS, eye + hand + voice input, M2 chip). Smart glasses (enterprise): RealWear Navigator (rugged, voice-controlled, front-facing camera for remote assist), Vuzix, and Google Glass Enterprise Edition 2. WebAR runs on any modern smartphone without dedicated hardware.' } },
      { '@type': 'Question', name: 'How do you approach AR 3D asset creation?', acceptedAnswer: { '@type': 'Answer', text: 'AR 3D assets need to be: accurate (matching real dimensions for placement or try-on use cases), visually realistic under varied real-world lighting (PBR materials — metallic/roughness workflow), and optimised for mobile GPU performance. Our AR developers work with 3D modelling teams (Blender, Maya, 3ds Max) for high-quality base assets, then optimise for AR: polygon reduction to mobile budgets (typically 10K–50K triangles per hero object), LOD (Level of Detail) generation, PBR texture atlasing (512x512 or 1024x1024), USDZ format for ARKit/QuickLook, GLB/glTF for ARCore and WebAR, and FBX for Unity import. We can source assets from existing CAD (STEP/IGES) files and convert them to game-ready assets for industrial AR use cases.' } },
    ] },
  ],
};

const SKILLS = [
  { n: '01', title: 'Mobile AR — ARKit (iOS) & ARCore (Android)', desc: 'Native mobile AR development — ARKit on iOS (plane detection, image tracking, object detection, face tracking, body tracking, LiDAR depth sensing, scene reconstruction, RealityKit, and AR Quick Look USDZ); ARCore on Android (plane detection, hit testing, light estimation, depth API, Geospatial API for location-anchored AR, Cloud Anchors for shared multi-user AR). Cross-platform AR using Unity AR Foundation.' },
  { n: '02', title: 'Unity AR Development (AR Foundation)', desc: 'Unity-based cross-platform AR with AR Foundation — single codebase targeting ARKit (iOS), ARCore (Android), and HoloLens; AR Raycast Manager for surface hit testing, AR Plane Manager for floor/wall/table detection, AR Image Tracking, AR Object Tracking, AR Face Manager, AR Body Tracking, AR Anchor Manager for persistent content, and AR Occlusion for realistic 3D object placement behind real-world objects.', feat: true },
  { n: '03', title: 'WebAR Development (8thWall, Three.js, WebXR)', desc: 'Browser-based AR without app install — 8thWall (Niantic) for production WebAR (world tracking SLAM, image targets, face effects, QR scanning, AR e-commerce try-on); Three.js + WebXR Device API for custom WebAR experiences; AR.js with A-Frame for simple marker-based WebAR; QR code trigger campaigns; and WebAR for retail product launches, packaging activations, and brand campaigns. Works on iOS Safari and Android Chrome.' },
  { n: '04', title: 'Microsoft HoloLens 2 / Mixed Reality', desc: 'Microsoft HoloLens 2 development for enterprise mixed reality — MRTK (Mixed Reality Toolkit) for hand and eye tracking UI, spatial anchors for persistent holographic content across sessions and devices, holographic UI panels, DirectX + Unity rendering, Azure Spatial Anchors for cloud-persisted multi-user AR, Azure Remote Rendering for complex 3D models beyond HoloLens GPU limits, and integration with Dynamics 365 Remote Assist for guided remote expert workflows.' },
  { n: '05', title: 'Apple Vision Pro (visionOS)', desc: 'Spatial computing apps for Apple Vision Pro — native visionOS development with SwiftUI + RealityKit 4; volumetric windows (3D content floating in space); fully immersive environments; Shared Space apps (multi-app coexistence); eye tracking and pinch gesture input; spatial audio; ARKit for visionOS (plane detection, image tracking, scene reconstruction); RealityKit animations, physics simulation, and PBR/ShaderGraph materials; and Unity PolySpatial for cross-platform Vision Pro content.' },
  { n: '06', title: 'AR E-Commerce & Virtual Try-On', desc: 'AR features for e-commerce and retail — virtual try-on for eyewear (face mesh, 3D glasses overlay, ARKit TrueDepth), apparel try-on (body tracking), furniture and home decor placement in room (LiDAR-precise floor plane, real scale), product visualisation (USDZ AR Quick Look for iOS, Scene Viewer for Android), in-aisle AR in retail environments, and WebAR product preview pages for no-install conversion. Integration with Shopify, WooCommerce, and custom e-commerce APIs.' },
  { n: '07', title: 'Industrial & Enterprise AR', desc: 'Enterprise AR applications for manufacturing, maintenance, and training — step-by-step holographic assembly guidance connected to CAD or PLM data (SolidWorks, PTC Windchill); remote expert video + AR annotation (custom or Microsoft Dynamics 365 Remote Assist); equipment inspection and maintenance (part overlay, spec lookup, procedure steps); safety training simulations; warehouse pick-by-vision (HoloLens 2 pick guidance); and custom industrial AR on RealWear, Vuzix, or HoloLens 2 platforms.' },
  { n: '08', title: 'Spatial Anchors & Multi-User AR', desc: 'Persistent and shared AR experiences — Azure Spatial Anchors (cloud-persisted world anchors, cross-device AR shared experiences on HoloLens, iOS, Android); ARCore Cloud Anchors (shared markerless AR between Android and iOS users); ARKit Persistent World Anchors; location-based AR using ARCore Geospatial API (Streetscape Geometry for building-scale AR); and multi-user AR game and collaboration experiences where multiple users see and interact with the same holographic content.' },
  { n: '09', title: 'AR 3D Asset Pipeline & Optimisation', desc: 'AR 3D asset creation and optimisation pipeline — high-poly to game-ready asset conversion (Blender, Maya), polygon reduction to mobile GPU budgets (10K–50K triangles for hero objects), PBR texture baking and atlasing (metallic/roughness workflow), LOD generation, USDZ export for ARKit/QuickLook, GLB/glTF for WebAR and ARCore, FBX for Unity, CAD-to-AR pipeline (STEP/IGES to game-ready mesh), and mobile GPU performance profiling (Unity Profiler, Xcode GPU Frame Debugger, Android GPU Inspector).' },
  { n: '10', title: 'AR Analytics, Backend & CMS Integration', desc: 'AR application backend and analytics — AR content management systems (update 3D models, images, and AR triggers without app store submission); usage analytics (session duration, interaction tracking, heat maps of AR content placement); integration with CRM (Salesforce, HubSpot) for AR lead capture in retail; product catalogue integration (fetch 3D model URLs and product data from backend); and A/B testing frameworks for AR creative (which 3D model or animation drives more purchases).' },
];

const TECH_STACK = [
  { group: 'Mobile AR Frameworks', color: '#0d9488', items: ['ARKit (iOS / visionOS)', 'ARCore (Android)', 'Unity AR Foundation', 'RealityKit 4', 'SceneKit (iOS)', 'Vuforia Engine'] },
  { group: 'Mixed Reality (MR)', color: '#0f766e', items: ['Microsoft HoloLens 2', 'MRTK (Mixed Reality Toolkit)', 'Azure Spatial Anchors', 'OpenXR', 'Magic Leap 2', 'Meta Quest (MR passthrough)'] },
  { group: 'WebAR', color: '#0369a1', items: ['8thWall (Niantic)', 'Three.js + WebXR', 'AR.js + A-Frame', 'Model Viewer (Google)', 'Spark AR (Meta)', 'Lens Studio (Snap)'] },
  { group: 'Spatial Computing', color: '#6d28d9', items: ['Apple Vision Pro (visionOS)', 'SwiftUI + RealityKit', 'Unity PolySpatial', 'ARKit for visionOS', 'Spatial Audio', 'Eye & Hand Tracking'] },
  { group: '3D & Rendering', color: '#b45309', items: ['Unity 3D (URP / HDRP)', 'Unreal Engine (AR)', 'Blender / Maya', 'USDZ / USD', 'GLB / glTF 2.0', 'PBR Materials (metallic/roughness)'] },
  { group: 'Programming Languages', color: '#c2185b', items: ['C# (Unity)', 'Swift / RealityKit', 'JavaScript (WebAR)', 'Kotlin (Android AR)', 'Python (backend)', 'HLSL / GLSL (shaders)'] },
  { group: 'Cloud & Backend', color: '#059669', items: ['Azure Spatial Anchors', 'ARCore Cloud Anchors', 'Firebase (Realtime DB)', 'AWS (asset delivery)', 'CDN (3D model serving)', 'Node.js / REST APIs'] },
  { group: 'Analytics & Tools', color: '#dc2626', items: ['Unity Profiler', 'Xcode Instruments', 'AR Quick Look (iOS)', 'Scene Viewer (Android)', 'Instruments (GPU)', 'Firebase Analytics'] },
];

const ENGAGEMENT_MODELS = [
  { id: 'full', name: 'Full-Time Dedicated AR Developer', badge: 'Most Popular', badgeColor: '#D97706', feat: true, icon: 'M16 11c1.66 0 2.99-1.34 2.99-3S17.66 5 16 5c-1.66 0-3 1.34-3 3s1.34 3 3 3zm-8 0c1.66 0 2.99-1.34 2.99-3S9.66 5 8 5C6.34 5 5 6.34 5 8s1.34 3 3 3zm0 2c-2.33 0-7 1.17-7 3.5V19h14v-2.5c0-2.33-4.67-3.5-7-3.5zm8 0c-.29 0-.62.02-.97.05 1.16.84 1.97 1.97 1.97 3.45V19h6v-2.5c0-2.33-4.67-3.5-7-3.5z', headline: '160 hrs/month — an AR engineer dedicated to your spatial product.', desc: 'A dedicated AR developer working exclusively on your AR application — building ARKit/ARCore features, Unity AR scenes, WebAR experiences, HoloLens enterprise tools, or visionOS spatial apps. They attend standups, commit to your repositories, and own the AR layer of your product.', bestFor: ['AR product or platform under active development (mobile AR app, WebAR experience)', 'Enterprise MR application for HoloLens 2 or Apple Vision Pro', 'AR e-commerce feature development (virtual try-on, product placement)', 'Teams needing a dedicated AR specialist alongside a web/mobile team'], process: 'Requirements → shortlist in 24 hrs → interview → start in 3–5 days', timeline: 'Available within 3–5 business days' },
  { id: 'part', name: 'Part-Time AR Developer (80 hrs/month)', badge: 'Flexible', badgeColor: '#0d9488', icon: 'M11.99 2C6.47 2 2 6.48 2 12s4.47 10 9.99 10C17.52 22 22 17.52 22 12S17.52 2 11.99 2zM12 20c-4.42 0-8-3.58-8-8s3.58-8 8-8 8 3.58 8 8-3.58 8-8 8zm.5-13H11v6l5.25 3.15.75-1.23-4.5-2.67V7z', headline: '80 hrs/month — AR expertise when you need it, without full-time overhead.', desc: 'A part-time AR developer for apps in maintenance, new AR feature additions to existing apps, or WebAR marketing campaigns that need an AR specialist a few days per week.', bestFor: ['Existing mobile apps adding a new AR feature', 'WebAR campaigns with defined scope and timeline', 'AR maintenance and 3D asset updates for live apps', 'Proof-of-concept AR development alongside another team'], process: 'Requirements → shortlist → start within 2–3 days', timeline: 'Available within 2–3 business days' },
  { id: 'project', name: 'Fixed-Scope AR Project', badge: 'Defined outcome', badgeColor: '#0369a1', icon: 'M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm-7 3c1.93 0 3.5 1.57 3.5 3.5S13.93 13 12 13s-3.5-1.57-3.5-3.5S10.07 6 12 6zm7 13H5v-.23c0-.62.28-1.2.76-1.58C7.47 15.82 9.64 15 12 15s4.53.82 6.24 2.19c.48.38.76.97.76 1.58V19z', headline: 'Fixed price for a defined AR experience or feature.', desc: 'Fixed-scope engagement for a well-defined AR project — a WebAR product launch campaign, an ARKit furniture placement feature, a virtual try-on for a product catalogue, a HoloLens assembly guidance pilot, or a visionOS proof of concept.', bestFor: ['WebAR brand activation (QR to AR experience)','ARKit furniture or product placement feature for e-commerce','Virtual try-on for eyewear, apparel, or accessories','HoloLens 2 assembly guidance pilot for a single workflow'], process: 'Scope → 3D asset review → development → device testing → launch', timeline: 'Typical 3–12 week engagements' },
];

const PROCESS_STEPS = [
  { num: '01', title: 'Share Your AR Requirements', desc: 'Tell us about your AR project — target platform (iOS ARKit, Android ARCore, WebAR, HoloLens, visionOS, or cross-platform Unity), use case (retail, industrial, marketing, training, e-commerce), 3D asset status (existing CAD or 3D files, or need to be created), and timeline. AR development depends heavily on 3D asset quality and device capabilities — the more detail you share, the better we can scope and match.' },
  { num: '02', title: 'AR Developer Shortlist in 24 Hours', desc: 'Within 24 business hours we send 2–3 pre-vetted AR developer profiles matched to your platform and use case — with their ARKit/ARCore/Unity portfolio, WebAR project examples, or HoloLens/visionOS experience. We distinguish between mobile AR developers, WebAR specialists, and enterprise MR engineers — you get the right specialist, not a generic "AR developer."' },
  { num: '03', title: 'Technical Interview — Test AR Platform Depth', desc: 'Interview candidates on your specific AR requirements. Ask them to explain ARKit plane detection and how they handle edge cases (poor lighting, featureless surfaces), walk through their 3D optimisation process for mobile GPU budgets, or design the architecture of your WebAR experience. We want you to test real AR engineering knowledge.' },
  { num: '04', title: '3D Asset Review & AR Architecture Planning', desc: 'Before development begins, our AR developer reviews your 3D assets — polygon count, texture sizes, material setup, and format suitability for the target platform. We flag asset issues that will cause performance problems before they become problems in development. If assets need to be created or optimised, we scope that work upfront.' },
  { num: '05', title: 'AR Development, Testing on Device', desc: 'AR development requires testing on real devices — not simulators. Our AR developers test on target hardware (iPhone with LiDAR, ARCore Android devices, HoloLens 2 physical device, or Quest 3 for mixed reality passthrough). We test lighting conditions, surface detection accuracy, 3D rendering performance (60fps target), occlusion accuracy, and edge cases. WebAR is tested across iOS Safari and Android Chrome versions.' },
  { num: '06', title: 'Launch, Performance Optimisation & Support', desc: 'App Store / Play Store submission (if mobile AR app), WebAR hosting setup (8thWall project hosting or custom CDN), HoloLens sideload or Windows Store deployment. Post-launch performance monitoring — frame rate, battery impact, thermal throttling on sustained use. Ongoing support for 3D asset updates, new product additions to AR catalogue, or new AR feature development.' },
];

const TESTIMONIALS = [
  { text: "1Solutions built our WebAR product launch campaign — customers scan the packaging QR code and the product comes to life in 3D on their phone, no app needed. 8thWall world tracking, custom animations, and a tap-to-purchase overlay. 38% of customers who triggered the AR went on to purchase within 24 hours. The AR developer delivered in 6 weeks.", name: 'Charlotte B.', role: 'Head of Digital Marketing, FMCG (UK)', init: 'CB', bg: '#0F3460' },
  { text: "We needed ARKit furniture placement for our iOS e-commerce app — real-scale 3D models placed on the floor, proper occlusion, and a share feature. 1Solutions found us an AR developer who built it in 10 weeks including the USDZ asset pipeline from our existing 3D models. Returns on AR-viewed products dropped 28% compared to non-AR purchases.", name: 'Marcus T.', role: 'CTO, Home Furnishings (AU)', init: 'MT', bg: '#0f3a2a', feat: true },
  { text: "1Solutions provided a HoloLens 2 developer for our assembly guidance pilot — holographic step-by-step instructions overlaid on the work surface, connected to our PLM system. Assembly error rate dropped 41% in the pilot line. He knew MRTK deeply, built the Azure Spatial Anchor integration for persistent anchors, and delivered full documentation.", name: 'Stefan H.', role: 'Innovation Lead, Manufacturing (US)', init: 'SH', bg: '#1e3a5f' },
];

const WHY_CARDS = [
  { title: 'Platform-Specific AR Expertise', desc: 'ARKit, ARCore, Unity AR Foundation, 8thWall WebAR, HoloLens MRTK, and visionOS RealityKit are distinct technical disciplines. We match you with a developer who has shipped on your specific target platform — not a Unity generalist who has "played with ARKit."' },
  { title: 'Real Device Testing', desc: 'AR cannot be validated on a simulator. Our AR developers test on physical devices throughout development — LiDAR iPhone Pro for depth sensing, ARCore-supported Android for compatibility, HoloLens 2 hardware for MR, Quest 3 for passthrough, and across iOS Safari / Android Chrome browser versions for WebAR.' },
  { title: 'Mobile GPU Performance Focus', desc: 'Mobile AR has real GPU constraints — 30ms frame budgets, thermal limits on sustained use, battery impact. Our AR developers profile performance (Unity Profiler, Xcode GPU Frame Debugger) from day one, not after users complain about heat and dropped frames.' },
  { title: '3D Asset Pipeline Knowledge', desc: 'Great AR experiences need optimised 3D assets. Our developers understand the pipeline from CAD or high-poly base mesh to mobile-ready AR asset — polygon reduction, PBR texture baking, LOD, format conversion (USDZ, GLB), and how asset quality directly impacts AR rendering performance.' },
  { title: 'WebAR for Zero-Friction Campaigns', desc: 'WebAR via 8thWall removes the app install barrier that kills marketing campaign conversion rates. Our WebAR developers have run product launch, retail, and brand activation campaigns — they know what makes WebAR work (good image targets, fast load times, smooth world tracking on mid-range phones).' },
  { title: 'Industrial AR Domain Knowledge', desc: 'Industrial AR requires understanding manufacturing workflows, PLM/CAD data integration, and the real constraints of factory floor hardware (gloves, lighting, noise, safety requirements). Our industrial AR developers have built guided assembly, remote assist, and maintenance AR for manufacturing and field service.' },
  { title: 'UX for Spatial Interfaces', desc: 'AR UX is fundamentally different from screen UI — users are in physical space, often in one hand, in varied lighting. Our AR developers understand spatial UI design principles: hand tracking UI for HoloLens, gaze-and-pinch for Vision Pro, AR overlay legibility at varying distances and lighting conditions, and world-locked vs head-locked UI placement.' },
  { title: 'Backend & Content Management', desc: 'AR applications need backends — to serve 3D models, update content without app releases, track usage analytics, and integrate with product catalogues. Our AR developers build the full stack: AR frontend, 3D asset delivery CDN, CMS for AR content management, and analytics pipeline.' },
];

const FAQS = [
  { q: 'What can an AR developer build?', a: "Mobile AR apps (ARKit iOS, ARCore Android), WebAR experiences (8thWall, no app install), Unity cross-platform AR, Microsoft HoloLens 2 enterprise MR, Apple Vision Pro visionOS apps, virtual try-on (eyewear, apparel, furniture), industrial guided assembly and remote assist AR, and marker-based AR for marketing campaigns." },
  { q: 'What is the difference between ARKit, ARCore, and WebAR?', a: "ARKit: Apple iOS native AR (highest performance, LiDAR depth on Pro models). ARCore: Google Android native AR (wide device support). WebAR (8thWall): browser-based AR, no app install — best for marketing campaigns. Unity AR Foundation: cross-platform single codebase for ARKit + ARCore. We recommend the right platform based on your use case and install-friction tolerance." },
  { q: 'What is Unity AR Foundation and when should I use it?', a: "Unity AR Foundation provides a common API that runs on ARKit (iOS), ARCore (Android), HoloLens, and other AR platforms from a single Unity codebase. Use it when you need cross-platform AR, want Unity\'s 3D engine (physics, animations, shaders), or are targeting both mobile and enterprise MR platforms." },
  { q: 'Can your AR developers build for Apple Vision Pro?', a: "Yes. Native visionOS apps with SwiftUI + RealityKit 4 — volumetric windows, fully immersive spaces, eye tracking and pinch gestures, spatial audio, ARKit for visionOS, and RealityKit physics/materials. Also Unity PolySpatial for cross-platform Vision Pro content." },
  { q: 'What is WebAR and can you build AR without an app?', a: "WebAR runs in the mobile browser — no app download needed. We use 8thWall (Niantic) for production WebAR: image tracking, world tracking (SLAM), face effects, working on iOS Safari and Android Chrome. Best for marketing campaigns, product launches, and e-commerce previews where zero install friction is critical." },
  { q: 'Can your AR developers build industrial AR?', a: "Yes. Step-by-step holographic assembly guidance (connected to CAD/PLM), remote expert assistance (AR annotation over live video), equipment maintenance overlays, warehouse pick-by-vision, and safety training simulations. Platforms: HoloLens 2 with MRTK, Unity AR, PTC Vuforia Engine, and RealWear Navigator." },
  { q: 'What hardware platforms do your AR developers target?', a: "Mobile AR: iPhone (ARKit, LiDAR Pro models) and Android (ARCore). Enterprise MR: HoloLens 2, Magic Leap 2. Spatial computing: Apple Vision Pro. Standalone MR: Meta Quest 3 (passthrough). Smart glasses: RealWear, Vuzix. WebAR: any modern smartphone browser." },
  { q: 'How do you approach AR 3D asset creation and optimisation?', a: "High-poly to game-ready conversion (Blender/Maya), polygon reduction to mobile budgets (10K–50K triangles), PBR texture baking and atlasing, LOD generation, USDZ for ARKit/QuickLook, GLB/glTF for WebAR/ARCore, CAD-to-AR pipeline from STEP/IGES files, and GPU performance profiling on target device hardware." },
];

function useCountUp(target, duration = 1800, start = false) {
  const [count, setCount] = useState(0);
  useEffect(() => { if (!start) return; const num = parseInt(target.replace(/\D/g, ''), 10); if (!num) return; let t0 = null; const step = ts => { if (!t0) t0 = ts; const p = Math.min((ts - t0) / duration, 1); setCount(Math.floor((1 - Math.pow(1 - p, 3)) * num)); if (p < 1) requestAnimationFrame(step); }; requestAnimationFrame(step); }, [start, target, duration]);
  return count;
}
function StatItem({ label, val, started }) {
  const num = useCountUp(val, 1800, started);
  const suffix = val.replace(/[\d,]/g, '');
  return (<div className="har-sc"><div className="har-sv">{started ? (val.includes(',') ? num.toLocaleString() : num) + suffix : val}</div><div className="har-sl">{label}</div></div>);
}

export default function HireARDeveloper() {
  const [showAll, setShowAll] = useState(false);
  const [openFaq, setOpenFaq] = useState(0);
  const [ss, setSs] = useState(false);
  const [vis, setVis] = useState(new Set());
  const [vSk, setVSk] = useState([]); const [vEn, setVEn] = useState([]); const [vWh, setVWh] = useState([]); const [vTe, setVTe] = useState([]); const [vSt, setVSt] = useState([]);
  const stR = useRef(null); const secR = useRef({});
  const skR = useRef(null); const enR = useRef(null); const whR = useRef(null); const teR = useRef(null); const stGr = useRef(null);
  useEffect(() => { if (!stR.current) return; const o = new IntersectionObserver(([e]) => { if (e.isIntersecting) { setSs(true); o.disconnect(); } }, { threshold: 0.4 }); o.observe(stR.current); return () => o.disconnect(); }, []);
  useEffect(() => { const pairs = [[skR, SKILLS.length, setVSk],[enR, 3, setVEn],[whR, WHY_CARDS.length, setVWh],[teR, 3, setVTe],[stGr, TECH_STACK.length, setVSt]]; const obs = pairs.map(([ref, count, setter]) => { if (!ref.current) return null; const o = new IntersectionObserver(([e]) => { if (e.isIntersecting) { Array.from({ length: count }, (_, i) => setTimeout(() => setter(p => p.includes(i) ? p : [...p, i]), i * 80)); o.disconnect(); } }, { threshold: 0.05 }); o.observe(ref.current); return o; }); return () => obs.forEach(o => o?.disconnect()); }, []);
  useEffect(() => { const ks = Object.keys(secR.current); const obs = ks.map(k => { const el = secR.current[k]; if (!el) return null; const o = new IntersectionObserver(([e]) => { if (e.isIntersecting) { setVis(p => new Set([...p, k])); o.disconnect(); } }, { threshold: 0.1 }); o.observe(el); return o; }); return () => obs.forEach(o => o?.disconnect()); }, []);
  const visSkills = showAll ? SKILLS : SKILLS.slice(0, 6);
  const C = '#0d9488';
  return (
    <>
      <Head>
        <title>Hire AR Developer | ARKit, ARCore, WebAR, HoloLens, visionOS | 1Solutions</title>
        <meta name="description" content="Hire expert AR developers from 1Solutions — ARKit, ARCore, Unity AR Foundation, WebAR (8thWall), Microsoft HoloLens 2, Apple Vision Pro visionOS, and industrial AR. Dedicated, part-time, or fixed-scope. Start in 3–5 days." />
        <link rel="canonical" href="https://www.1solutions.biz/hire-ar-developer/" />
        <meta property="og:title" content="Hire AR Developer | ARKit, ARCore, WebAR, HoloLens | 1Solutions" />
        <meta property="og:description" content="Hire vetted AR developers — ARKit, ARCore, Unity AR Foundation, 8thWall WebAR, HoloLens 2, Apple Vision Pro. Mobile AR, WebAR, enterprise MR, industrial AR." />
        <meta property="og:url" content="https://www.1solutions.biz/hire-ar-developer/" />
        <meta property="og:image" content="https://www.1solutions.biz/images/banner-1sol.jpg" />
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(SCHEMA) }} />
        <style>{`
          .har-page{font-family:'Inter',-apple-system,BlinkMacSystemFont,sans-serif;background:linear-gradient(135deg,#f0fdfa 0%,#ccfbf1 20%,#f0fdf4 50%,#fef3c7 75%,#f0f9ff 100%);color:#0F1F40;line-height:1.6;position:relative;overflow-x:hidden}
          .har-page *,.har-page *::before,.har-page *::after{box-sizing:border-box}
          .har-orb{position:absolute;border-radius:50%;pointer-events:none;z-index:0;filter:blur(20px)}
          .har-o1{width:860px;height:860px;background:radial-gradient(circle,rgba(13,148,136,.20) 0%,rgba(20,184,166,.08) 40%,transparent 70%);top:-260px;right:-240px}
          .har-o2{width:760px;height:760px;background:radial-gradient(circle,rgba(217,119,6,.15) 0%,rgba(251,191,36,.06) 40%,transparent 70%);bottom:0;left:-220px}
          .har-o3{width:520px;height:520px;background:radial-gradient(circle,rgba(3,105,161,.12) 0%,transparent 70%);top:44%;left:-100px;transform:translateY(-50%)}
          .har-bc{position:relative;z-index:2;padding:16px 40px 0;max-width:1440px;margin:0 auto}
          .har-bc ol{display:flex;flex-wrap:wrap;gap:6px;list-style:none;margin:0;padding:0;font-size:13px;color:#6A80A0}
          .har-bc li{display:flex;align-items:center;gap:6px}
          .har-bc li::after{content:'/';opacity:.45}
          .har-bc li:last-child::after{display:none}
          .har-bc a{color:#0F3460;text-decoration:none}
          .har-hero{position:relative;z-index:2;text-align:center;max-width:960px;margin:0 auto;padding:44px 40px 32px}
          .har-ey{display:block;font-size:11px;font-weight:700;letter-spacing:2.5px;text-transform:uppercase;color:#4A6080;margin-bottom:14px}
          .har-hero h1{font-size:50px;font-weight:900;line-height:1.09;letter-spacing:-1.5px;margin-bottom:16px;background:linear-gradient(90deg,#0F3460 0%,#0d9488 100%);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text}
          .har-desc{font-size:16px;color:#3A507A;line-height:1.65;max-width:740px;margin:0 auto 24px}
          .har-tr{display:flex;flex-wrap:wrap;justify-content:center;gap:10px;margin-bottom:26px}
          .har-badge{display:inline-flex;align-items:center;gap:6px;background:rgba(255,255,255,.60);backdrop-filter:blur(10px);border:1px solid rgba(255,255,255,.85);border-radius:100px;padding:6px 14px;font-size:12px;font-weight:600;color:#0F3460;box-shadow:0 2px 8px rgba(15,52,96,.07)}
          .har-dot{width:7px;height:7px;border-radius:50%;background:#0d9488;flex-shrink:0}
          .har-ctas{display:flex;flex-wrap:wrap;gap:12px;justify-content:center}
          .har-p{display:inline-block;padding:14px 36px;background:#0d9488;color:#fff;border-radius:50px;font-weight:700;font-size:15px;text-decoration:none;transition:all .25s;box-shadow:0 6px 24px rgba(13,148,136,.28)}
          .har-p:hover{background:#0F3460;transform:translateY(-2px)}
          .har-g{display:inline-block;padding:14px 36px;background:rgba(255,255,255,.55);backdrop-filter:blur(16px);border:1.5px solid rgba(255,255,255,.85);border-radius:50px;color:#0F3460;font-weight:700;font-size:15px;text-decoration:none;transition:all .25s}
          .har-g:hover{background:rgba(255,255,255,.85);border-color:rgba(13,148,136,.5);transform:translateY(-2px)}
          .har-stats{position:relative;z-index:2;display:grid;grid-template-columns:repeat(4,1fr);max-width:940px;margin:28px auto 0;background:rgba(255,255,255,.45);backdrop-filter:blur(24px);border:1px solid rgba(255,255,255,.85);box-shadow:0 4px 24px rgba(15,52,96,.08),inset 0 1px 0 rgba(255,255,255,.95)}
          .har-sc{padding:18px 16px;text-align:center;border-right:1px solid rgba(15,52,96,.10)}
          .har-sc:last-child{border-right:none}
          .har-sv{font-size:28px;font-weight:900;color:#0d9488;letter-spacing:-.5px;line-height:1}
          .har-sl{font-size:11px;color:#4A6080;font-weight:500;margin-top:5px}
          .har-logos{position:relative;z-index:2;padding:24px 40px 52px;display:flex;flex-direction:column;align-items:center;gap:14px}
          .har-ll{font-size:10px;font-weight:700;letter-spacing:2px;text-transform:uppercase;color:#6A80A0}
          .har-lw{width:100%;overflow:hidden}
          .har-lt{display:flex;align-items:center;gap:60px;width:max-content;animation:har-mq 28s linear infinite}
          .har-lt:hover{animation-play-state:paused}
          @keyframes har-mq{0%{transform:translateX(0)}100%{transform:translateX(-50%)}}
          .har-cl{height:24px;width:auto;max-width:110px;object-fit:contain;filter:grayscale(100%);opacity:.45;transition:opacity .25s,filter .25s}
          .har-cl:hover{opacity:.85;filter:grayscale(0%)}
          .har-sey{font-size:11px;font-weight:700;letter-spacing:2px;text-transform:uppercase;color:#D97706;margin-bottom:10px;display:block}
          .har-st{font-size:46px;font-weight:900;line-height:1.12;letter-spacing:-1px;background:linear-gradient(90deg,#0F3460 0%,#D97706 100%);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;margin-bottom:10px}
          .har-sd{font-size:15px;color:#4A6080;line-height:1.7}
          .har-rv{opacity:0;transform:translateY(44px);transition:opacity .7s cubic-bezier(0.22,1,.36,1),transform .7s cubic-bezier(0.22,1,.36,1)}
          .har-rv.har-ok{opacity:1;transform:translateY(0)}
          .har-in{max-width:1300px;margin:0 auto}
          .har-sk-s{background:transparent;padding:72px 40px 60px;position:relative;z-index:1}
          .har-sk-g{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-top:40px}
          .har-sk-c{background:linear-gradient(135deg,rgba(240,253,250,.50) 0%,rgba(255,255,255,.85) 55%,rgba(204,251,241,.40) 100%);backdrop-filter:blur(16px);border:1px solid rgba(255,255,255,.85);border-radius:20px;padding:26px 22px 22px;position:relative;overflow:hidden;box-shadow:0 4px 24px rgba(15,52,96,.08),inset 0 1px 0 rgba(255,255,255,.95);opacity:0;transform:translateY(36px);transition:opacity .6s cubic-bezier(0.22,1,.36,1),transform .6s cubic-bezier(0.22,1,.36,1),border-color .2s}
          .har-sk-c.har-cv{opacity:1;transform:translateY(0)}
          .har-sk-c.har-cv:hover{transform:translateY(-6px);border-color:rgba(13,148,136,.30);box-shadow:0 16px 48px rgba(15,52,96,.14)}
          .har-sk-c.feat{border-color:rgba(13,148,136,.20)}
          .har-sk-n{position:absolute;top:8px;right:14px;font-size:72px;font-weight:900;line-height:1;color:#0F3460;opacity:.055;pointer-events:none;letter-spacing:-4px;user-select:none}
          .har-sk-c h3{font-size:16px;font-weight:700;color:#0F1F40;margin:0 0 8px;position:relative;z-index:1}
          .har-sk-c p{font-size:13px;color:#4A6080;line-height:1.65;margin:0;position:relative;z-index:1}
          .har-sk-c::before{content:'';position:absolute;left:0;top:12%;height:76%;width:3px;background:linear-gradient(180deg,#0d9488,#14b8a6);border-radius:0 2px 2px 0;transform:scaleY(0);transform-origin:top center;transition:transform .3s cubic-bezier(0.22,1,.36,1)}
          .har-sk-c.har-cv:hover::before{transform:scaleY(1)}
          .har-sm{text-align:center;margin-top:22px}
          .har-bm{display:inline-block;background:#fff;border:1.5px solid rgba(15,52,96,.18);color:#0F3460;padding:10px 30px;border-radius:20px;font-weight:600;font-size:14px;cursor:pointer;transition:all .2s;font-family:inherit}
          .har-bm:hover{background:#0F3460;border-color:#0F3460;color:#fff;transform:translateY(-2px)}
          .har-tec-s{background:#f8fafd;border-top:1px solid rgba(15,52,96,.08);border-bottom:1px solid rgba(15,52,96,.08);padding:72px 40px;position:relative;z-index:1}
          .har-tec-g{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin-top:40px}
          .har-tec-c{background:linear-gradient(135deg,rgba(240,253,250,.50) 0%,rgba(255,255,255,.85) 55%,rgba(204,251,241,.40) 100%);backdrop-filter:blur(16px);border:1px solid rgba(255,255,255,.85);border-radius:20px;padding:22px 20px;box-shadow:0 4px 24px rgba(15,52,96,.08),inset 0 1px 0 rgba(255,255,255,.95);opacity:0;transform:translateY(32px);transition:opacity .55s cubic-bezier(0.22,1,.36,1),transform .55s cubic-bezier(0.22,1,.36,1),border-color .2s}
          .har-tec-c.har-sv2{opacity:1;transform:translateY(0)}
          .har-tec-c.har-sv2:hover{border-color:rgba(13,148,136,.25);box-shadow:0 14px 40px rgba(15,52,96,.12)}
          .har-tg{font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:1.2px;margin-bottom:12px;padding-bottom:8px;border-bottom:2px solid}
          .har-pills{display:flex;flex-wrap:wrap;gap:6px}
          .har-pill{display:inline-block;font-size:11.5px;font-weight:500;padding:4px 10px;border-radius:100px;border:1px solid}
          .har-en-s{padding:80px 40px;position:relative;z-index:1}
          .har-en-g{display:grid;grid-template-columns:repeat(3,1fr);gap:20px;margin-top:40px}
          .har-en-c{background:linear-gradient(135deg,rgba(240,253,250,.50) 0%,rgba(255,255,255,.85) 55%,rgba(204,251,241,.40) 100%);backdrop-filter:blur(16px);border:1px solid rgba(255,255,255,.85);border-radius:24px;padding:32px 28px;box-shadow:0 4px 24px rgba(15,52,96,.08),inset 0 1px 0 rgba(255,255,255,.95);opacity:0;transform:translateY(44px);transition:opacity .65s cubic-bezier(0.22,1,.36,1),transform .65s cubic-bezier(0.22,1,.36,1),border-color .2s}
          .har-en-c.har-ev{opacity:1;transform:translateY(0)}
          .har-en-c.har-ev:hover{border-color:rgba(13,148,136,.25);box-shadow:0 16px 48px rgba(15,52,96,.14)}
          .har-en-c.feat{background:linear-gradient(135deg,rgba(254,243,199,.52) 0%,rgba(255,255,255,.87) 55%,rgba(240,253,250,.45) 100%);border-color:rgba(217,119,6,.28);box-shadow:0 8px 32px rgba(217,119,6,.12),inset 0 1px 0 rgba(255,255,255,1);transform:translateY(-8px)}
          .har-en-c.feat.har-ev{transform:translateY(-8px)}
          .har-en-c.feat.har-ev:hover{transform:translateY(-12px)}
          .har-en-b{display:inline-block;font-size:10px;font-weight:700;letter-spacing:1.2px;text-transform:uppercase;padding:5px 12px;border-radius:100px;border:1px solid;margin-bottom:18px}
          .har-en-i{width:48px;height:48px;background:rgba(15,52,96,.07);border-radius:14px;display:flex;align-items:center;justify-content:center;margin-bottom:14px}
          .har-en-i svg{fill:#0F3460}
          .har-en-c.feat .har-en-i{background:rgba(217,119,6,.10)}
          .har-en-c.feat .har-en-i svg{fill:#D97706}
          .har-en-n{font-size:22px;font-weight:900;color:#0F3460;margin:0 0 6px;letter-spacing:-.3px}
          .har-en-h{font-size:13px;font-weight:600;color:#0d9488;margin-bottom:12px}
          .har-en-c.feat .har-en-h{color:#D97706}
          .har-en-d{font-size:14px;color:#4A6080;line-height:1.7;margin-bottom:18px}
          .har-en-ll{font-size:10px;font-weight:700;letter-spacing:1px;text-transform:uppercase;color:#6A80A0;margin-bottom:8px}
          .har-en-li{list-style:none;padding:0;margin:0 0 18px;display:flex;flex-direction:column;gap:7px}
          .har-en-li li{display:flex;align-items:flex-start;gap:8px;font-size:13px;color:#374151;line-height:1.5}
          .har-en-li li::before{content:'✓';font-weight:800;color:#0d9488;flex-shrink:0;margin-top:1px}
          .har-en-c.feat .har-en-li li::before{color:#D97706}
          .har-en-p{font-size:12px;color:#6A80A0;padding-top:14px;border-top:1px solid rgba(15,52,96,.08)}
          .har-en-p strong{color:#0F3460}
          .har-en-tl{display:inline-block;font-size:11px;font-weight:600;color:#D97706;margin-top:6px}
          .har-en-a{display:block;margin-top:18px;padding:11px;border-radius:50px;font-size:13px;font-weight:700;text-align:center;text-decoration:none;transition:all .22s;background:rgba(15,52,96,.09);color:#0F3460;border:1.5px solid rgba(15,52,96,.18)}
          .har-en-a:hover{background:#0F3460;color:#fff}
          .har-en-c.feat .har-en-a{background:#0d9488;color:#fff;border-color:#0d9488}
          .har-en-c.feat .har-en-a:hover{background:#0F3460;border-color:#0F3460}
          .har-pr-s{background:#f8fafd;border-top:1px solid rgba(15,52,96,.08);border-bottom:1px solid rgba(15,52,96,.08);padding:80px 40px;position:relative;z-index:1}
          .har-ps{display:flex;flex-direction:column;margin-top:52px}
          .har-ps-row{display:grid;grid-template-columns:56px 1fr;gap:0 20px;opacity:0;transform:translateY(48px);transition:opacity .65s cubic-bezier(0.22,1,.36,1),transform .65s cubic-bezier(0.22,1,.36,1)}
          .har-ps-row.har-pv{opacity:1;transform:translateY(0)}
          .har-ps-l{display:flex;flex-direction:column;align-items:center}
          .har-ps-ci{width:52px;height:52px;border-radius:50%;background:rgba(255,255,255,.65);backdrop-filter:blur(8px);border:2px solid rgba(15,52,96,.18);display:flex;align-items:center;justify-content:center;font-size:19px;font-weight:800;color:#0F3460;flex-shrink:0}
          .har-ps-row.har-pv:hover .har-ps-ci{background:rgba(13,148,136,.10);border-color:#0d9488;color:#0d9488}
          .har-ps-co{flex:1;display:flex;flex-direction:column;align-items:center;padding:6px 0;min-height:42px}
          .har-ps-co::before{content:'';width:2px;flex:1;background:#0F3460;opacity:.22}
          .har-ps-co::after{content:'';border-left:6px solid transparent;border-right:6px solid transparent;border-top:8px solid #0F3460;opacity:.40}
          .har-ps-row:last-child .har-ps-co{display:none}
          .har-ps-r{padding:4px 0 38px}
          .har-ps-row:last-child .har-ps-r{padding-bottom:0}
          .har-ps-t{font-size:20px;font-weight:700;color:#0F3460;margin:0 0 9px}
          .har-ps-d{font-size:15px;color:#4A6080;line-height:1.75;margin:0}
          .har-te-s{background:transparent;padding:80px 40px;position:relative;z-index:1}
          .har-ch{text-align:center;margin-bottom:48px}
          .har-tg2{display:grid;grid-template-columns:repeat(3,1fr);gap:24px}
          .har-tc{background:linear-gradient(135deg,rgba(240,253,250,.50) 0%,rgba(255,255,255,.85) 55%,rgba(204,251,241,.40) 100%);backdrop-filter:blur(16px);border:1px solid rgba(255,255,255,.85);border-radius:20px;padding:28px 24px;display:flex;flex-direction:column;gap:12px;box-shadow:0 4px 24px rgba(15,52,96,.08),inset 0 1px 0 rgba(255,255,255,.95);opacity:0;transform:translateY(40px);transition:opacity .6s cubic-bezier(0.22,1,.36,1),transform .6s cubic-bezier(0.22,1,.36,1)}
          .har-tc.feat{background:linear-gradient(135deg,rgba(254,243,199,.52) 0%,rgba(255,255,255,.87) 55%,rgba(240,253,250,.42) 100%);border-color:rgba(217,119,6,.22)}
          .har-tc.har-tv{opacity:1;transform:translateY(0)}
          .har-tc.har-tv:hover{transform:translateY(-6px);box-shadow:0 16px 48px rgba(15,52,96,.14)}
          .har-stars{font-size:16px;color:#D97706;letter-spacing:2px}
          .har-txt{font-size:14px;line-height:1.75;color:#374151;flex:1}
          .har-au{display:flex;align-items:center;gap:12px}
          .har-av{width:42px;height:42px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:13px;font-weight:800;color:#fff;flex-shrink:0}
          .har-an{font-size:14px;font-weight:700;color:#0F3460}
          .har-ar{font-size:12px;color:#6b7280}
          .har-wy-s{background:#f8fafd;border-top:1px solid rgba(15,52,96,.08);border-bottom:1px solid rgba(15,52,96,.08);padding:80px 40px;position:relative;z-index:1}
          .har-wy-g{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin-top:48px}
          .har-wc{background:linear-gradient(135deg,rgba(240,253,250,.50) 0%,rgba(255,255,255,.85) 55%,rgba(204,251,241,.40) 100%);backdrop-filter:blur(16px);border:1px solid rgba(255,255,255,.85);border-radius:20px;padding:26px 22px;box-shadow:0 4px 24px rgba(15,52,96,.08),inset 0 1px 0 rgba(255,255,255,.95);opacity:0;transform:translateY(32px) scale(.97);transition:opacity .55s cubic-bezier(0.22,1,.36,1),transform .55s cubic-bezier(0.22,1,.36,1),border-color .2s}
          .har-wc.har-wv{opacity:1;transform:translateY(0) scale(1)}
          .har-wc.har-wv:hover{transform:translateY(-5px) scale(1);border-color:rgba(13,148,136,.25);box-shadow:0 14px 40px rgba(15,52,96,.12)}
          .har-wd{width:10px;height:10px;border-radius:50%;background:#0d9488;margin-bottom:12px}
          .har-wc h3{font-size:14px;font-weight:700;color:#0F1F40;margin:0 0 8px;line-height:1.35}
          .har-wc p{font-size:13px;color:#4A6080;line-height:1.65;margin:0}
          .har-ct-s{padding:70px 40px;background:linear-gradient(135deg,rgba(240,253,250,.55) 0%,rgba(255,255,255,.60) 40%,rgba(204,251,241,.55) 100%);backdrop-filter:blur(20px);border-top:1px solid rgba(255,255,255,.80);position:relative;z-index:1}
          .har-ct-g{max-width:1440px;margin:0 auto;display:grid;grid-template-columns:1fr 1.15fr;gap:32px;align-items:start}
          .har-ctt{font-size:42px;font-weight:900;line-height:1.18;margin:0 0 14px;background:linear-gradient(90deg,#0F3460 0%,#0d9488 100%);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text}
          .har-ctd{font-size:14px;color:#4A6080;line-height:1.6;margin:0 0 22px}
          .har-ben{background:rgba(255,255,255,.70);border:1px solid rgba(255,255,255,.90);border-radius:14px;padding:22px;backdrop-filter:blur(12px);display:flex;flex-direction:column;gap:14px}
          .har-be{display:flex;gap:10px;align-items:flex-start}
          .har-bi{flex-shrink:0;color:#0d9488;font-weight:800;font-size:16px;margin-top:1px}
          .har-be p{font-size:13px;color:#4A6080;margin:0;line-height:1.55}
          .har-fb{background:linear-gradient(135deg,rgba(255,255,255,.88) 0%,rgba(240,253,250,.18) 50%,rgba(255,255,255,.84) 100%);backdrop-filter:blur(20px);border:1px solid rgba(255,255,255,.92);border-radius:20px;padding:34px;box-shadow:0 8px 40px rgba(15,52,96,.10),inset 0 1px 0 rgba(255,255,255,1)}
          .har-fb h3{font-size:22px;font-weight:700;color:#0F1F40;margin:0 0 22px;letter-spacing:-.3px}
          .har-form{display:flex;flex-direction:column;gap:13px}
          .har-fr{display:grid;grid-template-columns:1fr 1fr;gap:12px}
          .har-fg{display:flex;flex-direction:column;gap:5px}
          .har-fg.full{grid-column:1/-1}
          .har-fg label{font-size:12px;font-weight:500;color:#0F1F40}
          .har-fg input,.har-fg textarea,.har-fg select{padding:10px 13px;border:1px solid rgba(15,52,96,.14);border-radius:6px;font-size:13px;font-family:inherit;color:#0F1F40;background:rgba(255,255,255,.55);transition:border-color .2s}
          .har-fg input:focus,.har-fg textarea:focus,.har-fg select:focus{outline:none;border-color:#0d9488;box-shadow:0 0 0 3px rgba(13,148,136,.10)}
          .har-co{display:flex;gap:8px;align-items:flex-start}
          .har-co input{margin-top:3px;width:15px;height:15px}
          .har-co label{font-size:11px;color:#4A6080;line-height:1.5}
          .har-co a{color:#0F3460}
          .har-sub{width:100%;padding:14px;background:#0d9488;border:none;color:#fff;border-radius:50px;font-weight:700;font-size:15px;cursor:pointer;font-family:inherit;transition:all .25s;box-shadow:0 6px 24px rgba(13,148,136,.26)}
          .har-sub:hover{background:#0F3460;transform:translateY(-2px)}
          .har-fq-s{padding:80px 40px;background:#f8fafd;border-top:1px solid rgba(15,52,96,.08);position:relative;z-index:1}
          .har-fq-s h2{font-size:46px;font-weight:900;letter-spacing:-1px;background:linear-gradient(90deg,#0F3460 0%,#D97706 100%);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;margin:0 0 8px}
          .har-fq-sub{font-size:15px;color:#4A6080;margin:0 0 36px}
          .har-fql{display:flex;flex-direction:column;gap:10px}
          .har-fi{background:linear-gradient(135deg,rgba(240,253,250,.50) 0%,rgba(255,255,255,.85) 55%,rgba(204,251,241,.40) 100%);backdrop-filter:blur(16px);border:1px solid rgba(255,255,255,.85);border-radius:14px;overflow:hidden;box-shadow:0 4px 20px rgba(15,52,96,.06);transition:border-color .2s}
          .har-fi.open{border-color:rgba(13,148,136,.30)}
          .har-fi.open::before{content:'';display:block;height:3px;background:linear-gradient(90deg,#0d9488,#14b8a6);border-radius:3px 3px 0 0}
          .har-fqb{width:100%;background:none;border:none;padding:20px 20px 20px 58px;display:flex;align-items:center;justify-content:space-between;cursor:pointer;text-align:left;gap:14px;font-family:inherit;position:relative}
          .har-fqb2{position:absolute;left:16px;top:50%;transform:translateY(-50%);width:26px;height:26px;background:rgba(15,52,96,.08);color:#374151;font-size:11px;font-weight:700;display:flex;align-items:center;justify-content:center;border-radius:6px}
          .har-fi.open .har-fqb2{background:#0d9488;color:#fff}
          .har-fqb span{font-size:15px;font-weight:600;color:#0F1F40;line-height:1.4}
          .har-fi.open .har-fqb span{color:#0f766e}
          .har-fch{width:22px;height:22px;flex-shrink:0;color:#9ca3af;transition:transform .3s}
          .har-fi.open .har-fch{transform:rotate(180deg);color:#0d9488}
          .har-faw{overflow:hidden;transition:max-height .35s ease;max-height:0}
          .har-fi.open .har-faw{max-height:600px}
          .har-fa{padding:0 20px 20px 58px;font-size:14px;color:#4b5563;line-height:1.8}
          .har-rel{padding:80px 40px;background:rgba(240,253,250,.14);backdrop-filter:blur(10px);border-top:1px solid rgba(255,255,255,.60)}
          .har-ri{max-width:1300px;margin:0 auto;text-align:center}
          .har-ri h2{font-size:34px;font-weight:900;background:linear-gradient(90deg,#0F3460 0%,#D97706 100%);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;margin:10px 0 12px}
          .har-rs{font-size:14px;color:#4A6080;margin:0 auto;max-width:560px}
          .har-ri hr{border:none;border-top:1px solid rgba(15,52,96,.10);margin:32px 0}
          .har-rts{display:flex;flex-wrap:wrap;justify-content:center;gap:10px}
          .har-rt{display:inline-block;padding:10px 20px;border:1.5px solid;border-radius:50px;font-size:14px;font-weight:500;text-decoration:none;transition:all .22s}
          .har-rt:hover{transform:translateY(-2px);box-shadow:0 6px 18px rgba(0,0,0,.09)}
          .har-t{background:rgba(13,148,136,.09);border-color:rgba(13,148,136,.28);color:#0f766e}
          .har-v{background:rgba(109,40,217,.09);border-color:rgba(109,40,217,.28);color:#4c1d95}
          .har-b{background:rgba(30,64,175,.09);border-color:rgba(30,64,175,.28);color:#1e3a8a}
          .har-o{background:rgba(249,115,22,.09);border-color:rgba(249,115,22,.28);color:#c2410c}
          .har-a{background:rgba(202,138,4,.09);border-color:rgba(202,138,4,.28);color:#92400e}
          @media(max-width:1024px){.har-hero h1,.har-st,.har-fq-s h2{font-size:36px}.har-sk-g{grid-template-columns:repeat(2,1fr)}.har-tec-g{grid-template-columns:repeat(2,1fr)}.har-en-g{grid-template-columns:1fr;max-width:480px;margin-left:auto;margin-right:auto}.har-en-c.feat{transform:none}.har-en-c.feat.har-ev{transform:none}.har-en-c.feat.har-ev:hover{transform:translateY(-4px)}.har-wy-g{grid-template-columns:repeat(2,1fr)}.har-tg2{grid-template-columns:1fr}.har-ct-g{grid-template-columns:1fr}}
          @media(max-width:768px){.har-bc,.har-hero,.har-sk-s,.har-tec-s,.har-en-s,.har-pr-s,.har-te-s,.har-wy-s,.har-fq-s,.har-rel{padding-left:20px;padding-right:20px}.har-hero{padding-top:28px;padding-bottom:20px}.har-hero h1{font-size:26px;letter-spacing:-.3px}.har-stats{grid-template-columns:1fr 1fr}.har-sc:nth-child(2){border-right:none}.har-sc:nth-child(3),.har-sc:nth-child(4){border-top:1px solid rgba(15,52,96,.10)}.har-sc:nth-child(4){border-right:none}.har-sk-g,.har-tec-g,.har-wy-g{grid-template-columns:1fr}.har-fr{grid-template-columns:1fr}.har-ctt{font-size:28px}.har-st{font-size:28px}.har-ct-s{padding:48px 20px}.har-logos{padding-left:20px;padding-right:20px}}
        `}</style>
      </Head>
      <div className="har-page">
        <div className="har-orb har-o1" /><div className="har-orb har-o2" /><div className="har-orb har-o3" />
        <nav className="har-bc" aria-label="Breadcrumb"><ol itemScope itemType="https://schema.org/BreadcrumbList"><li itemScope itemType="https://schema.org/ListItem" itemProp="itemListElement"><Link href="/" itemProp="item"><span itemProp="name">Home</span></Link><meta itemProp="position" content="1" /></li><li itemScope itemType="https://schema.org/ListItem" itemProp="itemListElement"><span itemProp="name">Hire AR Developer</span><meta itemProp="position" content="2" /></li></ol></nav>
        <section className="har-hero">
          <span className="har-ey">Hire AR Developer</span>
          <h1>Hire Expert AR Developers — ARKit, ARCore, WebAR & HoloLens</h1>
          <p className="har-desc">Hire pre-vetted AR developers specialising in ARKit (iOS), ARCore (Android), Unity AR Foundation, WebAR (8thWall), Microsoft HoloLens 2, Apple Vision Pro visionOS, and industrial AR applications. Mobile AR, enterprise MR, or WebAR campaigns — dedicated, part-time, or fixed-scope. Start in 3–5 business days.</p>
          <div className="har-tr">{['ARKit / ARCore','Unity AR Foundation','WebAR (8thWall)','HoloLens 2','Apple Vision Pro'].map(b => (<div className="har-badge" key={b}><span className="har-dot" />{b}</div>))}</div>
          <div className="har-ctas"><Link href="#contact" className="har-p">Hire an AR Developer</Link><Link href="#engagement" className="har-g">View Engagement Models →</Link></div>
        </section>
        <div className="har-stats" ref={stR}>{[['50+','AR Projects Delivered'],['15+','Years Dev Experience'],['48hr','Avg Developer Match'],['98%','Client Retention']].map(([v, l]) => (<StatItem key={l} label={l} val={v} started={ss} />))}</div>
        <div className="har-logos"><span className="har-ll">Trusted by AR & XR Product Teams</span><div className="har-lw"><div className="har-lt">{[['/logo/Indian_Express_Logo_full.png','Indian Express'],['/logo/Verizon_2015_logo_-vector.svg.png','Verizon'],['/logo/Uniphore.jpg','Uniphore'],['/logo/ICCoLogo.png','ICC'],['/logo/Honor_Logo_(2020).svg.png','Honor'],['/logo/Zuari-Finserv-logo-new.png','Zuari Finserv'],['/logo/Indian_Express_Logo_full.png','Indian Express 2'],['/logo/Verizon_2015_logo_-vector.svg.png','Verizon 2'],['/logo/Uniphore.jpg','Uniphore 2'],['/logo/ICCoLogo.png','ICC 2'],['/logo/Honor_Logo_(2020).svg.png','Honor 2'],['/logo/Zuari-Finserv-logo-new.png','Zuari Finserv 2']].map(([src, alt]) => (<img key={alt} src={src} alt={alt.replace(/ \d$/, '')} className="har-cl" />))}</div></div></div>
        <section className="har-sk-s" aria-labelledby="har-sk-h"><div className="har-in"><div className={`har-rv${vis.has('sk') ? ' har-ok' : ''}`} ref={el => { secR.current['sk'] = el; }}><span className="har-sey">What Our AR Developers Build</span><h2 id="har-sk-h" className="har-st">AR Skills & Expertise</h2><p className="har-sd" style={{ maxWidth: 720 }}>Mobile AR (ARKit/ARCore), Unity AR Foundation, WebAR (8thWall), Microsoft HoloLens 2, Apple Vision Pro visionOS, AR e-commerce (virtual try-on), industrial AR, spatial anchors, 3D asset optimisation, and AR analytics integration.</p></div><div className="har-sk-g" ref={skR}>{visSkills.map((s, i) => (<div key={s.n} className={`har-sk-c${s.feat ? ' feat' : ''}${vSk.includes(i) ? ' har-cv' : ''}`} style={{ transitionDelay: `${i * 55}ms` }}><span className="har-sk-n">{s.n}</span><h3>{s.title}</h3><p>{s.desc}</p></div>))}</div>{SKILLS.length > 6 && (<div className="har-sm"><button className="har-bm" onClick={() => setShowAll(p => !p)}>{showAll ? 'Show fewer ↑' : `Show all ${SKILLS.length} areas ↓`}</button></div>)}</div></section>
        <section className="har-tec-s" aria-labelledby="har-tec-h"><div className="har-in"><div className={`har-rv${vis.has('stk') ? ' har-ok' : ''}`} ref={el => { secR.current['stk'] = el; }}><span className="har-sey">Technology Stack</span><h2 id="har-tec-h" className="har-st">AR Tools & Technologies</h2><p className="har-sd" style={{ maxWidth: 680 }}>ARKit, ARCore, Unity AR Foundation, RealityKit, 8thWall, Three.js + WebXR, MRTK, Azure Spatial Anchors, visionOS SwiftUI, C#, Swift, JavaScript, Blender, USDZ, GLB/glTF, and the full XR development stack.</p></div><div className="har-tec-g" ref={stGr}>{TECH_STACK.map((grp, i) => (<div key={grp.group} className={`har-tec-c${vSt.includes(i) ? ' har-sv2' : ''}`} style={{ transitionDelay: `${i * 60}ms` }}><div className="har-tg" style={{ color: grp.color, borderBottomColor: grp.color + '33' }}>{grp.group}</div><div className="har-pills">{grp.items.map(item => <span key={item} className="har-pill" style={{ color: grp.color, background: grp.color + '12', borderColor: grp.color + '30' }}>{item}</span>)}</div></div>))}</div></div></section>
        <section id="engagement" className="har-en-s" aria-labelledby="har-en-h"><div className="har-in"><div className={`har-rv${vis.has('eng') ? ' har-ok' : ''}`} ref={el => { secR.current['eng'] = el; }}><span className="har-sey">Engagement Models</span><h2 id="har-en-h" className="har-st">How to Hire an AR Developer</h2><p className="har-sd" style={{ maxWidth: 680 }}>Full-time dedicated AR engineer, part-time specialist, or fixed-scope AR project — structured for your platform and spatial computing stage.</p></div><div className="har-en-g" ref={enR}>{ENGAGEMENT_MODELS.map((m, i) => (<div key={m.id} className={`har-en-c${m.feat ? ' feat' : ''}${vEn.includes(i) ? ' har-ev' : ''}`} style={{ transitionDelay: `${i * 100}ms` }}><span className="har-en-b" style={{ color: m.badgeColor, borderColor: m.badgeColor + '44', background: m.badgeColor + '14' }}>{m.badge}</span><div className="har-en-i"><svg viewBox="0 0 24 24" width="26" height="26"><path d={m.icon} /></svg></div><div className="har-en-n">{m.name}</div><div className="har-en-h">{m.headline}</div><div className="har-en-d">{m.desc}</div><div className="har-en-ll">Best for</div><ul className="har-en-li">{m.bestFor.map(b => <li key={b}>{b}</li>)}</ul><div className="har-en-p"><strong>Process:</strong> {m.process}<br /><span className="har-en-tl">{m.timeline}</span></div><Link href="#contact" className="har-en-a">Get a free estimate →</Link></div>))}</div></div></section>
        <section className="har-pr-s" aria-labelledby="har-pr-h"><div className="har-in" style={{ maxWidth: 760 }}><div className={`har-rv${vis.has('proc') ? ' har-ok' : ''}`} ref={el => { secR.current['proc'] = el; }}><span className="har-sey">How We Hire</span><h2 id="har-pr-h" className="har-st">Our AR Developer Hiring Process</h2><p className="har-sd">From AR requirements to first device-tested build in 3–5 business days — platform-specific vetting, 3D asset review, real device testing, and post-launch support.</p></div><div className="har-ps">{PROCESS_STEPS.map((step, i) => (<div key={step.num} className={`har-ps-row${vis.has('proc') ? ' har-pv' : ''}`} style={{ transitionDelay: `${i * 120}ms` }}><div className="har-ps-l"><div className="har-ps-ci">{step.num}</div><div className="har-ps-co" /></div><div className="har-ps-r"><div className="har-ps-t">{step.title}</div><p className="har-ps-d">{step.desc}</p></div></div>))}</div></div></section>
        <section className="har-te-s" aria-labelledby="har-te-h"><div className="har-in"><div className={`har-ch har-rv${vis.has('ts') ? ' har-ok' : ''}`} ref={el => { secR.current['ts'] = el; }}><span className="har-sey">Client Results</span><h2 id="har-te-h" className="har-st">What Our Clients Say</h2><p className="har-sd">Marketing leads, e-commerce CTOs, and manufacturing innovation teams across the UK, AU, and US on hiring AR developers from 1Solutions.</p></div><div className="har-tg2" ref={teR}>{TESTIMONIALS.map((t, i) => (<div key={i} className={`har-tc${t.feat ? ' feat' : ''}${vTe.includes(i) ? ' har-tv' : ''}`} style={{ transitionDelay: `${i * 100}ms` }} itemScope itemType="https://schema.org/Review"><div className="har-stars">★★★★★</div><p className="har-txt" itemProp="reviewBody">{t.text}</p><div className="har-au"><div className="har-av" style={{ background: t.bg }}>{t.init}</div><div><div className="har-an" itemProp="author">{t.name}</div><div className="har-ar">{t.role}</div></div></div></div>))}</div></div></section>
        <section className="har-wy-s" aria-labelledby="har-wy-h"><div className="har-in"><div className={`har-rv${vis.has('wy') ? ' har-ok' : ''}`} ref={el => { secR.current['wy'] = el; }}><span className="har-sey">Why 1Solutions</span><h2 id="har-wy-h" className="har-st">Why Hire AR Developers From 1Solutions</h2><p className="har-sd" style={{ maxWidth: 680 }}>Platform-specific expertise, real device testing, mobile GPU performance focus, 3D asset pipeline knowledge, WebAR for zero-friction campaigns, industrial AR domain knowledge, spatial UX design, and full-stack AR + backend capability.</p></div><div className="har-wy-g" ref={whR}>{WHY_CARDS.map((c, i) => (<div key={i} className={`har-wc${vWh.includes(i) ? ' har-wv' : ''}`} style={{ transitionDelay: `${i * 60}ms` }}><div className="har-wd" /><h3>{c.title}</h3><p>{c.desc}</p></div>))}</div></div></section>
        <section id="contact" className="har-ct-s" aria-labelledby="har-ct-h"><div className="har-ct-g"><div><h2 id="har-ct-h" className="har-ctt">Hire an AR Developer Today</h2><p className="har-ctd">Share your AR project requirements — target platform, use case, 3D asset status, and timeline — and we will shortlist pre-vetted AR developers within 24 business hours. We match on platform-specific depth, not generic "3D developer" profiles.</p><div className="har-ben">{[['✓','Shortlisted AR developers within 24 business hours'],['✓','Platform-specific vetting — ARKit, ARCore, Unity AR, WebAR, HoloLens, visionOS'],['✓','Full-time, part-time, or fixed-scope — flexible engagement'],['✓','3D asset review before development begins'],['✓','5-day rapid replacement guarantee']].map(([icon, text]) => (<div className="har-be" key={text}><span className="har-bi">{icon}</span><p>{text}</p></div>))}</div></div>
        <div className="har-fb"><h3>Tell Us Your AR Requirements</h3><form className="har-form" onSubmit={e => e.preventDefault()}>
          <div className="har-fr"><div className="har-fg"><label htmlFor="har-nm">Full Name *</label><input id="har-nm" type="text" placeholder="Your name" required /></div><div className="har-fg"><label htmlFor="har-em">Work Email *</label><input id="har-em" type="email" placeholder="you@company.com" required /></div></div>
          <div className="har-fr"><div className="har-fg"><label htmlFor="har-co">Company Name</label><input id="har-co" type="text" placeholder="Your company" /></div><div className="har-fg"><label htmlFor="har-ph">Phone / WhatsApp</label><input id="har-ph" type="tel" placeholder="+1 555 000 0000" /></div></div>
          <div className="har-fg full"><label htmlFor="har-en">Engagement Type *</label><select id="har-en" required><option value="">Select engagement...</option><option>Full-Time Dedicated AR Developer (160 hrs/month)</option><option>Part-Time AR Developer (80 hrs/month)</option><option>Fixed-Scope AR Project</option></select></div>
          <div className="har-fg full"><label htmlFor="har-pl">Target AR Platform *</label><select id="har-pl" required><option value="">Select platform...</option><option>Mobile AR — iOS (ARKit)</option><option>Mobile AR — Android (ARCore)</option><option>Cross-platform Mobile AR (Unity AR Foundation)</option><option>WebAR (8thWall / no app install)</option><option>Microsoft HoloLens 2 / Mixed Reality</option><option>Apple Vision Pro (visionOS)</option><option>Meta Quest 3 (MR passthrough)</option><option>Multiple platforms</option></select></div>
          <div className="har-fg full"><label htmlFor="har-uc">AR Use Case *</label><select id="har-uc" required><option value="">Select use case...</option><option>E-commerce / Virtual Try-On / Product Placement</option><option>WebAR Marketing Campaign</option><option>Industrial / Assembly Guidance / Remote Assist</option><option>Enterprise Training / Safety Simulation</option><option>AR Game or Interactive Experience</option><option>Education / Museum / Cultural</option><option>Real Estate / Architecture Visualisation</option><option>Other / Custom</option></select></div>
          <div className="har-fg full"><label htmlFor="har-ms">Project Description *</label><textarea id="har-ms" rows={4} placeholder="Describe your AR project — target platform, use case, existing 3D assets (or need to create them), user context (indoor/outdoor, lighting), timeline, and any existing app or infrastructure..." required /></div>
          <div className="har-co"><input id="har-co2" type="checkbox" required /><label htmlFor="har-co2">I agree to the <Link href="/privacy-policy">Privacy Policy</Link>. Details are treated confidentially.</label></div>
          <button type="submit" className="har-sub">Get Shortlisted AR Developers →</button>
        </form></div></div></section>
        <section className="har-fq-s" aria-labelledby="har-fq-h"><div className="har-in" style={{ maxWidth: 860 }}><span className="har-sey">FAQ</span><h2 id="har-fq-h">Hiring AR Developers — FAQ</h2><p className="har-fq-sub">Common questions about hiring AR developers — ARKit vs ARCore, Unity AR Foundation, WebAR, HoloLens, Vision Pro, industrial AR, and 3D asset optimisation.</p><div className="har-fql">{FAQS.map((item, i) => (<div key={i} className={`har-fi${openFaq === i ? ' open' : ''}`} itemScope itemType="https://schema.org/Question"><button className="har-fqb" onClick={() => setOpenFaq(openFaq === i ? -1 : i)} aria-expanded={openFaq === i}><div className="har-fqb2">{String(i + 1).padStart(2, '0')}</div><span itemProp="name">{item.q}</span><svg className="har-fch" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2"><polyline points="6 9 12 15 18 9" /></svg></button><div className="har-faw" itemScope itemType="https://schema.org/Answer"><div className="har-fa" itemProp="text">{item.a}</div></div></div>))}</div></div></section>
        <section className="har-rel"><div className="har-ri"><span className="har-sey">Explore More</span><h2>Related Hire Developer Pages</h2><p className="har-rs">We also provide dedicated AI, ML, blockchain, and mobile app developers for innovative businesses worldwide.</p><hr /><div className="har-rts">{[['/hire-ai-developer/','Hire AI Developer','har-v'],['/hire-ml-developer/','Hire ML Developer','har-v'],['/hire-blockchain-developer/','Hire Blockchain Developer','har-o'],['/hire-javascript-developer/','Hire JS Developer','har-a'],['/android-app-development-company/','Android Development','har-b'],['/ios-app-development-company/','iOS Development','har-b'],['/flutter-app-development-company/','Flutter Development','har-b'],['/software-development-company/','Software Development','har-t']].map(([href, label, cls]) => (<Link key={href} href={href} className={`har-rt ${cls}`}>{label}</Link>))}</div></div></section>
      </div>
    </>
  );
}
