import { useState, useEffect, useRef } from 'react';
import Head from 'next/head';
import Link from 'next/link';

const SERVICES = [
  { n: '01', title: 'HVAC Local SEO', desc: 'Dominate local search for HVAC installation, repair, and maintenance in your service area — Google Business Profile optimisation, citation building, and geo-targeted keyword strategy for "AC repair near me," "heating installation," and emergency HVAC searches.' },
  { n: '02', title: 'Google Business Profile for HVAC', desc: 'Full Google Business Profile management — service categories, photos, review management, seasonal posts, emergency availability updates, and service area configuration — maximising local map pack visibility for HVAC emergency and non-emergency searches.' },
  { n: '03', title: 'HVAC Website SEO', desc: 'Dedicated service pages for each HVAC service — AC installation, heating repair, heat pump installation, air quality, maintenance plans — with local keyword optimisation, location pages, and technical SEO that drives organic rankings over time.' },
  { n: '04', title: 'HVAC Google Ads', desc: 'Search campaigns targeting high-intent HVAC keywords — "AC repair [city]," "furnace installation near me," "emergency HVAC" — with call-only ads for emergency services, geo-fencing, and day-parting to maximise lead volume and quality.' },
  { n: '05', title: 'Emergency HVAC Lead Generation', desc: 'Specialised campaigns for emergency HVAC calls — extended hours targeting (late evening, weekends), call-only ad formats, and landing pages optimised for immediate phone call conversion during peak emergency demand periods.' },
  { n: '06', title: 'HVAC Content & Blog Strategy', desc: 'SEO-optimised blog content targeting HVAC informational searches — maintenance guides, cost articles, comparison content, local buying guides — building topical authority and capturing research-stage organic traffic that converts to service enquiries.' },
  { n: '07', title: 'Review Generation for HVAC', desc: 'Automated review generation workflows — post-job follow-up texts and emails, Google review links, Yelp and HomeAdvisor profile management — building the review volume and rating that drives local rankings and phone call conversions.' },
  { n: '08', title: 'HVAC Maintenance Plan Marketing', desc: 'Email and SMS campaigns marketing annual maintenance plans to previous customers — a recurring revenue strategy that improves customer retention, reduces seasonal cash flow volatility, and generates predictable annual inspection revenue.' },
];

const SERVICES_LIST = ['AC Installation & Repair', 'Heating Systems', 'Heat Pumps', 'Ductwork & Air Quality', 'Emergency HVAC', 'Commercial HVAC', 'Maintenance Plans', 'Boiler Services', 'Mini-Split Systems', 'Refrigeration'];

const PROCESS = [
  { step: '01', title: 'HVAC Business Analysis', desc: 'Understanding your service area, current lead sources, seasonal patterns, service mix (residential / commercial), and competitive landscape — the foundation for an HVAC-specific marketing strategy.' },
  { step: '02', title: 'Local SEO & Paid Setup', desc: 'Google Business Profile configuration, local citation audit, website technical review, and Google Ads account setup — the infrastructure that generates both immediate paid leads and long-term organic growth.' },
  { step: '03', title: 'Service Page Optimisation', desc: 'Creating or optimising dedicated pages for every HVAC service and every location you serve — the content foundation for organic rankings and paid ad landing pages.' },
  { step: '04', title: 'Campaigns Launch', desc: 'Google Ads campaigns launched — emergency HVAC call-only ads, seasonal installation campaigns, maintenance plan campaigns — with conversion tracking set up to measure every call and form submission.' },
  { step: '05', title: 'Seasonal Campaigns', desc: 'Spring/summer AC tune-up and installation campaigns, autumn/winter heating campaigns — seasonal marketing calendar managed to align with peak HVAC demand in your market.' },
  { step: '06', title: 'Monthly Reporting', desc: 'Leads generated by channel, cost per lead, average job value, review score growth, and organic rankings — a full picture of marketing ROI with next month\'s optimisation priorities.' },
];

const WHY = [
  { title: 'Emergency HVAC Lead Expertise', desc: 'Emergency HVAC calls (broken AC in July, no heat in January) are high-value leads with immediate conversion pressure. We build dedicated emergency campaigns with call-only ads, extended hour targeting, and emergency-focused landing pages that convert these time-sensitive searches.' },
  { title: 'Seasonal Campaign Management', desc: 'HVAC has two clear peak seasons in most markets. We manage your marketing calendar around spring AC tune-ups, summer installation peaks, autumn furnace check-ups, and winter emergency heating — so ad spend rises and falls with actual demand.' },
  { title: 'Local Map Pack Focus', desc: 'For emergency HVAC searches, customers call the first result in the map pack without much comparison. We focus disproportionate attention on Google Business Profile optimisation, review generation, and citation building to achieve and maintain top-3 map pack positions.' },
  { title: 'Service Area Page Strategy', desc: 'HVAC companies typically serve multiple towns and cities. We build individual service area pages — "AC repair [town]," "HVAC installation [city]" — for every location in your service territory, creating geo-targeted organic ranking opportunities across your entire market.' },
  { title: 'Maintenance Plan Revenue Growth', desc: 'Annual maintenance plans are the recurring revenue backbone of a healthy HVAC business. We build email and SMS marketing campaigns that sell maintenance plans to previous customers — improving retention, smoothing seasonal revenue volatility, and increasing customer lifetime value.' },
  { title: 'Commercial HVAC Marketing', desc: 'Commercial HVAC contracts (offices, retail, industrial) are high-value but require different marketing than residential. We build separate SEO and LinkedIn campaigns targeting facility managers, property managers, and commercial property owners in your service area.' },
];

const FAQS = [
  { q: 'What is the best marketing strategy for an HVAC company?', a: 'The most effective HVAC marketing strategy combines: local SEO and Google Business Profile — appearing in the top 3 of the Google Maps pack for "HVAC near me," "AC repair [city]," and emergency HVAC searches is the single highest-value marketing position for most HVAC businesses; Google Search Ads — PPC campaigns capturing high-intent searches immediately, especially for emergency calls and seasonal installation demand; review generation — HVAC businesses with 100+ Google reviews at 4.8+ stars convert significantly more from map pack positions than competitors with fewer reviews; and maintenance plan marketing — email and SMS campaigns selling annual service agreements to previous customers create predictable recurring revenue that offsets seasonal demand volatility. The right mix depends on your current market position, budget, and whether you focus on residential, commercial, or both.' },
  { q: 'How do I get more emergency HVAC calls from Google?', a: 'Emergency HVAC calls primarily come from two places: Google Maps (local pack) and Google Search Ads. For Google Maps: fully optimised GBP with emergency/24-hour service indicated, high review volume and rating, correct service categories ("HVAC contractor," "Air conditioning repair service"), and consistent NAP citations across directories. For paid search: call-only ads targeting "emergency AC repair," "emergency heating repair," and related keywords with extended hour ad scheduling (evenings and weekends when emergencies peak). For organic search: dedicated emergency HVAC service pages with "24-hour," "emergency," and location keywords that appear in non-paid search results. Conversion optimisation (prominent phone numbers, click-to-call, fast loading) is also critical — emergency callers will move to the next result if your site is slow or your number is hard to find.' },
  { q: 'How much does HVAC Google Ads cost?', a: 'HVAC Google Ads costs vary significantly by market and keyword. HVAC is one of the more expensive service industries for Google Ads because of high customer lifetime value and competitive bidding. Typical cost-per-click for HVAC keywords in competitive US markets: $8 to $25 per click for non-emergency service keywords; $20 to $60 per click for emergency or high-intent keywords ("emergency AC repair," "furnace installation near me") in major metros. For a realistic budget: a $1,500 to $3,000 per month ad budget in a medium-competitive market might generate 30 to 80 leads per month, with cost per lead ranging from $40 to $100 depending on keyword quality and landing page conversion rate. Actual costs depend heavily on your specific market — large cities are significantly more expensive than smaller markets.' },
  { q: 'How long does HVAC SEO take to generate leads?', a: 'HVAC SEO has different timelines for different components. Google Business Profile improvements: meaningful improvement in local map pack rankings can appear within 4 to 12 weeks of full GBP optimisation, citation building, and review generation. On-page and technical SEO: improvements to existing page rankings typically appear within 6 to 12 weeks. New service and location pages: meaningful organic rankings for new pages take 3 to 8 months depending on competition and domain authority. Content and link building: building authority to compete for the most competitive HVAC keywords in large markets takes 12 to 24 months. For most HVAC companies, we recommend running Google Ads alongside SEO to generate immediate leads while organic rankings build — then gradually shifting budget from paid to organic as rankings improve.' },
  { q: 'Should my HVAC company be on Yelp, HomeAdvisor, Angi, and similar platforms?', a: 'Yes — for lead volume and review signals, these platforms are worth maintaining even if they are not your primary lead source. Yelp: significant traffic in some markets, particularly for residential HVAC. Maintain a profile with photos and respond to reviews, but do not pay for Yelp advertising unless you have tested it in your specific market. HomeAdvisor / Angi: lead quality varies widely — some HVAC companies find them highly profitable, others find the leads too price-competitive. Worth testing with a defined budget to measure your specific cost per acquired customer. Thumbtack: similar to HomeAdvisor/Angi — market dependent. The primary value of all these platforms is review signals and citation consistency for local SEO — even if you do not generate leads directly from them, active profiles with consistent NAP information strengthen your Google Business Profile rankings.' },
  { q: 'How important are Google reviews for HVAC lead generation?', a: 'Google reviews are extremely important for HVAC lead generation for two reasons. First, ranking: Google Business Profile reviews are a significant local ranking signal — businesses with higher review counts and better ratings rank higher in the local map pack. Second, conversion: emergency HVAC customers are making a fast decision under stress. They will choose the first business in the map pack with a high rating (4.5+) and a meaningful number of reviews (50+). A business with 3 reviews at 4.2 stars loses calls to a competitor with 90 reviews at 4.8 stars even from the same map pack position. Systematic review generation — automated post-job follow-up texts with a Google review link — is one of the highest-ROI HVAC marketing activities because it improves both ranking and conversion simultaneously.' },
  { q: 'Do you work with HVAC companies of all sizes?', a: 'Yes. We work with solo HVAC technicians building their first customer base, growing residential HVAC companies with 5 to 20 technicians, and larger commercial HVAC contractors. Strategy and budget scale with business size — a solo tech needs Google Business Profile optimisation and basic local SEO; a growing company needs multi-channel campaigns across local SEO, Google Ads, and review management; a commercial contractor needs LinkedIn, content marketing targeting facility managers, and a different keyword strategy than residential HVAC. We tailor the strategy and budget to where you are today and where you want to be in 12 to 24 months.' },
  { q: 'Can you help HVAC companies market maintenance plans?', a: 'Yes. Annual maintenance plans are one of the best growth levers for an HVAC company because they create predictable recurring revenue, smooth seasonal demand volatility, and increase customer lifetime value dramatically. We build maintenance plan marketing through: email campaigns to previous residential customers offering a maintenance plan at a compelling annual price; post-installation follow-up sequences that move customers from a one-time installation to an annual plan; seasonal campaigns (spring and autumn) that use the natural tune-up reminder as a lead-in to selling the annual plan; and content marketing (blog posts, emails) that educates homeowners on the value of annual HVAC servicing. A well-run maintenance plan campaign can add significant recurring revenue without requiring any new customer acquisition.' },
];

const STATS = [
  { label: 'HVAC Clients', val: '95+' },
  { label: 'Avg Lead Growth', val: '+2.9×' },
  { label: 'Years Experience', val: '12+' },
  { label: 'Client Retention', val: '93%' },
];

export default function HvacSeoServices() {
  const [openFaq, setOpenFaq] = useState(0);
  const [visibleCards, setVisibleCards] = useState([]);
  const [visibleSteps, setVisibleSteps] = useState([]);
  const [visibleWhy, setVisibleWhy] = useState([]);
  const cardsRef = useRef(null); const stepRefs = useRef([]); const whyRef = useRef(null);
  useEffect(() => { if (!cardsRef.current) return; const o = new IntersectionObserver(([e]) => { if (e.isIntersecting) { SERVICES.forEach((_, i) => setTimeout(() => setVisibleCards(p => p.includes(i) ? p : [...p, i]), i * 60)); o.disconnect(); } }, { threshold: 0.05 }); o.observe(cardsRef.current); return () => o.disconnect(); }, []);
  useEffect(() => { const obs = stepRefs.current.map((el, i) => { if (!el) return null; const o = new IntersectionObserver(([e]) => { if (e.isIntersecting) { setTimeout(() => setVisibleSteps(p => p.includes(i) ? p : [...p, i]), i * 120); o.disconnect(); } }, { threshold: 0.2 }); o.observe(el); return o; }); return () => obs.forEach(o => o && o.disconnect()); }, []);
  useEffect(() => { if (!whyRef.current) return; const o = new IntersectionObserver(([e]) => { if (e.isIntersecting) { WHY.forEach((_, i) => setTimeout(() => setVisibleWhy(p => p.includes(i) ? p : [...p, i]), i * 90)); o.disconnect(); } }, { threshold: 0.1 }); o.observe(whyRef.current); return () => o.disconnect(); }, []);
  const jsonLd = { '@context': 'https://schema.org', '@graph': [{ '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Home', item: 'https://www.1solutions.biz/' }, { '@type': 'ListItem', position: 2, name: 'SEO Services', item: 'https://www.1solutions.biz/seo-services-company/' }, { '@type': 'ListItem', position: 3, name: 'HVAC SEO Services', item: 'https://www.1solutions.biz/hvac-seo-services/' }] }, { '@type': 'Service', name: 'HVAC SEO Services', provider: { '@type': 'Organization', name: '1Solutions', url: 'https://www.1solutions.biz' }, serviceType: 'HVAC SEO & Digital Marketing', url: 'https://www.1solutions.biz/hvac-seo-services/' }, { '@type': 'FAQPage', mainEntity: FAQS.map(f => ({ '@type': 'Question', name: f.q, acceptedAnswer: { '@type': 'Answer', text: f.a } })) }] };
  return (
    <>
      <Head>
        <title>HVAC SEO Services | Digital Marketing for HVAC Companies | 1Solutions</title>
        <meta name="description" content="SEO and digital marketing services for HVAC companies — local SEO, Google Ads for HVAC, emergency call campaigns, review generation, and seasonal marketing to generate consistent HVAC leads." />
        <meta name="keywords" content="hvac seo services, hvac digital marketing, hvac local seo, hvac google ads, hvac lead generation, hvac marketing company, air conditioning seo, heating company seo" />
        <link rel="canonical" href="https://www.1solutions.biz/hvac-seo-services/" />
        <meta property="og:title" content="HVAC SEO Services | 1Solutions" />
        <meta property="og:url" content="https://www.1solutions.biz/hvac-seo-services/" />
        <meta name="twitter:card" content="summary_large_image" />
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
        <style>{`
          .hvacseo-page{font-family:'Inter',-apple-system,BlinkMacSystemFont,sans-serif;color:#0F1F40;line-height:1.6;overflow-x:hidden}
          .hvacseo-page *,.hvacseo-page *::before,.hvacseo-page *::after{box-sizing:border-box}
          .hvacseo-hero{background:linear-gradient(135deg,#eff6ff 0%,#dbeafe 30%,#bfdbfe 65%,#eff6ff 100%);position:relative;overflow:hidden;padding:80px 40px 0}
          .hvacseo-o1{position:absolute;top:-100px;right:-100px;width:560px;height:560px;border-radius:50%;background:radial-gradient(circle,rgba(59,130,246,0.12) 0%,transparent 65%);pointer-events:none;filter:blur(30px)}
          .hvacseo-o2{position:absolute;bottom:0;left:-80px;width:440px;height:440px;border-radius:50%;background:radial-gradient(circle,rgba(29,78,216,0.07) 0%,transparent 65%);pointer-events:none;filter:blur(30px)}
          .hvacseo-in{max-width:1280px;margin:0 auto;position:relative;z-index:2;text-align:center}
          .hvacseo-bc{display:flex;align-items:center;justify-content:center;flex-wrap:wrap;gap:6px;font-size:12px;color:#6b7280;margin-bottom:24px;font-weight:500}
          .hvacseo-bc a{color:#6b7280;text-decoration:none}.hvacseo-bc a:hover{color:#3B82F6}.hvacseo-bc span{color:#d1d5db}
          .hvacseo-ey{display:inline-flex;align-items:center;gap:8px;background:rgba(59,130,246,0.08);border:1px solid rgba(59,130,246,0.20);border-radius:100px;padding:5px 14px;font-size:11px;font-weight:700;letter-spacing:1.5px;text-transform:uppercase;color:#3B82F6;margin-bottom:28px}
          .hvacseo-h1{font-size:clamp(2.2rem,5vw,3.6rem);font-weight:900;line-height:1.1;letter-spacing:-1px;background:linear-gradient(90deg,#1E3A8A 0%,#3B82F6 50%,#2563EB 100%);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;margin-bottom:20px;max-width:900px;margin-left:auto;margin-right:auto}
          .hvacseo-sub{font-size:1.08rem;color:#4A6080;line-height:1.75;max-width:660px;margin:0 auto 36px}
          .hvacseo-btns{display:flex;gap:14px;justify-content:center;flex-wrap:wrap;margin-bottom:56px}
          .hvacseo-btn-p{display:inline-flex;align-items:center;gap:8px;background:#3B82F6;color:#fff;padding:14px 30px;border-radius:50px;font-weight:700;font-size:0.95rem;text-decoration:none;transition:all 0.25s;box-shadow:0 4px 20px rgba(59,130,246,0.28)}
          .hvacseo-btn-p:hover{background:#1E3A8A;box-shadow:0 8px 32px rgba(59,130,246,0.38);transform:translateY(-2px)}
          .hvacseo-btn-s{display:inline-flex;align-items:center;gap:8px;background:rgba(255,255,255,0.65);backdrop-filter:blur(12px);border:1.5px solid rgba(15,52,96,0.18);color:#0F3460;padding:14px 30px;border-radius:50px;font-weight:700;font-size:0.95rem;text-decoration:none;transition:all 0.25s}
          .hvacseo-btn-s:hover{border-color:#3B82F6;color:#3B82F6;transform:translateY(-2px)}
          .hvacseo-stats{display:grid;grid-template-columns:repeat(4,1fr);max-width:900px;margin:0 auto;background:rgba(255,255,255,0.55);backdrop-filter:blur(20px);border:1px solid rgba(255,255,255,0.85);border-radius:20px 20px 0 0;box-shadow:0 4px 24px rgba(59,130,246,0.07)}
          .hvacseo-stat{padding:20px 24px;text-align:center;border-right:1px solid rgba(59,130,246,0.08)}.hvacseo-stat:last-child{border-right:none}
          .hvacseo-stat-l{font-size:11px;color:#6b7280;font-weight:500;margin-bottom:4px}
          .hvacseo-stat-v{font-size:1.6rem;font-weight:900;color:#3B82F6;letter-spacing:-0.5px}
          .hvacseo-svc{background:#f8fafd;padding:80px 40px}.hvacseo-svc-in{max-width:1280px;margin:0 auto}
          .hvacseo-ey2{font-size:11px;font-weight:700;letter-spacing:2px;text-transform:uppercase;color:#3B82F6;margin-bottom:10px;display:block}
          .hvacseo-ttl{font-size:clamp(1.8rem,4vw,3rem);font-weight:900;line-height:1.15;letter-spacing:-1px;background:linear-gradient(90deg,#1E3A8A 0%,#3B82F6 100%);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;margin-bottom:10px}
          .hvacseo-desc{font-size:15px;color:#4A6080;line-height:1.7;max-width:640px;margin-bottom:44px}
          .hvacseo-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}
          .hvacseo-card{background:linear-gradient(135deg,rgba(239,246,255,0.65) 0%,rgba(255,255,255,0.88) 60%,rgba(219,234,254,0.25) 100%);border:1px solid rgba(255,255,255,0.85);border-radius:20px;padding:26px 22px 22px;position:relative;overflow:hidden;box-shadow:0 4px 24px rgba(59,130,246,0.05);opacity:0;transform:translateY(20px);transition:opacity 0.4s ease,transform 0.4s ease}
          .hvacseo-card.visible{opacity:1;transform:translateY(0)}.hvacseo-card:hover{transform:translateY(-6px);border-color:rgba(59,130,246,0.22);box-shadow:0 16px 48px rgba(59,130,246,0.09)}
          .hvacseo-num{position:absolute;top:8px;right:14px;font-size:72px;font-weight:900;line-height:1;color:#3B82F6;opacity:0.05;letter-spacing:-4px;pointer-events:none;user-select:none}
          .hvacseo-card h3{font-size:15px;font-weight:700;color:#0F1F40;margin-bottom:8px;position:relative;z-index:1}
          .hvacseo-card p{font-size:13px;color:#4A6080;line-height:1.6;position:relative;z-index:1;margin:0}
          .hvacseo-sv{background:linear-gradient(135deg,#1E3A8A 0%,#3B82F6 100%);padding:60px 40px}
          .hvacseo-sv-in{max-width:1280px;margin:0 auto;text-align:center}
          .hvacseo-sv h2{font-size:clamp(1.6rem,3vw,2.4rem);font-weight:900;color:#fff;margin-bottom:32px}
          .hvacseo-pills{display:flex;flex-wrap:wrap;gap:10px;justify-content:center}
          .hvacseo-pill{background:rgba(255,255,255,0.12);border:1px solid rgba(255,255,255,0.20);border-radius:100px;padding:8px 18px;font-size:13px;font-weight:600;color:#fff}
          .hvacseo-proc{background:linear-gradient(135deg,#eff6ff 0%,#eff6ff 50%,#dbeafe 100%);padding:80px 40px}
          .hvacseo-proc-in{max-width:900px;margin:0 auto}
          .hvacseo-steps{display:flex;flex-direction:column;margin-top:44px}
          .hvacseo-step{display:grid;grid-template-columns:80px 1fr;gap:24px;align-items:flex-start;padding:28px 0;border-bottom:1px solid rgba(59,130,246,0.10);opacity:0;transform:translateX(-20px);transition:opacity 0.45s ease,transform 0.45s ease}
          .hvacseo-step:last-child{border-bottom:none}.hvacseo-step.visible{opacity:1;transform:translateX(0)}
          .hvacseo-snum{font-size:3rem;font-weight:900;color:rgba(59,130,246,0.15);line-height:1;letter-spacing:-2px}
          .hvacseo-step h3{font-size:1.1rem;font-weight:800;color:#0F1F40;margin-bottom:6px}
          .hvacseo-step p{font-size:0.9rem;color:#4A6080;line-height:1.7;margin:0}
          .hvacseo-why{background:#fff;padding:80px 40px}.hvacseo-why-in{max-width:1280px;margin:0 auto}
          .hvacseo-why-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:20px;margin-top:44px}
          .hvacseo-wcard{background:linear-gradient(135deg,#eff6ff 0%,#fff 60%,#dbeafe 100%);border:1px solid rgba(59,130,246,0.10);border-radius:16px;padding:28px;opacity:0;transform:translateY(16px);transition:opacity 0.4s ease,transform 0.4s ease}
          .hvacseo-wcard.visible{opacity:1;transform:translateY(0)}.hvacseo-wcard:hover{border-color:rgba(59,130,246,0.20);box-shadow:0 8px 32px rgba(59,130,246,0.07)}
          .hvacseo-dot{width:8px;height:8px;border-radius:50%;background:#3B82F6;margin-bottom:16px}
          .hvacseo-wcard h3{font-size:1rem;font-weight:800;color:#0F1F40;margin-bottom:10px}
          .hvacseo-wcard p{font-size:0.88rem;color:#4A6080;line-height:1.7;margin:0}
          .hvacseo-faq{background:#f8fafd;padding:80px 40px}.hvacseo-faq-in{max-width:860px;margin:0 auto}
          .hvacseo-fitem{border-bottom:1px solid #e5e7eb}
          .hvacseo-fq{width:100%;background:none;border:none;text-align:left;padding:22px 0;display:flex;align-items:flex-start;justify-content:space-between;gap:16px;cursor:pointer;font-family:inherit;font-size:1rem;font-weight:700;color:#0F1F40;line-height:1.4}
          .hvacseo-fq:hover{color:#3B82F6}
          .hvacseo-ficon{width:22px;height:22px;border:2px solid #e5e7eb;border-radius:50%;display:flex;align-items:center;justify-content:center;flex-shrink:0;font-size:14px;color:#9ca3af;transition:all 0.2s;margin-top:2px}
          .hvacseo-fitem.open .hvacseo-ficon{border-color:#3B82F6;color:#3B82F6;background:rgba(59,130,246,0.06)}
          .hvacseo-fa{font-size:0.92rem;color:#4A6080;line-height:1.8;overflow:hidden;max-height:0;transition:max-height 0.35s ease,padding-bottom 0.35s ease}
          .hvacseo-fitem.open .hvacseo-fa{max-height:600px;padding-bottom:22px}
          .hvacseo-cta{background:linear-gradient(135deg,rgba(59,130,246,0.06) 0%,rgba(255,255,255,0.80) 40%,rgba(30,58,138,0.04) 100%);padding:90px 40px;position:relative;overflow:hidden}
          .hvacseo-cta-o1{position:absolute;top:-80px;right:-80px;width:360px;height:360px;border-radius:50%;background:radial-gradient(circle,rgba(59,130,246,0.10) 0%,transparent 70%);pointer-events:none}
          .hvacseo-cta-o2{position:absolute;bottom:-60px;left:-60px;width:280px;height:280px;border-radius:50%;background:radial-gradient(circle,rgba(30,58,138,0.08) 0%,transparent 70%);pointer-events:none}
          .hvacseo-cta-in{max-width:760px;margin:0 auto;text-align:center;position:relative;z-index:1}
          .hvacseo-cta-t{font-size:clamp(1.8rem,3.5vw,2.8rem);font-weight:900;background:linear-gradient(90deg,#1E3A8A 0%,#3B82F6 100%);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;margin-bottom:16px;line-height:1.2}
          .hvacseo-cta-s{font-size:1.05rem;color:#4A6080;line-height:1.75;margin:0 auto 36px;max-width:520px}
          @media(max-width:1024px){.hvacseo-grid{grid-template-columns:repeat(2,1fr)}.hvacseo-why-grid{grid-template-columns:repeat(2,1fr)}}
          @media(max-width:768px){.hvacseo-hero,.hvacseo-svc,.hvacseo-sv,.hvacseo-proc,.hvacseo-why,.hvacseo-faq,.hvacseo-cta{padding:60px 24px}.hvacseo-hero{padding-top:60px;padding-bottom:0}.hvacseo-stats{grid-template-columns:repeat(2,1fr);border-radius:16px 16px 0 0}.hvacseo-stat:nth-child(2){border-right:none}.hvacseo-grid{grid-template-columns:1fr}.hvacseo-why-grid{grid-template-columns:1fr}.hvacseo-step{grid-template-columns:56px 1fr}.hvacseo-btns{flex-direction:column;align-items:center}}
        `}</style>
      </Head>
      <div className="hvacseo-page">
        <section className="hvacseo-hero"><div className="hvacseo-o1"/><div className="hvacseo-o2"/>
          <div className="hvacseo-in">
            <nav className="hvacseo-bc"><Link href="/">Home</Link><span>/</span><Link href="/seo-services-company">SEO</Link><span>/</span><span style={{color:'#3B82F6'}}>HVAC SEO Services</span></nav>
            <span className="hvacseo-ey"><span style={{width:6,height:6,borderRadius:'50%',background:'#3B82F6',display:'inline-block'}}/> Local SEO · Emergency HVAC Ads · Review Generation</span>
            <h1 className="hvacseo-h1">HVAC SEO Services — More Leads, More Calls, More Jobs</h1>
            <p className="hvacseo-sub">SEO and digital marketing built specifically for HVAC companies — local map pack dominance, emergency call campaigns, seasonal marketing, and review generation that generates consistent high-quality HVAC leads.</p>
            <div className="hvacseo-btns">
              <Link href="/contact" className="hvacseo-btn-p">Get a Free HVAC Marketing Audit <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><path d="M5 12h14M12 5l7 7-7 7"/></svg></Link>
              <Link href="/local-seo-services" className="hvacseo-btn-s">Local SEO Services</Link>
            </div>
            <div className="hvacseo-stats">{STATS.map(s => <div key={s.label} className="hvacseo-stat"><div className="hvacseo-stat-l">{s.label}</div><div className="hvacseo-stat-v">{s.val}</div></div>)}</div>
          </div>
        </section>
        <section className="hvacseo-svc"><div className="hvacseo-svc-in">
          <span className="hvacseo-ey2">What We Do</span><h2 className="hvacseo-ttl">HVAC SEO &amp; Digital Marketing Services</h2>
          <p className="hvacseo-desc">Every digital marketing channel an HVAC company needs — local visibility, emergency call ads, content, review management, and maintenance plan campaigns.</p>
          <div className="hvacseo-grid" ref={cardsRef}>{SERVICES.map((s,i) => <div key={s.n} className={`hvacseo-card${visibleCards.includes(i)?' visible':''}`}><div className="hvacseo-num">{s.n}</div><h3>{s.title}</h3><p>{s.desc}</p></div>)}</div>
        </div></section>
        <section className="hvacseo-sv"><div className="hvacseo-sv-in"><h2>HVAC Services We Market</h2><div className="hvacseo-pills">{SERVICES_LIST.map(s => <span key={s} className="hvacseo-pill">{s}</span>)}</div></div></section>
        <section className="hvacseo-proc"><div className="hvacseo-proc-in">
          <span className="hvacseo-ey2">How We Work</span><h2 className="hvacseo-ttl">Our HVAC Marketing Process</h2>
          <p className="hvacseo-desc">From market analysis to seasonal campaigns — a structured approach built around your service territory and growth targets.</p>
          <div className="hvacseo-steps">{PROCESS.map((p,i) => <div key={p.step} ref={el=>{stepRefs.current[i]=el}} className={`hvacseo-step${visibleSteps.includes(i)?' visible':''}`}><div className="hvacseo-snum">{p.step}</div><div><h3>{p.title}</h3><p>{p.desc}</p></div></div>)}</div>
        </div></section>
        <section className="hvacseo-why"><div className="hvacseo-why-in">
          <span className="hvacseo-ey2">Why 1Solutions</span><h2 className="hvacseo-ttl">HVAC Marketing Specialists — Not Generic Service Business Templates</h2>
          <p className="hvacseo-desc">HVAC lead generation has unique dynamics — emergency demand, seasonal patterns, maintenance plan upsells, and route density economics. We build strategies around these specifics.</p>
          <div className="hvacseo-why-grid" ref={whyRef}>{WHY.map((w,i) => <div key={w.title} className={`hvacseo-wcard${visibleWhy.includes(i)?' visible':''}`}><div className="hvacseo-dot"/><h3>{w.title}</h3><p>{w.desc}</p></div>)}</div>
        </div></section>
        <section className="hvacseo-faq"><div className="hvacseo-faq-in">
          <span className="hvacseo-ey2">Got Questions?</span><h2 className="hvacseo-ttl">HVAC SEO &amp; Marketing FAQs</h2>
          <p className="hvacseo-desc" style={{marginBottom:44}}>Answers to the most common HVAC marketing questions.</p>
          <div>{FAQS.map((f,i) => <div key={i} className={`hvacseo-fitem${openFaq===i?' open':''}`}><button className="hvacseo-fq" onClick={()=>setOpenFaq(openFaq===i?-1:i)}>{f.q}<span className="hvacseo-ficon">{openFaq===i?'−':'+'}</span></button><div className="hvacseo-fa" style={openFaq===i?{maxHeight:600,paddingBottom:22}:{}}>{f.a}</div></div>)}</div>
        </div></section>
        <section className="hvacseo-cta"><div className="hvacseo-cta-o1"/><div className="hvacseo-cta-o2"/>
          <div className="hvacseo-cta-in">
            <span className="hvacseo-ey2" style={{textAlign:'center',display:'block',marginBottom:16}}>Ready to dominate HVAC searches in your area?</span>
            <h2 className="hvacseo-cta-t">Get a Free HVAC Marketing Audit</h2>
            <p className="hvacseo-cta-s">We&rsquo;ll audit your Google Business Profile, local rankings, competitor positioning, and current lead volume — then show you the fastest path to more HVAC calls.</p>
            <div className="hvacseo-btns">
              <Link href="/contact" className="hvacseo-btn-p">Request a Free HVAC Audit <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><path d="M5 12h14M12 5l7 7-7 7"/></svg></Link>
              <Link href="/lawn-care-marketing-services" className="hvacseo-btn-s">Lawn Care Marketing</Link>
            </div>
          </div>
        </section>
      </div>
    </>
  );
}
