'use client';
import { useState, useEffect, useRef } from 'react';
import Head from 'next/head';
import Link from 'next/link';

const SCHEMA = {
  '@context': 'https://schema.org',
  '@graph': [
    { '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Home', item: 'https://www.1solutions.biz/' }, { '@type': 'ListItem', position: 2, name: 'IT Staff Augmentation Services', item: 'https://www.1solutions.biz/it-staff-augmentation-services/' }] },
    { '@type': 'Service', name: 'IT Staff Augmentation Services', url: 'https://www.1solutions.biz/it-staff-augmentation-services/', description: '1Solutions IT staff augmentation — add pre-vetted frontend, backend, full-stack, mobile, DevOps, QA, and AI/ML developers to your existing engineering team in 5–7 business days. Offshore staff augmentation at 60–70% below US/UK hiring costs, with no recruitment fee or employer liability.', provider: { '@type': 'Organization', name: '1Solutions', url: 'https://www.1solutions.biz', logo: { '@type': 'ImageObject', url: 'https://www.1solutions.biz/images/1solutions-logo.png' }, foundingDate: '2008', areaServed: ['US', 'GB', 'AU', 'CA', 'IN'] }, aggregateRating: { '@type': 'AggregateRating', ratingValue: '4.9', reviewCount: '98', bestRating: '5' } },
    { '@type': 'FAQPage', mainEntity: [
      { '@type': 'Question', name: 'What is IT staff augmentation?', acceptedAnswer: { '@type': 'Answer', text: 'IT staff augmentation is a flexible hiring model where you add external software engineers or IT specialists directly to your existing in-house team — working in your tools (Jira, GitHub, Slack), attending your standups, and operating under your direct management and processes. Unlike project outsourcing (where you hand a deliverable to an external vendor and receive the result), staff augmentation means the developer is embedded in your team exactly like an employee — but without the overhead of permanent hiring. It is the model of choice when you need to: add a specific technical skill your team lacks (e.g. a Kubernetes specialist, a React Native developer, a data scientist); increase team velocity during a peak delivery period; cover for a maternity or medical leave; or evaluate a technology or role before committing to a full-time hire.' } },
      { '@type': 'Question', name: 'What is the difference between staff augmentation and managed services or outsourcing?', acceptedAnswer: { '@type': 'Answer', text: 'Staff augmentation: you manage the developer directly. They join your team, use your tools, follow your processes, attend your planning sessions. You have full control and visibility. The developer is an extension of your team. Managed services / outsourcing: you hand a scope or function to a vendor who manages the delivery internally. You interact with a project manager or account manager, not individual developers. You have less day-to-day control but less management overhead. The right choice depends on your management capacity: if you have a strong engineering manager and clear processes, staff augmentation gives you the most control and the most cost efficiency. If you do not have engineering management capacity to onboard and direct individual developers, managed services or a dedicated team with its own PM is a better fit.' } },
      { '@type': 'Question', name: 'How quickly can an augmented developer join my team?', acceptedAnswer: { '@type': 'Answer', text: 'In most cases, an augmented developer can join your team within 5–7 business days from the time you approve a candidate. The process: requirements to shortlist takes 24–48 hours; technical interview takes 1–2 days (your schedule permitting); contract takes 1–2 days; onboarding and access provisioning takes 1–2 days. In urgent cases (e.g. a production incident requiring a specialist, a hard project deadline approaching) we can shortlist within 4–6 hours from our bench of immediately available, pre-vetted developers and complete onboarding in 3–4 days. We maintain a ready bench of the most commonly requested roles — React, Node.js, Python, DevOps, React Native — specifically to support rapid placement.' } },
      { '@type': 'Question', name: 'Do I manage the augmented developer directly?', acceptedAnswer: { '@type': 'Answer', text: 'Yes. In staff augmentation you are the direct manager. The augmented developer attends your standups, picks up tasks from your sprint board, submits pull requests to your repositories, and is accountable to your engineering manager or tech lead. They do not have a separate project manager from our side managing their daily work — that is your responsibility. We provide: pre-vetting (so you are not managing a weak hire), a dedicated client success manager as an escalation point for HR or contract issues, monthly check-ins to assess performance and flag any concerns, and replacement within 5 days if the fit is not right. Think of us as the HR and legal infrastructure, while you provide the engineering management.' } },
      { '@type': 'Question', name: 'What roles can be augmented through 1Solutions?', acceptedAnswer: { '@type': 'Answer', text: 'Frontend developers (React, Next.js, Angular, Vue.js, TypeScript); backend developers (Node.js, Python/Django/FastAPI, PHP/Laravel, Java/Spring Boot, .NET/C#, Go, Ruby on Rails); full-stack developers (most frontend + backend combinations); mobile developers (React Native, Flutter, Swift/iOS, Kotlin/Android); DevOps and cloud engineers (AWS, Azure, GCP, Kubernetes, Terraform, CI/CD); QA engineers (manual testing, Selenium/Cypress/Playwright automation, Appium for mobile, k6/Locust for performance); data engineers (dbt, Spark, Airflow, BigQuery, Snowflake, Redshift); data scientists (Python ML, statistical analysis, A/B testing); AI/ML developers (PyTorch, TensorFlow, LangChain, RAG pipelines); and software architects.' } },
      { '@type': 'Question', name: 'How do you ensure the quality of augmented developers?', acceptedAnswer: { '@type': 'Answer', text: 'Every developer in our augmentation pool has passed: a technical coding assessment in their primary language (algorithm problem-solving, data structure knowledge, language-specific idiom quality); a system design or architecture interview for senior roles; a project-specific assessment for specialised roles (e.g. a smart contract developer completes a Solidity challenge, a ML engineer implements a classification pipeline); an English communication assessment (written and spoken, assessed by an experienced interviewer); and a reference check from a previous client engagement. The internal pass rate is approximately 15–20% — most candidates who apply are not shortlisted. When we send you a shortlist, every profile has already passed our bar.' } },
      { '@type': 'Question', name: 'What happens if the augmented developer is not the right fit?', acceptedAnswer: { '@type': 'Answer', text: 'We offer a 5-business-day replacement guarantee — if a developer is not working out within the first 4 weeks (technical skill gap, communication issues, cultural fit), we replace them within 5 business days at no additional cost. After 4 weeks, a 2-week transition period applies where the new candidate overlaps with the departing developer to transfer context. We find that most fit issues surface in the first 2 weeks of the sprint cycle, which is why we encourage clients to assign a real sprint task in week one rather than spending the first week on onboarding documentation. A real task reveals skill level, communication style, and proactivity faster than any interview.' } },
      { '@type': 'Question', name: 'Is staff augmentation cheaper than hiring locally?', acceptedAnswer: { '@type': 'Answer', text: 'Yes — significantly. A senior full-stack developer in San Francisco costs $160,000–$200,000 in salary plus 30–40% in employer taxes, benefits, and equity, totalling $210,000–$280,000 all-in per year. The same profile through our staff augmentation service costs $30,000–$55,000 per year all-inclusive — a saving of $160,000–$220,000 per developer per year. For a team of 5 augmented developers, the annual saving is $800,000–$1,100,000. In the UK and Australia, comparable savings apply. The cost saving is on labour only — we do not cut corners on seniority or technical quality.' } },
    ] },
  ],
};

const SERVICES = [
  { n: '01', title: 'Frontend Developer Augmentation', desc: 'Add React, Next.js, Angular, Vue.js, or TypeScript specialists to your frontend team — component library development, performance optimisation, accessibility (WCAG 2.2), micro-frontend architecture, state management (Redux, Zustand, TanStack Query), testing (Vitest, Playwright), and CI/CD-integrated build pipelines. Available in 5–7 days for a single developer or 2–3 weeks for a team of 3–5.' },
  { n: '02', title: 'Backend Developer Augmentation', desc: 'Node.js, Python (Django/FastAPI), PHP (Laravel), Java (Spring Boot), .NET/C#, Go, or Ruby on Rails backend specialists — REST and GraphQL API development, database architecture (PostgreSQL, MySQL, MongoDB), microservices, message queuing (Kafka, RabbitMQ, SQS), authentication (OAuth2, JWT), and backend performance optimisation. Senior engineers available for immediate augmentation.', feat: true },
  { n: '03', title: 'Full-Stack Developer Augmentation', desc: 'Full-stack developers spanning frontend (React/Next.js, Angular) and backend (Node.js, Python, PHP) — end-to-end feature ownership from UI component to database query. Ideal for smaller teams where a single developer needs to cover the full stack, or for product teams building new features rapidly without handoff overhead between frontend and backend specialists.' },
  { n: '04', title: 'Mobile Developer Augmentation', desc: 'React Native and Flutter cross-platform specialists, native iOS (Swift/SwiftUI) developers, and native Android (Kotlin/Jetpack Compose) developers — feature development, performance optimisation, app store submission compliance, push notifications, offline-first architecture, deep linking, and in-app purchase integration. Available for consumer apps, enterprise mobile, and healthcare or fintech regulated environments.' },
  { n: '05', title: 'DevOps & Cloud Engineer Augmentation', desc: 'AWS, Azure, and GCP cloud engineers, Kubernetes specialists, Terraform infrastructure-as-code developers, and CI/CD pipeline engineers — embedded in your team to manage cloud infrastructure, implement GitOps, automate deployments, set up monitoring (Prometheus, Grafana, Datadog), and reduce cloud costs. DevOps augmentation is the fastest way to add production operations expertise without a permanent hire.' },
  { n: '06', title: 'QA Engineer Augmentation', desc: 'Manual QA engineers for functional, regression, and exploratory testing, and automation engineers for Cypress, Playwright, Selenium, Appium (mobile), k6 or Locust (performance), and Postman/REST-assured (API) test suites. QA augmentation is particularly valuable before major releases, during scaling periods, or when introducing a new product line that the existing QA coverage does not cover.' },
  { n: '07', title: 'Data Engineer Augmentation', desc: 'dbt, Apache Spark, Airflow, Prefect, Airbyte/Fivetran, and warehouse-native SQL specialists — building and maintaining data pipelines, transformation layers, and analytics infrastructure on Snowflake, BigQuery, Redshift, or Databricks. Data engineering augmentation is ideal for product-led companies where the analytics team is growing faster than the engineering team that maintains the data infrastructure.' },
  { n: '08', title: 'AI / ML Developer Augmentation', desc: 'Machine learning engineers and AI developers for LLM integration (OpenAI, Anthropic, Gemini API), RAG pipeline development (LangChain, LlamaIndex, vector databases), computer vision (YOLOv8, OpenCV), NLP, and classical ML (scikit-learn, XGBoost). AI augmentation is valuable for product teams adding AI features — chat assistants, semantic search, document processing, recommendation systems — without hiring a full ML team.' },
  { n: '09', title: 'Software Architect Augmentation', desc: 'Senior software architects available on a part-time or full-time basis — system design review, microservices decomposition, API design standards, database schema review, technology selection, performance architecture, cloud cost optimisation design, and architecture documentation. Architect augmentation is ideal for scale-ups that have outgrown their founding architecture and need senior design capacity without a full-time VP Engineering hire.' },
  { n: '10', title: 'Tech Lead & Engineering Manager Augmentation', desc: 'Experienced tech leads and engineering managers for interim or long-term augmentation — sprint facilitation, code review culture, technical roadmap ownership, team productivity improvement, and developer mentoring. Tech lead augmentation bridges the gap between individual contributor senior engineers and formal engineering management, and is particularly valuable during team scaling or leadership transition periods.' },
];

const TECH_STACK = [
  { group: 'Frontend', color: '#4338ca', items: ['React / Next.js', 'Angular 17+', 'Vue.js 3', 'TypeScript', 'Tailwind / CSS-in-JS', 'Storybook / Chromatic'] },
  { group: 'Backend', color: '#0369a1', items: ['Node.js / Express / NestJS', 'Python / Django / FastAPI', 'PHP / Laravel', 'Java / Spring Boot', '.NET / C#', 'Go / Ruby on Rails'] },
  { group: 'Mobile', color: '#0f766e', items: ['React Native / Expo', 'Flutter / Dart', 'Swift / SwiftUI (iOS)', 'Kotlin / Jetpack (Android)', 'Capacitor', 'Firebase / OneSignal'] },
  { group: 'DevOps & Cloud', color: '#b45309', items: ['AWS / Azure / GCP', 'Kubernetes / Helm / ArgoCD', 'Terraform / Pulumi', 'GitHub Actions / GitLab CI', 'Prometheus / Grafana / Datadog', 'Docker / containerd'] },
  { group: 'Database & Storage', color: '#7e22ce', items: ['PostgreSQL / MySQL', 'MongoDB / DynamoDB', 'Redis / Valkey', 'Elasticsearch / OpenSearch', 'Snowflake / BigQuery', 'Supabase / Firebase'] },
  { group: 'QA & Testing', color: '#dc2626', items: ['Cypress / Playwright', 'Selenium / Appium', 'Jest / Vitest / Pytest', 'k6 / Locust (perf)', 'Postman / REST-assured', 'SonarQube / Trivy'] },
  { group: 'Data Engineering', color: '#059669', items: ['dbt (transformations)', 'Apache Spark / PySpark', 'Airflow / Prefect', 'Airbyte / Fivetran', 'BigQuery / Redshift / Snowflake', 'Kafka / Kinesis'] },
  { group: 'AI / ML', color: '#c2185b', items: ['LangChain / LlamaIndex', 'OpenAI / Anthropic API', 'PyTorch / TensorFlow', 'scikit-learn / XGBoost', 'Pinecone / Weaviate / pgvector', 'MLflow / BentoML'] },
];

const ENGAGEMENT_MODELS = [
  { id: 'fulltime', name: 'Full-Time Augmented Developer', badge: 'Most Popular', badgeColor: '#D97706', feat: true, icon: 'M16 11c1.66 0 2.99-1.34 2.99-3S17.66 5 16 5c-1.66 0-3 1.34-3 3s1.34 3 3 3zm-8 0c1.66 0 2.99-1.34 2.99-3S9.66 5 8 5C6.34 5 5 6.34 5 8s1.34 3 3 3zm0 2c-2.33 0-7 1.17-7 3.5V19h14v-2.5c0-2.33-4.67-3.5-7-3.5zm8 0c-.29 0-.62.02-.97.05 1.16.84 1.97 1.97 1.97 3.45V19h6v-2.5c0-2.33-4.67-3.5-7-3.5z', headline: '160 hrs/month — a dedicated engineer in your team.', desc: 'One or more full-time augmented developers working exclusively in your team — 160 hours per month, integrated into your sprint cycle, committing to your repositories, and attending your standups. You manage them directly. 60–70% below equivalent local hiring cost.', bestFor: ['Adding a specific technology specialist your team lacks', 'Scaling engineering capacity without 3–6 month local hiring timeline', 'Covering maternity, medical, or notice-period gaps in your team', 'Long-term product development at offshore economics'], process: 'Role definition → shortlist 24–48 hrs → technical interview → start in 5–7 days', timeline: 'Available within 5–7 business days' },
  { id: 'parttime', name: 'Part-Time Augmented Developer', badge: 'Flexible', badgeColor: '#4338ca', icon: 'M11.99 2C6.47 2 2 6.48 2 12s4.47 10 9.99 10C17.52 22 22 17.52 22 12S17.52 2 11.99 2zM12 20c-4.42 0-8-3.58-8-8s3.58-8 8-8 8 3.58 8 8-3.58 8-8 8zm.5-13H11v6l5.25 3.15.75-1.23-4.5-2.67V7z', headline: '80 hrs/month — specialist access without full-time commitment.', desc: 'A part-time augmented developer working 80 hours per month — half of a full-time engagement. Ideal for adding specialist expertise (architect review, DevOps support, QA automation) that does not need a full-time commitment, or for evaluating a developer before converting to full-time.', bestFor: ['DevOps or cloud specialist for 20 hrs/week platform management', 'QA engineer augmenting a team that does not need full-time QA', 'Software architect for part-time design and review work', 'Evaluation period before committing to a full-time augmentation'], process: 'Role definition → shortlist → interview → start in 5–7 days', timeline: 'Available within 5–7 business days' },
  { id: 'team', name: 'Augmented Squad (3–8 Developers)', badge: 'Scale Fast', badgeColor: '#0369a1', icon: 'M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm-7 3c1.93 0 3.5 1.57 3.5 3.5S13.93 13 12 13s-3.5-1.57-3.5-3.5S10.07 6 12 6zm7 13H5v-.23c0-.62.28-1.2.76-1.58C7.47 15.82 9.64 15 12 15s4.53.82 6.24 2.19c.48.38.76.97.76 1.58V19z', headline: 'An augmented squad of 3–8 specialists embedded in your team.', desc: 'Multiple augmented developers placed simultaneously — a React + Node.js + DevOps trio, a mobile squad of 4 (iOS + Android + React Native + QA), or a data team (data engineer + ML developer + analyst). Squad staffing takes 2–3 weeks but delivers significant velocity increase from day one.', bestFor: ['Post-funding scale-up needing to ship a 6-month roadmap in 3 months', 'Enterprise digital transformation with multiple parallel workstreams', 'Product relaunch requiring simultaneous frontend, backend, and mobile work', 'Replacing a departing engineering team with minimum delivery disruption'], process: 'Team composition → parallel shortlisting → interviews → start in 2–3 weeks', timeline: 'Squad of 3–5 available in 2–3 weeks' },
];

const PROCESS_STEPS = [
  { num: '01', title: 'Define the Role and Skills Required', desc: 'Tell us the exact skill set you need — primary language or framework, seniority level (junior, mid, senior, staff/principal), domain experience (fintech, healthtech, e-commerce), and any specific libraries or tools the developer must know. Also tell us about your team: stack, size, sprint cadence, and communication style. The more specific, the faster and more accurate the shortlist.' },
  { num: '02', title: 'Receive a Shortlist Within 24–48 Hours', desc: 'Within 24–48 business hours we send 2–4 pre-vetted developer profiles matched to your exact requirements — with CV, portfolio, years of experience per technology, and client references from similar team augmentation engagements. Not a database dump — a curated shortlist from our active developer pool who have already passed our technical and communication assessments.' },
  { num: '03', title: 'Technical Interview in Your Format', desc: 'Interview candidates using your preferred format — coding challenge (LeetCode-style or take-home project), live coding session, system design discussion, architecture whiteboard, or code review exercise. You choose the format and set the bar. Our developers are experienced with technical interviews from US and UK engineering teams and can typically do same-week interviews.' },
  { num: '04', title: 'Onboarding to Your Tools and Processes', desc: 'Once a candidate is selected, we complete the contractual and offshore-side onboarding within 2–3 days: NDA, contract, equipment, security setup, and VPN if required. We provision the developer with access to your GitHub/GitLab, Jira/Linear, Slack/Teams, and any other tools. We recommend a structured first-sprint onboarding task — a real, bounded feature or bug fix — rather than documentation review.' },
  { num: '05', title: 'Integrated Sprint Delivery', desc: 'The augmented developer joins your sprint from day one — daily standup, sprint planning, code review, and retrospective. All PRs go through your review process. Velocity is typically at 60–70% for the first sprint (ramp-up) and reaches full productivity by sprint 2–3. We conduct a 2-week check-in to confirm fit and address any early concerns before they become issues.' },
  { num: '06', title: 'Ongoing Performance & Scaling', desc: 'Monthly performance check-ins with your engineering manager and the developer. Quarterly business reviews to assess fit, velocity, and whether to add more augmented roles. If you need to scale down — a sprint velocity drop, a product pivot, a funding gap — we can reduce team size within 30 days notice. No long-term lock-in beyond the notice period in the contract.' },
];

const TESTIMONIALS = [
  { text: "We needed a senior React Native developer immediately — our lead mobile developer resigned 3 weeks before an app store submission deadline. 1Solutions shortlisted 3 candidates within 6 hours. We interviewed and selected the same day. The developer was onboarded and committed to our repository within 4 days. We hit the submission deadline. He is still with us 14 months later.", name: 'Sarah M.', role: 'Head of Engineering, Consumer App (UK)', init: 'SM', bg: '#1a0030' },
  { text: "We augmented with a Python FastAPI backend developer and a Kubernetes DevOps engineer simultaneously. Both were working in our Jira and GitHub within 6 days of the initial request. Code quality on both was equivalent to our senior in-house developers — rigorous pull request culture, proactive communication, and solid judgment on architectural trade-offs. The cost saving vs UK market rates is 65%.", name: 'Thomas K.', role: 'CTO, B2B SaaS (AU)', init: 'TK', bg: '#0a2a1a', feat: true },
  { text: "We added a QA automation engineer through 1Solutions to build our Playwright test suite before a major platform migration. He delivered 340 end-to-end tests covering our critical user journeys in 8 weeks. Zero regressions were shipped during the migration — a first for us. We extended the augmentation contract to ongoing QA maintenance at a fraction of what a local QA hire would cost.", name: 'Rachel B.', role: 'VP Product, E-Commerce Platform (US)', init: 'RB', bg: '#1e3a5f' },
];

const WHY_CARDS = [
  { title: 'Available in 5–7 Business Days', desc: 'Most augmented developers are onboarded and making their first commits within 5–7 business days from your initial request — faster than a local job posting gets its first qualified applicant. We maintain a ready bench of the most commonly requested roles.' },
  { title: '60–70% Below Local Hiring Cost', desc: 'Staff augmentation through 1Solutions costs 60–70% less than an equivalent local hire — with no recruitment fee, employer payroll taxes, benefits, equity, or office space. The developer is as capable; the employment overhead is ours.' },
  { title: 'You Manage Directly', desc: 'Augmented developers work in your tools, under your management. No vendor project manager between you and the developer. Full transparency — you see every commit, every PR, every Jira ticket.' },
  { title: '5-Day Replacement Guarantee', desc: 'If a developer does not meet your bar within the first 4 weeks, we replace within 5 business days at no cost. After that, a 2-week overlap transition applies. Fit risk is ours, not yours.' },
  { title: 'Pre-Vetted, Not Random', desc: 'Every profile shortlisted has already passed: a technical coding assessment, a system design interview (for senior roles), an English communication evaluation, and a reference check from a previous client engagement.' },
  { title: 'No Lock-In', desc: '30-day notice period to scale down or exit the engagement. No long-term minimum contract beyond the initial 3-month stabilisation period. You can scale up or down as your sprint velocity and product roadmap change.' },
  { title: 'Full Timezone Flexibility', desc: 'IST provides 4–5 hours of daily overlap with US timezones and 4.5 hours with UK and Europe — enough for a standup, code review, and same-day feedback loop. Extended shift hours available for early US West Coast overlap.' },
  { title: 'Any Role, Any Stack', desc: 'Frontend, backend, full-stack, mobile, DevOps, QA, data engineering, AI/ML, software architect, tech lead — single developers or squads. If we do not have the exact profile on the bench, we source from our extended vetted network.' },
];

const FAQS = [
  { q: 'What is IT staff augmentation?', a: 'IT staff augmentation adds external software developers directly to your existing team — working in your tools, attending your standups, under your direct management. Unlike outsourcing, you retain full control. Unlike permanent hiring, there is no 3–6 month recruitment timeline or employer overhead.' },
  { q: 'What is the difference between staff augmentation and outsourcing?', a: 'Staff augmentation: you manage the developer directly in your tools and processes. Outsourcing: you hand a scope or function to a vendor who manages delivery internally. Augmentation gives you maximum control and transparency; outsourcing reduces your management overhead. Choose augmentation if you have engineering management capacity; choose outsourcing or a dedicated team if you do not.' },
  { q: 'How quickly can an augmented developer join my team?', a: 'Most augmented developers are onboarded within 5–7 business days from your initial request. In urgent cases we can shortlist from our ready bench within 4–6 hours and complete onboarding in 3–4 days.' },
  { q: 'Do I manage the developer directly?', a: 'Yes. You are the direct manager. The developer attends your standups, picks up sprint tasks from your board, and submits PRs to your repositories. We provide pre-vetting, a client success manager for HR/contract issues, and replacement within 5 days if the fit is wrong.' },
  { q: 'What roles can be augmented?', a: 'Frontend (React, Angular, Vue), backend (Node.js, Python, PHP, Java, .NET, Go), full-stack, mobile (React Native, Flutter, Swift, Kotlin), DevOps/cloud, QA (manual + automation), data engineering, AI/ML, software architect, and tech lead.' },
  { q: 'Is staff augmentation cheaper than hiring locally?', a: 'Yes — 60–70% cheaper. A senior developer costs $210,000–$280,000/year all-in in San Francisco. The same profile through 1Solutions staff augmentation costs $30,000–$55,000/year all-inclusive. For a 5-developer augmented team, the annual saving is $800,000–$1,100,000.' },
  { q: 'What happens if the developer is not the right fit?', a: 'We replace within 5 business days at no additional cost within the first 4 weeks. After 4 weeks, a 2-week overlap transition applies. We find that most fit issues surface in the first sprint — which is why we recommend assigning a real task in week one.' },
  { q: 'What is the minimum engagement period?', a: 'We recommend a 3-month minimum to allow for onboarding ramp-up and full productivity measurement. After 3 months, the engagement is month-to-month with 30 days notice to scale down or exit. No long-term lock-in.' },
];

function useCountUp(target, duration = 1800, start = false) {
  const [count, setCount] = useState(0);
  useEffect(() => { if (!start) return; const num = parseInt(target.replace(/\D/g, ''), 10); if (!num) return; let t0 = null; const step = ts => { if (!t0) t0 = ts; const p = Math.min((ts - t0) / duration, 1); setCount(Math.floor((1 - Math.pow(1 - p, 3)) * num)); if (p < 1) requestAnimationFrame(step); }; requestAnimationFrame(step); }, [start, target, duration]);
  return count;
}
function StatItem({ label, val, started }) {
  const num = useCountUp(val, 1800, started);
  const suffix = val.replace(/[\d,]/g, '');
  return (<div className="isa-sc"><div className="isa-sv">{started ? (val.includes(',') ? num.toLocaleString() : num) + suffix : val}</div><div className="isa-sl">{label}</div></div>);
}

export default function ITStaffAugmentation() {
  const [showAll, setShowAll] = useState(false);
  const [openFaq, setOpenFaq] = useState(0);
  const [ss, setSs] = useState(false);
  const [vis, setVis] = useState(new Set());
  const [vSk, setVSk] = useState([]); const [vEn, setVEn] = useState([]); const [vWh, setVWh] = useState([]); const [vTe, setVTe] = useState([]); const [vSt, setVSt] = useState([]);
  const stR = useRef(null); const secR = useRef({});
  const skR = useRef(null); const enR = useRef(null); const whR = useRef(null); const teR = useRef(null); const stGr = useRef(null);
  useEffect(() => { if (!stR.current) return; const o = new IntersectionObserver(([e]) => { if (e.isIntersecting) { setSs(true); o.disconnect(); } }, { threshold: 0.4 }); o.observe(stR.current); return () => o.disconnect(); }, []);
  useEffect(() => { const pairs = [[skR, SERVICES.length, setVSk],[enR, 3, setVEn],[whR, WHY_CARDS.length, setVWh],[teR, 3, setVTe],[stGr, TECH_STACK.length, setVSt]]; const obs = pairs.map(([ref, count, setter]) => { if (!ref.current) return null; const o = new IntersectionObserver(([e]) => { if (e.isIntersecting) { Array.from({ length: count }, (_, i) => setTimeout(() => setter(p => p.includes(i) ? p : [...p, i]), i * 80)); o.disconnect(); } }, { threshold: 0.05 }); o.observe(ref.current); return o; }); return () => obs.forEach(o => o?.disconnect()); }, []);
  useEffect(() => { const ks = Object.keys(secR.current); const obs = ks.map(k => { const el = secR.current[k]; if (!el) return null; const o = new IntersectionObserver(([e]) => { if (e.isIntersecting) { setVis(p => new Set([...p, k])); o.disconnect(); } }, { threshold: 0.1 }); o.observe(el); return o; }); return () => obs.forEach(o => o?.disconnect()); }, []);
  const visServices = showAll ? SERVICES : SERVICES.slice(0, 6);
  return (
    <>
      <Head>
        <title>IT Staff Augmentation Services | Add Developers in 5–7 Days | 1Solutions</title>
        <meta name="description" content="IT staff augmentation services — add pre-vetted frontend, backend, mobile, DevOps, QA, and AI/ML developers to your team in 5–7 business days. 60–70% below US/UK hiring cost. No recruitment fee or employer liability." />
        <link rel="canonical" href="https://www.1solutions.biz/it-staff-augmentation-services/" />
        <meta property="og:title" content="IT Staff Augmentation Services | 1Solutions" />
        <meta property="og:description" content="Add pre-vetted offshore developers to your team in 5–7 days. Frontend, backend, mobile, DevOps, QA, AI/ML. 60–70% below local hiring costs." />
        <meta property="og:url" content="https://www.1solutions.biz/it-staff-augmentation-services/" />
        <meta property="og:image" content="https://www.1solutions.biz/images/banner-1sol.jpg" />
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(SCHEMA) }} />
        <style>{`
          .isa-page{font-family:'Inter',-apple-system,BlinkMacSystemFont,sans-serif;background:linear-gradient(135deg,#eef2ff 0%,#e0e7ff 20%,#f5f3ff 50%,#fef3c7 75%,#f0f9ff 100%);color:#1e1b4b;line-height:1.6;position:relative;overflow-x:hidden}
          .isa-page *,.isa-page *::before,.isa-page *::after{box-sizing:border-box}
          .isa-orb{position:absolute;border-radius:50%;pointer-events:none;z-index:0;filter:blur(20px)}
          .isa-o1{width:860px;height:860px;background:radial-gradient(circle,rgba(67,56,202,.20) 0%,rgba(99,102,241,.08) 40%,transparent 70%);top:-260px;right:-240px}
          .isa-o2{width:760px;height:760px;background:radial-gradient(circle,rgba(217,119,6,.15) 0%,rgba(251,191,36,.06) 40%,transparent 70%);bottom:0;left:-220px}
          .isa-o3{width:520px;height:520px;background:radial-gradient(circle,rgba(109,40,217,.12) 0%,transparent 70%);top:44%;left:-100px;transform:translateY(-50%)}
          .isa-bc{position:relative;z-index:2;padding:16px 40px 0;max-width:1440px;margin:0 auto}
          .isa-bc ol{display:flex;flex-wrap:wrap;gap:6px;list-style:none;margin:0;padding:0;font-size:13px;color:#6366f1}
          .isa-bc li{display:flex;align-items:center;gap:6px}
          .isa-bc li::after{content:'/';opacity:.45}
          .isa-bc li:last-child::after{display:none}
          .isa-bc a{color:#1e1b4b;text-decoration:none}
          .isa-hero{position:relative;z-index:2;text-align:center;max-width:960px;margin:0 auto;padding:44px 40px 32px}
          .isa-ey{display:block;font-size:11px;font-weight:700;letter-spacing:2.5px;text-transform:uppercase;color:#4338ca;margin-bottom:14px}
          .isa-hero h1{font-size:50px;font-weight:900;line-height:1.09;letter-spacing:-1.5px;margin-bottom:16px;background:linear-gradient(90deg,#1e1b4b 0%,#4338ca 100%);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text}
          .isa-desc{font-size:16px;color:#3730a3;line-height:1.65;max-width:740px;margin:0 auto 24px}
          .isa-tr{display:flex;flex-wrap:wrap;justify-content:center;gap:10px;margin-bottom:26px}
          .isa-badge{display:inline-flex;align-items:center;gap:6px;background:rgba(255,255,255,.60);backdrop-filter:blur(10px);border:1px solid rgba(255,255,255,.85);border-radius:100px;padding:6px 14px;font-size:12px;font-weight:600;color:#1e1b4b;box-shadow:0 2px 8px rgba(30,27,75,.07)}
          .isa-dot{width:7px;height:7px;border-radius:50%;background:#4338ca;flex-shrink:0}
          .isa-ctas{display:flex;flex-wrap:wrap;gap:12px;justify-content:center}
          .isa-p{display:inline-block;padding:14px 36px;background:#4338ca;color:#fff;border-radius:50px;font-weight:700;font-size:15px;text-decoration:none;transition:all .25s;box-shadow:0 6px 24px rgba(67,56,202,.28)}
          .isa-p:hover{background:#1e1b4b;transform:translateY(-2px)}
          .isa-g{display:inline-block;padding:14px 36px;background:rgba(255,255,255,.55);backdrop-filter:blur(16px);border:1.5px solid rgba(255,255,255,.85);border-radius:50px;color:#1e1b4b;font-weight:700;font-size:15px;text-decoration:none;transition:all .25s}
          .isa-g:hover{background:rgba(255,255,255,.85);border-color:rgba(67,56,202,.5);transform:translateY(-2px)}
          .isa-stats{position:relative;z-index:2;display:grid;grid-template-columns:repeat(4,1fr);max-width:940px;margin:28px auto 0;background:rgba(255,255,255,.45);backdrop-filter:blur(24px);border:1px solid rgba(255,255,255,.85);box-shadow:0 4px 24px rgba(30,27,75,.08),inset 0 1px 0 rgba(255,255,255,.95)}
          .isa-sc{padding:18px 16px;text-align:center;border-right:1px solid rgba(30,27,75,.10)}
          .isa-sc:last-child{border-right:none}
          .isa-sv{font-size:28px;font-weight:900;color:#4338ca;letter-spacing:-.5px;line-height:1}
          .isa-sl{font-size:11px;color:#4338ca;font-weight:500;margin-top:5px;opacity:.7}
          .isa-logos{position:relative;z-index:2;padding:24px 40px 52px;display:flex;flex-direction:column;align-items:center;gap:14px}
          .isa-ll{font-size:10px;font-weight:700;letter-spacing:2px;text-transform:uppercase;color:#6366f1}
          .isa-lw{width:100%;overflow:hidden}
          .isa-lt{display:flex;align-items:center;gap:60px;width:max-content;animation:isa-mq 28s linear infinite}
          .isa-lt:hover{animation-play-state:paused}
          @keyframes isa-mq{0%{transform:translateX(0)}100%{transform:translateX(-50%)}}
          .isa-cl{height:24px;width:auto;max-width:110px;object-fit:contain;filter:grayscale(100%);opacity:.45;transition:opacity .25s,filter .25s}
          .isa-cl:hover{opacity:.85;filter:grayscale(0%)}
          .isa-sey{font-size:11px;font-weight:700;letter-spacing:2px;text-transform:uppercase;color:#D97706;margin-bottom:10px;display:block}
          .isa-st{font-size:46px;font-weight:900;line-height:1.12;letter-spacing:-1px;background:linear-gradient(90deg,#1e1b4b 0%,#D97706 100%);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;margin-bottom:10px}
          .isa-sd{font-size:15px;color:#4338ca;opacity:.8;line-height:1.7}
          .isa-rv{opacity:0;transform:translateY(44px);transition:opacity .7s cubic-bezier(0.22,1,.36,1),transform .7s cubic-bezier(0.22,1,.36,1)}
          .isa-rv.isa-ok{opacity:1;transform:translateY(0)}
          .isa-in{max-width:1300px;margin:0 auto}
          .isa-sk-s{background:transparent;padding:72px 40px 60px;position:relative;z-index:1}
          .isa-sk-g{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-top:40px}
          .isa-sk-c{background:linear-gradient(135deg,rgba(238,242,255,.50) 0%,rgba(255,255,255,.85) 55%,rgba(224,231,255,.40) 100%);backdrop-filter:blur(16px);border:1px solid rgba(255,255,255,.85);border-radius:20px;padding:26px 22px 22px;position:relative;overflow:hidden;box-shadow:0 4px 24px rgba(30,27,75,.08),inset 0 1px 0 rgba(255,255,255,.95);opacity:0;transform:translateY(36px);transition:opacity .6s cubic-bezier(0.22,1,.36,1),transform .6s cubic-bezier(0.22,1,.36,1),border-color .2s}
          .isa-sk-c.isa-cv{opacity:1;transform:translateY(0)}
          .isa-sk-c.isa-cv:hover{transform:translateY(-6px);border-color:rgba(67,56,202,.30);box-shadow:0 16px 48px rgba(30,27,75,.14)}
          .isa-sk-c.feat{border-color:rgba(67,56,202,.20)}
          .isa-sk-n{position:absolute;top:8px;right:14px;font-size:72px;font-weight:900;line-height:1;color:#1e1b4b;opacity:.055;pointer-events:none;letter-spacing:-4px;user-select:none}
          .isa-sk-c h3{font-size:16px;font-weight:700;color:#1e1b4b;margin:0 0 8px;position:relative;z-index:1}
          .isa-sk-c p{font-size:13px;color:#3730a3;opacity:.8;line-height:1.65;margin:0;position:relative;z-index:1}
          .isa-sk-c::before{content:'';position:absolute;left:0;top:12%;height:76%;width:3px;background:linear-gradient(180deg,#4338ca,#6366f1);border-radius:0 2px 2px 0;transform:scaleY(0);transform-origin:top center;transition:transform .3s cubic-bezier(0.22,1,.36,1)}
          .isa-sk-c.isa-cv:hover::before{transform:scaleY(1)}
          .isa-sm{text-align:center;margin-top:22px}
          .isa-bm{display:inline-block;background:#fff;border:1.5px solid rgba(30,27,75,.18);color:#1e1b4b;padding:10px 30px;border-radius:20px;font-weight:600;font-size:14px;cursor:pointer;transition:all .2s;font-family:inherit}
          .isa-bm:hover{background:#1e1b4b;border-color:#1e1b4b;color:#fff;transform:translateY(-2px)}
          .isa-tec-s{background:#f5f4ff;border-top:1px solid rgba(30,27,75,.08);border-bottom:1px solid rgba(30,27,75,.08);padding:72px 40px;position:relative;z-index:1}
          .isa-tec-g{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin-top:40px}
          .isa-tec-c{background:linear-gradient(135deg,rgba(238,242,255,.50) 0%,rgba(255,255,255,.85) 55%,rgba(224,231,255,.40) 100%);backdrop-filter:blur(16px);border:1px solid rgba(255,255,255,.85);border-radius:20px;padding:22px 20px;box-shadow:0 4px 24px rgba(30,27,75,.08),inset 0 1px 0 rgba(255,255,255,.95);opacity:0;transform:translateY(32px);transition:opacity .55s cubic-bezier(0.22,1,.36,1),transform .55s cubic-bezier(0.22,1,.36,1),border-color .2s}
          .isa-tec-c.isa-sv2{opacity:1;transform:translateY(0)}
          .isa-tec-c.isa-sv2:hover{border-color:rgba(67,56,202,.25);box-shadow:0 14px 40px rgba(30,27,75,.12)}
          .isa-tg{font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:1.2px;margin-bottom:12px;padding-bottom:8px;border-bottom:2px solid}
          .isa-pills{display:flex;flex-wrap:wrap;gap:6px}
          .isa-pill{display:inline-block;font-size:11.5px;font-weight:500;padding:4px 10px;border-radius:100px;border:1px solid}
          .isa-en-s{padding:80px 40px;position:relative;z-index:1}
          .isa-en-g{display:grid;grid-template-columns:repeat(3,1fr);gap:20px;margin-top:40px}
          .isa-en-c{background:linear-gradient(135deg,rgba(238,242,255,.50) 0%,rgba(255,255,255,.85) 55%,rgba(224,231,255,.40) 100%);backdrop-filter:blur(16px);border:1px solid rgba(255,255,255,.85);border-radius:24px;padding:32px 28px;box-shadow:0 4px 24px rgba(30,27,75,.08),inset 0 1px 0 rgba(255,255,255,.95);opacity:0;transform:translateY(44px);transition:opacity .65s cubic-bezier(0.22,1,.36,1),transform .65s cubic-bezier(0.22,1,.36,1),border-color .2s}
          .isa-en-c.isa-ev{opacity:1;transform:translateY(0)}
          .isa-en-c.isa-ev:hover{border-color:rgba(67,56,202,.25);box-shadow:0 16px 48px rgba(30,27,75,.14)}
          .isa-en-c.feat{background:linear-gradient(135deg,rgba(254,243,199,.52) 0%,rgba(255,255,255,.87) 55%,rgba(238,242,255,.45) 100%);border-color:rgba(217,119,6,.28);box-shadow:0 8px 32px rgba(217,119,6,.12),inset 0 1px 0 rgba(255,255,255,1);transform:translateY(-8px)}
          .isa-en-c.feat.isa-ev{transform:translateY(-8px)}
          .isa-en-c.feat.isa-ev:hover{transform:translateY(-12px)}
          .isa-en-b{display:inline-block;font-size:10px;font-weight:700;letter-spacing:1.2px;text-transform:uppercase;padding:5px 12px;border-radius:100px;border:1px solid;margin-bottom:18px}
          .isa-en-i{width:48px;height:48px;background:rgba(30,27,75,.07);border-radius:14px;display:flex;align-items:center;justify-content:center;margin-bottom:14px}
          .isa-en-i svg{fill:#1e1b4b}
          .isa-en-c.feat .isa-en-i{background:rgba(217,119,6,.10)}
          .isa-en-c.feat .isa-en-i svg{fill:#D97706}
          .isa-en-n{font-size:22px;font-weight:900;color:#1e1b4b;margin:0 0 6px;letter-spacing:-.3px}
          .isa-en-h{font-size:13px;font-weight:600;color:#4338ca;margin-bottom:12px}
          .isa-en-c.feat .isa-en-h{color:#D97706}
          .isa-en-d{font-size:14px;color:#3730a3;opacity:.8;line-height:1.7;margin-bottom:18px}
          .isa-en-ll{font-size:10px;font-weight:700;letter-spacing:1px;text-transform:uppercase;color:#6366f1;margin-bottom:8px}
          .isa-en-li{list-style:none;padding:0;margin:0 0 18px;display:flex;flex-direction:column;gap:7px}
          .isa-en-li li{display:flex;align-items:flex-start;gap:8px;font-size:13px;color:#374151;line-height:1.5}
          .isa-en-li li::before{content:'✓';font-weight:800;color:#4338ca;flex-shrink:0;margin-top:1px}
          .isa-en-c.feat .isa-en-li li::before{color:#D97706}
          .isa-en-p{font-size:12px;color:#6366f1;padding-top:14px;border-top:1px solid rgba(30,27,75,.08)}
          .isa-en-p strong{color:#1e1b4b}
          .isa-en-tl{display:inline-block;font-size:11px;font-weight:600;color:#D97706;margin-top:6px}
          .isa-en-a{display:block;margin-top:18px;padding:11px;border-radius:50px;font-size:13px;font-weight:700;text-align:center;text-decoration:none;transition:all .22s;background:rgba(30,27,75,.09);color:#1e1b4b;border:1.5px solid rgba(30,27,75,.18)}
          .isa-en-a:hover{background:#1e1b4b;color:#fff}
          .isa-en-c.feat .isa-en-a{background:#4338ca;color:#fff;border-color:#4338ca}
          .isa-en-c.feat .isa-en-a:hover{background:#1e1b4b;border-color:#1e1b4b}
          .isa-pr-s{background:#f5f4ff;border-top:1px solid rgba(30,27,75,.08);border-bottom:1px solid rgba(30,27,75,.08);padding:80px 40px;position:relative;z-index:1}
          .isa-ps{display:flex;flex-direction:column;margin-top:52px}
          .isa-ps-row{display:grid;grid-template-columns:56px 1fr;gap:0 20px;opacity:0;transform:translateY(48px);transition:opacity .65s cubic-bezier(0.22,1,.36,1),transform .65s cubic-bezier(0.22,1,.36,1)}
          .isa-ps-row.isa-pv{opacity:1;transform:translateY(0)}
          .isa-ps-l{display:flex;flex-direction:column;align-items:center}
          .isa-ps-ci{width:52px;height:52px;border-radius:50%;background:rgba(255,255,255,.65);backdrop-filter:blur(8px);border:2px solid rgba(30,27,75,.18);display:flex;align-items:center;justify-content:center;font-size:19px;font-weight:800;color:#1e1b4b;flex-shrink:0}
          .isa-ps-row.isa-pv:hover .isa-ps-ci{background:rgba(67,56,202,.10);border-color:#4338ca;color:#4338ca}
          .isa-ps-co{flex:1;display:flex;flex-direction:column;align-items:center;padding:6px 0;min-height:42px}
          .isa-ps-co::before{content:'';width:2px;flex:1;background:#1e1b4b;opacity:.22}
          .isa-ps-co::after{content:'';border-left:6px solid transparent;border-right:6px solid transparent;border-top:8px solid #1e1b4b;opacity:.40}
          .isa-ps-row:last-child .isa-ps-co{display:none}
          .isa-ps-r{padding:4px 0 38px}
          .isa-ps-row:last-child .isa-ps-r{padding-bottom:0}
          .isa-ps-t{font-size:20px;font-weight:700;color:#1e1b4b;margin:0 0 9px}
          .isa-ps-d{font-size:15px;color:#3730a3;opacity:.8;line-height:1.75;margin:0}
          .isa-te-s{background:transparent;padding:80px 40px;position:relative;z-index:1}
          .isa-ch{text-align:center;margin-bottom:48px}
          .isa-tg2{display:grid;grid-template-columns:repeat(3,1fr);gap:24px}
          .isa-tc{background:linear-gradient(135deg,rgba(238,242,255,.50) 0%,rgba(255,255,255,.85) 55%,rgba(224,231,255,.40) 100%);backdrop-filter:blur(16px);border:1px solid rgba(255,255,255,.85);border-radius:20px;padding:28px 24px;display:flex;flex-direction:column;gap:12px;box-shadow:0 4px 24px rgba(30,27,75,.08),inset 0 1px 0 rgba(255,255,255,.95);opacity:0;transform:translateY(40px);transition:opacity .6s cubic-bezier(0.22,1,.36,1),transform .6s cubic-bezier(0.22,1,.36,1)}
          .isa-tc.feat{background:linear-gradient(135deg,rgba(254,243,199,.52) 0%,rgba(255,255,255,.87) 55%,rgba(238,242,255,.42) 100%);border-color:rgba(217,119,6,.22)}
          .isa-tc.isa-tv{opacity:1;transform:translateY(0)}
          .isa-tc.isa-tv:hover{transform:translateY(-6px);box-shadow:0 16px 48px rgba(30,27,75,.14)}
          .isa-stars{font-size:16px;color:#D97706;letter-spacing:2px}
          .isa-txt{font-size:14px;line-height:1.75;color:#374151;flex:1}
          .isa-au{display:flex;align-items:center;gap:12px}
          .isa-av{width:42px;height:42px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:13px;font-weight:800;color:#fff;flex-shrink:0}
          .isa-an{font-size:14px;font-weight:700;color:#1e1b4b}
          .isa-ar{font-size:12px;color:#6b7280}
          .isa-wy-s{background:#f5f4ff;border-top:1px solid rgba(30,27,75,.08);border-bottom:1px solid rgba(30,27,75,.08);padding:80px 40px;position:relative;z-index:1}
          .isa-wy-g{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin-top:48px}
          .isa-wc{background:linear-gradient(135deg,rgba(238,242,255,.50) 0%,rgba(255,255,255,.85) 55%,rgba(224,231,255,.40) 100%);backdrop-filter:blur(16px);border:1px solid rgba(255,255,255,.85);border-radius:20px;padding:26px 22px;box-shadow:0 4px 24px rgba(30,27,75,.08),inset 0 1px 0 rgba(255,255,255,.95);opacity:0;transform:translateY(32px) scale(.97);transition:opacity .55s cubic-bezier(0.22,1,.36,1),transform .55s cubic-bezier(0.22,1,.36,1),border-color .2s}
          .isa-wc.isa-wv{opacity:1;transform:translateY(0) scale(1)}
          .isa-wc.isa-wv:hover{transform:translateY(-5px) scale(1);border-color:rgba(67,56,202,.25);box-shadow:0 14px 40px rgba(30,27,75,.12)}
          .isa-wd{width:10px;height:10px;border-radius:50%;background:#4338ca;margin-bottom:12px}
          .isa-wc h3{font-size:14px;font-weight:700;color:#1e1b4b;margin:0 0 8px;line-height:1.35}
          .isa-wc p{font-size:13px;color:#3730a3;opacity:.8;line-height:1.65;margin:0}
          .isa-ct-s{padding:70px 40px;background:linear-gradient(135deg,rgba(238,242,255,.55) 0%,rgba(255,255,255,.60) 40%,rgba(224,231,255,.55) 100%);backdrop-filter:blur(20px);border-top:1px solid rgba(255,255,255,.80);position:relative;z-index:1}
          .isa-ct-g{max-width:1440px;margin:0 auto;display:grid;grid-template-columns:1fr 1.15fr;gap:32px;align-items:start}
          .isa-ctt{font-size:42px;font-weight:900;line-height:1.18;margin:0 0 14px;background:linear-gradient(90deg,#1e1b4b 0%,#4338ca 100%);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text}
          .isa-ctd{font-size:14px;color:#3730a3;opacity:.8;line-height:1.6;margin:0 0 22px}
          .isa-ben{background:rgba(255,255,255,.70);border:1px solid rgba(255,255,255,.90);border-radius:14px;padding:22px;backdrop-filter:blur(12px);display:flex;flex-direction:column;gap:14px}
          .isa-be{display:flex;gap:10px;align-items:flex-start}
          .isa-bi{flex-shrink:0;color:#4338ca;font-weight:800;font-size:16px;margin-top:1px}
          .isa-be p{font-size:13px;color:#3730a3;margin:0;line-height:1.55;opacity:.9}
          .isa-fb{background:linear-gradient(135deg,rgba(255,255,255,.88) 0%,rgba(238,242,255,.18) 50%,rgba(255,255,255,.84) 100%);backdrop-filter:blur(20px);border:1px solid rgba(255,255,255,.92);border-radius:20px;padding:34px;box-shadow:0 8px 40px rgba(30,27,75,.10),inset 0 1px 0 rgba(255,255,255,1)}
          .isa-fb h3{font-size:22px;font-weight:700;color:#1e1b4b;margin:0 0 22px;letter-spacing:-.3px}
          .isa-form{display:flex;flex-direction:column;gap:13px}
          .isa-fr{display:grid;grid-template-columns:1fr 1fr;gap:12px}
          .isa-fg{display:flex;flex-direction:column;gap:5px}
          .isa-fg.full{grid-column:1/-1}
          .isa-fg label{font-size:12px;font-weight:500;color:#1e1b4b}
          .isa-fg input,.isa-fg textarea,.isa-fg select{padding:10px 13px;border:1px solid rgba(30,27,75,.14);border-radius:6px;font-size:13px;font-family:inherit;color:#1e1b4b;background:rgba(255,255,255,.55);transition:border-color .2s}
          .isa-fg input:focus,.isa-fg textarea:focus,.isa-fg select:focus{outline:none;border-color:#4338ca;box-shadow:0 0 0 3px rgba(67,56,202,.10)}
          .isa-co{display:flex;gap:8px;align-items:flex-start}
          .isa-co input{margin-top:3px;width:15px;height:15px}
          .isa-co label{font-size:11px;color:#3730a3;line-height:1.5;opacity:.9}
          .isa-co a{color:#1e1b4b}
          .isa-sub{width:100%;padding:14px;background:#4338ca;border:none;color:#fff;border-radius:50px;font-weight:700;font-size:15px;cursor:pointer;font-family:inherit;transition:all .25s;box-shadow:0 6px 24px rgba(67,56,202,.26)}
          .isa-sub:hover{background:#1e1b4b;transform:translateY(-2px)}
          .isa-fq-s{padding:80px 40px;background:#f5f4ff;border-top:1px solid rgba(30,27,75,.08);position:relative;z-index:1}
          .isa-fq-s h2{font-size:46px;font-weight:900;letter-spacing:-1px;background:linear-gradient(90deg,#1e1b4b 0%,#D97706 100%);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;margin:0 0 8px}
          .isa-fq-sub{font-size:15px;color:#3730a3;opacity:.8;margin:0 0 36px}
          .isa-fql{display:flex;flex-direction:column;gap:10px}
          .isa-fi{background:linear-gradient(135deg,rgba(238,242,255,.50) 0%,rgba(255,255,255,.85) 55%,rgba(224,231,255,.40) 100%);backdrop-filter:blur(16px);border:1px solid rgba(255,255,255,.85);border-radius:14px;overflow:hidden;box-shadow:0 4px 20px rgba(30,27,75,.06);transition:border-color .2s}
          .isa-fi.open{border-color:rgba(67,56,202,.30)}
          .isa-fi.open::before{content:'';display:block;height:3px;background:linear-gradient(90deg,#4338ca,#6366f1);border-radius:3px 3px 0 0}
          .isa-fqb{width:100%;background:none;border:none;padding:20px 20px 20px 58px;display:flex;align-items:center;justify-content:space-between;cursor:pointer;text-align:left;gap:14px;font-family:inherit;position:relative}
          .isa-fqb2{position:absolute;left:16px;top:50%;transform:translateY(-50%);width:26px;height:26px;background:rgba(30,27,75,.08);color:#374151;font-size:11px;font-weight:700;display:flex;align-items:center;justify-content:center;border-radius:6px}
          .isa-fi.open .isa-fqb2{background:#4338ca;color:#fff}
          .isa-fqb span{font-size:15px;font-weight:600;color:#1e1b4b;line-height:1.4}
          .isa-fi.open .isa-fqb span{color:#4338ca}
          .isa-fch{width:22px;height:22px;flex-shrink:0;color:#9ca3af;transition:transform .3s}
          .isa-fi.open .isa-fch{transform:rotate(180deg);color:#4338ca}
          .isa-faw{overflow:hidden;transition:max-height .35s ease;max-height:0}
          .isa-fi.open .isa-faw{max-height:500px}
          .isa-fa{padding:0 20px 20px 58px;font-size:14px;color:#4b5563;line-height:1.8}
          .isa-rel{padding:80px 40px;background:rgba(238,242,255,.14);backdrop-filter:blur(10px);border-top:1px solid rgba(255,255,255,.60)}
          .isa-ri{max-width:1300px;margin:0 auto;text-align:center}
          .isa-ri h2{font-size:34px;font-weight:900;background:linear-gradient(90deg,#1e1b4b 0%,#D97706 100%);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;margin:10px 0 12px}
          .isa-rs{font-size:14px;color:#3730a3;margin:0 auto;max-width:560px;opacity:.8}
          .isa-ri hr{border:none;border-top:1px solid rgba(30,27,75,.10);margin:32px 0}
          .isa-rts{display:flex;flex-wrap:wrap;justify-content:center;gap:10px}
          .isa-rt{display:inline-block;padding:10px 20px;border:1.5px solid;border-radius:50px;font-size:14px;font-weight:500;text-decoration:none;transition:all .22s}
          .isa-rt:hover{transform:translateY(-2px);box-shadow:0 6px 18px rgba(0,0,0,.09)}
          .isa-b{background:rgba(67,56,202,.09);border-color:rgba(67,56,202,.28);color:#3730a3}
          .isa-c{background:rgba(14,116,144,.09);border-color:rgba(14,116,144,.28);color:#155e75}
          .isa-o{background:rgba(180,83,9,.09);border-color:rgba(180,83,9,.28);color:#92400e}
          .isa-a{background:rgba(190,18,60,.09);border-color:rgba(190,18,60,.28);color:#9f1239}
          .isa-fu{background:rgba(162,28,175,.09);border-color:rgba(162,28,175,.28);color:#86198f}
          @media(max-width:1024px){.isa-hero h1,.isa-st,.isa-fq-s h2{font-size:36px}.isa-sk-g{grid-template-columns:repeat(2,1fr)}.isa-tec-g{grid-template-columns:repeat(2,1fr)}.isa-en-g{grid-template-columns:1fr;max-width:480px;margin-left:auto;margin-right:auto}.isa-en-c.feat{transform:none}.isa-en-c.feat.isa-ev{transform:none}.isa-en-c.feat.isa-ev:hover{transform:translateY(-4px)}.isa-wy-g{grid-template-columns:repeat(2,1fr)}.isa-tg2{grid-template-columns:1fr}.isa-ct-g{grid-template-columns:1fr}}
          @media(max-width:768px){.isa-bc,.isa-hero,.isa-sk-s,.isa-tec-s,.isa-en-s,.isa-pr-s,.isa-te-s,.isa-wy-s,.isa-fq-s,.isa-rel{padding-left:20px;padding-right:20px}.isa-hero{padding-top:28px;padding-bottom:20px}.isa-hero h1{font-size:26px;letter-spacing:-.3px}.isa-stats{grid-template-columns:1fr 1fr}.isa-sc:nth-child(2){border-right:none}.isa-sc:nth-child(3),.isa-sc:nth-child(4){border-top:1px solid rgba(30,27,75,.10)}.isa-sc:nth-child(4){border-right:none}.isa-sk-g,.isa-tec-g,.isa-wy-g{grid-template-columns:1fr}.isa-fr{grid-template-columns:1fr}.isa-ctt{font-size:28px}.isa-st{font-size:28px}.isa-ct-s{padding:48px 20px}.isa-logos{padding-left:20px;padding-right:20px}}
        `}</style>
      </Head>
      <div className="isa-page">
        <div className="isa-orb isa-o1" /><div className="isa-orb isa-o2" /><div className="isa-orb isa-o3" />
        <nav className="isa-bc" aria-label="Breadcrumb"><ol itemScope itemType="https://schema.org/BreadcrumbList"><li itemScope itemType="https://schema.org/ListItem" itemProp="itemListElement"><Link href="/" itemProp="item"><span itemProp="name">Home</span></Link><meta itemProp="position" content="1" /></li><li itemScope itemType="https://schema.org/ListItem" itemProp="itemListElement"><span itemProp="name">IT Staff Augmentation Services</span><meta itemProp="position" content="2" /></li></ol></nav>
        <section className="isa-hero">
          <span className="isa-ey">IT Staff Augmentation</span>
          <h1>IT Staff Augmentation Services — Add Expert Developers to Your Team in 5–7 Days</h1>
          <p className="isa-desc">Augment your engineering team with pre-vetted offshore developers — frontend, backend, full-stack, mobile, DevOps, QA, data engineering, and AI/ML specialists embedded directly in your team, working in your tools, under your management. 60–70% below US/UK hiring cost. No recruitment fee. Available in 5–7 business days.</p>
          <div className="isa-tr">{['5–7 Day Onboarding','Frontend / Backend / Mobile','DevOps / QA / AI-ML','You Manage Directly','60–70% Cost Savings'].map(b => (<div className="isa-badge" key={b}><span className="isa-dot" />{b}</div>))}</div>
          <div className="isa-ctas"><Link href="#contact" className="isa-p">Augment Your Team Now</Link><Link href="#engagement" className="isa-g">View Engagement Models →</Link></div>
        </section>
        <div className="isa-stats" ref={stR}>{[['300+','Developers Placed'],['5-7','Days to Onboard'],['60-70%','Cost Saving vs Local'],['98%','Client Retention']].map(([v, l]) => (<StatItem key={l} label={l} val={v} started={ss} />))}</div>
        <div className="isa-logos"><span className="isa-ll">Engineering Teams Augmented Across US, UK, Australia</span><div className="isa-lw"><div className="isa-lt">{[['/logo/Indian_Express_Logo_full.png','Indian Express'],['/logo/Verizon_2015_logo_-vector.svg.png','Verizon'],['/logo/Uniphore.jpg','Uniphore'],['/logo/ICCoLogo.png','ICC'],['/logo/Honor_Logo_(2020).svg.png','Honor'],['/logo/Zuari-Finserv-logo-new.png','Zuari Finserv'],['/logo/Indian_Express_Logo_full.png','Indian Express 2'],['/logo/Verizon_2015_logo_-vector.svg.png','Verizon 2'],['/logo/Uniphore.jpg','Uniphore 2'],['/logo/ICCoLogo.png','ICC 2'],['/logo/Honor_Logo_(2020).svg.png','Honor 2'],['/logo/Zuari-Finserv-logo-new.png','Zuari Finserv 2']].map(([src, alt]) => (<img key={alt} src={src} alt={alt.replace(/ \d$/, '')} className="isa-cl" />))}</div></div></div>
        <section className="isa-sk-s" aria-labelledby="isa-sk-h"><div className="isa-in"><div className={`isa-rv${vis.has('sk') ? ' isa-ok' : ''}`} ref={el => { secR.current['sk'] = el; }}><span className="isa-sey">Augmentation Services</span><h2 id="isa-sk-h" className="isa-st">Developer Roles Available for Augmentation</h2><p className="isa-sd" style={{ maxWidth: 720 }}>Frontend, backend, full-stack, mobile, DevOps, QA, data engineering, AI/ML, software architect, and tech lead augmentation — individual developers or squads, full-time or part-time.</p></div><div className="isa-sk-g" ref={skR}>{visServices.map((s, i) => (<div key={s.n} className={`isa-sk-c${s.feat ? ' feat' : ''}${vSk.includes(i) ? ' isa-cv' : ''}`} style={{ transitionDelay: `${i * 55}ms` }}><span className="isa-sk-n">{s.n}</span><h3>{s.title}</h3><p>{s.desc}</p></div>))}</div>{SERVICES.length > 6 && (<div className="isa-sm"><button className="isa-bm" onClick={() => setShowAll(p => !p)}>{showAll ? 'Show fewer ↑' : `Show all ${SERVICES.length} roles ↓`}</button></div>)}</div></section>
        <section className="isa-tec-s" aria-labelledby="isa-tec-h"><div className="isa-in"><div className={`isa-rv${vis.has('stk') ? ' isa-ok' : ''}`} ref={el => { secR.current['stk'] = el; }}><span className="isa-sey">Technology Coverage</span><h2 id="isa-tec-h" className="isa-st">Technologies Our Augmented Developers Cover</h2><p className="isa-sd" style={{ maxWidth: 680 }}>React, Next.js, Angular, Node.js, Python, PHP, Java, .NET, Flutter, React Native, AWS, Kubernetes, Terraform, dbt, LangChain, PyTorch — specialists across the full modern software stack.</p></div><div className="isa-tec-g" ref={stGr}>{TECH_STACK.map((grp, i) => (<div key={grp.group} className={`isa-tec-c${vSt.includes(i) ? ' isa-sv2' : ''}`} style={{ transitionDelay: `${i * 60}ms` }}><div className="isa-tg" style={{ color: grp.color, borderBottomColor: grp.color + '33' }}>{grp.group}</div><div className="isa-pills">{grp.items.map(item => <span key={item} className="isa-pill" style={{ color: grp.color, background: grp.color + '12', borderColor: grp.color + '30' }}>{item}</span>)}</div></div>))}</div></div></section>
        <section id="engagement" className="isa-en-s" aria-labelledby="isa-en-h"><div className="isa-in"><div className={`isa-rv${vis.has('eng') ? ' isa-ok' : ''}`} ref={el => { secR.current['eng'] = el; }}><span className="isa-sey">Engagement Models</span><h2 id="isa-en-h" className="isa-st">Staff Augmentation Engagement Options</h2><p className="isa-sd" style={{ maxWidth: 680 }}>Full-time developer augmentation, part-time specialist access, or an augmented squad of 3–8 developers — structured to match your delivery timeline and team growth objectives.</p></div><div className="isa-en-g" ref={enR}>{ENGAGEMENT_MODELS.map((m, i) => (<div key={m.id} className={`isa-en-c${m.feat ? ' feat' : ''}${vEn.includes(i) ? ' isa-ev' : ''}`} style={{ transitionDelay: `${i * 100}ms` }}><span className="isa-en-b" style={{ color: m.badgeColor, borderColor: m.badgeColor + '44', background: m.badgeColor + '14' }}>{m.badge}</span><div className="isa-en-i"><svg viewBox="0 0 24 24" width="26" height="26"><path d={m.icon} /></svg></div><div className="isa-en-n">{m.name}</div><div className="isa-en-h">{m.headline}</div><div className="isa-en-d">{m.desc}</div><div className="isa-en-ll">Best for</div><ul className="isa-en-li">{m.bestFor.map(b => <li key={b}>{b}</li>)}</ul><div className="isa-en-p"><strong>Process:</strong> {m.process}<br /><span className="isa-en-tl">{m.timeline}</span></div><Link href="#contact" className="isa-en-a">Get a free estimate →</Link></div>))}</div></div></section>
        <section className="isa-pr-s" aria-labelledby="isa-pr-h"><div className="isa-in" style={{ maxWidth: 760 }}><div className={`isa-rv${vis.has('proc') ? ' isa-ok' : ''}`} ref={el => { secR.current['proc'] = el; }}><span className="isa-sey">How It Works</span><h2 id="isa-pr-h" className="isa-st">Our Staff Augmentation Process</h2><p className="isa-sd">From role definition to first commit in 5–7 business days — precision shortlisting, your-format technical interview, rapid onboarding, and transparent performance tracking.</p></div><div className="isa-ps">{PROCESS_STEPS.map((step, i) => (<div key={step.num} className={`isa-ps-row${vis.has('proc') ? ' isa-pv' : ''}`} style={{ transitionDelay: `${i * 120}ms` }}><div className="isa-ps-l"><div className="isa-ps-ci">{step.num}</div><div className="isa-ps-co" /></div><div className="isa-ps-r"><div className="isa-ps-t">{step.title}</div><p className="isa-ps-d">{step.desc}</p></div></div>))}</div></div></section>
        <section className="isa-te-s" aria-labelledby="isa-te-h"><div className="isa-in"><div className={`isa-ch isa-rv${vis.has('ts') ? ' isa-ok' : ''}`} ref={el => { secR.current['ts'] = el; }}><span className="isa-sey">Client Stories</span><h2 id="isa-te-h" className="isa-st">What Clients Say About Our Augmented Developers</h2><p className="isa-sd">Engineering leaders and product heads across the UK, AU, and US on augmenting their teams with 1Solutions developers.</p></div><div className="isa-tg2" ref={teR}>{TESTIMONIALS.map((t, i) => (<div key={i} className={`isa-tc${t.feat ? ' feat' : ''}${vTe.includes(i) ? ' isa-tv' : ''}`} style={{ transitionDelay: `${i * 100}ms` }} itemScope itemType="https://schema.org/Review"><div className="isa-stars">★★★★★</div><p className="isa-txt" itemProp="reviewBody">{t.text}</p><div className="isa-au"><div className="isa-av" style={{ background: t.bg }}>{t.init}</div><div><div className="isa-an" itemProp="author">{t.name}</div><div className="isa-ar">{t.role}</div></div></div></div>))}</div></div></section>
        <section className="isa-wy-s" aria-labelledby="isa-wy-h"><div className="isa-in"><div className={`isa-rv${vis.has('wy') ? ' isa-ok' : ''}`} ref={el => { secR.current['wy'] = el; }}><span className="isa-sey">Why 1Solutions</span><h2 id="isa-wy-h" className="isa-st">Why Choose 1Solutions for Staff Augmentation</h2><p className="isa-sd" style={{ maxWidth: 680 }}>5–7 day onboarding, 60–70% cost saving, direct management, 5-day replacement guarantee, pre-vetted talent pool, no lock-in, full timezone flexibility, and any role or stack.</p></div><div className="isa-wy-g" ref={whR}>{WHY_CARDS.map((c, i) => (<div key={i} className={`isa-wc${vWh.includes(i) ? ' isa-wv' : ''}`} style={{ transitionDelay: `${i * 60}ms` }}><div className="isa-wd" /><h3>{c.title}</h3><p>{c.desc}</p></div>))}</div></div></section>
        <section id="contact" className="isa-ct-s" aria-labelledby="isa-ct-h"><div className="isa-ct-g"><div><h2 id="isa-ct-h" className="isa-ctt">Augment Your Team Today</h2><p className="isa-ctd">Share the role, technology stack, seniority level, and hours needed — we will shortlist pre-vetted developers within 24–48 hours and have your augmented developer making commits within 5–7 business days.</p><div className="isa-ben">{[['✓','Pre-vetted shortlist within 24–48 business hours'],['✓','Your format technical interview — coding test, system design, or live session'],['✓','First commit within 5–7 business days'],['✓','5-day replacement guarantee in first 4 weeks'],['✓','30-day notice to scale down or exit — no lock-in']].map(([icon, text]) => (<div className="isa-be" key={text}><span className="isa-bi">{icon}</span><p>{text}</p></div>))}</div></div>
        <div className="isa-fb"><h3>Tell Us the Role You Need to Augment</h3><form className="isa-form" onSubmit={e => e.preventDefault()}>
          <div className="isa-fr"><div className="isa-fg"><label htmlFor="isa-nm">Full Name *</label><input id="isa-nm" type="text" placeholder="Your name" required /></div><div className="isa-fg"><label htmlFor="isa-em">Work Email *</label><input id="isa-em" type="email" placeholder="you@company.com" required /></div></div>
          <div className="isa-fr"><div className="isa-fg"><label htmlFor="isa-co">Company Name</label><input id="isa-co" type="text" placeholder="Your company" /></div><div className="isa-fg"><label htmlFor="isa-ph">Phone / WhatsApp</label><input id="isa-ph" type="tel" placeholder="+1 555 000 0000" /></div></div>
          <div className="isa-fg full"><label htmlFor="isa-ro">Role / Technology Needed *</label><select id="isa-ro" required><option value="">Select role...</option><option>Frontend Developer (React / Next.js / Angular)</option><option>Backend Developer (Node.js / Python / PHP / Java)</option><option>Full-Stack Developer</option><option>Mobile Developer (React Native / Flutter / iOS / Android)</option><option>DevOps / Cloud Engineer</option><option>QA Engineer (Manual or Automation)</option><option>Data Engineer</option><option>AI / ML Developer</option><option>Software Architect</option><option>Tech Lead / Engineering Manager</option><option>Multiple Roles / Squad</option></select></div>
          <div className="isa-fg full"><label htmlFor="isa-sn">Seniority Level *</label><select id="isa-sn" required><option value="">Select seniority...</option><option>Junior (1–3 years)</option><option>Mid-Level (3–6 years)</option><option>Senior (6–10 years)</option><option>Staff / Principal (10+ years)</option><option>Tech Lead / Architect</option></select></div>
          <div className="isa-fg full"><label htmlFor="isa-ho">Hours per Month *</label><select id="isa-ho" required><option value="">Select hours...</option><option>Full-Time (160 hrs/month)</option><option>Part-Time (80 hrs/month)</option><option>Part-Time (40 hrs/month)</option><option>Project-based (variable hours)</option></select></div>
          <div className="isa-fg full"><label htmlFor="isa-ms">Team Context & Requirements *</label><textarea id="isa-ms" rows={4} placeholder="Describe your current team, tech stack, what the augmented developer will work on, specific skills required, and your timeline..." required /></div>
          <div className="isa-co"><input id="isa-co2" type="checkbox" required /><label htmlFor="isa-co2">I agree to the <Link href="/privacy-policy">Privacy Policy</Link>. Details are treated confidentially.</label></div>
          <button type="submit" className="isa-sub">Get Developer Shortlist in 24 Hours →</button>
        </form></div></div></section>
        <section className="isa-fq-s" aria-labelledby="isa-fq-h"><div className="isa-in" style={{ maxWidth: 860 }}><span className="isa-sey">FAQ</span><h2 id="isa-fq-h">IT Staff Augmentation — FAQ</h2><p className="isa-fq-sub">What staff augmentation is, how it differs from outsourcing, how quickly developers can join, cost savings, quality assurance, and replacement guarantees.</p><div className="isa-fql">{FAQS.map((item, i) => (<div key={i} className={`isa-fi${openFaq === i ? ' open' : ''}`} itemScope itemType="https://schema.org/Question"><button className="isa-fqb" onClick={() => setOpenFaq(openFaq === i ? -1 : i)} aria-expanded={openFaq === i}><div className="isa-fqb2">{String(i + 1).padStart(2, '0')}</div><span itemProp="name">{item.q}</span><svg className="isa-fch" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2"><polyline points="6 9 12 15 18 9" /></svg></button><div className="isa-faw" itemScope itemType="https://schema.org/Answer"><div className="isa-fa" itemProp="text">{item.a}</div></div></div>))}</div></div></section>
        <section className="isa-rel"><div className="isa-ri"><span className="isa-sey">Related Services</span><h2>Related Offshore & Hiring Services</h2><p className="isa-rs">Offshore development teams, IT outsourcing, cost optimisation, virtual CTO, and dedicated hire developer services.</p><hr /><div className="isa-rts">{[['/offshore-development-company/','Offshore Development','isa-c'],['/it-outsourcing-services/','IT Outsourcing','isa-a'],['/software-development-cost-optimization/','Cost Optimization','isa-o'],['/virtual-cto-services/','Virtual CTO','isa-fu'],['/hire-ai-developer/','Hire AI Developer','isa-fu'],['/devops-services-company/','DevOps Services','isa-b'],['/cloud-native-services/','Cloud Native','isa-b'],['/software-development-company/','Software Development','isa-b']].map(([href, label, cls]) => (<Link key={href} href={href} className={`isa-rt ${cls}`}>{label}</Link>))}</div></div></section>
      </div>
    </>
  );
}
