export const PROJECTS = [
  { id: 'comtradesol',         title: 'Comtradesol Advisory Services',  category: 'Web Development',  industry: 'Financial Services',      tech: ['WordPress Development', 'UI/UX Design', 'LinkedIn Marketing'],   desc: 'Built a professional corporate website for a financial advisory firm specialising in Trade Financing, Debt Advisory, and Credit Rating — then grew their reach with a targeted LinkedIn brand programme.',                     image: '/images/portfolio/comtradesol-showcase.jpg', url: '/case-studies/comtradesol',         internal: true, dual: false, liveUrl: 'https://www.comtradesol.com/'         },
  { id: 'rngfoundation',       title: 'RNG Foundation Awards',           category: 'Web Development',  industry: 'Media & Journalism',      tech: ['Custom Development', 'Laravel CRM', 'Portal Design'],             desc: "Custom awards portal and Laravel CRM for India's most prestigious journalism honours — 14 award categories, Indian Express Group, EY as knowledge partner.",                                                                  image: '/images/portfolio/rngfoundation.webp',       url: '/case-studies/rngfoundation',       internal: true, dual: true,  liveUrl: 'https://rngfoundation.com/awards/'    },
  { id: 'aiplusstore',         title: 'AI+ Store',                       category: 'eCommerce',        industry: 'Consumer Electronics',    tech: ['Shopify', 'Liquid', 'UI/UX Design'],                              desc: 'Full-featured Shopify store for AI+ SmartPhones — Nova series 5G smartphones, NovaPods, and NovaWatches across India.',                                                                                                    image: '/images/portfolio/aiplusstore.jpg',           url: '/case-studies/aiplusstore',         internal: true, dual: false, liveUrl: 'https://aiplusstore.com/'             },
  { id: 'keiyura',             title: 'Keiyura',                         category: 'eCommerce',        industry: 'Fashion & Jewellery',     tech: ['Shopify', 'Liquid', 'UI/UX Design'],                              desc: 'Elegant Shopify store for a handcrafted jewellery brand featuring lookbooks, curated collections, and a storytelling-led shopping experience.',                                                                             image: '/images/portfolio/keiyura.jpg',               url: '/case-studies/keiyura',             internal: true, dual: true,  liveUrl: 'https://keiyura.com/'                 },
  { id: 'asiandispatch',       title: 'Asian Dispatch',                  category: 'Web Development',  industry: 'Media & Journalism',      tech: ['WordPress', 'Custom Theme', 'UI/UX Design'],                      desc: 'Digital news network for investigative journalism across 13 Asian countries — AI & Tech, Climate, Health, Politics, and Human Rights.',                                                                                     image: '/images/portfolio/asiandispatch.webp',        url: '/case-studies/asiandispatch',       internal: true, dual: false, liveUrl: 'https://www.asiandispatch.net'         },
  { id: 'vns',                 title: 'VNS Group of Institutions',       category: 'Web Development',  industry: 'Education',               tech: ['WordPress', 'Custom Theme', 'UI/UX Design'],                      desc: 'Multi-faculty institution website in Bhopal covering Engineering, Pharmacy, Management, Nursing, and Education across a 50+ acre campus.',                                                                                  image: '/images/portfolio/vns.webp',                  url: '/case-studies/vns',                 internal: true, dual: true,  liveUrl: 'https://vns.ac.in/'                   },
  { id: 'shopsamsin',          title: 'Samsin',                          category: 'eCommerce',        industry: 'Fashion & Apparel',       tech: ['Shopify', 'Liquid', 'Email Marketing'],                           desc: 'Minimalist Shopify store for a streetwear label selling tops, bottoms, and headwear — with VIP subscriber access and flash-sale promotions.',                                                                               image: '/images/portfolio/shopsamsin.jpg',            url: '/case-studies/shopsamsin',          internal: true, dual: false, liveUrl: 'https://shopsamsin.com/'              },
  { id: 'foreverring',         title: 'Forever Ring',                    category: 'eCommerce',        industry: 'Fashion & Jewellery',     tech: ['Shopify', 'Liquid', 'UI/UX Design'],                              desc: 'Sophisticated Shopify store for a Canadian fine jewellery brand — clean product presentation, trust-building pages, and a seamless checkout flow.',                                                                          image: '/images/portfolio/foreverring.jpg',           url: '/case-studies/foreverring',         internal: true, dual: true,  liveUrl: 'https://www.foreverring.ca/'           },
  { id: 'parfumfrance',        title: 'Parfum France',                   category: 'eCommerce',        industry: 'Beauty & Fragrance',      tech: ['Shopify', 'Liquid', 'UI/UX Design'],                              desc: 'Premium Shopify fragrance boutique bringing French parfumerie to a global audience with immersive design and rich product storytelling.',                                                                                    image: '/images/portfolio/parfumfrance.jpg',          url: '/case-studies/parfumfrance',        internal: true, dual: false, liveUrl: 'https://parfumfrance.com/'            },
  { id: '305aero',             title: '305 Aero Supplies',               category: 'eCommerce',        industry: 'Electronics & IT',        tech: ['Shopify', 'Liquid', 'eCommerce'],                                 desc: 'Complete IT solutions store offering hardware and software products — a one-stop electronics shop for end-to-end technology needs.',                                                                                          image: '/images/portfolio/305aerosupplies.jpg',       url: '/case-studies/305aero',             internal: true, dual: true,  liveUrl: 'https://305aerosupplies.com/'          },
  { id: 'yaahdy',              title: 'Yaahdy Store',                    category: 'eCommerce',        industry: 'Lifestyle & Gifts',       tech: ['Shopify', 'Liquid', 'Conversion Optimisation'],                   desc: 'Vibrant Shopify eCommerce store optimised for fast load times and high-converting product pages.',                                                                                                                          image: '/images/portfolio/yaahdy.jpg',                url: '/case-studies/yaahdy',              internal: true, dual: false, liveUrl: 'https://yaahdy.com/'                  },
  { id: 'copalcollective',     title: 'Copal Collective',                category: 'eCommerce',        industry: 'Home & Lifestyle',        tech: ['Shopify', 'Liquid', 'UI/UX Design'],                              desc: 'Artisan Shopify store for handmade throws and textiles with a focus on craftsmanship and natural materials.',                                                                                                               image: '/images/portfolio/copalcollective.webp',      url: '/case-studies/copalcollective',     internal: true, dual: true                                                         },
  { id: 'explorehonor',        title: 'Explore HONOR',                   category: 'eCommerce',        industry: 'Consumer Electronics',    tech: ['Shopify', 'Liquid', 'UI/UX Design'],                              desc: 'Official Shopify store for HONOR India — smartphones, accessories, audio, wearables, and laptops with no-cost EMI.',                                                                                                        image: '/images/portfolio/explorehonor.webp',         url: '/case-studies/explorehonor',        internal: true, dual: false                                                        },
  { id: 'recreator',           title: 'Recreator',                       category: 'eCommerce',        industry: 'Sustainable Fashion',     tech: ['WooCommerce', 'WordPress', 'UI/UX Design'],                       desc: "Eco-conscious WooCommerce store for a US hemp clothing brand — men's and women's sustainable apparel and accessories.",                                                                                                     image: '/images/portfolio/recreator.png',             url: '/case-studies/recreator',           internal: true, dual: false                                                        },
  { id: 'expetize',            title: 'Expetize',                        category: 'Web Development',  industry: 'SaaS & MarTech',          tech: ['Custom Build', 'UI/UX Design'],                                   desc: 'Bulk email verification platform with 10+ validation layers — detecting disposable addresses and blacklisted emails. Used by teams at Salesforce, HubSpot, and Apollo.',                                                    image: '/images/portfolio/expetize.png',              url: '/case-studies/expetize',            internal: true, dual: false                                                        },
  { id: 'novanttum',           title: 'Novanttum',                       category: 'Web Development',  industry: 'Alternative Investments', tech: ['WordPress', 'Custom Theme', 'UI/UX Design'],                      desc: 'SEBI-registered AIF platform offering private credit, equity, and structured finance to high-potential businesses.',                                                                                                        image: '/images/portfolio/novanttum.png',             url: '/case-studies/novanttum',           internal: true, dual: false                                                        },
  { id: 'febestbanksawards',   title: 'FE Best Banks Awards',            category: 'Web Development',  industry: 'Banking & Finance',       tech: ['WordPress', 'Custom Theme', 'UI/UX Design'],                      desc: "Award portal for the Financial Express Best Banks Awards — India's highest honour in banking excellence, with EY as knowledge partner.",                                                                                    image: '/images/portfolio/febestbanksawards.png',     url: '/case-studies/febestbanksawards',   internal: true, dual: false                                                        },
  { id: 'intellismart',        title: 'IntelliSmart Infra',              category: 'Web Development',  industry: 'Infrastructure',          tech: ['WordPress', 'Custom Theme', 'UI/UX Design'],                      desc: 'Smart infrastructure corporate website for a sustainability-focused company delivering solutions across India.',                                                                                                            image: '/images/portfolio/intellismart.png',          url: '/case-studies/intellismart',        internal: true, dual: false                                                        },
  { id: 'runaya',              title: 'Runaya',                          category: 'Web Development',  industry: 'Manufacturing',           tech: ['WordPress', 'Custom Theme', 'UI/UX Design'],                      desc: "India's first zero-waste, zero-discharge aluminium processing facility — recovering 16,000 MT of green aluminium annually.",                                                                                                image: '/images/portfolio/runaya.png',                url: '/case-studies/runaya',              internal: true, dual: false                                                        },
  { id: 'freyrenergy',         title: 'Freyr Energy',                    category: 'Web Development',  industry: 'Renewable Energy',        tech: ['WordPress', 'Custom Theme', 'UI/UX Design'],                      desc: 'Rooftop solar solutions for an MNRE-empanelled installer serving 18,000+ customers across India since 2014.',                                                                                                               image: '/images/portfolio/freyrenergy.png',           url: '/case-studies/freyrenergy',         internal: true, dual: false                                                        },
  { id: 'xcelaccounting',      title: 'Xcel Accounting',                 category: 'Web Development',  industry: 'Accounting & Finance',    tech: ['WordPress', 'Custom Theme', 'UI/UX Design'],                      desc: 'Xero Gold Partner website in Dubai — fractional CFO, outsourced accounting, and VAT services across the UAE.',                                                                                                             image: '/images/portfolio/xcelaccounting.png',        url: '/case-studies/xcelaccounting',      internal: true, dual: false                                                        },
  { id: 'phdcci',              title: 'PHDCCI',                          category: 'Web Development',  industry: 'Trade & Industry',        tech: ['WordPress', 'Custom Theme', 'UI/UX Design'],                      desc: "India's apex industry body with 121+ years of legacy in trade promotion, policy advocacy, and economic development.",                                                                                                       image: '/images/portfolio/phdcci.png',                url: '/case-studies/phdcci',              internal: true, dual: false                                                        },
  { id: 'aiinnovationsummit',  title: 'AI Innovation Summit 2026',       category: 'Web Development',  industry: 'Technology & Events',     tech: ['Next.js', 'UI/UX Design'],                                        desc: 'Event website for a technology conference bringing together industry leaders, researchers, and innovators to shape the future.',                                                                                             image: '/images/portfolio/aiinnovationsummit.png',    url: '/case-studies/aiinnovationsummit',  internal: true, dual: false                                                        },
  { id: 'zincfootball',        title: 'Zinc Football',                   category: 'Web Development',  industry: 'Sports & Education',      tech: ['WordPress', 'Custom Theme', 'UI/UX Design'],                      desc: "India's first technology-driven grassroots football initiative backed by Hindustan Zinc, training 350+ children across Rajasthan.",                                                                                          image: '/images/portfolio/zincfootball.png',          url: '/case-studies/zincfootball',        internal: true, dual: false                                                        },
  { id: 'youngmonk',           title: 'Young Monk',                      category: 'Web Development',  industry: 'Public Relations',        tech: ['WordPress', 'Custom Theme', 'UI/UX Design'],                      desc: 'PR and communications agency website specialising in Sports, Entertainment, and Change Agents.',                                                                                                                          image: '/images/portfolio/youngmonk.png',             url: '/case-studies/youngmonk',           internal: true, dual: false                                                        },
  { id: 'greycellpr',          title: 'Grey Cell PR',                    category: 'Web Development',  industry: 'Public Relations',        tech: ['WordPress', 'Custom Theme', 'UI/UX Design'],                      desc: 'Branding and communications consultancy delivering strategic media relations and corporate brand management.',                                                                                                             image: '/images/portfolio/greycellpr.png',            url: '/case-studies/greycellpr',          internal: true, dual: false                                                        },
  { id: 'empor',               title: 'Empor Marcom',                    category: 'Web Development',  industry: 'B2B Marketing',           tech: ['WordPress', 'Custom Theme', 'UI/UX Design'],                      desc: 'Pan-India B2B marketing firm delivering lead generation, telemarketing, virtual events, and content syndication for enterprise clients.',                                                                                   image: '/images/portfolio/empor.png',                 url: '/case-studies/empor',               internal: true, dual: false                                                        },
  { id: 'truckinsurancefl',    title: 'TruckInsuranceFL',                category: 'Web Development',  industry: 'Insurance',               tech: ['WordPress', 'Custom Theme', 'UI/UX Design'],                      desc: "Florida's commercial truck insurance specialists — same-day coverage, instant quotes, and FMCSA-compliant policies.",                                                                                                        image: '/images/portfolio/truckinsurancefl.png',      url: '/case-studies/truckinsurancefl',    internal: true, dual: false                                                        },
  { id: 'astropraveen',        title: 'AstroPraveen',                    category: 'Web Development',  industry: 'Wellness & Spirituality', tech: ['WordPress', 'Custom Theme', 'UI/UX Design'],                      desc: 'Personal brand website for an Asia Book of Records holder offering horoscope reading, corporate astrology, and palmistry.',                                                                                                 image: '/images/portfolio/astropraveen.png',          url: '/case-studies/astropraveen',        internal: true, dual: false                                                        },
  { id: 'defencenewsupdates',  title: 'Defence News Updates',            category: 'Web Development',  industry: 'Defence & Media',         tech: ['WordPress', 'Custom Theme', 'UI/UX Design'],                      desc: 'Indian defence and security news portal covering Army, Navy, Air Force, DRDO programmes, and global military developments.',                                                                                                image: '/images/portfolio/defencenewsupdates.png',    url: '/case-studies/defencenewsupdates',  internal: true, dual: false                                                        },
  { id: 'defenceaviationpost', title: 'Defence Aviation Post',           category: 'Web Development',  industry: 'Defence & Media',         tech: ['WordPress', 'Custom Theme', 'UI/UX Design'],                      desc: 'Defence and military news portal covering Indian Armed Forces, aerospace, missile systems, and global security developments.',                                                                                               image: '/images/portfolio/defenceaviationpost.png',   url: '/case-studies/defenceaviationpost', internal: true, dual: false                                                        },
  { id: 'playaorthodontics',   title: 'Playa Orthodontics',              category: 'Web Development',  industry: 'Healthcare',              tech: ['WordPress', 'Custom Theme', 'UI/UX Design'],                      desc: 'Los Angeles orthodontic clinic — Invisalign, braces, and treatments for all ages with online consultation booking.',                                                                                                         image: '/images/portfolio/playaorthodontics.png',     url: '/case-studies/playaorthodontics',   internal: true, dual: false                                                        },
  { id: 'skinlasercentre',     title: 'Skin Laser Centre',               category: 'Web Development',  industry: 'Healthcare',              tech: ['WordPress', 'Custom Theme', 'UI/UX Design'],                      desc: "23-year-old Delhi dermatology practice — vitiligo, acne, hair transplants, and laser treatments.",                                                                                                                          image: '/images/portfolio/skinlasercentre.png',       url: '/case-studies/skinlasercentre',     internal: true, dual: false, liveUrl: 'https://skinlasercentre.com/'         },
  { id: 'adiuvo',              title: 'Adiuvo Trustees',                 category: 'Web Development',  industry: 'Corporate Services',      tech: ['WordPress', 'Custom Theme', 'UI/UX Design'],                      desc: 'Fiduciary services website in Cyprus — company formation, trust structures, and immigration for 700+ international clients.',                                                                                                image: '/images/portfolio/adiuvo.png',                url: '/case-studies/adiuvo',              internal: true, dual: false                                                        },
  { id: 'smefutures',          title: 'SME Futures',                     category: 'Web Development',  industry: 'Business & Finance',      tech: ['WordPress', 'Custom Theme', 'UI/UX Design'],                      desc: 'Editorial platform for SMEs covering business news, growth strategies, funding, and industry insights.',                                                                                                                    image: '/images/portfolio/smefutures.png',            url: '/case-studies/smefutures',          internal: true, dual: false, liveUrl: 'https://smefutures.com/'              },
  { id: 'mountsystems',        title: 'Mount Systems',                   category: 'Web Development',  industry: 'IT & Security',           tech: ['WordPress', 'Custom Theme', 'UI/UX Design'],                      desc: 'End-to-end IT and security solutions provider corporate website.',                                                                                                                                                           image: '/images/portfolio/mountsystems.png',          url: '/case-studies/mountsystems',        internal: true, dual: false, liveUrl: 'https://www.mount-systems.com.ki/'    },
  { id: 'charlespuma',         title: 'Charles Puma',                    category: 'Web Development',  industry: 'Art & Culture',           tech: ['WordPress', 'Custom Theme', 'UI/UX Design'],                      desc: 'Contemporary pop art gallery across Toronto, Miami, Berlin, and Florence — showcasing original artworks and limited edition prints.',                                                                                        image: '/images/portfolio/charlespuma.webp',          url: '/case-studies/charlespuma',         internal: true, dual: false, liveUrl: 'https://www.charlespuma.com/'         },
  { id: 'creativeinterior',    title: 'Creative Interior & Decor',       category: 'Web Development',  industry: 'Interior Design',         tech: ['WordPress', 'Custom Theme', 'UI/UX Design'],                      desc: 'Interior design firm website featuring 3D visualisations, transparent pricing, and a 100% satisfaction guarantee.',                                                                                                         image: '/images/portfolio/creativeinterior.jpeg',     url: '/case-studies/creativeinterior',    internal: true, dual: false                                                        },
  { id: 'throneportapotties',  title: 'Throne Porta Potties',            category: 'Web Development',  industry: 'Sanitation & Events',     tech: ['WordPress', 'Custom Theme', 'UI/UX Design'],                      desc: 'Porta potty rental website showcasing sanitation solutions for construction sites, events, and outdoor projects.',                                                                                                          image: '/images/portfolio/throneportapotties.png',    url: '/case-studies/throneportapotties',  internal: true, dual: false                                                        },
];

export function getProjectBySlug(slug) {
  return PROJECTS.find(p => p.id === slug) ?? null;
}

export function getAllProjectSlugs() {
  return PROJECTS.map(p => ({ params: { slug: p.id } }));
}
