import { useState, useEffect, useRef } from 'react';
import Head from 'next/head';
import Link from 'next/link';

const SERVICES = [
  { n: '01', title: 'Local SEO for Lawn Care', desc: 'Dominate local search for lawn care, landscaping, and garden maintenance services in your area — Google Business Profile optimisation, local citation building, and geo-targeted keyword strategy to capture customers searching near them.' },
  { n: '02', title: 'Google Business Profile Management', desc: 'Set up and continuously manage your Google Business Profile — service categories, before/after photos, review management, seasonal posts, and service area updates — to maximise local map pack visibility and phone call conversions.' },
  { n: '03', title: 'Google Ads for Lawn Care', desc: 'Targeted Google Search campaigns for lawn care, landscaping, and garden maintenance keywords — capturing high-intent local searches with optimised ads, landing pages, and call tracking for measurable lead generation.' },
  { n: '04', title: 'Facebook & Instagram Ads', desc: 'Before/after photo campaigns, seasonal promotions, and neighbourhood targeting on Facebook and Instagram — reaching homeowners in your service area with visually compelling ads that drive calls and quote requests.' },
  { n: '05', title: 'Lawn Care Website SEO', desc: 'On-page optimisation for your website — service pages targeting local keywords, location-specific content, schema markup, and technical SEO improvements — building the organic rankings that generate leads without ongoing ad spend.' },
  { n: '06', title: 'Direct Mail & Neighbourhood Targeting', desc: 'EDDM (Every Door Direct Mail) campaigns, door hangers, and postcard marketing targeted to specific neighbourhoods — a high-ROI direct marketing channel for lawn care businesses, especially during seasonal acquisition periods.' },
  { n: '07', title: 'Review Generation & Reputation Management', desc: 'Systematic review generation through automated follow-up sequences after completed jobs — building the Google review volume and rating that drives both local SEO rankings and conversion rate for incoming leads.' },
  { n: '08', title: 'Lawn Care Customer Retention Marketing', desc: 'Email newsletters, seasonal service reminders, loyalty programmes, and referral incentives — retaining existing lawn care customers and maximising customer lifetime value through automated re-engagement campaigns.' },
];

const CHANNELS = ['Google Local Search', 'Google Maps Pack', 'Google Ads', 'Facebook Ads', 'Instagram Ads', 'Direct Mail / EDDM', 'Nextdoor Ads', 'Email Marketing', 'Review Management', 'Referral Programmes'];

const PROCESS = [
  { step: '01', title: 'Business & Market Analysis', desc: 'Understanding your service area, current customer base, seasonal patterns, services offered, and competitive landscape — the foundation for a marketing strategy that fits your specific lawn care operation.' },
  { step: '02', title: 'Marketing Plan & Budget Allocation', desc: 'A recommended multi-channel strategy with clear budget allocation — prioritising channels by expected ROI for your market size and service mix, with seasonal adjustments for peak periods.' },
  { step: '03', title: 'Foundation Setup', desc: 'Google Business Profile, website SEO, tracking setup, and review generation workflows — the foundational infrastructure that makes every other marketing channel more effective.' },
  { step: '04', title: 'Paid Advertising Launch', desc: 'Google Ads and/or social media campaigns launched targeting your service area — initial focus on spring and summer peaks, with budget and messaging tuned for maximum lead volume.' },
  { step: '05', title: 'Seasonal Campaigns', desc: 'Spring clean-up, summer lawn care, fall aeration, and winter preparation campaigns — seasonal marketing calendar managed for you, timed around your market\'s peak demand periods.' },
  { step: '06', title: 'Monthly Reporting', desc: 'Leads generated by channel, cost per lead, review growth, and website traffic — a clear view of marketing ROI, with next month\'s optimisation priorities.' },
];

const WHY = [
  { title: 'Seasonal Marketing Expertise', desc: 'Lawn care is one of the most seasonal service businesses. We build marketing strategies around the spring ramp-up, summer peak, fall services, and winter planning cycles — so your ad spend and lead generation peak when customers are actively looking to book.' },
  { title: 'Local Map Pack Domination', desc: 'Most lawn care customers search "lawn care near me" on mobile and call the first result they find. Appearing in the Google Maps pack for local searches is the single highest-value marketing position for a lawn care business — we focus disproportionately on achieving and maintaining it.' },
  { title: 'Before/After Visual Marketing', desc: 'Before/after photos are the most compelling marketing asset in lawn care. We build visual marketing strategies — Google Business Profile photos, Facebook/Instagram ads, and website galleries — that showcase your results and drive enquiry from people who want the same transformation.' },
  { title: 'Route Density Optimisation', desc: 'For recurring lawn care businesses, the ideal customer is close to existing customers — it reduces drive time and increases profitability per hour. We target Google Ads and Facebook campaigns geographically to build route density in your highest-concentration service areas.' },
  { title: 'Upsell & Cross-Sell Campaigns', desc: 'Existing customers are the most profitable growth lever for a lawn care business. We build automated email and SMS campaigns that offer additional services (aeration, overseeding, fertilisation, hedge trimming) to your existing customer base — increasing average revenue per client.' },
  { title: 'Franchise & Multi-Location Support', desc: 'For lawn care businesses with multiple locations or franchise operations, we manage multi-location local SEO, individual Google Business Profiles, and location-specific paid campaigns — with centralised reporting and brand consistency across all locations.' },
];

const FAQS = [
  { q: 'What marketing works best for a lawn care business?', a: 'The highest-ROI marketing channels for lawn care businesses are: Google Business Profile / local SEO — appearing in the Google Maps pack for "lawn care near me" searches captures extremely high-intent local customers; Google Ads — search ads targeting local lawn care and landscaping keywords capture demand from people actively searching; referral programmes — lawn care is highly word-of-mouth, so incentivising referrals from happy customers generates high-quality, pre-sold leads at low cost; direct mail / EDDM (Every Door Direct Mail) — targeted mailings to neighbourhoods near existing customers build route density; and review generation — high Google review volume and rating improve both local search rankings and conversion rate from all other channels. The mix that is right for your business depends on your current scale, geography, and budget.' },
  { q: 'How do I get more lawn care customers from Google?', a: 'Getting more lawn care customers from Google requires two complementary strategies. Local SEO / Google Business Profile: Optimise your GBP with correct service categories ("Lawn care service," "Landscaping company"), service area cities, high-quality before/after photos, and a review generation strategy. Consistent local citations (name, address, phone number across all directories) reinforce your local prominence. Appearing in the top 3 of the Google Maps pack is the goal — this position generates the most calls for local service searches. Website SEO: Create dedicated pages for each service you offer ("lawn mowing service [city]," "lawn fertilisation [city]," "hedge trimming [city]") with location-specific content targeting the keywords local homeowners search. Google Ads: Paid search ads for local lawn care keywords provide immediate visibility while organic SEO builds over time.' },
  { q: 'Should I use Google Ads or Facebook Ads for lawn care leads?', a: 'Both channels work for lawn care but serve different purposes. Google Ads captures demand — people actively searching "lawn care near me" or "lawn mowing service [city]" have immediate intent to book. These leads are typically high quality and ready to decide. Facebook and Instagram Ads create demand — running before/after photo ads or seasonal promotion ads in front of homeowners in your service area builds brand awareness and generates leads from people who were not actively searching but are interested when they see your work. Most successful lawn care businesses use both: Google Ads for high-intent search capture, and Facebook/Instagram for visual brand building and seasonal promotions. If budget is limited, start with Google Ads for immediate lead generation, then add social media once the foundation is stable.' },
  { q: 'How important are Google reviews for a lawn care business?', a: 'Google reviews are critically important for lawn care businesses for two reasons. First, ranking: Google Business Profile ranking in the local map pack is significantly influenced by review count and average rating — businesses with 50+ reviews and 4.8+ ratings consistently rank higher than competitors with fewer reviews, all else being equal. Second, conversion: potential customers choose between 3 map pack results based primarily on review count and rating. A business with 80 reviews at 4.9 stars will get more calls than a competitor with 15 reviews at 4.5 stars, even from the same map pack position. We implement systematic review generation workflows — automated follow-up texts or emails after every completed job — that build review volume over time and drive both SEO rankings and conversion rate.' },
  { q: 'What is the best season to start marketing a lawn care business?', a: 'The strategic answer is: start 2 to 3 months before your local peak season. For most markets in the US and UK, spring is peak season — which means starting marketing in January to February for spring customer acquisition. SEO takes 3 to 6+ months to produce significant results, so starting in January means your rankings are improving by spring. Google Ads should launch 4 to 6 weeks before peak season to allow campaign learning and optimisation before the highest-demand period. Direct mail and neighbourhood campaigns should be deployed 6 to 8 weeks before spring, when homeowners begin thinking about lawn care. Year-round: maintain Google Business Profile activity, review generation, and email marketing to existing customers for retention, upsells, and referrals through every season.' },
  { q: 'How much should a lawn care business spend on marketing?', a: 'Industry benchmarks for lawn care marketing spend are typically 5 to 10% of revenue for established businesses, and 10 to 15% for growth-stage businesses or those in competitive markets. For a business doing $200,000 per year in revenue, a $12,000 to $20,000 annual marketing budget ($1,000 to $1,700 per month) is a typical range. This might split roughly as: $600 to $900 per month on Google Ads during peak season; $300 to $500 per month on local SEO and GBP management; $200 to $400 per month on review management and email marketing. Direct mail campaigns are typically run as seasonal lump sums ($1,000 to $3,000 per campaign) rather than monthly spend. These are rough guides — your specific market competitiveness, service mix, and growth goals significantly affect the right investment level.' },
  { q: 'Do you work with solo operators and solo lawn care businesses?', a: 'Yes. We work with everything from solo lawn care operators looking to build a full schedule and eventually hire, to multi-truck operations and franchise-based lawn care businesses. For solo operators, we focus on the highest-ROI channels first — Google Business Profile, local SEO, and Google Ads — and build systems for review generation and customer retention that work even with a very small team. We also help solo operators build the marketing infrastructure and brand positioning that supports growth to multi-crew operations without needing to rebrand or rebuild their marketing from scratch.' },
  { q: 'Can you help with pricing and service packaging for marketing?', a: 'Yes, as part of our strategy work. How you price and package services significantly affects marketing effectiveness — bundled seasonal programmes (spring clean-up + summer mowing + fall aeration) are much easier to market profitably than one-off jobs, because they build predictable recurring revenue and allow better route planning. We advise on service packaging, upsell sequences, and pricing positioning as part of building your marketing strategy. We do not set your prices — but we can share what pricing structures work best for marketing campaigns and customer acquisition economics in your market.' },
];

const STATS = [
  { label: 'Lawn Care Clients', val: '80+' },
  { label: 'Avg Lead Volume Growth', val: '+3.4×' },
  { label: 'Years Experience', val: '12+' },
  { label: 'Client Retention', val: '90%' },
];

export default function LawnCareMarketingServices() {
  const [openFaq, setOpenFaq] = useState(0);
  const [visibleCards, setVisibleCards] = useState([]);
  const [visibleSteps, setVisibleSteps] = useState([]);
  const [visibleWhy, setVisibleWhy] = useState([]);
  const cardsRef = useRef(null); const stepRefs = useRef([]); const whyRef = useRef(null);
  useEffect(() => { if (!cardsRef.current) return; const o = new IntersectionObserver(([e]) => { if (e.isIntersecting) { SERVICES.forEach((_, i) => setTimeout(() => setVisibleCards(p => p.includes(i) ? p : [...p, i]), i * 60)); o.disconnect(); } }, { threshold: 0.05 }); o.observe(cardsRef.current); return () => o.disconnect(); }, []);
  useEffect(() => { const obs = stepRefs.current.map((el, i) => { if (!el) return null; const o = new IntersectionObserver(([e]) => { if (e.isIntersecting) { setTimeout(() => setVisibleSteps(p => p.includes(i) ? p : [...p, i]), i * 120); o.disconnect(); } }, { threshold: 0.2 }); o.observe(el); return o; }); return () => obs.forEach(o => o && o.disconnect()); }, []);
  useEffect(() => { if (!whyRef.current) return; const o = new IntersectionObserver(([e]) => { if (e.isIntersecting) { WHY.forEach((_, i) => setTimeout(() => setVisibleWhy(p => p.includes(i) ? p : [...p, i]), i * 90)); o.disconnect(); } }, { threshold: 0.1 }); o.observe(whyRef.current); return () => o.disconnect(); }, []);
  const jsonLd = { '@context': 'https://schema.org', '@graph': [{ '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Home', item: 'https://www.1solutions.biz/' }, { '@type': 'ListItem', position: 2, name: 'Digital Marketing', item: 'https://www.1solutions.biz/digital-marketing-services/' }, { '@type': 'ListItem', position: 3, name: 'Lawn Care Marketing', item: 'https://www.1solutions.biz/lawn-care-marketing-services/' }] }, { '@type': 'Service', name: 'Lawn Care Marketing Services', provider: { '@type': 'Organization', name: '1Solutions', url: 'https://www.1solutions.biz' }, serviceType: 'Lawn Care Digital Marketing', url: 'https://www.1solutions.biz/lawn-care-marketing-services/' }, { '@type': 'FAQPage', mainEntity: FAQS.map(f => ({ '@type': 'Question', name: f.q, acceptedAnswer: { '@type': 'Answer', text: f.a } })) }] };
  return (
    <>
      <Head>
        <title>Lawn Care Marketing Services | Digital Marketing for Lawn Care Businesses | 1Solutions</title>
        <meta name="description" content="Digital marketing services for lawn care businesses — local SEO, Google Ads, Facebook ads, review management, and seasonal campaigns that generate consistent leads and grow your customer base." />
        <meta name="keywords" content="lawn care marketing services, digital marketing for lawn care, lawn care local seo, lawn care google ads, lawn care advertising, landscaping marketing, lawn care leads" />
        <link rel="canonical" href="https://www.1solutions.biz/lawn-care-marketing-services/" />
        <meta property="og:title" content="Lawn Care Marketing Services | 1Solutions" />
        <meta property="og:url" content="https://www.1solutions.biz/lawn-care-marketing-services/" />
        <meta name="twitter:card" content="summary_large_image" />
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
        <style>{`
          .lcmkt-page{font-family:'Inter',-apple-system,BlinkMacSystemFont,sans-serif;color:#0F1F40;line-height:1.6;overflow-x:hidden}
          .lcmkt-page *,.lcmkt-page *::before,.lcmkt-page *::after{box-sizing:border-box}
          .lcmkt-hero{background:linear-gradient(135deg,#f0fdf4 0%,#dcfce7 30%,#bbf7d0 65%,#f0fdf4 100%);position:relative;overflow:hidden;padding:80px 40px 0}
          .lcmkt-o1{position:absolute;top:-100px;right:-100px;width:560px;height:560px;border-radius:50%;background:radial-gradient(circle,rgba(21,128,61,0.12) 0%,transparent 65%);pointer-events:none;filter:blur(30px)}
          .lcmkt-o2{position:absolute;bottom:0;left:-80px;width:440px;height:440px;border-radius:50%;background:radial-gradient(circle,rgba(20,83,45,0.07) 0%,transparent 65%);pointer-events:none;filter:blur(30px)}
          .lcmkt-in{max-width:1280px;margin:0 auto;position:relative;z-index:2;text-align:center}
          .lcmkt-bc{display:flex;align-items:center;justify-content:center;flex-wrap:wrap;gap:6px;font-size:12px;color:#6b7280;margin-bottom:24px;font-weight:500}
          .lcmkt-bc a{color:#6b7280;text-decoration:none}.lcmkt-bc a:hover{color:#15803D}.lcmkt-bc span{color:#d1d5db}
          .lcmkt-ey{display:inline-flex;align-items:center;gap:8px;background:rgba(21,128,61,0.08);border:1px solid rgba(21,128,61,0.20);border-radius:100px;padding:5px 14px;font-size:11px;font-weight:700;letter-spacing:1.5px;text-transform:uppercase;color:#15803D;margin-bottom:28px}
          .lcmkt-h1{font-size:clamp(2.2rem,5vw,3.6rem);font-weight:900;line-height:1.1;letter-spacing:-1px;background:linear-gradient(90deg,#14532D 0%,#15803D 50%,#16A34A 100%);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;margin-bottom:20px;max-width:900px;margin-left:auto;margin-right:auto}
          .lcmkt-sub{font-size:1.08rem;color:#4A6080;line-height:1.75;max-width:660px;margin:0 auto 36px}
          .lcmkt-btns{display:flex;gap:14px;justify-content:center;flex-wrap:wrap;margin-bottom:56px}
          .lcmkt-btn-p{display:inline-flex;align-items:center;gap:8px;background:#15803D;color:#fff;padding:14px 30px;border-radius:50px;font-weight:700;font-size:0.95rem;text-decoration:none;transition:all 0.25s;box-shadow:0 4px 20px rgba(21,128,61,0.28)}
          .lcmkt-btn-p:hover{background:#14532D;box-shadow:0 8px 32px rgba(21,128,61,0.38);transform:translateY(-2px)}
          .lcmkt-btn-s{display:inline-flex;align-items:center;gap:8px;background:rgba(255,255,255,0.65);backdrop-filter:blur(12px);border:1.5px solid rgba(15,52,96,0.18);color:#0F3460;padding:14px 30px;border-radius:50px;font-weight:700;font-size:0.95rem;text-decoration:none;transition:all 0.25s}
          .lcmkt-btn-s:hover{border-color:#15803D;color:#15803D;transform:translateY(-2px)}
          .lcmkt-stats{display:grid;grid-template-columns:repeat(4,1fr);max-width:900px;margin:0 auto;background:rgba(255,255,255,0.55);backdrop-filter:blur(20px);border:1px solid rgba(255,255,255,0.85);border-radius:20px 20px 0 0;box-shadow:0 4px 24px rgba(21,128,61,0.07)}
          .lcmkt-stat{padding:20px 24px;text-align:center;border-right:1px solid rgba(21,128,61,0.08)}.lcmkt-stat:last-child{border-right:none}
          .lcmkt-stat-l{font-size:11px;color:#6b7280;font-weight:500;margin-bottom:4px}
          .lcmkt-stat-v{font-size:1.6rem;font-weight:900;color:#15803D;letter-spacing:-0.5px}
          .lcmkt-svc{background:#f8fafd;padding:80px 40px}.lcmkt-svc-in{max-width:1280px;margin:0 auto}
          .lcmkt-ey2{font-size:11px;font-weight:700;letter-spacing:2px;text-transform:uppercase;color:#15803D;margin-bottom:10px;display:block}
          .lcmkt-ttl{font-size:clamp(1.8rem,4vw,3rem);font-weight:900;line-height:1.15;letter-spacing:-1px;background:linear-gradient(90deg,#14532D 0%,#15803D 100%);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;margin-bottom:10px}
          .lcmkt-desc{font-size:15px;color:#4A6080;line-height:1.7;max-width:640px;margin-bottom:44px}
          .lcmkt-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}
          .lcmkt-card{background:linear-gradient(135deg,rgba(240,253,244,0.65) 0%,rgba(255,255,255,0.88) 60%,rgba(220,252,231,0.25) 100%);border:1px solid rgba(255,255,255,0.85);border-radius:20px;padding:26px 22px 22px;position:relative;overflow:hidden;box-shadow:0 4px 24px rgba(21,128,61,0.05);opacity:0;transform:translateY(20px);transition:opacity 0.4s ease,transform 0.4s ease}
          .lcmkt-card.visible{opacity:1;transform:translateY(0)}.lcmkt-card:hover{transform:translateY(-6px);border-color:rgba(21,128,61,0.22);box-shadow:0 16px 48px rgba(21,128,61,0.09)}
          .lcmkt-num{position:absolute;top:8px;right:14px;font-size:72px;font-weight:900;line-height:1;color:#15803D;opacity:0.05;letter-spacing:-4px;pointer-events:none;user-select:none}
          .lcmkt-card h3{font-size:15px;font-weight:700;color:#0F1F40;margin-bottom:8px;position:relative;z-index:1}
          .lcmkt-card p{font-size:13px;color:#4A6080;line-height:1.6;position:relative;z-index:1;margin:0}
          .lcmkt-ch{background:linear-gradient(135deg,#14532D 0%,#15803D 100%);padding:60px 40px}
          .lcmkt-ch-in{max-width:1280px;margin:0 auto;text-align:center}
          .lcmkt-ch h2{font-size:clamp(1.6rem,3vw,2.4rem);font-weight:900;color:#fff;margin-bottom:32px}
          .lcmkt-pills{display:flex;flex-wrap:wrap;gap:10px;justify-content:center}
          .lcmkt-pill{background:rgba(255,255,255,0.12);border:1px solid rgba(255,255,255,0.20);border-radius:100px;padding:8px 18px;font-size:13px;font-weight:600;color:#fff}
          .lcmkt-proc{background:linear-gradient(135deg,#f0fdf4 0%,#f0fdf4 50%,#dcfce7 100%);padding:80px 40px}
          .lcmkt-proc-in{max-width:900px;margin:0 auto}
          .lcmkt-steps{display:flex;flex-direction:column;margin-top:44px}
          .lcmkt-step{display:grid;grid-template-columns:80px 1fr;gap:24px;align-items:flex-start;padding:28px 0;border-bottom:1px solid rgba(21,128,61,0.10);opacity:0;transform:translateX(-20px);transition:opacity 0.45s ease,transform 0.45s ease}
          .lcmkt-step:last-child{border-bottom:none}.lcmkt-step.visible{opacity:1;transform:translateX(0)}
          .lcmkt-snum{font-size:3rem;font-weight:900;color:rgba(21,128,61,0.15);line-height:1;letter-spacing:-2px}
          .lcmkt-step h3{font-size:1.1rem;font-weight:800;color:#0F1F40;margin-bottom:6px}
          .lcmkt-step p{font-size:0.9rem;color:#4A6080;line-height:1.7;margin:0}
          .lcmkt-why{background:#fff;padding:80px 40px}.lcmkt-why-in{max-width:1280px;margin:0 auto}
          .lcmkt-why-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:20px;margin-top:44px}
          .lcmkt-wcard{background:linear-gradient(135deg,#f0fdf4 0%,#fff 60%,#dcfce7 100%);border:1px solid rgba(21,128,61,0.10);border-radius:16px;padding:28px;opacity:0;transform:translateY(16px);transition:opacity 0.4s ease,transform 0.4s ease}
          .lcmkt-wcard.visible{opacity:1;transform:translateY(0)}.lcmkt-wcard:hover{border-color:rgba(21,128,61,0.20);box-shadow:0 8px 32px rgba(21,128,61,0.07)}
          .lcmkt-dot{width:8px;height:8px;border-radius:50%;background:#15803D;margin-bottom:16px}
          .lcmkt-wcard h3{font-size:1rem;font-weight:800;color:#0F1F40;margin-bottom:10px}
          .lcmkt-wcard p{font-size:0.88rem;color:#4A6080;line-height:1.7;margin:0}
          .lcmkt-faq{background:#f8fafd;padding:80px 40px}.lcmkt-faq-in{max-width:860px;margin:0 auto}
          .lcmkt-fitem{border-bottom:1px solid #e5e7eb}
          .lcmkt-fq{width:100%;background:none;border:none;text-align:left;padding:22px 0;display:flex;align-items:flex-start;justify-content:space-between;gap:16px;cursor:pointer;font-family:inherit;font-size:1rem;font-weight:700;color:#0F1F40;line-height:1.4}
          .lcmkt-fq:hover{color:#15803D}
          .lcmkt-ficon{width:22px;height:22px;border:2px solid #e5e7eb;border-radius:50%;display:flex;align-items:center;justify-content:center;flex-shrink:0;font-size:14px;color:#9ca3af;transition:all 0.2s;margin-top:2px}
          .lcmkt-fitem.open .lcmkt-ficon{border-color:#15803D;color:#15803D;background:rgba(21,128,61,0.06)}
          .lcmkt-fa{font-size:0.92rem;color:#4A6080;line-height:1.8;overflow:hidden;max-height:0;transition:max-height 0.35s ease,padding-bottom 0.35s ease}
          .lcmkt-fitem.open .lcmkt-fa{max-height:600px;padding-bottom:22px}
          .lcmkt-cta{background:linear-gradient(135deg,rgba(21,128,61,0.06) 0%,rgba(255,255,255,0.80) 40%,rgba(20,83,45,0.04) 100%);padding:90px 40px;position:relative;overflow:hidden}
          .lcmkt-cta-o1{position:absolute;top:-80px;right:-80px;width:360px;height:360px;border-radius:50%;background:radial-gradient(circle,rgba(21,128,61,0.10) 0%,transparent 70%);pointer-events:none}
          .lcmkt-cta-o2{position:absolute;bottom:-60px;left:-60px;width:280px;height:280px;border-radius:50%;background:radial-gradient(circle,rgba(20,83,45,0.08) 0%,transparent 70%);pointer-events:none}
          .lcmkt-cta-in{max-width:760px;margin:0 auto;text-align:center;position:relative;z-index:1}
          .lcmkt-cta-t{font-size:clamp(1.8rem,3.5vw,2.8rem);font-weight:900;background:linear-gradient(90deg,#14532D 0%,#15803D 100%);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;margin-bottom:16px;line-height:1.2}
          .lcmkt-cta-s{font-size:1.05rem;color:#4A6080;line-height:1.75;margin:0 auto 36px;max-width:520px}
          @media(max-width:1024px){.lcmkt-grid{grid-template-columns:repeat(2,1fr)}.lcmkt-why-grid{grid-template-columns:repeat(2,1fr)}}
          @media(max-width:768px){.lcmkt-hero,.lcmkt-svc,.lcmkt-ch,.lcmkt-proc,.lcmkt-why,.lcmkt-faq,.lcmkt-cta{padding:60px 24px}.lcmkt-hero{padding-top:60px;padding-bottom:0}.lcmkt-stats{grid-template-columns:repeat(2,1fr);border-radius:16px 16px 0 0}.lcmkt-stat:nth-child(2){border-right:none}.lcmkt-grid{grid-template-columns:1fr}.lcmkt-why-grid{grid-template-columns:1fr}.lcmkt-step{grid-template-columns:56px 1fr}.lcmkt-btns{flex-direction:column;align-items:center}}
        `}</style>
      </Head>
      <div className="lcmkt-page">
        <section className="lcmkt-hero"><div className="lcmkt-o1"/><div className="lcmkt-o2"/>
          <div className="lcmkt-in">
            <nav className="lcmkt-bc"><Link href="/">Home</Link><span>/</span><Link href="/digital-marketing-services">Digital Marketing</Link><span>/</span><span style={{color:'#15803D'}}>Lawn Care Marketing</span></nav>
            <span className="lcmkt-ey"><span style={{width:6,height:6,borderRadius:'50%',background:'#15803D',display:'inline-block'}}/> Local SEO · Google Ads · Facebook Ads · Seasonal Campaigns</span>
            <h1 className="lcmkt-h1">Lawn Care Marketing Services — More Customers, More Route Density</h1>
            <p className="lcmkt-sub">Digital marketing built specifically for lawn care, landscaping, and garden maintenance businesses — local SEO, Google Ads, review generation, and seasonal campaigns that fill your schedule and build recurring customer revenue.</p>
            <div className="lcmkt-btns">
              <Link href="/contact" className="lcmkt-btn-p">Get a Free Lawn Care Marketing Audit <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><path d="M5 12h14M12 5l7 7-7 7"/></svg></Link>
              <Link href="/local-seo-services" className="lcmkt-btn-s">Local SEO Services</Link>
            </div>
            <div className="lcmkt-stats">{STATS.map(s => <div key={s.label} className="lcmkt-stat"><div className="lcmkt-stat-l">{s.label}</div><div className="lcmkt-stat-v">{s.val}</div></div>)}</div>
          </div>
        </section>
        <section className="lcmkt-svc"><div className="lcmkt-svc-in">
          <span className="lcmkt-ey2">What We Do</span><h2 className="lcmkt-ttl">Lawn Care Marketing Services</h2>
          <p className="lcmkt-desc">Every marketing channel a lawn care business needs — from local map pack visibility to seasonal paid campaigns and customer retention.</p>
          <div className="lcmkt-grid" ref={cardsRef}>{SERVICES.map((s,i) => <div key={s.n} className={`lcmkt-card${visibleCards.includes(i)?' visible':''}`}><div className="lcmkt-num">{s.n}</div><h3>{s.title}</h3><p>{s.desc}</p></div>)}</div>
        </div></section>
        <section className="lcmkt-ch"><div className="lcmkt-ch-in"><h2>Marketing Channels We Use</h2><div className="lcmkt-pills">{CHANNELS.map(c => <span key={c} className="lcmkt-pill">{c}</span>)}</div></div></section>
        <section className="lcmkt-proc"><div className="lcmkt-proc-in">
          <span className="lcmkt-ey2">How We Work</span><h2 className="lcmkt-ttl">Our Lawn Care Marketing Process</h2>
          <p className="lcmkt-desc">Market analysis to seasonal campaigns — a structured approach built around your service area, seasonal patterns, and growth goals.</p>
          <div className="lcmkt-steps">{PROCESS.map((p,i) => <div key={p.step} ref={el=>{stepRefs.current[i]=el}} className={`lcmkt-step${visibleSteps.includes(i)?' visible':''}`}><div className="lcmkt-snum">{p.step}</div><div><h3>{p.title}</h3><p>{p.desc}</p></div></div>)}</div>
        </div></section>
        <section className="lcmkt-why"><div className="lcmkt-why-in">
          <span className="lcmkt-ey2">Why 1Solutions</span><h2 className="lcmkt-ttl">Built for Lawn Care — Not Adapted from Generic Marketing Templates</h2>
          <p className="lcmkt-desc">Lawn care has unique marketing dynamics: seasonal demand, route density economics, before/after visual content, and high referral potential. We build strategies around these specifics.</p>
          <div className="lcmkt-why-grid" ref={whyRef}>{WHY.map((w,i) => <div key={w.title} className={`lcmkt-wcard${visibleWhy.includes(i)?' visible':''}`}><div className="lcmkt-dot"/><h3>{w.title}</h3><p>{w.desc}</p></div>)}</div>
        </div></section>
        <section className="lcmkt-faq"><div className="lcmkt-faq-in">
          <span className="lcmkt-ey2">Got Questions?</span><h2 className="lcmkt-ttl">Lawn Care Marketing FAQs</h2>
          <p className="lcmkt-desc" style={{marginBottom:44}}>Answers to the most common lawn care marketing questions.</p>
          <div>{FAQS.map((f,i) => <div key={i} className={`lcmkt-fitem${openFaq===i?' open':''}`}><button className="lcmkt-fq" onClick={()=>setOpenFaq(openFaq===i?-1:i)}>{f.q}<span className="lcmkt-ficon">{openFaq===i?'−':'+'}</span></button><div className="lcmkt-fa" style={openFaq===i?{maxHeight:600,paddingBottom:22}:{}}>{f.a}</div></div>)}</div>
        </div></section>
        <section className="lcmkt-cta"><div className="lcmkt-cta-o1"/><div className="lcmkt-cta-o2"/>
          <div className="lcmkt-cta-in">
            <span className="lcmkt-ey2" style={{textAlign:'center',display:'block',marginBottom:16}}>Ready to fill your schedule and grow your lawn care business?</span>
            <h2 className="lcmkt-cta-t">Get a Free Lawn Care Marketing Audit</h2>
            <p className="lcmkt-cta-s">We&rsquo;ll audit your local search visibility, Google Business Profile, competitor positioning, and ad opportunities — then recommend the marketing mix most likely to generate ROI for your operation.</p>
            <div className="lcmkt-btns">
              <Link href="/contact" className="lcmkt-btn-p">Request a Free Marketing Audit <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><path d="M5 12h14M12 5l7 7-7 7"/></svg></Link>
              <Link href="/hvac-seo-services" className="lcmkt-btn-s">HVAC SEO Services</Link>
            </div>
          </div>
        </section>
      </div>
    </>
  );
}
