'use client';
import { useState, useEffect, useRef } from 'react';
import Head from 'next/head';
import Link from 'next/link';

const SCHEMA = {
  '@context': 'https://schema.org',
  '@graph': [
    { '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Home', item: 'https://www.1solutions.biz/' }, { '@type': 'ListItem', position: 2, name: 'IT Outsourcing Services', item: 'https://www.1solutions.biz/it-outsourcing-services/' }] },
    { '@type': 'Service', name: 'IT Outsourcing Services', url: 'https://www.1solutions.biz/it-outsourcing-services/', description: '1Solutions IT outsourcing services — outsource software development, cloud infrastructure management, QA and testing, DevOps, AI/ML engineering, mobile development, and application maintenance to a reliable India-based IT outsourcing partner. 15+ years serving US, UK, AU, and CA clients. NDA-protected, SLA-backed engagements.', provider: { '@type': 'Organization', name: '1Solutions', url: 'https://www.1solutions.biz', logo: { '@type': 'ImageObject', url: 'https://www.1solutions.biz/images/1solutions-logo.png' }, foundingDate: '2008', areaServed: ['US', 'GB', 'AU', 'CA', 'IN'] }, aggregateRating: { '@type': 'AggregateRating', ratingValue: '4.9', reviewCount: '118', bestRating: '5' } },
    { '@type': 'FAQPage', mainEntity: [
      { '@type': 'Question', name: 'What IT functions can be outsourced to 1Solutions?', acceptedAnswer: { '@type': 'Answer', text: 'The IT functions most commonly outsourced to 1Solutions: Software application development (web, mobile, SaaS, APIs) — the largest category. Outsourced development teams are responsible for end-to-end feature delivery against a product roadmap. Cloud infrastructure management (AWS, Azure, GCP) — including Terraform IaC, Kubernetes management, CI/CD pipelines, monitoring setup, and cloud cost management. Quality assurance and software testing — manual testing, automation testing (Cypress, Playwright, Selenium, Appium), performance testing, and security testing. DevOps engineering — CI/CD pipeline implementation, container orchestration, GitOps, and site reliability engineering. Application maintenance and support — bug fixing, security patching, dependency updates, and performance monitoring for existing applications. AI/ML engineering — model development, LLM integration, RAG pipeline development, and AI product feature development. Data engineering — data pipeline development, dbt transformations, and data warehouse management.' } },
      { '@type': 'Question', name: 'What is the difference between IT outsourcing and staff augmentation?', acceptedAnswer: { '@type': 'Answer', text: 'IT outsourcing and staff augmentation both involve using an external provider for IT work, but the management model is fundamentally different. Staff augmentation: external developers are embedded in your team, working under your direct management using your tools, processes, and sprint cadence. You manage the individuals directly. Best when you have strong engineering management capacity. IT outsourcing (also called a dedicated team or managed delivery): the outsourcing provider takes responsibility for team management, sprint facilitation, delivery process, and outcomes. You interact with the team through a project manager or technical lead, not managing individual developers directly. Best when you want delivery accountability without engineering management overhead. In practice, 1Solutions operates across the spectrum — we can provide pure staff augmentation, pure managed delivery, or a hybrid where some functions (e.g. DevOps, QA) are managed by us while others (product development) are augmented directly into your team.' } },
      { '@type': 'Question', name: 'How do you ensure quality in IT outsourcing engagements?', acceptedAnswer: { '@type': 'Answer', text: 'Quality assurance in our IT outsourcing engagements operates at three levels. (1) Input quality — pre-vetted engineers with coding assessments and communication evaluations before they join any project. (2) Process quality — mandatory code reviews (all PRs require a senior developer review before merge), automated CI/CD with test gates (unit tests, linting, security scanning must pass before deployment), weekly architecture reviews, and sprint retrospectives. (3) Outcome quality — SLA agreements covering delivery commitments, defect rates, and response times; monthly quality reports including deployment frequency, defect rate, MTTR, and sprint velocity; and a dedicated client success manager as an escalation point for any quality concern. Our defect escape rate to production (post-release bugs reported by end users) is tracked and reviewed monthly, with root cause analysis for any spike.' } },
      { '@type': 'Question', name: 'What SLA commitments do you provide for IT outsourcing?', acceptedAnswer: { '@type': 'Answer', text: 'Typical SLA commitments in our IT outsourcing engagements: Sprint delivery commitments — 90%+ of committed sprint story points delivered in the agreed sprint cycle (2-week standard). Response time SLAs for application maintenance engagements — P1 (production down): 2-hour response, 8-hour resolution target; P2 (major feature broken): 4-hour response, 24-hour resolution; P3 (minor issue): 24-hour response, 5-business-day resolution. Communication SLA — daily standup by agreed time, email response within 4 business hours, urgent escalation via Slack/Teams with 1-hour response during overlap hours. Code review SLA — all PRs reviewed within 24 business hours. Security patch SLA — critical vulnerabilities (CVSS 9.0+) patched within 48 hours; high (CVSS 7.0–8.9) within 5 business days. Specific SLA terms are agreed in the engagement contract and can be customised based on your requirements.' } },
      { '@type': 'Question', name: 'How do you handle intellectual property and data security in IT outsourcing?', acceptedAnswer: { '@type': 'Answer', text: 'IP and data security in our IT outsourcing engagements: (1) IP ownership — all code, documentation, and deliverables created during the engagement are the exclusive property of the client. Our contracts include an explicit IP assignment clause. (2) NDA — mutual NDA signed before any project discussions. (3) Data security — developers access client systems through VPN; source code remains in client-controlled repositories (GitHub, GitLab, Bitbucket); no client data is stored on developer personal devices; we can accommodate specific security requirements such as dedicated VMs, client-managed laptops, or air-gapped environments for sensitive projects. (4) Background screening — all team members undergo background verification. (5) GDPR and data handling — we process personal data only as a data processor, under the instructions of the client as data controller, with a signed Data Processing Agreement (DPA) for engagements involving EU/UK personal data.' } },
      { '@type': 'Question', name: 'Can you take over an existing application or codebase?', acceptedAnswer: { '@type': 'Answer', text: 'Yes — taking over an existing application or codebase is one of the most common IT outsourcing scenarios. The process: (1) Code audit — a 1–2 week audit of the existing codebase: architecture assessment, technical debt quantification, test coverage review, security vulnerability scan, and documentation completeness. (2) Knowledge transfer — sessions with the previous team (if available) or documentation review to transfer domain knowledge. (3) Stabilisation sprint — a sprint focused on understanding the codebase, adding tests for critical paths, fixing critical bugs, and documenting the system before new feature development begins. (4) Ongoing development — feature development following the client roadmap, with continuous improvement of code quality and test coverage alongside new development. We have successfully taken over codebases in Node.js, Python, PHP/Laravel, Java, React/Next.js, Ruby on Rails, and .NET, including codebases with minimal documentation and low test coverage.' } },
      { '@type': 'Question', name: 'What is the typical process for starting an IT outsourcing engagement?', acceptedAnswer: { '@type': 'Answer', text: 'Starting an IT outsourcing engagement with 1Solutions: Week 1–2: Discovery — requirements gathering (team composition, technology stack, project scope, delivery cadence, SLA requirements), existing codebase review (if applicable), and proposal with team composition, timeline, and commercial terms. Week 2–4: Team formation — shortlisting and interviews for each role on the proposed team, NDA and contract signing, toolchain access setup (GitHub, Jira, Slack, VPN), and development environment setup. Week 4–6: Onboarding sprint — first sprint focused on environment familiarisation, codebase understanding, existing test coverage baseline, and first small deliverable. This sprint is deliberately scoped conservatively — the goal is establishing working processes, not maximum output. Month 2+: Full delivery — regular sprint cadence with weekly demos, monthly velocity reporting, and quarterly business reviews.' } },
      { '@type': 'Question', name: 'What are the cost advantages of IT outsourcing to India?', acceptedAnswer: { '@type': 'Answer', text: 'IT outsourcing to India reduces engineering costs for three structural reasons. (1) Labour arbitrage — senior software engineers in India earn $20,000–$40,000/year. Equivalent experience in San Francisco costs $160,000–$200,000. The difference, minus management overhead, passes through to the client. (2) No employer overhead — no employer payroll taxes, benefits, equity, office space, or equipment cost. The outsourcing fee is the total cost. (3) No recruitment cost or timeline — no 3–6 month hiring cycle, no recruiter fee (typically 15–25% of first year salary), and no gap in team capacity while recruiting. The combined effect is 60–70% reduction in engineering cost for outsourced roles vs local equivalent. For a 6-person outsourced development team (3 developers, 1 QA, 1 DevOps, 1 mobile), the annual saving vs a US-based equivalent team is typically $600,000–$900,000.' } },
    ] },
  ],
};

const SERVICES = [
  { n: '01', title: 'Software Application Development Outsourcing', desc: 'End-to-end outsourced software development — web applications (React/Next.js, Angular, Vue.js frontend; Node.js, Python, PHP, Java backend), mobile applications (React Native, Flutter, Swift, Kotlin), SaaS product development, REST and GraphQL API development, and database architecture. A dedicated outsourced development team responsible for full sprint delivery against your product roadmap, with weekly demos and transparent velocity tracking.' },
  { n: '02', title: 'Cloud Infrastructure Management Outsourcing', desc: 'Outsourced cloud management across AWS, Azure, and GCP — infrastructure-as-code with Terraform, Kubernetes cluster operations (EKS/AKS/GKE), CI/CD pipeline management (GitHub Actions, GitLab CI, ArgoCD), monitoring and alerting (Prometheus, Grafana, Datadog), security posture management (DevSecOps), cloud cost optimisation, and 24/7 infrastructure support with defined SLAs for incident response.', feat: true },
  { n: '03', title: 'QA & Software Testing Outsourcing', desc: 'Outsourced QA function — manual testing (functional, regression, UAT, exploratory, cross-browser, cross-device), test automation (Cypress and Playwright for E2E, Jest/Pytest for unit, k6/Locust for performance, Postman for API, Appium for mobile), test strategy development, QA process setup (definition of done, bug triage, release sign-off), and integration with your CI/CD pipeline for continuous quality gates.' },
  { n: '04', title: 'DevOps & Platform Engineering Outsourcing', desc: 'Outsourced DevOps engineering — CI/CD pipeline design and implementation, infrastructure-as-code migration from manual provisioning, Kubernetes cluster provisioning and operations, GitOps with ArgoCD or Flux, monitoring stack setup (three pillars: metrics, logs, traces), DevSecOps (SAST, SCA, container scanning in CI), and site reliability engineering practices (SLI/SLO, error budgets, incident runbooks, chaos engineering).' },
  { n: '05', title: 'Application Maintenance & Support Outsourcing', desc: 'Outsourced application maintenance for existing production systems — bug fixing and security patching, dependency version updates (avoiding abandoned packages and known CVEs), performance monitoring and optimisation, database maintenance (index analysis, query optimisation, vacuum/statistics), feature enhancements against a maintenance roadmap, infrastructure scaling as traffic grows, and documentation updates. SLA-backed response times for production incidents.' },
  { n: '06', title: 'AI & Machine Learning Engineering Outsourcing', desc: 'Outsourced AI engineering — LLM integration (OpenAI, Anthropic, Gemini, Mistral APIs), RAG pipeline development (LangChain, LlamaIndex, vector databases — Pinecone, Weaviate, pgvector), AI product feature development (chat assistants, document processing, semantic search, recommendation systems), classical ML model development and deployment, computer vision systems, and MLOps (training pipelines, model monitoring, A/B testing of models).' },
  { n: '07', title: 'Mobile App Development Outsourcing', desc: 'Outsourced mobile development — React Native and Flutter cross-platform development (iOS + Android from a single codebase), native Swift/SwiftUI for iOS, native Kotlin/Jetpack Compose for Android, full-cycle from UI/UX design through development to App Store and Google Play submission, and ongoing maintenance. Experienced in consumer apps, enterprise mobile, healthcare (HIPAA), fintech (PCI-DSS), and marketplace applications.' },
  { n: '08', title: 'Data Engineering & Analytics Outsourcing', desc: 'Outsourced data engineering — ELT/ETL pipeline development (Airflow, Prefect, Dagster), data warehouse management (Snowflake, BigQuery, Redshift), dbt transformation layer development, data quality framework (Great Expectations, dbt tests), API data integration (Airbyte, Fivetran, custom connectors), streaming data pipelines (Kafka, Kinesis), and BI dashboard development (Looker, Tableau, Metabase, Power BI).' },
  { n: '09', title: 'E-Commerce Platform Outsourcing', desc: 'Outsourced e-commerce development and management — Shopify and Shopify Plus (custom themes, Hydrogen/Remix, app development, complex checkout customisation), Magento/Adobe Commerce (B2B, multi-store, complex product catalogues), WooCommerce (custom plugins, performance optimisation), and headless commerce (custom frontend + Shopify/BigCommerce/Medusa backend). Includes ongoing platform maintenance, theme updates, and conversion optimisation.' },
  { n: '10', title: 'Legacy System Modernisation Outsourcing', desc: 'Outsourced legacy system modernisation — assessment of existing legacy architecture (PHP 5, .NET Framework, Java EE, classic ASP), modernisation roadmap development, incremental migration strategy (strangler fig pattern to avoid big-bang rewrites), migration to modern frameworks and cloud infrastructure, test suite development for the legacy system before migration begins, and parallel running validation. We have successfully modernised systems as old as 15 years.' },
];

const TECH_STACK = [
  { group: 'Frontend', color: '#be123c', items: ['React / Next.js / Remix', 'Angular 17+ / Vue.js 3', 'TypeScript', 'Tailwind / MUI / Shadcn', 'Storybook', 'PWA / Web Components'] },
  { group: 'Backend', color: '#0369a1', items: ['Node.js / NestJS / Express', 'Python / Django / FastAPI', 'PHP / Laravel / Symfony', 'Java / Spring Boot', '.NET / C# / ASP.NET', 'Go / Ruby on Rails'] },
  { group: 'Mobile', color: '#0f766e', items: ['React Native / Expo', 'Flutter / Dart', 'Swift / SwiftUI', 'Kotlin / Jetpack Compose', 'Capacitor / Ionic', 'Firebase / Supabase'] },
  { group: 'Cloud & DevOps', color: '#b45309', items: ['AWS / Azure / GCP', 'Kubernetes / Helm / ArgoCD', 'Terraform / Pulumi', 'GitHub Actions / GitLab CI', 'Docker / containerd', 'Prometheus / Grafana / Datadog'] },
  { group: 'Data & AI', color: '#7e22ce', items: ['dbt / Airflow / Prefect', 'Snowflake / BigQuery / Redshift', 'LangChain / LlamaIndex', 'PyTorch / scikit-learn', 'Pinecone / pgvector', 'Kafka / Kinesis'] },
  { group: 'QA & Testing', color: '#dc2626', items: ['Cypress / Playwright', 'Selenium / Appium', 'Jest / Vitest / Pytest', 'k6 / Locust', 'Postman / REST-assured', 'SonarQube / Semgrep'] },
  { group: 'Database', color: '#059669', items: ['PostgreSQL / MySQL', 'MongoDB / DynamoDB', 'Redis / Valkey', 'Elasticsearch / OpenSearch', 'CockroachDB / PlanetScale', 'Supabase / Firebase'] },
  { group: 'E-Commerce & CMS', color: '#c2185b', items: ['Shopify / Hydrogen', 'Magento / Adobe Commerce', 'WooCommerce', 'Drupal / WordPress', 'Contentful / Sanity', 'Medusa / BigCommerce'] },
];

const ENGAGEMENT_MODELS = [
  { id: 'dedicated', name: 'Dedicated Outsourced Team', badge: 'Most Popular', badgeColor: '#D97706', feat: true, icon: 'M16 11c1.66 0 2.99-1.34 2.99-3S17.66 5 16 5c-1.66 0-3 1.34-3 3s1.34 3 3 3zm-8 0c1.66 0 2.99-1.34 2.99-3S9.66 5 8 5C6.34 5 5 6.34 5 8s1.34 3 3 3zm0 2c-2.33 0-7 1.17-7 3.5V19h14v-2.5c0-2.33-4.67-3.5-7-3.5zm8 0c-.29 0-.62.02-.97.05 1.16.84 1.97 1.97 1.97 3.45V19h6v-2.5c0-2.33-4.67-3.5-7-3.5z', headline: 'A fully managed outsourced IT team — dedicated, accountable, scalable.', desc: 'A dedicated team working exclusively for your company on a monthly retainer — with a technical lead or project manager provided by 1Solutions, operating your sprint cadence, delivering against your roadmap, and reporting weekly. You interact with the team through a project manager, not by managing individual developers.', bestFor: ['Companies that want delivery accountability without engineering management overhead', 'Businesses outsourcing a complete IT function (product development, infrastructure, QA)', 'Startups building their product with an outsourced CTO and development team', 'Enterprises running a digital transformation with a parallel outsourced delivery stream'], process: 'Discovery → team formation → onboarding sprint → full delivery cadence', timeline: 'First sprint begins within 3–4 weeks of contract' },
  { id: 'maintenance', name: 'Application Maintenance & Support', badge: 'SLA-Backed', badgeColor: '#be123c', icon: 'M11.99 2C6.47 2 2 6.48 2 12s4.47 10 9.99 10C17.52 22 22 17.52 22 12S17.52 2 11.99 2zM12 20c-4.42 0-8-3.58-8-8s3.58-8 8-8 8 3.58 8 8-3.58 8-8 8zm.5-13H11v6l5.25 3.15.75-1.23-4.5-2.67V7z', headline: 'Ongoing outsourced maintenance with defined incident SLAs.', desc: 'SLA-backed outsourced maintenance for existing production applications — bug fixing, security patching, dependency updates, performance monitoring, and minor feature enhancements. P1 (production down): 2-hour response, 8-hour resolution. P2: 4-hour response. Monthly maintenance reports.', bestFor: ['Production applications requiring ongoing maintenance without a full internal team', 'Legacy systems where the original development team has moved on', 'SaaS companies needing a maintenance retainer for stability while the core team focuses on growth', 'Post-migration applications in a steady-state maintenance phase'], process: 'Codebase audit → SLA agreement → monitoring setup → ongoing maintenance', timeline: 'Maintenance coverage begins within 2–3 weeks' },
  { id: 'project', name: 'Fixed-Price Project Outsourcing', badge: 'Cost Certainty', badgeColor: '#0369a1', icon: 'M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm-7 3c1.93 0 3.5 1.57 3.5 3.5S13.93 13 12 13s-3.5-1.57-3.5-3.5S10.07 6 12 6zm7 13H5v-.23c0-.62.28-1.2.76-1.58C7.47 15.82 9.64 15 12 15s4.53.82 6.24 2.19c.48.38.76.97.76 1.58V19z', headline: 'Defined scope, fixed price, SLA-backed delivery.', desc: 'Fixed-price IT outsourcing for well-scoped projects — a new web or mobile application, legacy system migration, data warehouse implementation, or e-commerce platform build. Discovery phase locks requirements and architecture before fixed-price proposal. Milestone-based payment schedule.', bestFor: ['Well-scoped IT projects with clear requirements and defined deliverables', 'Businesses that need budget certainty for board or investor reporting', 'Projects with a defined go-live date and no appetite for cost overruns', 'One-off IT projects that do not justify building a permanent internal capability'], process: 'Discovery → fixed-price proposal → milestones → delivery → handover', timeline: 'Project kick-off within 1–2 weeks of contract' },
];

const PROCESS_STEPS = [
  { num: '01', title: 'Discovery & Requirements', desc: 'A structured 1–2 week discovery covering: what IT functions to outsource, the technology stack involved, current team and system state (for maintenance or takeover engagements), SLA requirements, communication preferences and timezone overlap needs, security and compliance requirements (GDPR, HIPAA, SOC 2, PCI-DSS), and desired delivery cadence. Output: a detailed engagement proposal with team composition, timeline, SLAs, and commercial terms.' },
  { num: '02', title: 'Team Formation & Vetting', desc: 'We shortlist and interview team members matched to your specific requirements — technology stack, domain experience (fintech, healthtech, e-commerce, SaaS), and seniority. For dedicated team engagements, you interview and approve each team member individually. For managed delivery, we assemble the team and you review CVs and conduct a team introduction call. NDAs, contracts, and background verifications are completed in parallel.' },
  { num: '03', title: 'Environment Setup & Access Provisioning', desc: 'Toolchain and environment setup: client GitHub/GitLab access, Jira/Linear project setup (or integration with your existing PM tool), Slack/Teams channel, VPN configuration, development and staging environment access, monitoring tool access, and any CI/CD pipeline credentials. Security review of access scope — developers have access only to the systems needed for their specific role.' },
  { num: '04', title: 'Onboarding Sprint & Knowledge Transfer', desc: 'For new product development: an architecture planning sprint, technology stack confirmation, and first working prototype or API by end of week 2. For codebase takeover: a code audit, documentation of existing architecture, test coverage baseline, and stabilisation of critical paths before new features begin. The onboarding sprint is deliberately conservative in scope — the goal is process establishment and context transfer, not maximum output.' },
  { num: '05', title: 'Sprint Delivery & Weekly Demos', desc: 'Regular delivery cadence: 2-week sprints with daily standups (in the agreed overlap window), sprint planning, code review, retrospective, and weekly demo to stakeholders. All code through pull request review. Velocity tracked from sprint one. Monthly quality report including deployment frequency, defect rate, MTTR, and sprint velocity vs commitment. Dedicated client success manager for non-technical escalation.' },
  { num: '06', title: 'Continuous Improvement & Scale', desc: 'Quarterly business reviews to assess delivery quality, team fit, SLA performance, and whether to expand or adjust the outsourcing scope. Proactive recommendations on technology upgrades, architecture evolution, and team composition changes as your product scales. Salary benchmarking to retain key team members long-term. Most IT outsourcing engagements at 1Solutions run for 2–5 years.' },
];

const TESTIMONIALS = [
  { text: "We outsourced our entire product engineering function to 1Solutions 3 years ago — a team of 8 (5 developers, 1 QA lead, 1 DevOps, 1 mobile dev). They manage their own sprints, run their own retrospectives, and deliver against our roadmap with minimal management from our side. Product velocity is higher than it was with our previous 6-person in-house team. Total cost is 58% lower.", name: 'Alex M.', role: 'CEO, SaaS Platform (UK)', init: 'AM', bg: '#3B0D1A' },
  { text: "We engaged 1Solutions to take over a 4-year-old Laravel/Vue.js application from a vendor who was closing. They completed the code audit in 8 days, documented the entire architecture, and had a maintenance team running within 3 weeks. Zero downtime during the transition. Their P1 SLA (2-hour response, 8-hour resolution) has been met 100% in 18 months.", name: 'Sophie R.', role: 'Head of IT, Professional Services Firm (AU)', init: 'SR', bg: '#1a2e0a', feat: true },
  { text: "We outsourced our data engineering function to 1Solutions — 2 data engineers and a data scientist. They rebuilt our entire dbt transformation layer, reduced our BigQuery bill by 34%, and shipped our first ML churn model in 9 weeks. The team runs independently from our product engineers and delivers a monthly data roadmap against our analytics objectives.", name: 'Nathan K.', role: 'VP Data, E-Commerce (US)', init: 'NK', bg: '#1e3a5f' },
];

const WHY_CARDS = [
  { title: '15+ Years IT Outsourcing Experience', desc: 'Founded in 2008, 1Solutions has 15+ years of IT outsourcing delivery for US, UK, Australian, and Canadian clients. Our processes reflect what actually works in long-term outsourcing relationships — not what looks good in a pitch deck.' },
  { title: 'SLA-Backed Commitments', desc: 'All IT outsourcing engagements include documented SLA commitments: sprint delivery percentages, incident response times (P1/P2/P3), communication response times, and code review turnaround. SLA performance is reported monthly against the baseline.' },
  { title: 'Full IP Ownership', desc: 'All code, documentation, and deliverables are the exclusive property of the client — explicitly assigned in the contract. We do not retain any licence, usage rights, or portfolio rights to your systems.' },
  { title: 'NDA From Day One', desc: 'Mutual NDA signed before any project discussions. All team members sign individual NDAs. Source code stays in client-controlled repositories. Data processing agreements available for GDPR/CCPA compliance.' },
  { title: 'Codebase Takeover Specialists', desc: 'We have taken over dozens of applications from previous vendors, in-house teams, and closing providers — in codebases from well-documented to completely undocumented. Our structured takeover process minimises disruption.' },
  { title: '60–70% Cost Reduction', desc: 'IT outsourcing to 1Solutions reduces fully-loaded engineering cost by 60–70% vs equivalent local hires — with no recruitment overhead, employer taxes, benefits, office cost, or hiring delay.' },
  { title: 'Full-Stack Technology Coverage', desc: 'Frontend, backend, mobile, cloud, DevOps, QA, AI/ML, data engineering, and e-commerce — covered by specialists, not generalists. One vendor for your entire IT stack rather than managing multiple specialist contractors.' },
  { title: 'Transparent Reporting', desc: 'Weekly progress reports, monthly quality metrics (velocity, defect rate, MTTR), quarterly business reviews, and full access to your team through your communication tools — no black-box delivery.' },
];

const FAQS = [
  { q: 'What IT functions can be outsourced to 1Solutions?', a: 'Software application development (web, mobile, SaaS), cloud infrastructure management (AWS/Azure/GCP), QA and testing, DevOps engineering, application maintenance and support, AI/ML engineering, data engineering and analytics, e-commerce development, and legacy system modernisation.' },
  { q: 'What is the difference between IT outsourcing and staff augmentation?', a: 'Staff augmentation: you manage individual developers directly, embedded in your team. IT outsourcing: 1Solutions manages the team and takes delivery accountability. You interact through a project manager or technical lead, not managing individuals. Outsourcing suits companies without engineering management capacity; augmentation suits companies with strong in-house engineering management.' },
  { q: 'How do you ensure quality?', a: 'Pre-vetted engineers (coding assessments + communication evaluations), mandatory PR code reviews, automated CI/CD test gates, weekly architecture reviews, monthly quality reports (deployment frequency, defect rate, MTTR, sprint velocity), and SLA commitments with documented response times.' },
  { q: 'What SLA commitments do you provide?', a: 'Sprint delivery: 90%+ committed story points per sprint. P1 incident: 2-hour response, 8-hour resolution. P2: 4-hour response, 24-hour resolution. P3: 24-hour response, 5-day resolution. PR review: within 24 business hours. Security patches (critical): within 48 hours. Custom SLAs negotiated per engagement.' },
  { q: 'Can you take over an existing application or codebase?', a: 'Yes — this is one of our most common engagements. We conduct a 1–2 week code audit, document the architecture, add tests for critical paths, stabilise before new features begin, and transition maintenance ownership. We have taken over applications in Node.js, Python, PHP/Laravel, Java, React/Next.js, Ruby on Rails, and .NET.' },
  { q: 'How is IP protected?', a: 'All code and deliverables are explicitly assigned to the client in the contract. Mutual NDA from day one. All team members sign individual NDAs. Source code stays in client-controlled repositories. Data Processing Agreements available for GDPR/CCPA engagements.' },
  { q: 'What does IT outsourcing to India cost vs local?', a: 'IT outsourcing to 1Solutions costs 60–70% less than equivalent local IT staff in the US or UK. A 6-person outsourced team (3 developers, 1 QA, 1 DevOps, 1 mobile) costs approximately $140,000–$220,000/year all-inclusive through 1Solutions vs $700,000–$1,000,000/year for an equivalent local team in San Francisco or London.' },
  { q: 'How long does it take to start an IT outsourcing engagement?', a: 'Discovery and team formation: 2–4 weeks. Onboarding sprint: 2 weeks. First full sprint delivery: week 4–6 from contract signing. Application maintenance coverage begins within 2–3 weeks. Fixed-price project kick-off within 1–2 weeks.' },
];

function useCountUp(target, duration = 1800, start = false) {
  const [count, setCount] = useState(0);
  useEffect(() => { if (!start) return; const num = parseInt(target.replace(/\D/g, ''), 10); if (!num) return; let t0 = null; const step = ts => { if (!t0) t0 = ts; const p = Math.min((ts - t0) / duration, 1); setCount(Math.floor((1 - Math.pow(1 - p, 3)) * num)); if (p < 1) requestAnimationFrame(step); }; requestAnimationFrame(step); }, [start, target, duration]);
  return count;
}
function StatItem({ label, val, started }) {
  const num = useCountUp(val, 1800, started);
  const suffix = val.replace(/[\d,]/g, '');
  return (<div className="ito-sc"><div className="ito-sv">{started ? (val.includes(',') ? num.toLocaleString() : num) + suffix : val}</div><div className="ito-sl">{label}</div></div>);
}

export default function ITOutsourcingServices() {
  const [showAll, setShowAll] = useState(false);
  const [openFaq, setOpenFaq] = useState(0);
  const [ss, setSs] = useState(false);
  const [vis, setVis] = useState(new Set());
  const [vSk, setVSk] = useState([]); const [vEn, setVEn] = useState([]); const [vWh, setVWh] = useState([]); const [vTe, setVTe] = useState([]); const [vSt, setVSt] = useState([]);
  const stR = useRef(null); const secR = useRef({});
  const skR = useRef(null); const enR = useRef(null); const whR = useRef(null); const teR = useRef(null); const stGr = useRef(null);
  useEffect(() => { if (!stR.current) return; const o = new IntersectionObserver(([e]) => { if (e.isIntersecting) { setSs(true); o.disconnect(); } }, { threshold: 0.4 }); o.observe(stR.current); return () => o.disconnect(); }, []);
  useEffect(() => { const pairs = [[skR, SERVICES.length, setVSk],[enR, 3, setVEn],[whR, WHY_CARDS.length, setVWh],[teR, 3, setVTe],[stGr, TECH_STACK.length, setVSt]]; const obs = pairs.map(([ref, count, setter]) => { if (!ref.current) return null; const o = new IntersectionObserver(([e]) => { if (e.isIntersecting) { Array.from({ length: count }, (_, i) => setTimeout(() => setter(p => p.includes(i) ? p : [...p, i]), i * 80)); o.disconnect(); } }, { threshold: 0.05 }); o.observe(ref.current); return o; }); return () => obs.forEach(o => o?.disconnect()); }, []);
  useEffect(() => { const ks = Object.keys(secR.current); const obs = ks.map(k => { const el = secR.current[k]; if (!el) return null; const o = new IntersectionObserver(([e]) => { if (e.isIntersecting) { setVis(p => new Set([...p, k])); o.disconnect(); } }, { threshold: 0.1 }); o.observe(el); return o; }); return () => obs.forEach(o => o?.disconnect()); }, []);
  const visServices = showAll ? SERVICES : SERVICES.slice(0, 6);
  return (
    <>
      <Head>
        <title>IT Outsourcing Services | Software Development, Cloud, QA | 1Solutions</title>
        <meta name="description" content="IT outsourcing services — outsource software development, cloud management, QA testing, DevOps, AI/ML, mobile, data engineering, and application maintenance to 1Solutions. SLA-backed, NDA-protected. 15+ years, 60–70% cost savings vs US/UK." />
        <link rel="canonical" href="https://www.1solutions.biz/it-outsourcing-services/" />
        <meta property="og:title" content="IT Outsourcing Services | 1Solutions" />
        <meta property="og:description" content="Outsource software development, cloud management, QA, DevOps, AI/ML, and application maintenance. SLA-backed, NDA-protected, 60–70% below US/UK costs." />
        <meta property="og:url" content="https://www.1solutions.biz/it-outsourcing-services/" />
        <meta property="og:image" content="https://www.1solutions.biz/images/banner-1sol.jpg" />
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(SCHEMA) }} />
        <style>{`
          .ito-page{font-family:'Inter',-apple-system,BlinkMacSystemFont,sans-serif;background:linear-gradient(135deg,#fff1f2 0%,#ffe4e6 20%,#fff5f5 50%,#fef3c7 75%,#f0f9ff 100%);color:#3b0018;line-height:1.6;position:relative;overflow-x:hidden}
          .ito-page *,.ito-page *::before,.ito-page *::after{box-sizing:border-box}
          .ito-orb{position:absolute;border-radius:50%;pointer-events:none;z-index:0;filter:blur(20px)}
          .ito-o1{width:860px;height:860px;background:radial-gradient(circle,rgba(190,18,60,.18) 0%,rgba(244,63,94,.07) 40%,transparent 70%);top:-260px;right:-240px}
          .ito-o2{width:760px;height:760px;background:radial-gradient(circle,rgba(217,119,6,.15) 0%,rgba(251,191,36,.06) 40%,transparent 70%);bottom:0;left:-220px}
          .ito-o3{width:520px;height:520px;background:radial-gradient(circle,rgba(3,105,161,.10) 0%,transparent 70%);top:44%;left:-100px;transform:translateY(-50%)}
          .ito-bc{position:relative;z-index:2;padding:16px 40px 0;max-width:1440px;margin:0 auto}
          .ito-bc ol{display:flex;flex-wrap:wrap;gap:6px;list-style:none;margin:0;padding:0;font-size:13px;color:#9f1239}
          .ito-bc li{display:flex;align-items:center;gap:6px}
          .ito-bc li::after{content:'/';opacity:.45}
          .ito-bc li:last-child::after{display:none}
          .ito-bc a{color:#3b0018;text-decoration:none}
          .ito-hero{position:relative;z-index:2;text-align:center;max-width:960px;margin:0 auto;padding:44px 40px 32px}
          .ito-ey{display:block;font-size:11px;font-weight:700;letter-spacing:2.5px;text-transform:uppercase;color:#be123c;margin-bottom:14px}
          .ito-hero h1{font-size:50px;font-weight:900;line-height:1.09;letter-spacing:-1.5px;margin-bottom:16px;background:linear-gradient(90deg,#3b0018 0%,#be123c 100%);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text}
          .ito-desc{font-size:16px;color:#881337;line-height:1.65;max-width:740px;margin:0 auto 24px}
          .ito-tr{display:flex;flex-wrap:wrap;justify-content:center;gap:10px;margin-bottom:26px}
          .ito-badge{display:inline-flex;align-items:center;gap:6px;background:rgba(255,255,255,.60);backdrop-filter:blur(10px);border:1px solid rgba(255,255,255,.85);border-radius:100px;padding:6px 14px;font-size:12px;font-weight:600;color:#3b0018;box-shadow:0 2px 8px rgba(59,0,24,.07)}
          .ito-dot{width:7px;height:7px;border-radius:50%;background:#be123c;flex-shrink:0}
          .ito-ctas{display:flex;flex-wrap:wrap;gap:12px;justify-content:center}
          .ito-p{display:inline-block;padding:14px 36px;background:#be123c;color:#fff;border-radius:50px;font-weight:700;font-size:15px;text-decoration:none;transition:all .25s;box-shadow:0 6px 24px rgba(190,18,60,.28)}
          .ito-p:hover{background:#3b0018;transform:translateY(-2px)}
          .ito-g{display:inline-block;padding:14px 36px;background:rgba(255,255,255,.55);backdrop-filter:blur(16px);border:1.5px solid rgba(255,255,255,.85);border-radius:50px;color:#3b0018;font-weight:700;font-size:15px;text-decoration:none;transition:all .25s}
          .ito-g:hover{background:rgba(255,255,255,.85);border-color:rgba(190,18,60,.5);transform:translateY(-2px)}
          .ito-stats{position:relative;z-index:2;display:grid;grid-template-columns:repeat(4,1fr);max-width:940px;margin:28px auto 0;background:rgba(255,255,255,.45);backdrop-filter:blur(24px);border:1px solid rgba(255,255,255,.85);box-shadow:0 4px 24px rgba(59,0,24,.08),inset 0 1px 0 rgba(255,255,255,.95)}
          .ito-sc{padding:18px 16px;text-align:center;border-right:1px solid rgba(59,0,24,.10)}
          .ito-sc:last-child{border-right:none}
          .ito-sv{font-size:28px;font-weight:900;color:#be123c;letter-spacing:-.5px;line-height:1}
          .ito-sl{font-size:11px;color:#9f1239;font-weight:500;margin-top:5px}
          .ito-logos{position:relative;z-index:2;padding:24px 40px 52px;display:flex;flex-direction:column;align-items:center;gap:14px}
          .ito-ll{font-size:10px;font-weight:700;letter-spacing:2px;text-transform:uppercase;color:#9f1239}
          .ito-lw{width:100%;overflow:hidden}
          .ito-lt{display:flex;align-items:center;gap:60px;width:max-content;animation:ito-mq 28s linear infinite}
          .ito-lt:hover{animation-play-state:paused}
          @keyframes ito-mq{0%{transform:translateX(0)}100%{transform:translateX(-50%)}}
          .ito-cl{height:24px;width:auto;max-width:110px;object-fit:contain;filter:grayscale(100%);opacity:.45;transition:opacity .25s,filter .25s}
          .ito-cl:hover{opacity:.85;filter:grayscale(0%)}
          .ito-sey{font-size:11px;font-weight:700;letter-spacing:2px;text-transform:uppercase;color:#D97706;margin-bottom:10px;display:block}
          .ito-st{font-size:46px;font-weight:900;line-height:1.12;letter-spacing:-1px;background:linear-gradient(90deg,#3b0018 0%,#D97706 100%);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;margin-bottom:10px}
          .ito-sd{font-size:15px;color:#881337;line-height:1.7}
          .ito-rv{opacity:0;transform:translateY(44px);transition:opacity .7s cubic-bezier(0.22,1,.36,1),transform .7s cubic-bezier(0.22,1,.36,1)}
          .ito-rv.ito-ok{opacity:1;transform:translateY(0)}
          .ito-in{max-width:1300px;margin:0 auto}
          .ito-sk-s{background:transparent;padding:72px 40px 60px;position:relative;z-index:1}
          .ito-sk-g{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-top:40px}
          .ito-sk-c{background:linear-gradient(135deg,rgba(255,241,242,.50) 0%,rgba(255,255,255,.85) 55%,rgba(255,228,230,.40) 100%);backdrop-filter:blur(16px);border:1px solid rgba(255,255,255,.85);border-radius:20px;padding:26px 22px 22px;position:relative;overflow:hidden;box-shadow:0 4px 24px rgba(59,0,24,.08),inset 0 1px 0 rgba(255,255,255,.95);opacity:0;transform:translateY(36px);transition:opacity .6s cubic-bezier(0.22,1,.36,1),transform .6s cubic-bezier(0.22,1,.36,1),border-color .2s}
          .ito-sk-c.ito-cv{opacity:1;transform:translateY(0)}
          .ito-sk-c.ito-cv:hover{transform:translateY(-6px);border-color:rgba(190,18,60,.30);box-shadow:0 16px 48px rgba(59,0,24,.14)}
          .ito-sk-c.feat{border-color:rgba(190,18,60,.20)}
          .ito-sk-n{position:absolute;top:8px;right:14px;font-size:72px;font-weight:900;line-height:1;color:#3b0018;opacity:.055;pointer-events:none;letter-spacing:-4px;user-select:none}
          .ito-sk-c h3{font-size:16px;font-weight:700;color:#3b0018;margin:0 0 8px;position:relative;z-index:1}
          .ito-sk-c p{font-size:13px;color:#881337;line-height:1.65;margin:0;position:relative;z-index:1}
          .ito-sk-c::before{content:'';position:absolute;left:0;top:12%;height:76%;width:3px;background:linear-gradient(180deg,#be123c,#f43f5e);border-radius:0 2px 2px 0;transform:scaleY(0);transform-origin:top center;transition:transform .3s cubic-bezier(0.22,1,.36,1)}
          .ito-sk-c.ito-cv:hover::before{transform:scaleY(1)}
          .ito-sm{text-align:center;margin-top:22px}
          .ito-bm{display:inline-block;background:#fff;border:1.5px solid rgba(59,0,24,.18);color:#3b0018;padding:10px 30px;border-radius:20px;font-weight:600;font-size:14px;cursor:pointer;transition:all .2s;font-family:inherit}
          .ito-bm:hover{background:#3b0018;border-color:#3b0018;color:#fff;transform:translateY(-2px)}
          .ito-tec-s{background:#fff4f5;border-top:1px solid rgba(59,0,24,.08);border-bottom:1px solid rgba(59,0,24,.08);padding:72px 40px;position:relative;z-index:1}
          .ito-tec-g{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin-top:40px}
          .ito-tec-c{background:linear-gradient(135deg,rgba(255,241,242,.50) 0%,rgba(255,255,255,.85) 55%,rgba(255,228,230,.40) 100%);backdrop-filter:blur(16px);border:1px solid rgba(255,255,255,.85);border-radius:20px;padding:22px 20px;box-shadow:0 4px 24px rgba(59,0,24,.08),inset 0 1px 0 rgba(255,255,255,.95);opacity:0;transform:translateY(32px);transition:opacity .55s cubic-bezier(0.22,1,.36,1),transform .55s cubic-bezier(0.22,1,.36,1),border-color .2s}
          .ito-tec-c.ito-sv2{opacity:1;transform:translateY(0)}
          .ito-tec-c.ito-sv2:hover{border-color:rgba(190,18,60,.25);box-shadow:0 14px 40px rgba(59,0,24,.12)}
          .ito-tg{font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:1.2px;margin-bottom:12px;padding-bottom:8px;border-bottom:2px solid}
          .ito-pills{display:flex;flex-wrap:wrap;gap:6px}
          .ito-pill{display:inline-block;font-size:11.5px;font-weight:500;padding:4px 10px;border-radius:100px;border:1px solid}
          .ito-en-s{padding:80px 40px;position:relative;z-index:1}
          .ito-en-g{display:grid;grid-template-columns:repeat(3,1fr);gap:20px;margin-top:40px}
          .ito-en-c{background:linear-gradient(135deg,rgba(255,241,242,.50) 0%,rgba(255,255,255,.85) 55%,rgba(255,228,230,.40) 100%);backdrop-filter:blur(16px);border:1px solid rgba(255,255,255,.85);border-radius:24px;padding:32px 28px;box-shadow:0 4px 24px rgba(59,0,24,.08),inset 0 1px 0 rgba(255,255,255,.95);opacity:0;transform:translateY(44px);transition:opacity .65s cubic-bezier(0.22,1,.36,1),transform .65s cubic-bezier(0.22,1,.36,1),border-color .2s}
          .ito-en-c.ito-ev{opacity:1;transform:translateY(0)}
          .ito-en-c.ito-ev:hover{border-color:rgba(190,18,60,.25);box-shadow:0 16px 48px rgba(59,0,24,.14)}
          .ito-en-c.feat{background:linear-gradient(135deg,rgba(254,243,199,.52) 0%,rgba(255,255,255,.87) 55%,rgba(255,241,242,.45) 100%);border-color:rgba(217,119,6,.28);box-shadow:0 8px 32px rgba(217,119,6,.12),inset 0 1px 0 rgba(255,255,255,1);transform:translateY(-8px)}
          .ito-en-c.feat.ito-ev{transform:translateY(-8px)}
          .ito-en-c.feat.ito-ev:hover{transform:translateY(-12px)}
          .ito-en-b{display:inline-block;font-size:10px;font-weight:700;letter-spacing:1.2px;text-transform:uppercase;padding:5px 12px;border-radius:100px;border:1px solid;margin-bottom:18px}
          .ito-en-i{width:48px;height:48px;background:rgba(59,0,24,.07);border-radius:14px;display:flex;align-items:center;justify-content:center;margin-bottom:14px}
          .ito-en-i svg{fill:#3b0018}
          .ito-en-c.feat .ito-en-i{background:rgba(217,119,6,.10)}
          .ito-en-c.feat .ito-en-i svg{fill:#D97706}
          .ito-en-n{font-size:22px;font-weight:900;color:#3b0018;margin:0 0 6px;letter-spacing:-.3px}
          .ito-en-h{font-size:13px;font-weight:600;color:#be123c;margin-bottom:12px}
          .ito-en-c.feat .ito-en-h{color:#D97706}
          .ito-en-d{font-size:14px;color:#881337;line-height:1.7;margin-bottom:18px}
          .ito-en-ll{font-size:10px;font-weight:700;letter-spacing:1px;text-transform:uppercase;color:#9f1239;margin-bottom:8px}
          .ito-en-li{list-style:none;padding:0;margin:0 0 18px;display:flex;flex-direction:column;gap:7px}
          .ito-en-li li{display:flex;align-items:flex-start;gap:8px;font-size:13px;color:#374151;line-height:1.5}
          .ito-en-li li::before{content:'✓';font-weight:800;color:#be123c;flex-shrink:0;margin-top:1px}
          .ito-en-c.feat .ito-en-li li::before{color:#D97706}
          .ito-en-p{font-size:12px;color:#9f1239;padding-top:14px;border-top:1px solid rgba(59,0,24,.08)}
          .ito-en-p strong{color:#3b0018}
          .ito-en-tl{display:inline-block;font-size:11px;font-weight:600;color:#D97706;margin-top:6px}
          .ito-en-a{display:block;margin-top:18px;padding:11px;border-radius:50px;font-size:13px;font-weight:700;text-align:center;text-decoration:none;transition:all .22s;background:rgba(59,0,24,.09);color:#3b0018;border:1.5px solid rgba(59,0,24,.18)}
          .ito-en-a:hover{background:#3b0018;color:#fff}
          .ito-en-c.feat .ito-en-a{background:#be123c;color:#fff;border-color:#be123c}
          .ito-en-c.feat .ito-en-a:hover{background:#3b0018;border-color:#3b0018}
          .ito-pr-s{background:#fff4f5;border-top:1px solid rgba(59,0,24,.08);border-bottom:1px solid rgba(59,0,24,.08);padding:80px 40px;position:relative;z-index:1}
          .ito-ps{display:flex;flex-direction:column;margin-top:52px}
          .ito-ps-row{display:grid;grid-template-columns:56px 1fr;gap:0 20px;opacity:0;transform:translateY(48px);transition:opacity .65s cubic-bezier(0.22,1,.36,1),transform .65s cubic-bezier(0.22,1,.36,1)}
          .ito-ps-row.ito-pv{opacity:1;transform:translateY(0)}
          .ito-ps-l{display:flex;flex-direction:column;align-items:center}
          .ito-ps-ci{width:52px;height:52px;border-radius:50%;background:rgba(255,255,255,.65);backdrop-filter:blur(8px);border:2px solid rgba(59,0,24,.18);display:flex;align-items:center;justify-content:center;font-size:19px;font-weight:800;color:#3b0018;flex-shrink:0}
          .ito-ps-row.ito-pv:hover .ito-ps-ci{background:rgba(190,18,60,.10);border-color:#be123c;color:#be123c}
          .ito-ps-co{flex:1;display:flex;flex-direction:column;align-items:center;padding:6px 0;min-height:42px}
          .ito-ps-co::before{content:'';width:2px;flex:1;background:#3b0018;opacity:.22}
          .ito-ps-co::after{content:'';border-left:6px solid transparent;border-right:6px solid transparent;border-top:8px solid #3b0018;opacity:.40}
          .ito-ps-row:last-child .ito-ps-co{display:none}
          .ito-ps-r{padding:4px 0 38px}
          .ito-ps-row:last-child .ito-ps-r{padding-bottom:0}
          .ito-ps-t{font-size:20px;font-weight:700;color:#3b0018;margin:0 0 9px}
          .ito-ps-d{font-size:15px;color:#881337;line-height:1.75;margin:0}
          .ito-te-s{background:transparent;padding:80px 40px;position:relative;z-index:1}
          .ito-ch{text-align:center;margin-bottom:48px}
          .ito-tg2{display:grid;grid-template-columns:repeat(3,1fr);gap:24px}
          .ito-tc{background:linear-gradient(135deg,rgba(255,241,242,.50) 0%,rgba(255,255,255,.85) 55%,rgba(255,228,230,.40) 100%);backdrop-filter:blur(16px);border:1px solid rgba(255,255,255,.85);border-radius:20px;padding:28px 24px;display:flex;flex-direction:column;gap:12px;box-shadow:0 4px 24px rgba(59,0,24,.08),inset 0 1px 0 rgba(255,255,255,.95);opacity:0;transform:translateY(40px);transition:opacity .6s cubic-bezier(0.22,1,.36,1),transform .6s cubic-bezier(0.22,1,.36,1)}
          .ito-tc.feat{background:linear-gradient(135deg,rgba(254,243,199,.52) 0%,rgba(255,255,255,.87) 55%,rgba(255,241,242,.42) 100%);border-color:rgba(217,119,6,.22)}
          .ito-tc.ito-tv{opacity:1;transform:translateY(0)}
          .ito-tc.ito-tv:hover{transform:translateY(-6px);box-shadow:0 16px 48px rgba(59,0,24,.14)}
          .ito-stars{font-size:16px;color:#D97706;letter-spacing:2px}
          .ito-txt{font-size:14px;line-height:1.75;color:#374151;flex:1}
          .ito-au{display:flex;align-items:center;gap:12px}
          .ito-av{width:42px;height:42px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:13px;font-weight:800;color:#fff;flex-shrink:0}
          .ito-an{font-size:14px;font-weight:700;color:#3b0018}
          .ito-ar{font-size:12px;color:#6b7280}
          .ito-wy-s{background:#fff4f5;border-top:1px solid rgba(59,0,24,.08);border-bottom:1px solid rgba(59,0,24,.08);padding:80px 40px;position:relative;z-index:1}
          .ito-wy-g{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin-top:48px}
          .ito-wc{background:linear-gradient(135deg,rgba(255,241,242,.50) 0%,rgba(255,255,255,.85) 55%,rgba(255,228,230,.40) 100%);backdrop-filter:blur(16px);border:1px solid rgba(255,255,255,.85);border-radius:20px;padding:26px 22px;box-shadow:0 4px 24px rgba(59,0,24,.08),inset 0 1px 0 rgba(255,255,255,.95);opacity:0;transform:translateY(32px) scale(.97);transition:opacity .55s cubic-bezier(0.22,1,.36,1),transform .55s cubic-bezier(0.22,1,.36,1),border-color .2s}
          .ito-wc.ito-wv{opacity:1;transform:translateY(0) scale(1)}
          .ito-wc.ito-wv:hover{transform:translateY(-5px) scale(1);border-color:rgba(190,18,60,.25);box-shadow:0 14px 40px rgba(59,0,24,.12)}
          .ito-wd{width:10px;height:10px;border-radius:50%;background:#be123c;margin-bottom:12px}
          .ito-wc h3{font-size:14px;font-weight:700;color:#3b0018;margin:0 0 8px;line-height:1.35}
          .ito-wc p{font-size:13px;color:#881337;line-height:1.65;margin:0}
          .ito-ct-s{padding:70px 40px;background:linear-gradient(135deg,rgba(255,241,242,.55) 0%,rgba(255,255,255,.60) 40%,rgba(255,228,230,.55) 100%);backdrop-filter:blur(20px);border-top:1px solid rgba(255,255,255,.80);position:relative;z-index:1}
          .ito-ct-g{max-width:1440px;margin:0 auto;display:grid;grid-template-columns:1fr 1.15fr;gap:32px;align-items:start}
          .ito-ctt{font-size:42px;font-weight:900;line-height:1.18;margin:0 0 14px;background:linear-gradient(90deg,#3b0018 0%,#be123c 100%);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text}
          .ito-ctd{font-size:14px;color:#881337;line-height:1.6;margin:0 0 22px}
          .ito-ben{background:rgba(255,255,255,.70);border:1px solid rgba(255,255,255,.90);border-radius:14px;padding:22px;backdrop-filter:blur(12px);display:flex;flex-direction:column;gap:14px}
          .ito-be{display:flex;gap:10px;align-items:flex-start}
          .ito-bi{flex-shrink:0;color:#be123c;font-weight:800;font-size:16px;margin-top:1px}
          .ito-be p{font-size:13px;color:#881337;margin:0;line-height:1.55}
          .ito-fb{background:linear-gradient(135deg,rgba(255,255,255,.88) 0%,rgba(255,241,242,.18) 50%,rgba(255,255,255,.84) 100%);backdrop-filter:blur(20px);border:1px solid rgba(255,255,255,.92);border-radius:20px;padding:34px;box-shadow:0 8px 40px rgba(59,0,24,.10),inset 0 1px 0 rgba(255,255,255,1)}
          .ito-fb h3{font-size:22px;font-weight:700;color:#3b0018;margin:0 0 22px;letter-spacing:-.3px}
          .ito-form{display:flex;flex-direction:column;gap:13px}
          .ito-fr{display:grid;grid-template-columns:1fr 1fr;gap:12px}
          .ito-fg{display:flex;flex-direction:column;gap:5px}
          .ito-fg.full{grid-column:1/-1}
          .ito-fg label{font-size:12px;font-weight:500;color:#3b0018}
          .ito-fg input,.ito-fg textarea,.ito-fg select{padding:10px 13px;border:1px solid rgba(59,0,24,.14);border-radius:6px;font-size:13px;font-family:inherit;color:#3b0018;background:rgba(255,255,255,.55);transition:border-color .2s}
          .ito-fg input:focus,.ito-fg textarea:focus,.ito-fg select:focus{outline:none;border-color:#be123c;box-shadow:0 0 0 3px rgba(190,18,60,.10)}
          .ito-co{display:flex;gap:8px;align-items:flex-start}
          .ito-co input{margin-top:3px;width:15px;height:15px}
          .ito-co label{font-size:11px;color:#881337;line-height:1.5}
          .ito-co a{color:#3b0018}
          .ito-sub{width:100%;padding:14px;background:#be123c;border:none;color:#fff;border-radius:50px;font-weight:700;font-size:15px;cursor:pointer;font-family:inherit;transition:all .25s;box-shadow:0 6px 24px rgba(190,18,60,.26)}
          .ito-sub:hover{background:#3b0018;transform:translateY(-2px)}
          .ito-fq-s{padding:80px 40px;background:#fff4f5;border-top:1px solid rgba(59,0,24,.08);position:relative;z-index:1}
          .ito-fq-s h2{font-size:46px;font-weight:900;letter-spacing:-1px;background:linear-gradient(90deg,#3b0018 0%,#D97706 100%);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;margin:0 0 8px}
          .ito-fq-sub{font-size:15px;color:#881337;margin:0 0 36px}
          .ito-fql{display:flex;flex-direction:column;gap:10px}
          .ito-fi{background:linear-gradient(135deg,rgba(255,241,242,.50) 0%,rgba(255,255,255,.85) 55%,rgba(255,228,230,.40) 100%);backdrop-filter:blur(16px);border:1px solid rgba(255,255,255,.85);border-radius:14px;overflow:hidden;box-shadow:0 4px 20px rgba(59,0,24,.06);transition:border-color .2s}
          .ito-fi.open{border-color:rgba(190,18,60,.30)}
          .ito-fi.open::before{content:'';display:block;height:3px;background:linear-gradient(90deg,#be123c,#f43f5e);border-radius:3px 3px 0 0}
          .ito-fqb{width:100%;background:none;border:none;padding:20px 20px 20px 58px;display:flex;align-items:center;justify-content:space-between;cursor:pointer;text-align:left;gap:14px;font-family:inherit;position:relative}
          .ito-fqb2{position:absolute;left:16px;top:50%;transform:translateY(-50%);width:26px;height:26px;background:rgba(59,0,24,.08);color:#374151;font-size:11px;font-weight:700;display:flex;align-items:center;justify-content:center;border-radius:6px}
          .ito-fi.open .ito-fqb2{background:#be123c;color:#fff}
          .ito-fqb span{font-size:15px;font-weight:600;color:#3b0018;line-height:1.4}
          .ito-fi.open .ito-fqb span{color:#be123c}
          .ito-fch{width:22px;height:22px;flex-shrink:0;color:#9ca3af;transition:transform .3s}
          .ito-fi.open .ito-fch{transform:rotate(180deg);color:#be123c}
          .ito-faw{overflow:hidden;transition:max-height .35s ease;max-height:0}
          .ito-fi.open .ito-faw{max-height:500px}
          .ito-fa{padding:0 20px 20px 58px;font-size:14px;color:#4b5563;line-height:1.8}
          .ito-rel{padding:80px 40px;background:rgba(255,241,242,.14);backdrop-filter:blur(10px);border-top:1px solid rgba(255,255,255,.60)}
          .ito-ri{max-width:1300px;margin:0 auto;text-align:center}
          .ito-ri h2{font-size:34px;font-weight:900;background:linear-gradient(90deg,#3b0018 0%,#D97706 100%);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;margin:10px 0 12px}
          .ito-rs{font-size:14px;color:#881337;margin:0 auto;max-width:560px}
          .ito-ri hr{border:none;border-top:1px solid rgba(59,0,24,.10);margin:32px 0}
          .ito-rts{display:flex;flex-wrap:wrap;justify-content:center;gap:10px}
          .ito-rt{display:inline-block;padding:10px 20px;border:1.5px solid;border-radius:50px;font-size:14px;font-weight:500;text-decoration:none;transition:all .22s}
          .ito-rt:hover{transform:translateY(-2px);box-shadow:0 6px 18px rgba(0,0,0,.09)}
          .ito-b{background:rgba(190,18,60,.09);border-color:rgba(190,18,60,.28);color:#9f1239}
          .ito-c{background:rgba(14,116,144,.09);border-color:rgba(14,116,144,.28);color:#155e75}
          .ito-v{background:rgba(67,56,202,.09);border-color:rgba(67,56,202,.28);color:#3730a3}
          .ito-g2{background:rgba(22,101,52,.09);border-color:rgba(22,101,52,.28);color:#14532d}
          .ito-o{background:rgba(146,64,14,.09);border-color:rgba(146,64,14,.28);color:#92400e}
          @media(max-width:1024px){.ito-hero h1,.ito-st,.ito-fq-s h2{font-size:36px}.ito-sk-g{grid-template-columns:repeat(2,1fr)}.ito-tec-g{grid-template-columns:repeat(2,1fr)}.ito-en-g{grid-template-columns:1fr;max-width:480px;margin-left:auto;margin-right:auto}.ito-en-c.feat{transform:none}.ito-en-c.feat.ito-ev{transform:none}.ito-en-c.feat.ito-ev:hover{transform:translateY(-4px)}.ito-wy-g{grid-template-columns:repeat(2,1fr)}.ito-tg2{grid-template-columns:1fr}.ito-ct-g{grid-template-columns:1fr}}
          @media(max-width:768px){.ito-bc,.ito-hero,.ito-sk-s,.ito-tec-s,.ito-en-s,.ito-pr-s,.ito-te-s,.ito-wy-s,.ito-fq-s,.ito-rel{padding-left:20px;padding-right:20px}.ito-hero{padding-top:28px;padding-bottom:20px}.ito-hero h1{font-size:26px;letter-spacing:-.3px}.ito-stats{grid-template-columns:1fr 1fr}.ito-sc:nth-child(2){border-right:none}.ito-sc:nth-child(3),.ito-sc:nth-child(4){border-top:1px solid rgba(59,0,24,.10)}.ito-sc:nth-child(4){border-right:none}.ito-sk-g,.ito-tec-g,.ito-wy-g{grid-template-columns:1fr}.ito-fr{grid-template-columns:1fr}.ito-ctt{font-size:28px}.ito-st{font-size:28px}.ito-ct-s{padding:48px 20px}.ito-logos{padding-left:20px;padding-right:20px}}
        `}</style>
      </Head>
      <div className="ito-page">
        <div className="ito-orb ito-o1" /><div className="ito-orb ito-o2" /><div className="ito-orb ito-o3" />
        <nav className="ito-bc" aria-label="Breadcrumb"><ol itemScope itemType="https://schema.org/BreadcrumbList"><li itemScope itemType="https://schema.org/ListItem" itemProp="itemListElement"><Link href="/" itemProp="item"><span itemProp="name">Home</span></Link><meta itemProp="position" content="1" /></li><li itemScope itemType="https://schema.org/ListItem" itemProp="itemListElement"><span itemProp="name">IT Outsourcing Services</span><meta itemProp="position" content="2" /></li></ol></nav>
        <section className="ito-hero">
          <span className="ito-ey">IT Outsourcing Services</span>
          <h1>IT Outsourcing Services — Software Development, Cloud, QA & DevOps</h1>
          <p className="ito-desc">Outsource software development, cloud infrastructure management, QA and testing, DevOps, AI/ML engineering, data engineering, mobile development, and application maintenance to 1Solutions — a trusted India-based IT outsourcing company with 15+ years serving clients in the US, UK, Australia, and Canada. SLA-backed, NDA-protected, 60–70% below local hiring costs.</p>
          <div className="ito-tr">{['Software Development Outsourcing','Cloud & DevOps Outsourcing','QA & Testing Outsourcing','AI / ML / Data Engineering','SLA-Backed & NDA-Protected'].map(b => (<div className="ito-badge" key={b}><span className="ito-dot" />{b}</div>))}</div>
          <div className="ito-ctas"><Link href="#contact" className="ito-p">Discuss Your Outsourcing Needs</Link><Link href="#engagement" className="ito-g">View Engagement Models →</Link></div>
        </section>
        <div className="ito-stats" ref={stR}>{[['500+','Projects Outsourced'],['15+','Years IT Outsourcing'],['98%','Client Retention'],['60-70%','Cost vs Local Teams']].map(([v, l]) => (<StatItem key={l} label={l} val={v} started={ss} />))}</div>
        <div className="ito-logos"><span className="ito-ll">IT Outsourcing Clients in US, UK, Australia, Canada</span><div className="ito-lw"><div className="ito-lt">{[['/logo/Indian_Express_Logo_full.png','Indian Express'],['/logo/Verizon_2015_logo_-vector.svg.png','Verizon'],['/logo/Uniphore.jpg','Uniphore'],['/logo/ICCoLogo.png','ICC'],['/logo/Honor_Logo_(2020).svg.png','Honor'],['/logo/Zuari-Finserv-logo-new.png','Zuari Finserv'],['/logo/Indian_Express_Logo_full.png','Indian Express 2'],['/logo/Verizon_2015_logo_-vector.svg.png','Verizon 2'],['/logo/Uniphore.jpg','Uniphore 2'],['/logo/ICCoLogo.png','ICC 2'],['/logo/Honor_Logo_(2020).svg.png','Honor 2'],['/logo/Zuari-Finserv-logo-new.png','Zuari Finserv 2']].map(([src, alt]) => (<img key={alt} src={src} alt={alt.replace(/ \d$/, '')} className="ito-cl" />))}</div></div></div>
        <section className="ito-sk-s" aria-labelledby="ito-sk-h"><div className="ito-in"><div className={`ito-rv${vis.has('sk') ? ' ito-ok' : ''}`} ref={el => { secR.current['sk'] = el; }}><span className="ito-sey">IT Outsourcing Services</span><h2 id="ito-sk-h" className="ito-st">IT Functions We Outsource</h2><p className="ito-sd" style={{ maxWidth: 720 }}>Software development, cloud management, QA, DevOps, AI/ML, mobile, data engineering, e-commerce, application maintenance, and legacy system modernisation — all delivered by specialist offshore teams with defined SLAs.</p></div><div className="ito-sk-g" ref={skR}>{visServices.map((s, i) => (<div key={s.n} className={`ito-sk-c${s.feat ? ' feat' : ''}${vSk.includes(i) ? ' ito-cv' : ''}`} style={{ transitionDelay: `${i * 55}ms` }}><span className="ito-sk-n">{s.n}</span><h3>{s.title}</h3><p>{s.desc}</p></div>))}</div>{SERVICES.length > 6 && (<div className="ito-sm"><button className="ito-bm" onClick={() => setShowAll(p => !p)}>{showAll ? 'Show fewer ↑' : `Show all ${SERVICES.length} services ↓`}</button></div>)}</div></section>
        <section className="ito-tec-s" aria-labelledby="ito-tec-h"><div className="ito-in"><div className={`ito-rv${vis.has('stk') ? ' ito-ok' : ''}`} ref={el => { secR.current['stk'] = el; }}><span className="ito-sey">Technology Coverage</span><h2 id="ito-tec-h" className="ito-st">Technologies Our Outsourced Teams Cover</h2><p className="ito-sd" style={{ maxWidth: 680 }}>React, Next.js, Angular, Node.js, Python, PHP, Java, .NET, Flutter, Swift, Kotlin, AWS, Kubernetes, Terraform, dbt, LangChain, PyTorch, Shopify, Magento — the full modern IT stack.</p></div><div className="ito-tec-g" ref={stGr}>{TECH_STACK.map((grp, i) => (<div key={grp.group} className={`ito-tec-c${vSt.includes(i) ? ' ito-sv2' : ''}`} style={{ transitionDelay: `${i * 60}ms` }}><div className="ito-tg" style={{ color: grp.color, borderBottomColor: grp.color + '33' }}>{grp.group}</div><div className="ito-pills">{grp.items.map(item => <span key={item} className="ito-pill" style={{ color: grp.color, background: grp.color + '12', borderColor: grp.color + '30' }}>{item}</span>)}</div></div>))}</div></div></section>
        <section id="engagement" className="ito-en-s" aria-labelledby="ito-en-h"><div className="ito-in"><div className={`ito-rv${vis.has('eng') ? ' ito-ok' : ''}`} ref={el => { secR.current['eng'] = el; }}><span className="ito-sey">Engagement Models</span><h2 id="ito-en-h" className="ito-st">IT Outsourcing Engagement Models</h2><p className="ito-sd" style={{ maxWidth: 680 }}>Dedicated outsourced team, SLA-backed application maintenance, or fixed-price project — structured for your delivery model and risk appetite.</p></div><div className="ito-en-g" ref={enR}>{ENGAGEMENT_MODELS.map((m, i) => (<div key={m.id} className={`ito-en-c${m.feat ? ' feat' : ''}${vEn.includes(i) ? ' ito-ev' : ''}`} style={{ transitionDelay: `${i * 100}ms` }}><span className="ito-en-b" style={{ color: m.badgeColor, borderColor: m.badgeColor + '44', background: m.badgeColor + '14' }}>{m.badge}</span><div className="ito-en-i"><svg viewBox="0 0 24 24" width="26" height="26"><path d={m.icon} /></svg></div><div className="ito-en-n">{m.name}</div><div className="ito-en-h">{m.headline}</div><div className="ito-en-d">{m.desc}</div><div className="ito-en-ll">Best for</div><ul className="ito-en-li">{m.bestFor.map(b => <li key={b}>{b}</li>)}</ul><div className="ito-en-p"><strong>Process:</strong> {m.process}<br /><span className="ito-en-tl">{m.timeline}</span></div><Link href="#contact" className="ito-en-a">Get a free estimate →</Link></div>))}</div></div></section>
        <section className="ito-pr-s" aria-labelledby="ito-pr-h"><div className="ito-in" style={{ maxWidth: 760 }}><div className={`ito-rv${vis.has('proc') ? ' ito-ok' : ''}`} ref={el => { secR.current['proc'] = el; }}><span className="ito-sey">How We Work</span><h2 id="ito-pr-h" className="ito-st">Our IT Outsourcing Process</h2><p className="ito-sd">From discovery to full delivery in 3–4 weeks — structured onboarding, SLA setup, toolchain access, codebase handover (if applicable), and continuous improvement cadence.</p></div><div className="ito-ps">{PROCESS_STEPS.map((step, i) => (<div key={step.num} className={`ito-ps-row${vis.has('proc') ? ' ito-pv' : ''}`} style={{ transitionDelay: `${i * 120}ms` }}><div className="ito-ps-l"><div className="ito-ps-ci">{step.num}</div><div className="ito-ps-co" /></div><div className="ito-ps-r"><div className="ito-ps-t">{step.title}</div><p className="ito-ps-d">{step.desc}</p></div></div>))}</div></div></section>
        <section className="ito-te-s" aria-labelledby="ito-te-h"><div className="ito-in"><div className={`ito-ch ito-rv${vis.has('ts') ? ' ito-ok' : ''}`} ref={el => { secR.current['ts'] = el; }}><span className="ito-sey">Client Outcomes</span><h2 id="ito-te-h" className="ito-st">What IT Outsourcing Clients Say</h2><p className="ito-sd">CEOs, IT heads, and data leaders across the UK, AU, and US on outsourcing IT functions to 1Solutions.</p></div><div className="ito-tg2" ref={teR}>{TESTIMONIALS.map((t, i) => (<div key={i} className={`ito-tc${t.feat ? ' feat' : ''}${vTe.includes(i) ? ' ito-tv' : ''}`} style={{ transitionDelay: `${i * 100}ms` }} itemScope itemType="https://schema.org/Review"><div className="ito-stars">★★★★★</div><p className="ito-txt" itemProp="reviewBody">{t.text}</p><div className="ito-au"><div className="ito-av" style={{ background: t.bg }}>{t.init}</div><div><div className="ito-an" itemProp="author">{t.name}</div><div className="ito-ar">{t.role}</div></div></div></div>))}</div></div></section>
        <section className="ito-wy-s" aria-labelledby="ito-wy-h"><div className="ito-in"><div className={`ito-rv${vis.has('wy') ? ' ito-ok' : ''}`} ref={el => { secR.current['wy'] = el; }}><span className="ito-sey">Why 1Solutions</span><h2 id="ito-wy-h" className="ito-st">Why Outsource IT to 1Solutions</h2><p className="ito-sd" style={{ maxWidth: 680 }}>15+ years of IT outsourcing, SLA-backed commitments, full IP ownership, NDA from day one, codebase takeover expertise, 60–70% cost reduction, full-stack coverage, and transparent reporting.</p></div><div className="ito-wy-g" ref={whR}>{WHY_CARDS.map((c, i) => (<div key={i} className={`ito-wc${vWh.includes(i) ? ' ito-wv' : ''}`} style={{ transitionDelay: `${i * 60}ms` }}><div className="ito-wd" /><h3>{c.title}</h3><p>{c.desc}</p></div>))}</div></div></section>
        <section id="contact" className="ito-ct-s" aria-labelledby="ito-ct-h"><div className="ito-ct-g"><div><h2 id="ito-ct-h" className="ito-ctt">Discuss Your IT Outsourcing Needs</h2><p className="ito-ctd">Share the IT functions you want to outsource, your technology stack, current team and system state, and SLA requirements — we will propose the right engagement model and team composition within 24–48 hours.</p><div className="ito-ben">{[['✓','Proposal with team composition and SLAs within 24–48 hours'],['✓','NDA signed before any project discussions'],['✓','All IP exclusively assigned to your company in the contract'],['✓','15+ years IT outsourcing — US, UK, AU, CA clients'],['✓','Codebase takeover specialists — no disruption during transition']].map(([icon, text]) => (<div className="ito-be" key={text}><span className="ito-bi">{icon}</span><p>{text}</p></div>))}</div></div>
        <div className="ito-fb"><h3>Tell Us About Your IT Outsourcing Needs</h3><form className="ito-form" onSubmit={e => e.preventDefault()}>
          <div className="ito-fr"><div className="ito-fg"><label htmlFor="ito-nm">Full Name *</label><input id="ito-nm" type="text" placeholder="Your name" required /></div><div className="ito-fg"><label htmlFor="ito-em">Work Email *</label><input id="ito-em" type="email" placeholder="you@company.com" required /></div></div>
          <div className="ito-fr"><div className="ito-fg"><label htmlFor="ito-co">Company Name</label><input id="ito-co" type="text" placeholder="Your company" /></div><div className="ito-fg"><label htmlFor="ito-ph">Phone / WhatsApp</label><input id="ito-ph" type="tel" placeholder="+1 555 000 0000" /></div></div>
          <div className="ito-fg full"><label htmlFor="ito-fn">IT Function to Outsource *</label><select id="ito-fn" required><option value="">Select function...</option><option>Software Application Development</option><option>Cloud Infrastructure Management</option><option>QA & Software Testing</option><option>DevOps & Platform Engineering</option><option>Application Maintenance & Support</option><option>AI / ML Engineering</option><option>Mobile App Development</option><option>Data Engineering & Analytics</option><option>E-Commerce Development</option><option>Legacy System Modernisation</option><option>Multiple Functions</option></select></div>
          <div className="ito-fg full"><label htmlFor="ito-em2">Engagement Model</label><select id="ito-em2"><option value="">Select model...</option><option>Dedicated Outsourced Team (monthly retainer)</option><option>Application Maintenance & Support (SLA)</option><option>Fixed-Price Project</option><option>Not sure — need advice</option></select></div>
          <div className="ito-fg full"><label htmlFor="ito-ms">Project Context & Requirements *</label><textarea id="ito-ms" rows={4} placeholder="Describe the IT function you want to outsource, current system state (for maintenance engagements), technology stack, team size needed, SLA requirements, and timeline..." required /></div>
          <div className="ito-co"><input id="ito-co2" type="checkbox" required /><label htmlFor="ito-co2">I agree to the <Link href="/privacy-policy">Privacy Policy</Link>. Details are treated confidentially.</label></div>
          <button type="submit" className="ito-sub">Get Outsourcing Proposal in 24 Hours →</button>
        </form></div></div></section>
        <section className="ito-fq-s" aria-labelledby="ito-fq-h"><div className="ito-in" style={{ maxWidth: 860 }}><span className="ito-sey">FAQ</span><h2 id="ito-fq-h">IT Outsourcing Services — FAQ</h2><p className="ito-fq-sub">What IT functions can be outsourced, differences from staff augmentation, quality assurance, SLA commitments, IP protection, codebase takeover, and cost advantages.</p><div className="ito-fql">{FAQS.map((item, i) => (<div key={i} className={`ito-fi${openFaq === i ? ' open' : ''}`} itemScope itemType="https://schema.org/Question"><button className="ito-fqb" onClick={() => setOpenFaq(openFaq === i ? -1 : i)} aria-expanded={openFaq === i}><div className="ito-fqb2">{String(i + 1).padStart(2, '0')}</div><span itemProp="name">{item.q}</span><svg className="ito-fch" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2"><polyline points="6 9 12 15 18 9" /></svg></button><div className="ito-faw" itemScope itemType="https://schema.org/Answer"><div className="ito-fa" itemProp="text">{item.a}</div></div></div>))}</div></div></section>
        <section className="ito-rel"><div className="ito-ri"><span className="ito-sey">Related Services</span><h2>Related Offshore & IT Services</h2><p className="ito-rs">Offshore development, staff augmentation, cost optimization, virtual CTO, and specialist hire developer services.</p><hr /><div className="ito-rts">{[['/offshore-development-company/','Offshore Development','ito-c'],['/it-staff-augmentation-services/','Staff Augmentation','ito-v'],['/software-development-cost-optimization/','Cost Optimization','ito-g2'],['/virtual-cto-services/','Virtual CTO','ito-o'],['/devops-services-company/','DevOps Services','ito-b'],['/cloud-migration-services/','Cloud Migration','ito-c'],['/hire-ai-developer/','Hire AI Developer','ito-v'],['/software-development-company/','Software Development','ito-b']].map(([href, label, cls]) => (<Link key={href} href={href} className={`ito-rt ${cls}`}>{label}</Link>))}</div></div></section>
      </div>
    </>
  );
}
